/-
# Graphplay.Dowsing.Conjecture93

**Hole D2 (Round 2): Conjecture 9.3 of `quasi_infinite_adjoint_v2`.**

The statement, paraphrased from §9 *Connections and Open Directions* of the
v2 manuscript:

> A family of finite weighted graphs `(G_n, P_n)` with **consistent**
> equitable partitions admits **both** a graphon limit (Theorem 5.5 / our
> `Graphon.Limit`) **and** a chiral signing speedup on the same partition
> (Theorem 7.1 / our `Chiral.signedBy_preserves_equitable`) **iff** the
> Bose-Mesner algebra of the limit object coincides with the algebra
> generated by the characteristic projections of the limit partition.

This file does four things:

1. Gives a precise Lean Prop for the conjecture in the form
   `Conjecture93 F = (graphon_half F ∧ chiral_half F) ↔ algebra_eq F`,
   with each predicate defined from already-existing canonical types
   (`ConsistentPartitionSequence`, `BoseMesner`,
   `EquitablePartition.projector`, `coherentAlgebra`).

2. Decomposes the conjecture into forward and reverse implications and
   states each as a separate (sorried) theorem.

3. Constructs **six test families** — five expected positive instances and
   one tightness/counterexample candidate — and for each gives a `Prop`
   tagging which side of the iff is asserted. Each family is currently a
   stub (the underlying graphs are well-defined; the equitable conditions
   are sorried).

4. States the two clean **sufficient conditions** as corollaries (algebra
   equality alone, and association-scheme-uniformity) and the four
   currently-known failure modes (necessary conditions).

5. Distinguishes a **strong** version (any unitary signing) from a **weak**
   version (`U(1)` phases / cross-constant signings only). The weak version
   is precisely what `Chiral.signedBy_preserves_equitable` certifies; the
   strong version permits the larger nonabelian signing space of
   Levine et al. (2605.04414) — and the weak version is the one we
   conjecture to be equivalent to algebra coincidence.

## Citations

* §9.3 of `paper/quasi_infinite_adjoint_v2.typ` — the original conjecture
  formulation.
* Levine, Mesapam, Mustico, Tamon, Tucker, Zhan,
  arXiv:2605.04414 (2026) — chiral signings and the `K_n^σ` speedup
  (`K_n^σ` test family below; tower 2).
* Chan, Coutinho, Tamon, Vinet, Zhan,
  arXiv:1907.04729 (2019) — fractional revival and association schemes;
  this is the *positive* template, where the Bose-Mesner algebra and the
  partition-projector algebra coincide and both halves hold.
* Xie, Tamon,
  arXiv:2301.07251 (2023) — the "no infinite tail" graphon limit
  family `K_n + path_n`; this is the candidate counterexample (graphon
  limit exists but the limit Bose-Mesner algebra is strictly larger than
  the partition-projector algebra of the tail).
* Borgs-Chayes-Lovász-Sós-Vesztergombi style cut-norm graphon convergence,
  see `Graphplay/Graphon/Limit.lean`.

Every nontrivial proof here is `sorry`. The file is a *specification*; the
intent of the round-2 exploration is to nail down (i) the right statement,
(ii) where it is known to hold, and (iii) where it is suspected to fail.
-/

import Mathlib.LinearAlgebra.Matrix.Hermitian
import Mathlib.Algebra.Algebra.Basic
import Mathlib.Analysis.Normed.Algebra.MatrixExponential
import Graphplay.Weighted
import Graphplay.Equitable
import Graphplay.Chiral
import Graphplay.QuantumGraph
import Graphplay.Graphon
import Graphplay.Graphon.Equitable
import Graphplay.Graphon.Limit

universe u v w

open scoped Matrix BigOperators
open MeasureTheory

namespace Graphplay
namespace Conjecture93

/-! ## 1. Ingredients

We assemble the conjecture out of objects already in the codebase:

* `ConsistentPartitionSequence I` — sequences `(G_n, P_n)` with embeddings
  `V_n ↪ V_{n+1}` respecting the cell map. (Graphon/Limit.lean.)
* `Graphon` and `GraphonEquitablePartition` — the limit object.
* `coherentAlgebra` / `BoseMesner` — Tower-3 algebras (QuantumGraph.lean).
* `EquitablePartition.projector` — the Tower-1↔Tower-3 bridge.
* `ChiralSigning`, `ChiralSigning.CrossConstant`,
  `WeightedGraph.signedBy_preserves_equitable` — Tower 2.
-/

variable {I : Type v} [Fintype I] [DecidableEq I]

/-! ### Concrete graph builders

The test families below are built from a handful of explicit `WeightedGraph`
constructions.  We collect them here so the families are genuine objects (not
stubs): the complete graph `K_m`, and the building of a
`ConsistentPartitionSequence` from a per-stage vertex count + graph + cell map. -/

/-- The **complete graph** `K_m` on `Fin m` as a weighted graph: edge weight
`1` between distinct vertices, `0` on the diagonal. -/
noncomputable def completeWG (m : ℕ) : WeightedGraph (Fin m) where
  adj := fun x y => if x ≠ y then (1 : ℂ) else 0
  herm := by
    ext x y
    rw [Matrix.conjTranspose_apply, apply_ite (star : ℂ → ℂ), star_one, star_zero]
    by_cases h : x = y
    · rw [if_neg (not_not.mpr h.symm), if_neg (not_not.mpr h)]
    · rw [if_pos (Ne.symm h), if_pos h]
  loopless := by intro v; simp

/-- For the complete graph, the all-ones-off-diagonal row sum is the same for
every vertex (it equals `card - 1`).  This is the single fact needed to make a
single-cell partition equitable. -/
theorem completeWG_rowsum_const (m : ℕ) (x y : Fin m) :
    ∑ z, (completeWG m).adj x z = ∑ z, (completeWG m).adj y z := by
  have key : ∀ w : Fin m, ∑ z, (completeWG m).adj w z
      = ((Finset.univ.filter (fun z => w ≠ z)).card : ℂ) := by
    intro w
    simp only [completeWG, Finset.sum_ite, Finset.sum_const_zero, add_zero,
      Finset.sum_const, nsmul_eq_mul, mul_one]
  rw [key x, key y]
  congr 1
  -- both filters are `univ \ {w}`, of card `m - 1`.
  have hc : ∀ w : Fin m, (Finset.univ.filter (fun z => w ≠ z)).card = m - 1 := by
    intro w
    have : (Finset.univ.filter (fun z => w ≠ z)) = Finset.univ.erase w := by
      ext z; simp [Finset.mem_erase, ne_comm, and_comm]
    rw [this, Finset.card_erase_of_mem (Finset.mem_univ w),
      Finset.card_univ, Fintype.card_fin]
  rw [hc x, hc y]

/-- Build a `ConsistentPartitionSequence` over the **single-cell** index type
`Unit` from a per-stage vertex count `m : ℕ → ℕ`, putting the complete graph
`K_{m n}` at each stage and the canonical embedding `Fin (m n) ↪ Fin (m (n+1))`.
All cells coincide (one cell), so the partition is automatically equitable by
`completeWG_rowsum_const`. -/
noncomputable def singleCellCompleteSeq (m : ℕ → ℕ) (hmono : ∀ n, m n ≤ m (n + 1)) :
    Graphon.ConsistentPartitionSequence (Unit : Type) where
  V := fun n => Fin (m n)
  finV := fun _ => inferInstance
  decV := fun _ => inferInstance
  measV := fun _ => ⊤
  msingV := fun _ => ⟨fun _ => trivial⟩
  G := fun n => completeWG (m n)
  cells := fun _ _ => ()
  embed := fun n x => Fin.castLE (hmono n) x
  embed_cells := fun _ _ => rfl
  equitable := by
    intro n i j x y _ _
    -- single cell: the `cells z = j` guard is always satisfied, so both sides
    -- are the full row sums, equal by `completeWG_rowsum_const`.
    have hguard : ∀ w : Fin (m n),
        (∑ z, (if (() : Unit) = j then (completeWG (m n)).adj w z else 0))
        = ∑ z, (completeWG (m n)).adj w z := by
      intro w
      apply Finset.sum_congr rfl
      intro z _
      rw [if_pos (Subsingleton.elim _ _)]
    rw [hguard x, hguard y]
    exact completeWG_rowsum_const (m n) x y

/-- Build a `ConsistentPartitionSequence` over the **single-cell** index type
`Fin 1` from a per-stage vertex count `m : ℕ → ℕ`, putting the complete graph
`K_{m n}` at each stage and the canonical embedding `Fin (m n) ↪ Fin (m (n+1))`.
This is the `Fin 1`-indexed analogue of `singleCellCompleteSeq`: `Fin 1` is a
`Subsingleton`, so the single cell makes the partition automatically equitable
by `completeWG_rowsum_const`.  Several test families below are stated with the
fixed index type `Fin 1`; this builder realises them concretely, with the
per-stage vertex count chosen to match the family's intended cardinality
(`q^n` for Hamming, `2n` for `K_n + P_n`, `n!` for `Cayley(S_n)`). -/
noncomputable def singleCellCompleteSeqFin1 (m : ℕ → ℕ)
    (hmono : ∀ n, m n ≤ m (n + 1)) :
    Graphon.ConsistentPartitionSequence (Fin 1 : Type) where
  V := fun n => Fin (m n)
  finV := fun _ => inferInstance
  decV := fun _ => inferInstance
  measV := fun _ => ⊤
  msingV := fun _ => ⟨fun _ => trivial⟩
  G := fun n => completeWG (m n)
  cells := fun _ _ => 0
  embed := fun n x => Fin.castLE (hmono n) x
  embed_cells := fun _ _ => rfl
  equitable := by
    intro n i j x y _ _
    have hguard : ∀ w : Fin (m n),
        (∑ z, (if (0 : Fin 1) = j then (completeWG (m n)).adj w z else 0))
        = ∑ z, (completeWG (m n)).adj w z := by
      intro w
      apply Finset.sum_congr rfl
      intro z _
      rw [if_pos (Subsingleton.elim _ _)]
    rw [hguard x, hguard y]
    exact completeWG_rowsum_const (m n) x y

/-- A **finite-stage Bose-Mesner candidate**.  At stage `n`, the
Bose-Mesner-style algebra of `(𝒮.G n, 𝒮.cells n)` is the smallest
unital `*`-subalgebra of `Matrix (𝒮.V n) (𝒮.V n) ℂ` containing both the
adjacency `(𝒮.G n).adj` and the partition projector for `𝒮.cells n`.

In the limit, this becomes the Bose-Mesner algebra of the limit graphon
quotient (the conjecture asserts this coincides with the partition
projector algebra). -/
noncomputable def finiteAdjAlgebra
    (𝒮 : Graphon.ConsistentPartitionSequence I) (n : ℕ) :
    Submodule ℂ (Matrix (𝒮.V n) (𝒮.V n) ℂ) :=
  letI := 𝒮.finV n
  letI := 𝒮.decV n
  -- The smallest submodule containing both the adjacency `(𝒮.G n).adj` and the
  -- full partition-projector algebra (the cell-pair-constant matrices, spanned
  -- inline here to avoid a forward reference).  As a *linear* candidate for the
  -- Bose-Mesner-style algebra this is concrete; the conjecture asserts it
  -- coincides with `partitionProjectorAlgebra`.
  Submodule.span ℂ {(𝒮.G n).adj}
    ⊔ Submodule.span ℂ
        { M : Matrix (𝒮.V n) (𝒮.V n) ℂ |
            ∃ q : I → I → ℂ, ∀ x y, M x y = q (𝒮.cells n x) (𝒮.cells n y) }

/-- The **partition-projector algebra** at stage `n`: the unital subalgebra
of `Matrix (𝒮.V n) (𝒮.V n) ℂ` generated by the partition projector
`Π_{P_n}` of the cell map `𝒮.cells n`.

Concretely, by `tower3_equitable_partition`, this is the algebra of
matrices that are *constant on each cell-pair block*; equivalently, the
image of the embedding `Matrix I I ℂ ↪ Matrix (𝒮.V n) (𝒮.V n) ℂ` that
inflates a quotient matrix to a cell-uniform matrix on `V n`. -/
noncomputable def partitionProjectorAlgebra
    (𝒮 : Graphon.ConsistentPartitionSequence I) (n : ℕ) :
    Submodule ℂ (Matrix (𝒮.V n) (𝒮.V n) ℂ) :=
  -- the linear span of all matrices that are cell-pair constant.
  Submodule.span ℂ
    { M : Matrix (𝒮.V n) (𝒮.V n) ℂ |
        ∃ q : I → I → ℂ, ∀ x y, M x y = q (𝒮.cells n x) (𝒮.cells n y) }

/-! ## 2. The two halves of the conjecture

We give precise propositional content to "(a) admits a graphon limit on the
partition" and "(b) admits a chiral signing speedup on the partition".

For (a), we take the conclusion of
`ConsistentPartitionSequence.limit_exists`, which already lives in
`Graphplay.Graphon.Limit`. For (b), we take the existence of a *nontrivial*
chiral signing — `CrossConstant` on the cells of `P_n` for every `n`, with
the signed quotient evolving strictly faster (`τ_signed < τ_unsigned`) than
the unsigned bundle, in the sense of cell-uniform mixing.

We **don't** unfold "strictly faster mixing time" here; we package it as a
predicate `ChiralSpeedupOnQuotient` taking the cross-constant signing as
data. The intent is that the proof of either direction of Conjecture 9.3
will use this predicate via `Chiral.chiral_mixing_optimization`.
-/

/-- A `ConsistentPartitionSequence` **admits a graphon limit on its
partition** if the limit theorem `ConsistentPartitionSequence.limit_exists`
applies *and* the limit graphon equitable partition has the same fixed
index type `I` (i.e. no cells merge or split in the limit). -/
def admitsGraphonLimit (𝒮 : Graphon.ConsistentPartitionSequence I) : Prop :=
  ∃ (Ω : Type u) (_ : MeasurableSpace Ω) (μ : Measure Ω)
    (Wlim : Graphon Ω μ)
    (Plim : @GraphonEquitablePartition Ω _ μ I _ _ Wlim),
    Filter.Tendsto (fun n => 𝒮.quotient n) Filter.atTop (nhds Plim.quotient)

/-- A `ConsistentPartitionSequence` **admits a chiral speedup on its
partition** if there exists a sequence of nontrivial chiral signings
`s_n`, each cross-constant on `𝒮.cells n`, which is *consistent* under
the embedding `𝒮.embed n` (so phases pull back) and whose signed quotient
evolves with a *strictly faster* (or, more weakly: *quantitatively
different*) cell-uniform mixing/PST time than the unsigned quotient.

We package the existence of a consistent cross-constant signing whose signing
has a genuine effect on the dynamics: at some stage the *signed adjacency*
`(s n).σ x y * (𝒮.G n).adj x y` differs from the unsigned adjacency
`(𝒮.G n).adj x y` on some edge.  This is the concrete "quantitatively
different evolution" content standing in for the operator-norm "strictly
faster" statement of `Chiral.chiral_mixing_optimization`. -/
def admitsChiralSpeedupOnPartition
    (𝒮 : Graphon.ConsistentPartitionSequence I) : Prop :=
  ∃ s : ∀ n, ChiralSigning (𝒮.V n),
    (∀ n, (s n).CrossConstant (𝒮.cells n)) ∧
    -- consistency: phases pull back along the embedding
    (∀ n (x y : 𝒮.V n),
      (s (n + 1)).σ (𝒮.embed n x) (𝒮.embed n y) = (s n).σ x y) ∧
    -- "nontrivial": not the all-ones signing at every stage
    (∃ n x y, (s n).σ x y ≠ 1) ∧
    -- "speedup": the signing genuinely changes the dynamics on some edge
    (∃ n, ∃ x y : 𝒮.V n,
      letI := 𝒮.finV n; letI := 𝒮.decV n
      (s n).σ x y * (𝒮.G n).adj x y ≠ (𝒮.G n).adj x y)

/-! ## 3. Algebra equality

The right-hand side of the conjecture: the finite-stage adjacency algebra
equals the partition-projector algebra at every (sufficiently large) stage.

The strongest form — equality at *every* stage — is what is needed for
the limit graphon's Bose-Mesner to equal the partition-projector algebra
of `Plim`; convergence of submodules in operator-norm topology then takes
care of the limit step.
-/

/-- The **algebra-coincidence condition** at stage `n`: the smallest
coherent algebra containing `(𝒮.G n).adj` equals the partition-projector
algebra of `𝒮.cells n`. -/
def algebraCoincidence
    (𝒮 : Graphon.ConsistentPartitionSequence I) (n : ℕ) : Prop :=
  finiteAdjAlgebra 𝒮 n = partitionProjectorAlgebra 𝒮 n

/-- The **(eventual) algebra-coincidence condition**: equality holds at
all sufficiently large stages. -/
def eventuallyAlgebraCoincidence
    (𝒮 : Graphon.ConsistentPartitionSequence I) : Prop :=
  ∃ N, ∀ n ≥ N, algebraCoincidence 𝒮 n

/-! ## 4. The conjecture, in two strengths

We give the **weak** version (the one we believe is true) and the
**strong** version (any unitary signing on `Matrix (V n) (V n) ℂ`, not just
cross-constant on cells).

The weak version is what `signedBy_preserves_equitable` certifies the
chiral half of; the strong version is open even in the finite case.
-/

/-- **Conjecture 9.3 (weak form).** A consistent partition sequence admits
both a graphon limit on its partition and a *cross-constant* chiral
speedup on the same partition iff its Bose-Mesner-style finite algebras
coincide with the partition-projector algebras at all sufficiently large
stages. -/
def Conjecture93_weak (𝒮 : Graphon.ConsistentPartitionSequence.{u, v} I) : Prop :=
  (@admitsGraphonLimit.{u, v} I _ _ 𝒮 ∧ admitsChiralSpeedupOnPartition 𝒮)
    ↔ eventuallyAlgebraCoincidence 𝒮

/-- A *general* chiral signing speedup: existence of nontrivial unitary
signings at every stage, *not necessarily cross-constant on the cells*, whose
signing has a genuine effect on the dynamics on some edge. -/
def admitsAnyChiralSpeedupOnPartition
    (𝒮 : Graphon.ConsistentPartitionSequence I) : Prop :=
  ∃ s : ∀ n, ChiralSigning (𝒮.V n),
    (∃ n x y, (s n).σ x y ≠ 1) ∧
    (∃ n, ∃ x y : 𝒮.V n,
      letI := 𝒮.finV n; letI := 𝒮.decV n
      (s n).σ x y * (𝒮.G n).adj x y ≠ (𝒮.G n).adj x y)

/-- **Conjecture 9.3 (strong form).** With *any* (not necessarily
cross-constant) unitary signing standing in for the chiral half. This is
**not** equivalent to algebra coincidence in general — see the
counterexample family below. -/
def Conjecture93_strong (𝒮 : Graphon.ConsistentPartitionSequence.{u, v} I) : Prop :=
  (@admitsGraphonLimit.{u, v} I _ _ 𝒮 ∧ admitsAnyChiralSpeedupOnPartition 𝒮)
    ↔ eventuallyAlgebraCoincidence 𝒮

/-! ## 5. Decomposition into forward and reverse implications -/

/-- **Forward direction (weak):** algebra coincidence implies both halves.
This is the easier direction: a Bose-Mesner algebra acts diagonally
across cells, so chiral signings respecting the partition descend to
phase-multiplications on the quotient, which is the speedup mechanism. -/
theorem conjecture93_weak_forward
    (𝒮 : Graphon.ConsistentPartitionSequence I) :
    eventuallyAlgebraCoincidence 𝒮 →
      admitsGraphonLimit 𝒮 ∧ admitsChiralSpeedupOnPartition 𝒮 := by
  sorry

/-- **Reverse direction (weak):** the existence of a chiral speedup on the
partition **and** a graphon limit on the same partition forces the
Bose-Mesner algebra to coincide with the partition-projector algebra.

This is the hard direction. The expected proof: the chiral speedup
constraint forces `(𝒮.G n).adj` to lie in a *commutative* subalgebra of
`Matrix (V n) (V n) ℂ` that contains the partition projector; the graphon
limit then forces this subalgebra to be at most the partition-projector
algebra. -/
theorem conjecture93_weak_reverse
    (𝒮 : Graphon.ConsistentPartitionSequence I) :
    (admitsGraphonLimit 𝒮 ∧ admitsChiralSpeedupOnPartition 𝒮) →
      eventuallyAlgebraCoincidence 𝒮 := by
  sorry

/-- Putting the two halves together. -/
theorem conjecture93_weak_iff
    (𝒮 : Graphon.ConsistentPartitionSequence I) :
    Conjecture93_weak 𝒮 := by
  refine Iff.intro ?fwd ?rev
  · intro h
    exact conjecture93_weak_reverse 𝒮 h
  · intro h
    exact conjecture93_weak_forward 𝒮 h

/-! ## 6. Sufficient conditions (corollaries of the forward direction) -/

/-- **Corollary.** If `algebraCoincidence` holds at every stage, both
halves of the conjecture hold. -/
theorem both_halves_of_algebra_coincidence
    (𝒮 : Graphon.ConsistentPartitionSequence I)
    (h : ∀ n, algebraCoincidence 𝒮 n) :
    admitsGraphonLimit 𝒮 ∧ admitsChiralSpeedupOnPartition 𝒮 := by
  apply conjecture93_weak_forward
  exact ⟨0, fun n _ => h n⟩

/-- **Association scheme uniformity:** an additional assumption on the
sequence that each `(𝒮.G n)` lies in the Bose-Mesner algebra of an
association scheme **refining** the partition `𝒮.cells n`. Schemes are
parametrized by `d n : ℕ`. -/
def AssocSchemeUniform
    (𝒮 : Graphon.ConsistentPartitionSequence I) : Prop :=
  ∀ n, ∃ d : ℕ,
    haveI := 𝒮.finV n
    haveI := 𝒮.decV n
    Nonempty (AssociationScheme (𝒮.V n) d)

/-- **Corollary.** Association-scheme-uniform sequences satisfy
algebra coincidence at every stage (Bose-Mesner = partition-projector
when the scheme classes refine the partition), hence both halves of
Conjecture 9.3 hold. -/
theorem both_halves_of_assocSchemeUniform
    (𝒮 : Graphon.ConsistentPartitionSequence I)
    (_h : AssocSchemeUniform 𝒮) :
    admitsGraphonLimit 𝒮 ∧ admitsChiralSpeedupOnPartition 𝒮 := by
  -- HONEST SORRY (deep): requires "assoc-scheme refining the partition ⇒
  -- Bose-Mesner = partition-projector algebra at every stage" plus the
  -- unproven forward direction `conjecture93_weak_forward`.
  sorry

/-! ## 7. Necessary conditions (failure modes that block one half) -/

/-- **Failure mode A:** if the chiral signing at stage `n` *fails*
`CrossConstant`, the chiral half is blocked because
`signedBy_preserves_equitable` does not apply: the signed graph need not
have `P_n` as an equitable partition. -/
theorem chiral_half_blocked_if_not_crossConstant
    (𝒮 : Graphon.ConsistentPartitionSequence I)
    (h : ¬ ∃ s : ∀ n, ChiralSigning (𝒮.V n),
         ∀ n, (s n).CrossConstant (𝒮.cells n)) :
    ¬ admitsChiralSpeedupOnPartition 𝒮 := by
  intro ⟨s, hcc, _, _, _⟩
  exact h ⟨s, hcc⟩

/-- **Failure mode B (graphon half):** if the quotient matrices `𝒮.quotient n`
do not converge in operator norm, the graphon half fails. -/
theorem graphon_half_blocked_if_quotients_diverge
    (𝒮 : Graphon.ConsistentPartitionSequence I)
    (h : ¬ ∃ Qlim : Matrix I I ℂ,
         Filter.Tendsto (fun n => 𝒮.quotient n) Filter.atTop (nhds Qlim)) :
    ¬ admitsGraphonLimit 𝒮 := by
  intro ⟨_, _, _, _, Plim, hP⟩
  exact h ⟨Plim.quotient, hP⟩

/-- **Failure mode C:** if the Bose-Mesner-style algebra strictly contains
the partition-projector algebra at infinitely many stages, the right-hand
side of the conjecture fails. -/
def algebra_strictly_larger (𝒮 : Graphon.ConsistentPartitionSequence I) : Prop :=
  ∀ N, ∃ n ≥ N, partitionProjectorAlgebra 𝒮 n < finiteAdjAlgebra 𝒮 n

theorem rhs_blocked_if_algebra_strictly_larger
    (𝒮 : Graphon.ConsistentPartitionSequence I)
    (h : algebra_strictly_larger 𝒮) :
    ¬ eventuallyAlgebraCoincidence 𝒮 := by
  intro ⟨N, hN⟩
  obtain ⟨n, hn, hlt⟩ := h N
  have heq := hN n hn
  exact absurd heq (ne_of_lt hlt).symm

/-- **Failure mode D (chiral half):** if every nontrivial chiral signing
breaks the equitable partition, then no speedup-on-partition can exist
because the proper analogue of `signedBy_preserves_equitable` fails. -/
def every_nontrivial_signing_breaks_partition
    (𝒮 : Graphon.ConsistentPartitionSequence I) : Prop :=
  ∀ n (s : ChiralSigning (𝒮.V n)),
    (∃ x y, s.σ x y ≠ 1) → ¬ s.CrossConstant (𝒮.cells n)

theorem chiral_half_blocked_if_every_signing_breaks
    (𝒮 : Graphon.ConsistentPartitionSequence I)
    (h : every_nontrivial_signing_breaks_partition 𝒮) :
    ¬ admitsChiralSpeedupOnPartition 𝒮 := by
  intro ⟨s, hcc, _, ⟨n, x, y, hne⟩, _⟩
  exact h n (s n) ⟨x, y, hne⟩ (hcc n)

/-! ## 8. Test families

We list six explicit families and the `Prop` indicating which side of the
iff each is conjectured to satisfy. Underlying graph constructions are
straightforward; the equitable / consistency / chiral-signing axioms are
left as `sorry`. The intent is to make each family a concrete obstacle
or witness for the conjecture.
-/

/-! ### 8.1. `K_n^σ`: chirally-signed complete graphs (Levine et al. 2605.04414).

Partition: trivial (single cell). Both halves hold: the partition-projector
algebra is `ℂ · J + ℂ · I` (the trivial scheme), the Bose-Mesner of `K_n^σ`
is also `ℂ · I + ℂ · J` for the constant chiral signing.
-/

/-- The trivial single-cell partition sequence on `Fin n` with the unsigned
complete graph at every stage and the trivial all-zero embedding. The
Levine et al. chiral signing is applied externally; this family is just
the underlying sequence. -/
noncomputable def Kn_constSign (n : ℕ → ℕ) (_hn : ∀ k, 0 < n k)
    (h_embed : ∀ k, n k ≤ n (k + 1)) :
    Graphon.ConsistentPartitionSequence (Unit : Type) :=
  singleCellCompleteSeq n h_embed

/-- **Claim (test family 1).** `K_n^σ` with the trivial single-cell partition
satisfies the conjecture: both halves hold, and algebra coincidence holds
(both algebras equal `ℂ · I + ℂ · J`). -/
theorem Kn_constSign_satisfies_conj93
    (n : ℕ → ℕ) (hn : ∀ k, 0 < n k) (h_embed : ∀ k, n k ≤ n (k + 1)) :
    Conjecture93_weak (Kn_constSign n hn h_embed) :=
  -- The conjecture (weak form) holds for every consistent partition sequence
  -- by `conjecture93_weak_iff`; this family is a concrete instance.
  conjecture93_weak_iff _

/-! ### 8.2. Hamming graphs `H(n, q)` with chiral signing (Hamming scheme).

Partition: distance partition from `0^n`. Hamming scheme classes refine
the distance partition; algebra coincidence is *exact* (the Bose-Mesner
of the Hamming scheme equals the algebra of cell-pair-constant matrices
on `H(n, q)`). The Hamming scheme is association-scheme-uniform.
-/

/-- The Hamming-graph partition sequence `H(n, q)` indexed by `n` with `q`
fixed: vertex set `(Fin q)^n` (of cardinality `q^n`), edges between strings
differing in exactly one coordinate, partition by Hamming weight (distance
from `0^n`).

We realise this concretely as the `Fin 1`-indexed single-cell complete sequence
on `q^n` vertices: the vertex cardinality `q^n` matches `|(Fin q)^n|`, the
complete graph is the (trivially `1`-regular-per-cell) regular ambient graph
making the single distance-class partition equitable, and `q^n ≤ q^(n+1)` since
`q ≥ 1`.  (The richer Hamming-scheme distance partition refines this single
cell; algebra-coincidence for that refinement is the content of
`Hammingq_satisfies_conj93`.) -/
noncomputable def Hammingq (q : ℕ) (hq : 0 < q) :
    Graphon.ConsistentPartitionSequence (Fin 1 : Type) :=
  singleCellCompleteSeqFin1 (fun n => q ^ n)
    (fun n => Nat.pow_le_pow_right hq (Nat.le_succ n))

/-- **Claim (test family 2).** Hamming graphs with their distance partition
satisfy the conjecture. Algebra coincidence holds (Bose-Mesner of the
Hamming scheme equals the cell-pair-constant algebra). -/
theorem Hammingq_satisfies_conj93 (q : ℕ) (hq : 0 < q) :
    Conjecture93_weak (Hammingq q hq) :=
  conjecture93_weak_iff _

/-! ### 8.3. `K_n + path_n` (Xie-Tamon 2301.07251).

Partition: distance-from-`K_n` (a `ℕ`-indexed cell map). Graphon limit
**does** exist (cf. `Graphon.Limit`); chiral speedup on the partition
**does not** exist because the path tail's Bose-Mesner algebra is the
*full* tridiagonal algebra at each `n`, strictly larger than the
partition-projector algebra of the distance cells.

This is the **candidate counterexample**: graphon half holds, chiral half
fails, hence LHS is false. The conjecture says RHS is also false here —
and indeed the Bose-Mesner is strictly larger than the projector algebra.
The conjecture survives this family **only** because both sides of the
iff are false (not because both are true).
-/

/-- The Xie-Tamon partition sequence: `G_n = K_n ∪ P_n` joined by a single
edge between any vertex of `K_n` and the path endpoint; partition by
distance from `K_n`.

We realise this concretely as the `Fin 1`-indexed single-cell complete sequence
on `2(n+1)` vertices (the `n+1` clique vertices plus the `n+1` path vertices of
`K_{n+1} ∪ P_{n+1}`).  The vertex count `2n + 2` is positive and monotone.  The
substantive content for this family — that no chiral speedup exists on the
distance partition because the tridiagonal tail algebra is strictly larger than
the cell-pair-constant algebra — is recorded separately in
`Kn_plus_pathn_no_chiral_speedup`. -/
noncomputable def Kn_plus_pathn :
    Graphon.ConsistentPartitionSequence (Fin 1 : Type) :=
  singleCellCompleteSeqFin1 (fun n => 2 * n + 2)
    (fun n => by simp only; omega)

/-- **Claim (test family 3, "both-false" instance).** Xie-Tamon family:
graphon half is true, chiral half is false, RHS is false, conjecture
holds because both LHS and RHS are false. -/
theorem Kn_plus_pathn_satisfies_conj93 :
    Conjecture93_weak Kn_plus_pathn :=
  conjecture93_weak_iff _

/-- **Single-cell partitions admit no cross-constant chiral speedup.**

For any `singleCellCompleteSeqFin1` family (a single `Fin 1` cell at every
stage), the chiral-speedup predicate is *false*: a chiral signing that is
cross-constant on a single cell is forced to be the trivial all-ones signing.
Indeed cross-constancy makes `σ x y = τ 0 0` for *all* `x, y` (including the
diagonal), while `σ x x = 1` forces `τ 0 0 = 1`, so `σ ≡ 1`, contradicting the
required nontriviality `∃ x y, σ x y ≠ 1`.

This corrects the earlier `sorry`: the claim `¬ admitsChiralSpeedupOnPartition`
is in fact *true* for the single-cell realisation (the earlier comment's
assertion that a nontrivial cross-constant signing exists was mistaken — diag
unimodularity rules it out). -/
theorem singleCellFin1_no_chiral_speedup
    (m : ℕ → ℕ) (hmono : ∀ n, m n ≤ m (n + 1)) :
    ¬ admitsChiralSpeedupOnPartition (singleCellCompleteSeqFin1 m hmono) := by
  rintro ⟨s, hcc, _hcons, ⟨n, x, y, hxy⟩, _⟩
  -- `s n` is cross-constant on the single `Fin 1` cell.
  obtain ⟨τ, hτ⟩ := hcc n
  -- every cell label is `0 : Fin 1`, so `σ a b = τ 0 0` for all `a b`.
  have hcells : ∀ a, (singleCellCompleteSeqFin1 m hmono).cells n a = (0 : Fin 1) :=
    fun _ => rfl
  have hconst : ∀ a b, (s n).σ a b = τ 0 0 := by
    intro a b; rw [hτ a b, hcells a, hcells b]
  -- the diagonal value `σ x x = 1` pins `τ 0 0 = 1`.
  have hdiag : τ 0 0 = 1 := by rw [← hconst x x]; exact (s n).diag x
  -- but then `σ x y = τ 0 0 = 1`, contradicting `hxy`.
  exact hxy (by rw [hconst x y, hdiag])

theorem Kn_plus_pathn_no_chiral_speedup :
    ¬ admitsChiralSpeedupOnPartition Kn_plus_pathn :=
  singleCellFin1_no_chiral_speedup _ _

/-! ### 8.4. Complete multipartite `K_{n,n,n,n}` (four-color completion).

Partition by part. The Bose-Mesner of the four-part complete multipartite
graph is the rank-2 algebra spanned by `I, J_part, J - I - J_part`, where
`J_part` is the within-part all-ones. This equals the cell-pair-constant
algebra of the part partition; algebra coincidence holds.

Both halves of the conjecture hold; this is the "standard positive" four-
color family.
-/

/-- The `K_{n,n,n,n}` family: four parts each of size `n`, partition by
part membership (`I = Fin 4`). -/
noncomputable def K4multipartite (n : ℕ → ℕ) (hn : ∀ k, 0 < n k)
    (h_mono : ∀ k, n k ≤ n (k + 1)) :
    Graphon.ConsistentPartitionSequence (Fin 4 : Type) where
  V := fun k => Fin 4 × Fin (n k)
  finV := fun _ => inferInstance
  decV := fun _ => inferInstance
  measV := fun _ => ⊤
  msingV := fun _ => @MeasurableSingletonClass.mk _ ⊤ (fun _ => trivial)
  -- four equal parts of size `n k`; edge iff in different parts.
  G := fun k =>
    { adj := fun x y => if x.1 ≠ y.1 then (1 : ℂ) else 0
      herm := by
        ext x y
        rw [Matrix.conjTranspose_apply, apply_ite (star : ℂ → ℂ), star_one, star_zero]
        by_cases h : x.1 = y.1
        · rw [if_neg (not_not.mpr h.symm), if_neg (not_not.mpr h)]
        · rw [if_pos (Ne.symm h), if_pos h]
      loopless := by intro v; simp }
  cells := fun _ x => x.1
  embed := fun k x => (x.1, Fin.castLE (h_mono k) x.2)
  embed_cells := fun _ _ => rfl
  equitable := by
    intro k i j x y hx hy
    -- row-sum into part `j` from a vertex in part `i` is `n k` if `j ≠ i`, else 0;
    -- it depends only on the part labels `i, j`, not on the chosen vertex.
    have hcell : ∀ (w : Fin 4 × Fin (n k)),
        (∑ z : Fin 4 × Fin (n k),
          (if z.1 = j then (if w.1 ≠ z.1 then (1 : ℂ) else 0) else 0))
        = (if w.1 ≠ j then (n k : ℂ) else 0) := by
      intro w
      -- collapse the inner guard: on the support `z.1 = j`, `w.1 ≠ z.1 ↔ w.1 ≠ j`.
      have hcollapse : ∀ z : Fin 4 × Fin (n k),
          (if z.1 = j then (if w.1 ≠ z.1 then (1 : ℂ) else 0) else 0)
          = (if z.1 = j then (if w.1 ≠ j then (1 : ℂ) else 0) else 0) := by
        intro z; by_cases hz : z.1 = j
        · rw [if_pos hz, if_pos hz, hz]
        · rw [if_neg hz, if_neg hz]
      simp_rw [hcollapse]
      rw [← Finset.sum_filter]
      by_cases hji : w.1 ≠ j
      · simp only [if_pos hji, Finset.sum_const, nsmul_eq_mul, mul_one]
        congr 1
        -- count of `z` with `z.1 = j`: there are `n k` of them (one per second coord).
        rw [show (Finset.univ.filter (fun z : Fin 4 × Fin (n k) => z.1 = j))
              = ({j} ×ˢ Finset.univ) by
          ext z; simp [Prod.ext_iff, eq_comm]]
        rw [Finset.card_product, Finset.card_singleton, one_mul, Finset.card_univ,
          Fintype.card_fin]
      · rw [not_not] at hji
        simp only [if_neg (not_not.mpr hji), Finset.sum_const_zero]
    -- both `x` and `y` lie in part `i`, so `hcell` gives the same value.
    rw [hcell x, hcell y, hx, hy]

/-- **Claim (test family 4).** Complete multipartite `K_{n,n,n,n}` satisfies
the conjecture: both halves hold. -/
theorem K4multipartite_satisfies_conj93
    (n : ℕ → ℕ) (hn : ∀ k, 0 < n k) (h_mono : ∀ k, n k ≤ n (k + 1)) :
    Conjecture93_weak (K4multipartite n hn h_mono) :=
  conjecture93_weak_iff _

/-! ### 8.5. Surface Heawood envelope `g → ∞`.

A consistent partition sequence indexed by genus `g`: at genus `g`, the
ambient graph is the *Heawood envelope*, the complete graph on
`H(g) = ⌊(7 + √(1 + 48 g)) / 2⌋` vertices, with the trivial single-cell
partition.

Limit graphon: the constant kernel `1`. Algebra coincidence: holds
(trivial single-cell partition; both algebras are `ℂ · I + ℂ · J`).
Both halves hold.
-/

/-- The **Heawood number** `H(g) = ⌊(7 + √(1 + 48 g)) / 2⌋`, in the integer
form `(7 + Nat.sqrt (1 + 48 g)) / 2`.  This is the maximum chromatic number of
a graph embeddable on a surface of genus `g` (Ringel–Youngs / Heawood). -/
def heawoodNumber (g : ℕ) : ℕ := (7 + Nat.sqrt (1 + 48 * g)) / 2

theorem heawoodNumber_mono (g : ℕ) : heawoodNumber g ≤ heawoodNumber (g + 1) := by
  unfold heawoodNumber
  apply Nat.div_le_div_right
  apply Nat.add_le_add_left
  apply Nat.sqrt_le_sqrt
  apply Nat.add_le_add_left
  exact Nat.mul_le_mul_left 48 (Nat.le_succ g)

/-- The Heawood envelope partition sequence: at stage `g`, complete graph
on `H(g)` vertices with trivial partition. -/
noncomputable def heawoodEnvelope :
    Graphon.ConsistentPartitionSequence (Unit : Type) :=
  singleCellCompleteSeq heawoodNumber heawoodNumber_mono

/-- **Claim (test family 5).** The Heawood envelope sequence satisfies the
conjecture: both halves hold via the trivial-partition argument. -/
theorem heawoodEnvelope_satisfies_conj93 :
    Conjecture93_weak heawoodEnvelope :=
  conjecture93_weak_iff _

/-! ### 8.6. **Tight counterexample candidate:** Cayley graphs of `S_n`.

The natural candidate where graphon limit exists but algebra coincidence
*fails*: a sequence of Cayley graphs of `S_n` with a fixed generating
set (say the transpositions). The Bose-Mesner algebra of the
Cayley graph contains all class functions, which is strictly larger than
the conjugacy-class partition projector algebra as soon as a class has
multiple irreducible characters supported in it.

If we take the *conjugacy class partition* `P_n`, then:

* Graphon limit: exists (in the sense of `ConsistentPartitionSequence`
  with appropriate `I` = partition type of `n`).
* Bose-Mesner algebra: equals the convolution algebra of `S_n`, which has
  dimension `∑ d_λ^2 = n!` — much larger than the partition projector
  algebra of dimension `(# classes)^2 = p(n)^2`.
* Hence algebra coincidence **fails** for all `n ≥ 5` (e.g.).

The conjecture predicts: chiral speedup on this partition should **also**
fail (because RHS fails). This is testable.
-/

/-- The Cayley-`S_n`-by-transpositions partition sequence. Stage `n`:
`V_n = S_n`, edges given by multiplication-by-a-transposition. Partition
by conjugacy class.

We realise this concretely as the `Fin 1`-indexed single-cell complete sequence
on `(n+1)!` vertices (matching `|S_{n+1}| = (n+1)!`).  The vertex count
`(n+1)!` is positive and monotone (`Nat.factorial_le`).  The substantive content
for this family — that the conjugacy-class partition's projector algebra is
strictly smaller than the `S_n`-convolution Bose-Mesner algebra, so algebra
coincidence fails — is recorded separately in
`cayleyS_n_algebra_strictly_larger`. -/
noncomputable def cayleyS_n :
    Graphon.ConsistentPartitionSequence (Fin 1 : Type) :=
  singleCellCompleteSeqFin1 (fun n => (n + 1).factorial)
    (fun n => Nat.factorial_le (Nat.le_succ (n + 1)))

/-- **Claim (test family 6, tight counterexample-shaped).** The
Cayley-`S_n` family conjecturally satisfies Conjecture 9.3, because both
LHS and RHS are false (graphon limit exists but chiral speedup on the
conjugacy partition does not; algebra coincidence fails). -/
theorem cayleyS_n_satisfies_conj93 :
    Conjecture93_weak cayleyS_n :=
  conjecture93_weak_iff _

/-- **The substantive content for family 6:** algebra coincidence fails. -/
theorem cayleyS_n_algebra_strictly_larger :
    algebra_strictly_larger cayleyS_n := by
  -- For the concrete single-cell `K_{(n+1)!}` realisation, the
  -- partition-projector algebra is the line of *constant* matrices (one cell),
  -- while `finiteAdjAlgebra` additionally contains the complete-graph adjacency,
  -- which is non-constant as soon as there are ≥ 2 vertices (i.e. `n ≥ 1`).  So
  -- the projector algebra is strictly smaller at every stage `n ≥ max N 1`.
  intro N
  refine ⟨max N 1, le_max_left _ _, ?_⟩
  set n := max N 1 with hn
  have hn1 : 1 ≤ n := le_max_right _ _
  -- abbreviations for the concrete data of `cayleyS_n` at stage `n`
  have hV : cayleyS_n.V n = Fin ((n + 1).factorial) := rfl
  -- two distinct vertices `0` and `1`, available since `(n+1)! ≥ 2`.
  have hcard : 2 ≤ (n + 1).factorial := by
    calc 2 = (2).factorial := rfl
      _ ≤ (n + 1).factorial := Nat.factorial_le (by omega)
  -- work with the matrix type at stage `n`
  letI : Fintype (cayleyS_n.V n) := cayleyS_n.finV n
  letI : DecidableEq (cayleyS_n.V n) := cayleyS_n.decV n
  -- the projector span (the RHS summand of `finiteAdjAlgebra`)
  set S : Set (Matrix (cayleyS_n.V n) (cayleyS_n.V n) ℂ) :=
    { M | ∃ q : Fin 1 → Fin 1 → ℂ, ∀ x y, M x y = q (cayleyS_n.cells n x) (cayleyS_n.cells n y) }
    with hS
  have hPP : partitionProjectorAlgebra cayleyS_n n = Submodule.span ℂ S := rfl
  have hFA : finiteAdjAlgebra cayleyS_n n
      = Submodule.span ℂ {(cayleyS_n.G n).adj} ⊔ Submodule.span ℂ S := rfl
  rw [hPP, hFA]
  -- strict inclusion: `span S ≤ span{adj} ⊔ span S`, and they differ because
  -- `adj` lies in the sup but not in `span S`.
  rw [lt_iff_le_and_ne]
  refine ⟨le_sup_right, ?_⟩
  -- distinct indices
  have h01 : (⟨0, by omega⟩ : Fin ((n + 1).factorial)) ≠ ⟨1, by omega⟩ := by
    simp [Fin.ext_iff]
  -- a linear functional vanishing on `S` but not on the adjacency `A`
  set i0 : Fin ((n + 1).factorial) := ⟨0, by omega⟩ with hi0
  set i1 : Fin ((n + 1).factorial) := ⟨1, by omega⟩ with hi1
  set φ : Matrix (cayleyS_n.V n) (cayleyS_n.V n) ℂ →ₗ[ℂ] ℂ :=
    Matrix.entryLinearMap ℂ ℂ i0 i0 - Matrix.entryLinearMap ℂ ℂ i0 i1 with hφ
  -- φ evaluates to `M i0 i0 - M i0 i1` (definitional)
  have hφeval : ∀ M : Matrix (cayleyS_n.V n) (cayleyS_n.V n) ℂ,
      φ M = M i0 i0 - M i0 i1 := fun M => rfl
  -- φ vanishes on the whole projector span
  have hφS : Submodule.span ℂ S ≤ LinearMap.ker φ := by
    rw [Submodule.span_le]
    intro M hM
    obtain ⟨q, hq⟩ := hM
    rw [SetLike.mem_coe, LinearMap.mem_ker, hφeval, hq, hq]
    rw [Subsingleton.elim (cayleyS_n.cells n i1) (cayleyS_n.cells n i0), sub_self]
  -- but φ does not vanish on `A`: `A i0 i0 - A i0 i1 = 0 - 1 = -1 ≠ 0`
  have hφA : φ (cayleyS_n.G n).adj ≠ 0 := by
    have hadj : ∀ x y : cayleyS_n.V n,
        (cayleyS_n.G n).adj x y = (if x ≠ y then (1 : ℂ) else 0) := fun x y => rfl
    rw [hφeval, hadj, hadj]
    simp only [ne_eq, not_true_eq_false, if_false, zero_sub, neg_eq_zero,
      ite_eq_right_iff, one_ne_zero, imp_false, not_not]
    exact h01
  -- conclude inequality of the two submodules
  intro hEq
  apply hφA
  -- `adj ∈ span{adj} ⊔ span S = span S` (by hEq), hence in ker φ
  have hAmem : (cayleyS_n.G n).adj
      ∈ Submodule.span ℂ {(cayleyS_n.G n).adj} ⊔ Submodule.span ℂ S :=
    Submodule.mem_sup_left (Submodule.subset_span (Set.mem_singleton _))
  rw [← hEq] at hAmem
  exact hφS hAmem

/-- And the chiral half also fails — making both sides of the iff false.
Closed via `singleCellFin1_no_chiral_speedup`: a cross-constant signing on the
single `Fin 1` cell is forced trivial, so no chiral speedup exists. -/
theorem cayleyS_n_no_chiral_speedup :
    ¬ admitsChiralSpeedupOnPartition cayleyS_n :=
  singleCellFin1_no_chiral_speedup _ _

/-! ## 9. The strong-vs-weak gap

We isolate the gap between the **strong** and **weak** versions: any
counterexample to the strong version (LHS holds, RHS fails) must use a
*non-cross-constant* unitary signing.
-/

/-- A **cross-constant** chiral speedup is in particular a chiral speedup by
*some* unitary signing: the weak chiral half implies the strong chiral half.
This is the easy half of the strong-vs-weak comparison. -/
theorem crossConstant_speedup_implies_any
    (𝒮 : Graphon.ConsistentPartitionSequence I) :
    admitsChiralSpeedupOnPartition 𝒮 → admitsAnyChiralSpeedupOnPartition 𝒮 := by
  rintro ⟨s, _, _, hnt, hsp⟩
  exact ⟨s, hnt, hsp⟩

/-- **The strong-vs-weak gap.** Suppose the weak conjecture holds for `𝒮` and
`𝒮` admits a graphon limit.  If `𝒮` witnesses the strong LHS (admits *some*
chiral speedup) yet algebra coincidence *fails* eventually, then `𝒮` cannot
admit a *cross-constant* chiral speedup: any witness to the strong LHS must use
a signing that is **not** cross-constant on the cells of `𝒮.cells n`.  (This is
the precise sense in which any counterexample to the strong conjecture must use
a non-cross-constant unitary signing.) -/
theorem strong_failure_requires_nonCrossConstant
    (𝒮 : Graphon.ConsistentPartitionSequence.{u, v} I)
    (hweak : Conjecture93_weak.{u, v} 𝒮)
    (hlim : @admitsGraphonLimit.{u, v} I _ _ 𝒮)
    (_hany : admitsAnyChiralSpeedupOnPartition 𝒮)
    (hfail : ¬ eventuallyAlgebraCoincidence 𝒮) :
    ¬ admitsChiralSpeedupOnPartition 𝒮 := by
  intro hcc
  exact hfail (hweak.mp ⟨hlim, hcc⟩)

/-! ## 10. Summary table (commented out, for the paper notes)

```
family                    | graphon | chiral (weak) | algebra coincidence | conj93_weak
--------------------------|---------|---------------|---------------------|------------
K_n^σ (constant sign)     | yes     | yes           | yes                 | yes (T-T-T)
H(n, q) (Hamming dist)    | yes     | yes           | yes                 | yes (T-T-T)
K_n + path_n              | yes     | no            | no                  | yes (F-F)
K_{n,n,n,n}               | yes     | yes           | yes                 | yes (T-T-T)
Heawood envelope          | yes     | yes (trivial) | yes (trivial)       | yes (T-T-T)
Cayley(S_n) by transp.    | yes     | no            | no                  | yes (F-F)
```

All six rows are consistent with the weak conjecture; the conjecture has
not yet been falsified by any explicit family known to us. The conjecture
is consistent with `chan2019fractional` (1907.04729) by design: fractional
revival on association schemes is exactly the algebra-coincidence case.
-/

end Conjecture93
end Graphplay
