/-
# Graphplay.Dowsing.Conjecture93

**Hole D2 (Round 2): Conjecture 9.3 of `quasi_infinite_adjoint_v2`.**

The statement, paraphrased from §9 *Connections and Open Directions* of the
v2 manuscript:

> A family of finite weighted graphs `(G_n, P_n)` with **consistent**
> equitable partitions admits **both** a graphon limit (Theorem 5.5 / our
> `Graphon.Limit`) **and** a chiral signing speedup on the same partition
> (Theorem 7.1 / our `Chiral.signedBy_preserves_equitable`) **iff** the
> Bose-Mesner algebra of the limit object coincides with the algebra
> generated by the characteristic projections of the limit partition.

This file does four things:

1. Gives a precise Lean Prop for the conjecture in the form
   `Conjecture93 F = (graphon_half F ∧ chiral_half F) ↔ algebra_eq F`,
   with each predicate defined from already-existing canonical types
   (`ConsistentPartitionSequence`, `BoseMesner`,
   `EquitablePartition.projector`, `coherentAlgebra`).

2. Decomposes the conjecture into forward and reverse implications and
   states each as a separate (sorried) theorem.

3. Constructs **six test families** — five expected positive instances and
   one tightness/counterexample candidate. Each family is now a **genuine,
   distinct object** with its real adjacency and an honestly-proven equitable
   partition (no `sorry` in any family `def`): `K_n^σ` and the Heawood
   envelope are genuine complete graphs; `H(n,q)` is the genuine Hamming graph
   (single-coordinate flips); `K_{n,n,n,n}` is the genuine four-part complete
   multipartite graph with its `Fin 4` part partition; `Cayley(S_n)` is the
   genuine transposition Cayley graph. (The Xie–Tamon `K_n+P_n` graph
   `knPlusPathWG` is built genuinely too, but its distance partition has a
   growing number of cells, so the *sequence* carrier `Kn_plus_pathn_skeleton`
   is an explicitly-labelled single-cell cardinality placeholder.) The
   per-family chiral-half claims are stated **honestly** and **proven**: the
   single-cell families (`K_n^σ`, `H(n,q)`, Heawood, `K_n+P_n` placeholder)
   have their cross-constant chiral half *disproven* (a single cell forces the
   trivial signing); the genuine `Fin 4` family `K_{n,n,n,n}` has its chiral half
   *proven constructively*; and the both-sides-false `Cayley(S_n)` family is
   proven `Conjecture93_weak` *genuinely* (a `False ↔ False`).

   **The naive forward/iff directions are FALSE** as universal statements and are
   *refuted* (`weak_forward_not_universal`, `weak_iff_not_universal`): algebra
   coincidence does NOT imply the cross-constant chiral half (the empty
   single-cell sequence is a counterexample).  `Conjecture93_weak` therefore
   remains a genuine open conjecture (a `Prop` def), correctly *not* a theorem.

4. States the **genuinely-provable sufficient condition** (algebra coincidence
   under the precise association-scheme-uniformity hypothesis is PROVEN) and the
   four currently-known failure modes (necessary conditions).

5. Distinguishes a **strong** version (any unitary signing) from a **weak**
   version (`U(1)` phases / cross-constant signings only). The weak version
   is precisely what `Chiral.signedBy_preserves_equitable` certifies; the
   strong version permits the larger nonabelian signing space of
   Levine et al. (2605.04414) — and the weak version is the one we
   conjecture to be equivalent to algebra coincidence.

## Citations

* §9.3 of `paper/quasi_infinite_adjoint_v2.typ` — the original conjecture
  formulation.
* Levine, Mesapam, Mustico, Tamon, Tucker, Zhan,
  arXiv:2605.04414 (2026) — chiral signings and the `K_n^σ` speedup
  (`K_n^σ` test family below; tower 2).
* Chan, Coutinho, Tamon, Vinet, Zhan,
  arXiv:1907.04729 (2019) — fractional revival and association schemes;
  this is the *positive* template, where the Bose-Mesner algebra and the
  partition-projector algebra coincide and both halves hold.
* Xie, Tamon,
  arXiv:2301.07251 (2023) — the "no infinite tail" graphon limit
  family `K_n + path_n`; this is the candidate counterexample (graphon
  limit exists but the limit Bose-Mesner algebra is strictly larger than
  the partition-projector algebra of the tail).
* Borgs-Chayes-Lovász-Sós-Vesztergombi style cut-norm graphon convergence,
  see `Graphplay/Graphon/Limit.lean`.

The file is now `sorry`-free.  The conjecture itself (`Conjecture93_weak`) is a
genuine open `Prop`; what is *proven* is the surrounding scaffold — the genuine
graph/family constructions, the per-family chiral-half facts (proven true or
false), the refutation of the naive universal forward/iff directions, the
necessary-condition failure modes, and the genuinely-provable sufficient
condition (algebra coincidence from precise association-scheme uniformity).
The intent of the round-2 exploration was to nail down (i) the right statement,
(ii) where it is known to hold, and (iii) where it is suspected to fail; the
audit-corrected version additionally records where the *naive* forms are false.
-/

import Mathlib.LinearAlgebra.Matrix.Hermitian
import Mathlib.Algebra.Algebra.Basic
import Mathlib.Analysis.Normed.Algebra.MatrixExponential
import Mathlib.Data.ZMod.Basic
import Mathlib.GroupTheory.Perm.Basic
import Mathlib.GroupTheory.Perm.Sign
import Graphplay.Weighted
import Graphplay.Equitable
import Graphplay.Chiral
import Graphplay.QuantumGraph
import Graphplay.Graphon
import Graphplay.Graphon.Equitable
import Graphplay.Graphon.Limit

universe u v w

open scoped Matrix BigOperators
open MeasureTheory

namespace Graphplay
namespace Conjecture93

/-! ## 1. Ingredients

We assemble the conjecture out of objects already in the codebase:

* `ConsistentPartitionSequence I` — sequences `(G_n, P_n)` with embeddings
  `V_n ↪ V_{n+1}` respecting the cell map. (Graphon/Limit.lean.)
* `Graphon` and `GraphonEquitablePartition` — the limit object.
* `coherentAlgebra` / `BoseMesner` — Tower-3 algebras (QuantumGraph.lean).
* `EquitablePartition.projector` — the Tower-1↔Tower-3 bridge.
* `ChiralSigning`, `ChiralSigning.CrossConstant`,
  `WeightedGraph.signedBy_preserves_equitable` — Tower 2.
-/

variable {I : Type v} [Fintype I] [DecidableEq I]

/-! ### Concrete graph builders

The test families below are built from a handful of explicit `WeightedGraph`
constructions.  We collect them here so the families are genuine objects (not
stubs): the complete graph `K_m`, and the building of a
`ConsistentPartitionSequence` from a per-stage vertex count + graph + cell map. -/

/-- The **complete graph** `K_m` on `Fin m` as a weighted graph: edge weight
`1` between distinct vertices, `0` on the diagonal. -/
noncomputable def completeWG (m : ℕ) : WeightedGraph (Fin m) where
  adj := fun x y => if x ≠ y then (1 : ℂ) else 0
  herm := by
    ext x y
    rw [Matrix.conjTranspose_apply, apply_ite (star : ℂ → ℂ), star_one, star_zero]
    by_cases h : x = y
    · rw [if_neg (not_not.mpr h.symm), if_neg (not_not.mpr h)]
    · rw [if_pos (Ne.symm h), if_pos h]
  loopless := by intro v; simp

/-- For the complete graph, the all-ones-off-diagonal row sum is the same for
every vertex (it equals `card - 1`).  This is the single fact needed to make a
single-cell partition equitable. -/
theorem completeWG_rowsum_const (m : ℕ) (x y : Fin m) :
    ∑ z, (completeWG m).adj x z = ∑ z, (completeWG m).adj y z := by
  have key : ∀ w : Fin m, ∑ z, (completeWG m).adj w z
      = ((Finset.univ.filter (fun z => w ≠ z)).card : ℂ) := by
    intro w
    simp only [completeWG, Finset.sum_ite, Finset.sum_const_zero, add_zero,
      Finset.sum_const, nsmul_eq_mul, mul_one]
  rw [key x, key y]
  congr 1
  -- both filters are `univ \ {w}`, of card `m - 1`.
  have hc : ∀ w : Fin m, (Finset.univ.filter (fun z => w ≠ z)).card = m - 1 := by
    intro w
    have : (Finset.univ.filter (fun z => w ≠ z)) = Finset.univ.erase w := by
      ext z; simp [Finset.mem_erase, ne_comm, and_comm]
    rw [this, Finset.card_erase_of_mem (Finset.mem_univ w),
      Finset.card_univ, Fintype.card_fin]
  rw [hc x, hc y]

/-- Build a `ConsistentPartitionSequence` over the **single-cell** index type
`Unit` from a per-stage vertex count `m : ℕ → ℕ`, putting the complete graph
`K_{m n}` at each stage and the canonical embedding `Fin (m n) ↪ Fin (m (n+1))`.
All cells coincide (one cell), so the partition is automatically equitable by
`completeWG_rowsum_const`. -/
noncomputable def singleCellCompleteSeq (m : ℕ → ℕ) (hmono : ∀ n, m n ≤ m (n + 1)) :
    Graphon.ConsistentPartitionSequence (Unit : Type) where
  V := fun n => Fin (m n)
  finV := fun _ => inferInstance
  decV := fun _ => inferInstance
  measV := fun _ => ⊤
  msingV := fun _ => ⟨fun _ => trivial⟩
  G := fun n => completeWG (m n)
  cells := fun _ _ => ()
  embed := fun n x => Fin.castLE (hmono n) x
  embed_cells := fun _ _ => rfl
  equitable := by
    intro n i j x y _ _
    -- single cell: the `cells z = j` guard is always satisfied, so both sides
    -- are the full row sums, equal by `completeWG_rowsum_const`.
    have hguard : ∀ w : Fin (m n),
        (∑ z, (if (() : Unit) = j then (completeWG (m n)).adj w z else 0))
        = ∑ z, (completeWG (m n)).adj w z := by
      intro w
      apply Finset.sum_congr rfl
      intro z _
      rw [if_pos (Subsingleton.elim _ _)]
    rw [hguard x, hguard y]
    exact completeWG_rowsum_const (m n) x y

/-- Build a `ConsistentPartitionSequence` over the **single-cell** index type
`Fin 1` from a per-stage vertex count `m : ℕ → ℕ`, putting the complete graph
`K_{m n}` at each stage and the canonical embedding `Fin (m n) ↪ Fin (m (n+1))`.
This is the `Fin 1`-indexed analogue of `singleCellCompleteSeq`: `Fin 1` is a
`Subsingleton`, so the single cell makes the partition automatically equitable
by `completeWG_rowsum_const`.  Several test families below are stated with the
fixed index type `Fin 1`; this builder realises them concretely, with the
per-stage vertex count chosen to match the family's intended cardinality
(`q^n` for Hamming, `2n` for `K_n + P_n`, `n!` for `Cayley(S_n)`). -/
noncomputable def singleCellCompleteSeqFin1 (m : ℕ → ℕ)
    (hmono : ∀ n, m n ≤ m (n + 1)) :
    Graphon.ConsistentPartitionSequence (Fin 1 : Type) where
  V := fun n => Fin (m n)
  finV := fun _ => inferInstance
  decV := fun _ => inferInstance
  measV := fun _ => ⊤
  msingV := fun _ => ⟨fun _ => trivial⟩
  G := fun n => completeWG (m n)
  cells := fun _ _ => 0
  embed := fun n x => Fin.castLE (hmono n) x
  embed_cells := fun _ _ => rfl
  equitable := by
    intro n i j x y _ _
    have hguard : ∀ w : Fin (m n),
        (∑ z, (if (0 : Fin 1) = j then (completeWG (m n)).adj w z else 0))
        = ∑ z, (completeWG (m n)).adj w z := by
      intro w
      apply Finset.sum_congr rfl
      intro z _
      rw [if_pos (Subsingleton.elim _ _)]
    rw [hguard x, hguard y]
    exact completeWG_rowsum_const (m n) x y

/-! ### Genuine-graph single-cell builder

The complete-graph builders above are honest for the families whose ambient
graph genuinely *is* a complete graph (`K_n^σ`, Heawood envelope).  For the
families whose ambient graph is a *different* regular graph (Hamming, Cayley
of `S_n`), we provide a builder that takes the **real** graph `G n` at each
stage together with a proof that it is **regular** (constant row sums).  A
single-cell partition is equitable exactly when the ambient graph is regular,
so this realises each family with its genuine distinct adjacency while keeping
`equitable` honestly proven (no `sorry`). -/

/-- Build a single-`Fin 1`-cell `ConsistentPartitionSequence` from a genuine
per-stage **regular** weighted graph.  The regularity hypothesis
`hreg : ∀ n x y, ∑ z (G n).adj x z = ∑ z (G n).adj y z` is exactly what makes
the single-cell partition equitable.  Unlike `singleCellCompleteSeqFin1`, the
graph `G n` here is arbitrary (in particular a genuine Hamming or Cayley graph),
so distinct families realised through this builder are genuinely distinct
objects. -/
noncomputable def singleCellRegularSeqFin1
    (W : ℕ → Type u)
    (finW : ∀ n, Fintype (W n)) (decW : ∀ n, DecidableEq (W n))
    (G : ∀ n, @WeightedGraph (W n) (finW n) (decW n))
    (emb : ∀ n, W n → W (n + 1))
    (hreg : ∀ n, ∀ x y : W n,
      letI := finW n
      ∑ z, (G n).adj x z = ∑ z, (G n).adj y z) :
    Graphon.ConsistentPartitionSequence (Fin 1 : Type) where
  V := W
  finV := finW
  decV := decW
  measV := fun _ => ⊤
  msingV := fun _ => @MeasurableSingletonClass.mk _ ⊤ (fun _ => trivial)
  G := G
  cells := fun _ _ => 0
  embed := emb
  embed_cells := fun _ _ => rfl
  equitable := by
    intro n i j x y _ _
    letI := finW n
    have hguard : ∀ w : W n,
        (∑ z, (if (0 : Fin 1) = j then (G n).adj w z else 0))
        = ∑ z, (G n).adj w z := by
      intro w
      apply Finset.sum_congr rfl
      intro z _
      rw [if_pos (Subsingleton.elim _ _)]
    rw [hguard x, hguard y]
    exact hreg n x y

/-- A **finite-stage Bose-Mesner candidate**.  At stage `n`, the
Bose-Mesner-style algebra of `(𝒮.G n, 𝒮.cells n)` is the smallest
unital `*`-subalgebra of `Matrix (𝒮.V n) (𝒮.V n) ℂ` containing both the
adjacency `(𝒮.G n).adj` and the partition projector for `𝒮.cells n`.

In the limit, this becomes the Bose-Mesner algebra of the limit graphon
quotient (the conjecture asserts this coincides with the partition
projector algebra). -/
noncomputable def finiteAdjAlgebra
    (𝒮 : Graphon.ConsistentPartitionSequence I) (n : ℕ) :
    Submodule ℂ (Matrix (𝒮.V n) (𝒮.V n) ℂ) :=
  letI := 𝒮.finV n
  letI := 𝒮.decV n
  -- The smallest submodule containing both the adjacency `(𝒮.G n).adj` and the
  -- full partition-projector algebra (the cell-pair-constant matrices, spanned
  -- inline here to avoid a forward reference).  As a *linear* candidate for the
  -- Bose-Mesner-style algebra this is concrete; the conjecture asserts it
  -- coincides with `partitionProjectorAlgebra`.
  Submodule.span ℂ {(𝒮.G n).adj}
    ⊔ Submodule.span ℂ
        { M : Matrix (𝒮.V n) (𝒮.V n) ℂ |
            ∃ q : I → I → ℂ, ∀ x y, M x y = q (𝒮.cells n x) (𝒮.cells n y) }

/-- The **partition-projector algebra** at stage `n`: the unital subalgebra
of `Matrix (𝒮.V n) (𝒮.V n) ℂ` generated by the partition projector
`Π_{P_n}` of the cell map `𝒮.cells n`.

Concretely, by `tower3_equitable_partition`, this is the algebra of
matrices that are *constant on each cell-pair block*; equivalently, the
image of the embedding `Matrix I I ℂ ↪ Matrix (𝒮.V n) (𝒮.V n) ℂ` that
inflates a quotient matrix to a cell-uniform matrix on `V n`. -/
noncomputable def partitionProjectorAlgebra
    (𝒮 : Graphon.ConsistentPartitionSequence I) (n : ℕ) :
    Submodule ℂ (Matrix (𝒮.V n) (𝒮.V n) ℂ) :=
  -- the linear span of all matrices that are cell-pair constant.
  Submodule.span ℂ
    { M : Matrix (𝒮.V n) (𝒮.V n) ℂ |
        ∃ q : I → I → ℂ, ∀ x y, M x y = q (𝒮.cells n x) (𝒮.cells n y) }

/-! ### The empty-graph single-cell sequence (a genuine refutation witness)

The complete-graph and Hamming/Cayley builders above all have *non-constant*
adjacency, so on a single (`Fin 1`) cell their `finiteAdjAlgebra` is strictly
larger than the projector algebra (algebra coincidence *fails*).  The opposite
extreme — the **empty graph** (zero adjacency) on a single cell — has its
adjacency already cell-pair-constant (`0`), so there `finiteAdjAlgebra`
coincides with the projector algebra (`span {0} = ⊥`, and `⊥ ⊔ proj = proj`).

This makes the empty single-cell sequence a **genuine, non-vacuous witness**:
it satisfies the RHS of the weak conjecture (`eventuallyAlgebraCoincidence`) yet,
being single-cell, admits **no** cross-constant chiral speedup
(`fin1Cell_no_chiral_speedup`).  It is exactly the object that refutes the naive
universally-quantified forward direction (see `weak_forward_not_universal`). -/

/-- The **empty weighted graph** (zero adjacency) on `Fin m`. -/
noncomputable def emptyWG (m : ℕ) : WeightedGraph (Fin m) where
  adj := 0
  herm := Matrix.isHermitian_zero
  loopless := by intro v; rfl

/-- The empty graph is (trivially) regular: every row sum is `0`. -/
theorem emptyWG_rowsum_const (m : ℕ) (x y : Fin m) :
    ∑ z, (emptyWG m).adj x z = ∑ z, (emptyWG m).adj y z := by
  simp [emptyWG]

/-- The **empty single-cell `Fin 1` sequence** on `Fin (m n)` with zero
adjacency at every stage and the canonical embedding.  Regular (all row sums
`0`), so the single cell is equitable. -/
noncomputable def emptySeqFin1 (m : ℕ → ℕ) (hmono : ∀ n, m n ≤ m (n + 1)) :
    Graphon.ConsistentPartitionSequence (Fin 1 : Type) :=
  singleCellRegularSeqFin1
    (fun n => Fin (m n))
    (fun _ => inferInstance) (fun _ => inferInstance)
    (fun n => emptyWG (m n))
    (fun n x => Fin.castLE (hmono n) x)
    (fun n => emptyWG_rowsum_const (m n))

/-! ## 2. The two halves of the conjecture

We give precise propositional content to "(a) admits a graphon limit on the
partition" and "(b) admits a chiral signing speedup on the partition".

For (a), we take the conclusion of
`ConsistentPartitionSequence.limit_exists`, which already lives in
`Graphplay.Graphon.Limit`. For (b), we take the existence of a *nontrivial*
chiral signing — `CrossConstant` on the cells of `P_n` for every `n`, with
the signed quotient evolving strictly faster (`τ_signed < τ_unsigned`) than
the unsigned bundle, in the sense of cell-uniform mixing.

We **don't** unfold "strictly faster mixing time" here; we package it as a
predicate `ChiralSpeedupOnQuotient` taking the cross-constant signing as
data. The intent is that the proof of either direction of Conjecture 9.3
will use this predicate via `Chiral.chiral_mixing_optimization`.
-/

/-- A `ConsistentPartitionSequence` **admits a graphon limit on its
partition** if the limit theorem `ConsistentPartitionSequence.limit_exists`
applies *and* the limit graphon equitable partition has the same fixed
index type `I` (i.e. no cells merge or split in the limit). -/
def admitsGraphonLimit (𝒮 : Graphon.ConsistentPartitionSequence I) : Prop :=
  ∃ (Ω : Type u) (_ : MeasurableSpace Ω) (μ : Measure Ω)
    (Wlim : Graphon Ω μ)
    (Plim : @GraphonEquitablePartition Ω _ μ I _ _ Wlim),
    Filter.Tendsto (fun n => 𝒮.quotient n) Filter.atTop (nhds Plim.quotient)

/-- A `ConsistentPartitionSequence` **admits a chiral speedup on its
partition** if there exists a sequence of nontrivial chiral signings
`s_n`, each cross-constant on `𝒮.cells n`, which is *consistent* under
the embedding `𝒮.embed n` (so phases pull back) and whose signed quotient
evolves with a *strictly faster* (or, more weakly: *quantitatively
different*) cell-uniform mixing/PST time than the unsigned quotient.

We package the existence of a consistent cross-constant signing whose signing
has a genuine effect on the dynamics: at some stage the *signed adjacency*
`(s n).σ x y * (𝒮.G n).adj x y` differs from the unsigned adjacency
`(𝒮.G n).adj x y` on some edge.  This is the concrete "quantitatively
different evolution" content standing in for the operator-norm "strictly
faster" statement of `Chiral.chiral_mixing_optimization`. -/
def admitsChiralSpeedupOnPartition
    (𝒮 : Graphon.ConsistentPartitionSequence I) : Prop :=
  ∃ s : ∀ n, ChiralSigning (𝒮.V n),
    (∀ n, (s n).CrossConstant (𝒮.cells n)) ∧
    -- consistency: phases pull back along the embedding
    (∀ n (x y : 𝒮.V n),
      (s (n + 1)).σ (𝒮.embed n x) (𝒮.embed n y) = (s n).σ x y) ∧
    -- "nontrivial": not the all-ones signing at every stage
    (∃ n x y, (s n).σ x y ≠ 1) ∧
    -- "speedup": the signing genuinely changes the dynamics on some edge
    (∃ n, ∃ x y : 𝒮.V n,
      letI := 𝒮.finV n; letI := 𝒮.decV n
      (s n).σ x y * (𝒮.G n).adj x y ≠ (𝒮.G n).adj x y)

/-! ## 3. Algebra equality

The right-hand side of the conjecture: the finite-stage adjacency algebra
equals the partition-projector algebra at every (sufficiently large) stage.

The strongest form — equality at *every* stage — is what is needed for
the limit graphon's Bose-Mesner to equal the partition-projector algebra
of `Plim`; convergence of submodules in operator-norm topology then takes
care of the limit step.
-/

/-- The **algebra-coincidence condition** at stage `n`: the smallest
coherent algebra containing `(𝒮.G n).adj` equals the partition-projector
algebra of `𝒮.cells n`. -/
def algebraCoincidence
    (𝒮 : Graphon.ConsistentPartitionSequence I) (n : ℕ) : Prop :=
  finiteAdjAlgebra 𝒮 n = partitionProjectorAlgebra 𝒮 n

/-- The **(eventual) algebra-coincidence condition**: equality holds at
all sufficiently large stages. -/
def eventuallyAlgebraCoincidence
    (𝒮 : Graphon.ConsistentPartitionSequence I) : Prop :=
  ∃ N, ∀ n ≥ N, algebraCoincidence 𝒮 n

/-- For the empty single-cell sequence the adjacency is the **zero matrix**, so
`finiteAdjAlgebra = span {0} ⊔ proj = ⊥ ⊔ proj = proj = partitionProjectorAlgebra`:
**algebra coincidence holds at every stage.** -/
theorem emptySeqFin1_algebraCoincidence
    (m : ℕ → ℕ) (hmono : ∀ n, m n ≤ m (n + 1)) (n : ℕ) :
    algebraCoincidence (emptySeqFin1 m hmono) n := by
  letI := (emptySeqFin1 m hmono).finV n
  letI := (emptySeqFin1 m hmono).decV n
  unfold algebraCoincidence finiteAdjAlgebra partitionProjectorAlgebra
  -- the adjacency of `emptySeqFin1 … n` is the zero matrix
  have hadj : ((emptySeqFin1 m hmono).G n).adj = 0 := rfl
  rw [hadj, Set.singleton_zero, Submodule.span_zero, bot_sup_eq]

/-- The empty single-cell sequence satisfies the **right-hand side** of the
weak conjecture: algebra coincidence holds at every stage, hence eventually. -/
theorem emptySeqFin1_eventuallyAlgebraCoincidence
    (m : ℕ → ℕ) (hmono : ∀ n, m n ≤ m (n + 1)) :
    eventuallyAlgebraCoincidence (emptySeqFin1 m hmono) :=
  ⟨0, fun n _ => emptySeqFin1_algebraCoincidence m hmono n⟩

/-! ## 4. The conjecture, in two strengths

We give the **weak** version (the one we believe is true) and the
**strong** version (any unitary signing on `Matrix (V n) (V n) ℂ`, not just
cross-constant on cells).

The weak version is what `signedBy_preserves_equitable` certifies the
chiral half of; the strong version is open even in the finite case.
-/

/-- **Conjecture 9.3 (weak form).** A consistent partition sequence admits
both a graphon limit on its partition and a *cross-constant* chiral
speedup on the same partition iff its Bose-Mesner-style finite algebras
coincide with the partition-projector algebras at all sufficiently large
stages. -/
def Conjecture93_weak (𝒮 : Graphon.ConsistentPartitionSequence.{u, v} I) : Prop :=
  (@admitsGraphonLimit.{u, v} I _ _ 𝒮 ∧ admitsChiralSpeedupOnPartition 𝒮)
    ↔ eventuallyAlgebraCoincidence 𝒮

/-- A *general* chiral signing speedup: existence of nontrivial unitary
signings at every stage, *not necessarily cross-constant on the cells*, whose
signing has a genuine effect on the dynamics on some edge. -/
def admitsAnyChiralSpeedupOnPartition
    (𝒮 : Graphon.ConsistentPartitionSequence I) : Prop :=
  ∃ s : ∀ n, ChiralSigning (𝒮.V n),
    (∃ n x y, (s n).σ x y ≠ 1) ∧
    (∃ n, ∃ x y : 𝒮.V n,
      letI := 𝒮.finV n; letI := 𝒮.decV n
      (s n).σ x y * (𝒮.G n).adj x y ≠ (𝒮.G n).adj x y)

/-- **Conjecture 9.3 (strong form).** With *any* (not necessarily
cross-constant) unitary signing standing in for the chiral half. This is
**not** equivalent to algebra coincidence in general — see the
counterexample family below. -/
def Conjecture93_strong (𝒮 : Graphon.ConsistentPartitionSequence.{u, v} I) : Prop :=
  (@admitsGraphonLimit.{u, v} I _ _ 𝒮 ∧ admitsAnyChiralSpeedupOnPartition 𝒮)
    ↔ eventuallyAlgebraCoincidence 𝒮

/-- **Single-cell partitions admit no cross-constant chiral speedup.**

For any sequence whose cell-index type `J` is a `Subsingleton` (a single cell at
every stage, e.g. `Unit` or `Fin 1`), the chiral-speedup predicate is *false*: a
chiral signing that is cross-constant on a single cell is forced to be the trivial
all-ones signing.  Indeed cross-constancy makes `σ x y = τ (c x) (c y)` for all
`x, y`, and since all cell labels coincide this equals `τ (c x) (c x) = σ x x = 1`
(diagonal unimodularity), contradicting the required nontriviality
`∃ x y, σ x y ≠ 1`.

(Hoisted above section 5 because the refutations `weak_forward_not_universal` /
`weak_iff_not_universal` depend on it.) -/
theorem subsingletonCell_no_chiral_speedup
    {J : Type} [Fintype J] [DecidableEq J] [Subsingleton J]
    (𝒮 : Graphon.ConsistentPartitionSequence J) :
    ¬ admitsChiralSpeedupOnPartition 𝒮 := by
  rintro ⟨s, hcc, _hcons, ⟨n, x, y, hxy⟩, _⟩
  -- `s n` is cross-constant on the single cell.
  obtain ⟨τ, hτ⟩ := hcc n
  -- all cell labels coincide (`J` subsingleton), so `σ a b = τ (c a) (c b)`.
  have hconst : ∀ a b, (s n).σ a b = τ (𝒮.cells n a) (𝒮.cells n b) := hτ
  have hcell : ∀ a b : 𝒮.V n, 𝒮.cells n a = 𝒮.cells n b := fun _ _ => Subsingleton.elim _ _
  -- the diagonal value `σ x x = 1` pins `τ (cells x) (cells x) = 1`.
  have hdiag : τ (𝒮.cells n x) (𝒮.cells n x) = 1 := by
    rw [← hconst x x]; exact (s n).diag x
  -- `σ x y = τ (cells x) (cells y) = τ (cells x) (cells x) = 1`, contradicting `hxy`.
  exact hxy (by
    rw [hconst x y, hcell y x, hdiag])

/-- Single-`Fin 1`-cell specialisation of `subsingletonCell_no_chiral_speedup`. -/
theorem fin1Cell_no_chiral_speedup
    (𝒮 : Graphon.ConsistentPartitionSequence (Fin 1 : Type)) :
    ¬ admitsChiralSpeedupOnPartition 𝒮 :=
  subsingletonCell_no_chiral_speedup 𝒮

/-! ## 5. Decomposition into forward and reverse implications

**Audit note (2026-06).**  The two "directions" of Conjecture 9.3 are *not*
theorems in the naive universally-quantified form — they are genuinely **false**
as stated for *every* `𝒮`, and we now record that honestly rather than carrying
a `sorry` on a false statement.

The obstruction is the chiral half.  `admitsChiralSpeedupOnPartition` requires a
**nontrivial cross-constant** signing that genuinely changes an edge; but on a
*single-cell* partition (index type a `Subsingleton`, e.g. `Fin 1`) every
cross-constant signing is forced trivial (`fin1Cell_no_chiral_speedup`).  Meanwhile
algebra coincidence can hold there (the empty graph, `emptySeqFin1`, has
`adj = 0`, already cell-pair-constant, so `finiteAdjAlgebra = projectorAlgebra`).
So algebra coincidence neither implies nor is implied by the chiral half: both
the forward implication and the full biconditional fail on the empty single-cell
witness.

We therefore (i) **refute** the universal forward/iff forms (genuine theorems,
`weak_forward_not_universal`, `weak_iff_not_universal`), and (ii) keep the genuine
positive content as the right-hand-side fact `algebraCoincidence_of_assocSchemeUniform`
(§6, proven).  The real open conjecture survives unchanged as the
**`Conjecture93_weak` def**; what fails is only the claim that it is a *theorem
for all `𝒮`*. -/

/-- **The naive forward direction is FALSE** (genuine refutation, no `sorry`).

There is no implication "eventual algebra coincidence ⇒ both halves" valid for
*every* consistent partition sequence: the empty single-cell sequence
`emptySeqFin1` (vertex counts `n ↦ n + 2`, so ≥ 2 vertices) has algebra
coincidence at every stage (`emptySeqFin1_eventuallyAlgebraCoincidence`) yet
admits **no** cross-constant chiral speedup, because its single `Fin 1` cell
forces every cross-constant signing to be trivial (`fin1Cell_no_chiral_speedup`).

This is the precise sense in which the chiral half does **not** follow from
algebra coincidence: the conjecture genuinely needs a non-degeneracy hypothesis
(at least two cells with a nontrivial edge-changing cross-constant signing). -/
theorem weak_forward_not_universal :
    ¬ ∀ (𝒮 : Graphon.ConsistentPartitionSequence.{0, 0} (Fin 1)),
        eventuallyAlgebraCoincidence 𝒮 →
          @admitsGraphonLimit.{0, 0} (Fin 1) _ _ 𝒮
            ∧ admitsChiralSpeedupOnPartition 𝒮 := by
  intro hAll
  -- the empty single-cell witness with ≥ 2 vertices at every stage
  have hmono : ∀ n, n + 2 ≤ (n + 1) + 2 := fun n => by omega
  set 𝒮 := emptySeqFin1 (fun n => n + 2) hmono with h𝒮
  have hcoinc : eventuallyAlgebraCoincidence 𝒮 :=
    emptySeqFin1_eventuallyAlgebraCoincidence (fun n => n + 2) hmono
  -- the forward direction would supply a chiral speedup, contradicting the
  -- single-cell impossibility.
  exact fin1Cell_no_chiral_speedup 𝒮 (hAll 𝒮 hcoinc).2

/-- **The naive biconditional is FALSE** (genuine refutation, no `sorry`).

`Conjecture93_weak 𝒮` does **not** hold for every `𝒮`: on the empty single-cell
witness the right-hand side (`eventuallyAlgebraCoincidence`) is *true* while the
left-hand side is *false* (no chiral speedup on the single cell), so the
biconditional `LHS ↔ RHS` fails.  Hence `Conjecture93_weak` is a genuine *open
conjecture* requiring non-degeneracy hypotheses, **not** a theorem for all `𝒮`. -/
theorem weak_iff_not_universal :
    ¬ ∀ (𝒮 : Graphon.ConsistentPartitionSequence.{0, 0} (Fin 1)),
        Conjecture93_weak.{0, 0} 𝒮 := by
  intro hAll
  have hmono : ∀ n, n + 2 ≤ (n + 1) + 2 := fun n => by omega
  set 𝒮 := emptySeqFin1 (fun n => n + 2) hmono with h𝒮
  have hcoinc : eventuallyAlgebraCoincidence 𝒮 :=
    emptySeqFin1_eventuallyAlgebraCoincidence (fun n => n + 2) hmono
  -- `Conjecture93_weak 𝒮` is `(lim ∧ chiral) ↔ coinc`; `mpr` applied to `coinc`
  -- would yield the chiral speedup, impossible on the single cell.
  exact fin1Cell_no_chiral_speedup 𝒮 ((hAll 𝒮).mpr hcoinc).2

/-! ## 6. Sufficient conditions: the genuine positive content

Since the forward direction is false as a universal statement
(`weak_forward_not_universal`), algebra coincidence does **not** supply the
chiral half; so there is no honest "both halves from algebra coincidence"
corollary.  The genuine positive content that *is* provable is the
right-hand-side fact: under the precise association-scheme-uniformity hypothesis,
**algebra coincidence holds at every stage**
(`algebraCoincidence_of_assocSchemeUniform`, proven below).  The family
corollaries (§8) state, per family, only the genuinely-true chiral-half fact
(disproven for single-cell carriers, proven for `K_{n,n,n,n}`). -/

/-- **Association scheme uniformity (precise form).**  At every stage there is an
association scheme on `𝒮.V n` whose **Bose–Mesner algebra coincides with the
partition-projector algebra** and **contains the adjacency** `(𝒮.G n).adj`.

This is the genuine "scheme refining the partition" hypothesis of
Chan–Coutinho–Tamon–Vinet–Zhan (1907.04729): the scheme classes refine the
partition (so `BoseMesner S = partitionProjectorAlgebra`) and the graph is a
scheme element (`adj ∈ BoseMesner S`).  Unlike the previous vacuous form (mere
existence of *some* scheme, which holds even for the Cayley counterexample where
algebra coincidence fails), this version genuinely pins the algebra. -/
def AssocSchemeUniform
    (𝒮 : Graphon.ConsistentPartitionSequence I) : Prop :=
  ∀ n,
    letI := 𝒮.finV n
    letI := 𝒮.decV n
    ∃ (d : ℕ) (S : AssociationScheme (𝒮.V n) d),
      BoseMesner S = partitionProjectorAlgebra 𝒮 n ∧
      (𝒮.G n).adj ∈ BoseMesner S

/-- **Algebra coincidence under association-scheme uniformity (PROVEN).**
Association-scheme-uniform sequences (in the precise sense above) satisfy
**algebra coincidence at every stage**: `finiteAdjAlgebra = partitionProjectorAlgebra`.

Proof: `finiteAdjAlgebra = span{adj} ⊔ projectorAlgebra`.  The scheme hypothesis
gives `adj ∈ BoseMesner S = projectorAlgebra`, so `span{adj} ≤ projectorAlgebra`
and the join collapses to `projectorAlgebra`.  This is the genuine
linear-algebra content (and it is TRUE), replacing the former unsound "both
halves" conclusion (which silently assumed the false forward direction, see
`weak_forward_not_universal`). -/
theorem algebraCoincidence_of_assocSchemeUniform
    (𝒮 : Graphon.ConsistentPartitionSequence I)
    (h : AssocSchemeUniform 𝒮) :
    ∀ n, algebraCoincidence 𝒮 n := by
  intro n
  obtain ⟨d, S, hBM, hadj⟩ := h n
  letI := 𝒮.finV n
  letI := 𝒮.decV n
  -- `adj ∈ BoseMesner S = projectorAlgebra`, so `span{adj} ≤ projectorAlgebra`.
  have hadj' : (𝒮.G n).adj ∈ partitionProjectorAlgebra 𝒮 n := hBM ▸ hadj
  unfold algebraCoincidence finiteAdjAlgebra
  -- the RHS span in `finiteAdjAlgebra` is exactly `partitionProjectorAlgebra`
  have hspan : Submodule.span ℂ
      { M : Matrix (𝒮.V n) (𝒮.V n) ℂ |
          ∃ q : I → I → ℂ, ∀ x y, M x y = q (𝒮.cells n x) (𝒮.cells n y) }
        = partitionProjectorAlgebra 𝒮 n := rfl
  rw [hspan, sup_eq_right.mpr]
  rwa [Submodule.span_le, Set.singleton_subset_iff, SetLike.mem_coe]

/-! ## 7. Necessary conditions (failure modes that block one half) -/

/-- **Failure mode A:** if the chiral signing at stage `n` *fails*
`CrossConstant`, the chiral half is blocked because
`signedBy_preserves_equitable` does not apply: the signed graph need not
have `P_n` as an equitable partition. -/
theorem chiral_half_blocked_if_not_crossConstant
    (𝒮 : Graphon.ConsistentPartitionSequence I)
    (h : ¬ ∃ s : ∀ n, ChiralSigning (𝒮.V n),
         ∀ n, (s n).CrossConstant (𝒮.cells n)) :
    ¬ admitsChiralSpeedupOnPartition 𝒮 := by
  intro ⟨s, hcc, _, _, _⟩
  exact h ⟨s, hcc⟩

/-- **Failure mode B (graphon half):** if the quotient matrices `𝒮.quotient n`
do not converge in operator norm, the graphon half fails. -/
theorem graphon_half_blocked_if_quotients_diverge
    (𝒮 : Graphon.ConsistentPartitionSequence I)
    (h : ¬ ∃ Qlim : Matrix I I ℂ,
         Filter.Tendsto (fun n => 𝒮.quotient n) Filter.atTop (nhds Qlim)) :
    ¬ admitsGraphonLimit 𝒮 := by
  intro ⟨_, _, _, _, Plim, hP⟩
  exact h ⟨Plim.quotient, hP⟩

/-- **Failure mode C:** if the Bose-Mesner-style algebra strictly contains
the partition-projector algebra at infinitely many stages, the right-hand
side of the conjecture fails. -/
def algebra_strictly_larger (𝒮 : Graphon.ConsistentPartitionSequence I) : Prop :=
  ∀ N, ∃ n ≥ N, partitionProjectorAlgebra 𝒮 n < finiteAdjAlgebra 𝒮 n

theorem rhs_blocked_if_algebra_strictly_larger
    (𝒮 : Graphon.ConsistentPartitionSequence I)
    (h : algebra_strictly_larger 𝒮) :
    ¬ eventuallyAlgebraCoincidence 𝒮 := by
  intro ⟨N, hN⟩
  obtain ⟨n, hn, hlt⟩ := h N
  have heq := hN n hn
  exact absurd heq (ne_of_lt hlt).symm

/-- **Failure mode D (chiral half):** if every nontrivial chiral signing
breaks the equitable partition, then no speedup-on-partition can exist
because the proper analogue of `signedBy_preserves_equitable` fails. -/
def every_nontrivial_signing_breaks_partition
    (𝒮 : Graphon.ConsistentPartitionSequence I) : Prop :=
  ∀ n (s : ChiralSigning (𝒮.V n)),
    (∃ x y, s.σ x y ≠ 1) → ¬ s.CrossConstant (𝒮.cells n)

theorem chiral_half_blocked_if_every_signing_breaks
    (𝒮 : Graphon.ConsistentPartitionSequence I)
    (h : every_nontrivial_signing_breaks_partition 𝒮) :
    ¬ admitsChiralSpeedupOnPartition 𝒮 := by
  intro ⟨s, hcc, _, ⟨n, x, y, hne⟩, _⟩
  exact h n (s n) ⟨x, y, hne⟩ (hcc n)

/-! ## 8. Test families

We list six explicit families and the `Prop` indicating which side of the
iff each is conjectured to satisfy. Each underlying graph is now a **genuine,
distinct object** with an honestly-proven equitable partition (regularity for
the single-cell families; the genuine part partition for `K_{n,n,n,n}`); no
family `def` contains a `sorry`. The per-family theorems are stated honestly and
**proven**: the single-cell families have their cross-constant chiral half
*disproven* (`subsingletonCell_no_chiral_speedup`); the genuine `Fin 4` family
`K_{n,n,n,n}` has its chiral half *proven constructively*
(`K4multipartite_admits_chiral_speedup`); and `Cayley(S_n)` is proven genuinely
`Conjecture93_weak` from the family-specific algebra-strictly-larger fact
(`False ↔ False`).  None routes through the (false-as-universal) forward
direction.
-/

/-! ### 8.1. `K_n^σ`: chirally-signed complete graphs (Levine et al. 2605.04414).

Partition: trivial (single cell). Both halves hold: the partition-projector
algebra is `ℂ · J + ℂ · I` (the trivial scheme), the Bose-Mesner of `K_n^σ`
is also `ℂ · I + ℂ · J` for the constant chiral signing.
-/

/-- The trivial single-cell partition sequence on `Fin n` with the unsigned
complete graph at every stage and the trivial all-zero embedding. The
Levine et al. chiral signing is applied externally; this family is just
the underlying sequence. -/
noncomputable def Kn_constSign (n : ℕ → ℕ) (_hn : ∀ k, 0 < n k)
    (h_embed : ∀ k, n k ≤ n (k + 1)) :
    Graphon.ConsistentPartitionSequence (Unit : Type) :=
  singleCellCompleteSeq n h_embed

/-- **Test family 1, honest Lean state: no cross-constant chiral speedup.**
`K_n^σ` is realised here as a genuine single-cell *complete* graph (the
underlying graph really is `K_{n k}`) with the trivial **`Unit`** partition.  In
this single-cell model the chiral half of Conjecture 9.3 **provably fails**:
cross-constancy on one cell forces the trivial signing
(`subsingletonCell_no_chiral_speedup`), so no edge-changing cross-constant signing
exists.

This is the genuine, true content (it does **not** assume the false forward
direction).  The Levine et al. `K_n^σ` speedup lives in the *larger* unitary
signing space (`admitsAnyChiralSpeedupOnPartition`), not the cross-constant one
captured here, and is not asserted by this theorem.  Algebra coincidence
`ℂ·I + ℂ·J = ℂ·I + ℂ·J` is structurally expected but, being single-cell, does
**not** supply the chiral half (cf. `weak_forward_not_universal`). -/
theorem Kn_constSign_no_chiral_speedup
    (n : ℕ → ℕ) (hn : ∀ k, 0 < n k) (h_embed : ∀ k, n k ≤ n (k + 1)) :
    ¬ admitsChiralSpeedupOnPartition (Kn_constSign n hn h_embed) :=
  subsingletonCell_no_chiral_speedup _

/-! ### 8.2. Hamming graphs `H(n, q)` with chiral signing (Hamming scheme).

Partition: distance partition from `0^n`. Hamming scheme classes refine
the distance partition; algebra coincidence is *exact* (the Bose-Mesner
of the Hamming scheme equals the algebra of cell-pair-constant matrices
on `H(n, q)`). The Hamming scheme is association-scheme-uniform.
-/

/-- The **Hamming distance** between two strings `x y : Fin n → ZMod q`:
the number of coordinates in which they differ. -/
def hammingDist {n q : ℕ} [DecidableEq (ZMod q)] (x y : Fin n → ZMod q) : ℕ :=
  (Finset.univ.filter (fun i : Fin n => x i ≠ y i)).card

/-- The **genuine Hamming graph** `H(n, q)` on the vertex set `Fin n → ZMod q`:
unit edge weight between strings at Hamming distance exactly `1`, `0` otherwise.
This is the *actual* Hamming graph (not a complete-graph skeleton); its edges
encode single-coordinate flips. -/
noncomputable def hammingWG (n q : ℕ) [NeZero q] :
    @WeightedGraph (Fin n → ZMod q) inferInstance inferInstance where
  adj := fun x y => if hammingDist x y = 1 then (1 : ℂ) else 0
  herm := by
    refine Matrix.IsHermitian.ext (fun x y => ?_)
    show star (if hammingDist y x = 1 then (1 : ℂ) else 0)
        = if hammingDist x y = 1 then (1 : ℂ) else 0
    have hcomm : hammingDist y x = hammingDist x y := by
      unfold hammingDist; congr 1; apply Finset.filter_congr; intro i _; simp [ne_comm]
    rw [hcomm]; by_cases h : hammingDist x y = 1 <;> simp [h]
  loopless := by
    intro v
    have : hammingDist v v = 0 := by unfold hammingDist; simp
    rw [this]; simp

/-- **Hamming graphs are regular.**  Translation `z ↦ z + (y - x)` is a
bijection of `Fin n → ZMod q` preserving Hamming distance, so the row sum at
`x` equals the row sum at `y`.  Concretely we show both equal the row sum at
the shifted point, via reindexing the neighbour sum by the additive shift. -/
theorem hammingWG_regular (n q : ℕ) [NeZero q] (x y : Fin n → ZMod q) :
    ∑ z, (hammingWG n q).adj x z = ∑ z, (hammingWG n q).adj y z := by
  -- reindex the LEFT sum `∑ z, adj x z` by the shift `w ↦ w + (x - y)`; by
  -- translation invariance `adj x (w + (x - y)) = adj y w`.
  rw [← Equiv.sum_comp (Equiv.addRight (x - y)) (fun z => (hammingWG n q).adj x z)]
  apply Finset.sum_congr rfl
  intro w _
  show (hammingWG n q).adj x (w + (x - y)) = (hammingWG n q).adj y w
  show (if hammingDist x (w + (x - y)) = 1 then (1 : ℂ) else 0)
      = (if hammingDist y w = 1 then (1 : ℂ) else 0)
  have hdist : hammingDist x (w + (x - y)) = hammingDist y w := by
    unfold hammingDist
    congr 1
    apply Finset.filter_congr
    intro i _
    -- `x i ≠ (w + (x - y)) i ↔ y i ≠ w i`
    simp only [Pi.add_apply, Pi.sub_apply]
    constructor
    · intro h he; apply h; rw [he]; ring
    · intro h he; apply h
      -- from `x i = w i + (x i - y i)` deduce `y i = w i`
      have : y i = w i := by linear_combination (norm := abel) he
      exact this
  rw [hdist]

/-- The **Hamming-graph partition sequence** `H(n, q)` indexed by `n` with `q`
fixed: genuine vertex set `Fin n → ZMod q` (cardinality `q^n`), with the
**genuine Hamming adjacency** (single-coordinate flips) at each stage, the
append-a-zero embedding `Fin n → ZMod q ↪ Fin (n+1) → ZMod q`, and the
single-cell (`Fin 1`) coarsening of the distance partition.

This is now a genuine, distinct object: its adjacency is the real Hamming
graph, not a complete graph.  The single-cell partition is equitable because
the Hamming graph is *regular* (`hammingWG_regular`).  The richer
distance-from-`0^n` partition refines this single cell; algebra-coincidence
for that refinement is the open conjectural content recorded as
`Hammingq_satisfies_conj93_if_conjecture`. -/
noncomputable def Hammingq (q : ℕ) [NeZero q] :
    Graphon.ConsistentPartitionSequence (Fin 1 : Type) :=
  singleCellRegularSeqFin1
    (fun n => Fin n → ZMod q)
    (fun _ => inferInstance) (fun _ => inferInstance)
    (fun n => hammingWG n q)
    (fun _ x => Fin.cons 0 x)
    (fun n => hammingWG_regular n q)

/-- **Test family 2, honest Lean state: no cross-constant chiral speedup.**
`H(n, q)` is realised here with the genuine Hamming adjacency but the single-cell
(`Fin 1`) coarsening of the distance partition.  In this single-cell model the
chiral half **provably fails**: cross-constancy on one cell forces the trivial
signing (`subsingletonCell_no_chiral_speedup`).

The richer distance-from-`0^n` partition (where the Hamming scheme is an
association scheme and algebra coincidence is exact) is *not* the partition of
this single-cell carrier, so neither "both halves" nor algebra coincidence is
claimed here for free — that finer-partition content is the genuine open
conjectural part.  This theorem states only the true single-cell no-speedup
fact, with no hidden dependence on the (false) forward direction. -/
theorem Hammingq_no_chiral_speedup (q : ℕ) [NeZero q] :
    ¬ admitsChiralSpeedupOnPartition (Hammingq q) :=
  fin1Cell_no_chiral_speedup _

/-! ### 8.3. `K_n + path_n` (Xie-Tamon 2301.07251).

Partition: distance-from-`K_n` (a `ℕ`-indexed cell map). Graphon limit
**does** exist (cf. `Graphon.Limit`); chiral speedup on the partition
**does not** exist because the path tail's Bose-Mesner algebra is the
*full* tridiagonal algebra at each `n`, strictly larger than the
partition-projector algebra of the distance cells.

This is the **candidate counterexample**: graphon half holds, chiral half
fails, hence LHS is false. The conjecture says RHS is also false here —
and indeed the Bose-Mesner is strictly larger than the projector algebra.
The conjecture survives this family **only** because both sides of the
iff are false (not because both are true).
-/

/-- The **genuine Xie–Tamon graph** `K_m + P_m`: clique vertices
`Sum.inl : Fin m` (a complete graph `K_m`) and path vertices
`Sum.inr : Fin m` (a path `P_m`), joined by a single bridge edge between
clique vertex `0` and path vertex `0`.  Unit edge weights throughout.

This is the *real* graph (not a complete-graph skeleton): the path tail has
the tridiagonal structure whose Bose–Mesner algebra strictly exceeds the
distance-partition projector algebra — the heart of the Xie–Tamon
counterexample.  It is provided here as a standalone object to make the
family genuinely present in the file; the *sequence* version
`Kn_plus_pathn_skeleton` below cannot use the genuine distance partition,
because that partition has a number of cells growing with `m` and so is
incompatible with the fixed index type `I` of a
`ConsistentPartitionSequence`. -/
noncomputable def knPlusPathWG (m : ℕ) :
    @WeightedGraph (Fin m ⊕ Fin m) inferInstance inferInstance where
  adj := fun x y =>
    match x, y with
    -- clique block: complete graph on the left copy
    | Sum.inl a, Sum.inl b => if a ≠ b then (1 : ℂ) else 0
    -- path block: adjacent iff indices differ by one
    | Sum.inr a, Sum.inr b =>
        if (a.val + 1 = b.val ∨ b.val + 1 = a.val) then (1 : ℂ) else 0
    -- bridge: clique-0 to path-0
    | Sum.inl a, Sum.inr b => if a.val = 0 ∧ b.val = 0 then (1 : ℂ) else 0
    | Sum.inr a, Sum.inl b => if a.val = 0 ∧ b.val = 0 then (1 : ℂ) else 0
  herm := by
    refine Matrix.IsHermitian.ext (fun x y => ?_)
    -- every entry is `0` or `1` (real), so `star` is the identity; it then
    -- suffices to see the underlying boolean condition is symmetric in `x, y`.
    rcases x with a | a <;> rcases y with b | b <;>
      simp only [apply_ite (star : ℂ → ℂ), star_one, star_zero]
    · -- clique/clique: `a ≠ b` is symmetric
      by_cases h : a = b <;> simp [h, eq_comm]
    · -- clique/path bridge: `a.val = 0 ∧ b.val = 0` symmetric
      by_cases h : a.val = 0 ∧ b.val = 0 <;> simp [h, And.comm]
    · -- path/clique bridge
      by_cases h : a.val = 0 ∧ b.val = 0 <;> simp [h, And.comm]
    · -- path/path: the "differ by one" condition is symmetric
      by_cases h : (a.val + 1 = b.val ∨ b.val + 1 = a.val) <;>
        simp [h, Or.comm]
  loopless := by
    intro v; rcases v with a | a
    · show (if a ≠ a then (1 : ℂ) else 0) = 0; simp
    · show (if a.val + 1 = a.val ∨ a.val + 1 = a.val then (1 : ℂ) else 0) = 0
      rw [if_neg]; omega

/-- **Honest cardinality skeleton for test family 3.** The genuine Xie–Tamon
graph is `knPlusPathWG` above; its genuine equitable partition is the
distance-from-`K_m` partition, whose cell count grows with `m` and therefore
**cannot** be packaged as a `ConsistentPartitionSequence` over a fixed index
type.  This `def` is therefore an explicit *placeholder*: a single-cell
complete graph `K_{2m+2}` with the same vertex count `2(m+1) = |Fin m ⊕ Fin m|`
as the genuine graph, used only as a stand-in carrier for the structural
no-speedup fact below.  It is **not** the Xie–Tamon graph; see `knPlusPathWG`
for that. -/
noncomputable def Kn_plus_pathn_skeleton :
    Graphon.ConsistentPartitionSequence (Fin 1 : Type) :=
  singleCellCompleteSeqFin1 (fun n => 2 * n + 2)
    (fun n => by simp only; omega)

/-- Specialisation to the complete-graph single-cell builder. -/
theorem singleCellFin1_no_chiral_speedup
    (m : ℕ → ℕ) (hmono : ∀ n, m n ≤ m (n + 1)) :
    ¬ admitsChiralSpeedupOnPartition (singleCellCompleteSeqFin1 m hmono) :=
  fin1Cell_no_chiral_speedup _

theorem Kn_plus_pathn_no_chiral_speedup :
    ¬ admitsChiralSpeedupOnPartition Kn_plus_pathn_skeleton :=
  fin1Cell_no_chiral_speedup _

/-! ### 8.4. Complete multipartite `K_{n,n,n,n}` (four-color completion).

Partition by part. The Bose-Mesner of the four-part complete multipartite
graph is the rank-2 algebra spanned by `I, J_part, J - I - J_part`, where
`J_part` is the within-part all-ones. This equals the cell-pair-constant
algebra of the part partition; algebra coincidence holds.

Both halves of the conjecture hold; this is the "standard positive" four-
color family.
-/

/-- The `K_{n,n,n,n}` family: four parts each of size `n`, partition by
part membership (`I = Fin 4`). -/
noncomputable def K4multipartite (n : ℕ → ℕ) (hn : ∀ k, 0 < n k)
    (h_mono : ∀ k, n k ≤ n (k + 1)) :
    Graphon.ConsistentPartitionSequence (Fin 4 : Type) where
  V := fun k => Fin 4 × Fin (n k)
  finV := fun _ => inferInstance
  decV := fun _ => inferInstance
  measV := fun _ => ⊤
  msingV := fun _ => @MeasurableSingletonClass.mk _ ⊤ (fun _ => trivial)
  -- four equal parts of size `n k`; edge iff in different parts.
  G := fun k =>
    { adj := fun x y => if x.1 ≠ y.1 then (1 : ℂ) else 0
      herm := by
        ext x y
        rw [Matrix.conjTranspose_apply, apply_ite (star : ℂ → ℂ), star_one, star_zero]
        by_cases h : x.1 = y.1
        · rw [if_neg (not_not.mpr h.symm), if_neg (not_not.mpr h)]
        · rw [if_pos (Ne.symm h), if_pos h]
      loopless := by intro v; simp }
  cells := fun _ x => x.1
  embed := fun k x => (x.1, Fin.castLE (h_mono k) x.2)
  embed_cells := fun _ _ => rfl
  equitable := by
    intro k i j x y hx hy
    -- row-sum into part `j` from a vertex in part `i` is `n k` if `j ≠ i`, else 0;
    -- it depends only on the part labels `i, j`, not on the chosen vertex.
    have hcell : ∀ (w : Fin 4 × Fin (n k)),
        (∑ z : Fin 4 × Fin (n k),
          (if z.1 = j then (if w.1 ≠ z.1 then (1 : ℂ) else 0) else 0))
        = (if w.1 ≠ j then (n k : ℂ) else 0) := by
      intro w
      -- collapse the inner guard: on the support `z.1 = j`, `w.1 ≠ z.1 ↔ w.1 ≠ j`.
      have hcollapse : ∀ z : Fin 4 × Fin (n k),
          (if z.1 = j then (if w.1 ≠ z.1 then (1 : ℂ) else 0) else 0)
          = (if z.1 = j then (if w.1 ≠ j then (1 : ℂ) else 0) else 0) := by
        intro z; by_cases hz : z.1 = j
        · rw [if_pos hz, if_pos hz, hz]
        · rw [if_neg hz, if_neg hz]
      simp_rw [hcollapse]
      rw [← Finset.sum_filter]
      by_cases hji : w.1 ≠ j
      · simp only [if_pos hji, Finset.sum_const, nsmul_eq_mul, mul_one]
        congr 1
        -- count of `z` with `z.1 = j`: there are `n k` of them (one per second coord).
        rw [show (Finset.univ.filter (fun z : Fin 4 × Fin (n k) => z.1 = j))
              = ({j} ×ˢ Finset.univ) by
          ext z; simp [Prod.ext_iff, eq_comm]]
        rw [Finset.card_product, Finset.card_singleton, one_mul, Finset.card_univ,
          Fintype.card_fin]
      · rw [not_not] at hji
        simp only [if_neg (not_not.mpr hji), Finset.sum_const_zero]
    -- both `x` and `y` lie in part `i`, so `hcell` gives the same value.
    rw [hcell x, hcell y, hx, hy]

/-- **Test family 4, STRENGTHENED: the chiral half is proven GENUINELY.**
Unlike the single-cell families, `K_{n,n,n,n}` has a genuine **`Fin 4`** part
partition with ≥ 2 cells, so a nontrivial cross-constant signing *does* exist:
signing every cross-part edge by `-1` (`τ(i,j) = if i = j then 1 else -1`).  This
signing is unimodular (`±1`), Hermitian (real symmetric), diagonal-`1`,
cross-constant on the part partition, consistent under the part-preserving
embedding, nontrivial (parts `0` and `1` are populated since `n k > 0`), and
genuinely changes a cross-part edge (`(-1)·1 ≠ 1`).  Hence
`admitsChiralSpeedupOnPartition` holds — a real constructive witness, not the
(false) algebra-coincidence ⇒ chiral inference.

(The graphon-limit half is the separate deep analytic part and is **not** claimed
here; cf. `weak_forward_not_universal`, which shows it does not follow from
algebra coincidence.) -/
theorem K4multipartite_admits_chiral_speedup
    (n : ℕ → ℕ) (hn : ∀ k, 0 < n k) (h_mono : ∀ k, n k ≤ n (k + 1)) :
    admitsChiralSpeedupOnPartition (K4multipartite n hn h_mono) := by
  -- the sign-cross-part-edges-by-(-1) signing `σ x y = if x.1 = y.1 then 1 else -1`
  -- (cross-constant via `τ i j = if i = j then 1 else -1`)
  refine ⟨fun _ =>
    { σ := fun x y => if x.1 = y.1 then (1 : ℂ) else -1
      unimod := fun x y => by by_cases h : x.1 = y.1 <;> simp [h]
      herm := fun x y => by
        by_cases h : x.1 = y.1
        · rw [if_pos h, if_pos h.symm]; norm_num
        · rw [if_neg h, if_neg (fun he => h he.symm)]; norm_num
      diag := fun x => by simp }, ?_, ?_, ?_, ?_⟩
  · -- cross-constant on the part cells `x ↦ x.1`
    exact fun _ => ⟨fun i j => if i = j then (1 : ℂ) else -1, fun _ _ => rfl⟩
  · -- consistency under the part-preserving embedding (it preserves `.1`)
    intro k x y; rfl
  · -- nontrivial: parts 0 and 1 are populated, and the phase there is `-1 ≠ 1`
    refine ⟨0, ((0 : Fin 4), (⟨0, hn 0⟩ : Fin (n 0))),
              ((1 : Fin 4), (⟨0, hn 0⟩ : Fin (n 0))), ?_⟩
    show (if (0 : Fin 4) = (1 : Fin 4) then (1 : ℂ) else -1) ≠ 1
    rw [if_neg (by decide : ¬ (0 : Fin 4) = (1 : Fin 4))]; norm_num
  · -- speedup: on the cross-part edge, `σ · adj = (-1)·1 = -1 ≠ 1 = adj`
    refine ⟨0, ((0 : Fin 4), (⟨0, hn 0⟩ : Fin (n 0))),
              ((1 : Fin 4), (⟨0, hn 0⟩ : Fin (n 0))), ?_⟩
    show (if (0 : Fin 4) = (1 : Fin 4) then (1 : ℂ) else -1)
          * (if (0 : Fin 4) ≠ (1 : Fin 4) then (1 : ℂ) else 0)
        ≠ (if (0 : Fin 4) ≠ (1 : Fin 4) then (1 : ℂ) else 0)
    rw [if_neg (by decide : ¬ (0 : Fin 4) = (1 : Fin 4)),
      if_pos (by decide : (0 : Fin 4) ≠ (1 : Fin 4))]
    norm_num

/-! ### 8.5. Surface Heawood envelope `g → ∞`.

A consistent partition sequence indexed by genus `g`: at genus `g`, the
ambient graph is the *Heawood envelope*, the complete graph on
`H(g) = ⌊(7 + √(1 + 48 g)) / 2⌋` vertices, with the trivial single-cell
partition.

Limit graphon: the constant kernel `1`. Algebra coincidence: holds
(trivial single-cell partition; both algebras are `ℂ · I + ℂ · J`).
Both halves hold.
-/

/-- The **Heawood number** `H(g) = ⌊(7 + √(1 + 48 g)) / 2⌋`, in the integer
form `(7 + Nat.sqrt (1 + 48 g)) / 2`.  This is the maximum chromatic number of
a graph embeddable on a surface of genus `g` (Ringel–Youngs / Heawood). -/
def heawoodNumber (g : ℕ) : ℕ := (7 + Nat.sqrt (1 + 48 * g)) / 2

theorem heawoodNumber_mono (g : ℕ) : heawoodNumber g ≤ heawoodNumber (g + 1) := by
  unfold heawoodNumber
  apply Nat.div_le_div_right
  apply Nat.add_le_add_left
  apply Nat.sqrt_le_sqrt
  apply Nat.add_le_add_left
  exact Nat.mul_le_mul_left 48 (Nat.le_succ g)

/-- The Heawood envelope partition sequence: at stage `g`, complete graph
on `H(g)` vertices with trivial partition. -/
noncomputable def heawoodEnvelope :
    Graphon.ConsistentPartitionSequence (Unit : Type) :=
  singleCellCompleteSeq heawoodNumber heawoodNumber_mono

/-- **Test family 5, honest Lean state: no cross-constant chiral speedup.**
The Heawood envelope is a genuine single-cell *complete* graph `K_{H(g)}` (its
adjacency really is `completeWG (H g)`) with the trivial **`Unit`** partition.
As for `K_n^σ`, this single-cell model **provably** admits no cross-constant
chiral speedup: cross-constancy on one cell forces the trivial signing
(`subsingletonCell_no_chiral_speedup`).

Algebra coincidence `ℂ·I + ℂ·J = ℂ·I + ℂ·J` is structurally expected, but (as
`weak_forward_not_universal` shows) it does **not** supply the chiral half on a
single cell.  This theorem states only the genuinely-true no-speedup fact. -/
theorem heawoodEnvelope_no_chiral_speedup :
    ¬ admitsChiralSpeedupOnPartition heawoodEnvelope :=
  subsingletonCell_no_chiral_speedup _

/-! ### 8.6. **Tight counterexample candidate:** Cayley graphs of `S_n`.

The natural candidate where graphon limit exists but algebra coincidence
*fails*: a sequence of Cayley graphs of `S_n` with a fixed generating
set (say the transpositions). The Bose-Mesner algebra of the
Cayley graph contains all class functions, which is strictly larger than
the conjugacy-class partition projector algebra as soon as a class has
multiple irreducible characters supported in it.

If we take the *conjugacy class partition* `P_n`, then:

* Graphon limit: exists (in the sense of `ConsistentPartitionSequence`
  with appropriate `I` = partition type of `n`).
* Bose-Mesner algebra: equals the convolution algebra of `S_n`, which has
  dimension `∑ d_λ^2 = n!` — much larger than the partition projector
  algebra of dimension `(# classes)^2 = p(n)^2`.
* Hence algebra coincidence **fails** for all `n ≥ 5` (e.g.).

The conjecture predicts: chiral speedup on this partition should **also**
fail (because RHS fails). This is testable.
-/

/-- The **genuine Cayley graph of `S_m` by transpositions**, on the vertex set
`Equiv.Perm (Fin m)`: unit edge weight between permutations `g, h` exactly when
`g⁻¹ * h` is a transposition (a permutation whose support has cardinality `2`),
and `0` otherwise.

This is the *actual* transposition Cayley graph (not a complete-graph skeleton):
its edges encode single swaps.  Two permutations are adjacent iff they differ by
a transposition, so e.g. the identity is **not** adjacent to a 3-cycle — the
adjacency matrix is genuinely non-constant.  The connection predicate
`p.support.card = 2` is decidable and, by `Equiv.Perm.card_support_eq_two`,
equivalent to `IsSwap p`. -/
noncomputable def cayleyTranspositionWG (m : ℕ) :
    @WeightedGraph (Equiv.Perm (Fin m)) inferInstance inferInstance where
  adj := fun g h => if (g⁻¹ * h).support.card = 2 then (1 : ℂ) else 0
  herm := by
    refine Matrix.IsHermitian.ext (fun g h => ?_)
    show star (if (h⁻¹ * g).support.card = 2 then (1 : ℂ) else 0)
        = if (g⁻¹ * h).support.card = 2 then (1 : ℂ) else 0
    -- `h⁻¹ * g = (g⁻¹ * h)⁻¹` has the same support cardinality.
    have hsupp : (h⁻¹ * g).support.card = (g⁻¹ * h).support.card := by
      have : h⁻¹ * g = (g⁻¹ * h)⁻¹ := by group
      rw [this, Equiv.Perm.support_inv]
    rw [hsupp]; by_cases hc : (g⁻¹ * h).support.card = 2 <;> simp [hc]
  loopless := by
    intro g
    have : (g⁻¹ * g).support.card = 0 := by simp
    rw [if_neg (by rw [this]; decide)]

/-- **Transposition Cayley graphs are regular.**  Left translation
`z ↦ (h * g⁻¹) * z` is a bijection of `Equiv.Perm (Fin m)` carrying the
neighbour set of `g` onto that of `h`, since `h⁻¹ * ((h g⁻¹) z) = g⁻¹ z`.  So the
row sums at `g` and `h` agree. -/
theorem cayleyTranspositionWG_regular (m : ℕ) (g h : Equiv.Perm (Fin m)) :
    ∑ z, (cayleyTranspositionWG m).adj g z = ∑ z, (cayleyTranspositionWG m).adj h z := by
  -- reindex the right sum `∑ z, adj h z` by left translation `z ↦ (h * g⁻¹) * z`
  rw [← Equiv.sum_comp (Equiv.mulLeft (h * g⁻¹)) (fun z => (cayleyTranspositionWG m).adj h z)]
  apply Finset.sum_congr rfl
  intro w _
  show (cayleyTranspositionWG m).adj g w
      = (cayleyTranspositionWG m).adj h ((h * g⁻¹) * w)
  show (if (g⁻¹ * w).support.card = 2 then (1 : ℂ) else 0)
      = (if (h⁻¹ * ((h * g⁻¹) * w)).support.card = 2 then (1 : ℂ) else 0)
  have hkey : h⁻¹ * ((h * g⁻¹) * w) = g⁻¹ * w := by group
  rw [hkey]

/-- The **genuine Cayley-`S_n`-by-transpositions partition sequence**.  Stage
`n`: vertex set `Equiv.Perm (Fin (n+1))` (cardinality `(n+1)!`), with the
**genuine transposition Cayley adjacency** (`cayleyTranspositionWG`), the natural
inclusion `S_{n+1} ↪ S_{n+2}` extending a permutation by fixing the new point
(`Equiv.Perm.decomposeFin.symm (0, ·)`), and the single-cell (`Fin 1`)
coarsening of the conjugacy-class partition.

This is a genuine, distinct object: its adjacency is the real transposition
Cayley graph, not a complete graph.  The single-cell partition is equitable
because the Cayley graph is *regular* (`cayleyTranspositionWG_regular`).  The
richer conjugacy-class partition refines this single cell; that the conjugacy
partition's projector algebra is strictly smaller than the `S_n`-convolution
Bose–Mesner algebra (so algebra coincidence fails) is the open conjectural
content recorded in `cayleyS_n_algebra_strictly_larger`.  We start at
`Fin (n+1)` so the vertex set is always nonempty.  -/
noncomputable def cayleyS_n :
    Graphon.ConsistentPartitionSequence (Fin 1 : Type) :=
  singleCellRegularSeqFin1
    (fun n => Equiv.Perm (Fin (n + 1)))
    (fun _ => inferInstance) (fun _ => inferInstance)
    (fun n => cayleyTranspositionWG (n + 1))
    (fun _ p => Equiv.Perm.decomposeFin.symm (0, p))
    (fun n => cayleyTranspositionWG_regular (n + 1))

/-- **The substantive content for family 6:** algebra coincidence fails.
For the genuine transposition Cayley graph, the partition-projector algebra of
the single (`Fin 1`) cell is the line of *constant* matrices, while
`finiteAdjAlgebra` additionally contains the genuine Cayley adjacency, which is
non-constant: the identity is **not** adjacent to itself (diagonal `0`) but **is**
adjacent to the transposition `swap 0 1` (off-diagonal `1`).  So the projector
algebra is strictly smaller at every stage `n ≥ max N 1` (where `Fin (n+1)` has
at least two points). -/
theorem cayleyS_n_algebra_strictly_larger :
    algebra_strictly_larger cayleyS_n := by
  intro N
  refine ⟨max N 1, le_max_left _ _, ?_⟩
  set n := max N 1 with hn
  have hn1 : 1 ≤ n := le_max_right _ _
  -- the vertex type at stage `n` is `Equiv.Perm (Fin (n+1))`
  letI : Fintype (cayleyS_n.V n) := cayleyS_n.finV n
  letI : DecidableEq (cayleyS_n.V n) := cayleyS_n.decV n
  -- the projector span (the RHS summand of `finiteAdjAlgebra`)
  set S : Set (Matrix (cayleyS_n.V n) (cayleyS_n.V n) ℂ) :=
    { M | ∃ q : Fin 1 → Fin 1 → ℂ, ∀ x y, M x y = q (cayleyS_n.cells n x) (cayleyS_n.cells n y) }
    with hS
  have hPP : partitionProjectorAlgebra cayleyS_n n = Submodule.span ℂ S := rfl
  have hFA : finiteAdjAlgebra cayleyS_n n
      = Submodule.span ℂ {(cayleyS_n.G n).adj} ⊔ Submodule.span ℂ S := rfl
  rw [hPP, hFA]
  -- strict inclusion: `span S ≤ span{adj} ⊔ span S`, and they differ because
  -- `adj` lies in the sup but not in `span S`.
  rw [lt_iff_le_and_ne]
  refine ⟨le_sup_right, ?_⟩
  -- two distinct points of `Fin (n+1)` (since `n + 1 ≥ 2`): `0 ≠ 1`.
  have hpt : (0 : Fin (n + 1)) ≠ (1 : Fin (n + 1)) := by
    have h2 : (1 : ℕ) < n + 1 := by omega
    refine Fin.ne_of_val_ne ?_
    rw [Fin.val_zero, Fin.val_one' (n + 1), Nat.mod_eq_of_lt h2]
    omega
  -- the two witness vertices: identity `i0 = 1` and the transposition `i1 = swap 0 1`.
  set i0 : cayleyS_n.V n := (1 : Equiv.Perm (Fin (n + 1))) with hi0
  set i1 : cayleyS_n.V n := Equiv.swap (0 : Fin (n + 1)) (1 : Fin (n + 1)) with hi1
  -- a linear functional vanishing on `S` but not on the adjacency `A`
  set φ : Matrix (cayleyS_n.V n) (cayleyS_n.V n) ℂ →ₗ[ℂ] ℂ :=
    Matrix.entryLinearMap ℂ ℂ i0 i0 - Matrix.entryLinearMap ℂ ℂ i0 i1 with hφ
  -- φ evaluates to `M i0 i0 - M i0 i1` (definitional)
  have hφeval : ∀ M : Matrix (cayleyS_n.V n) (cayleyS_n.V n) ℂ,
      φ M = M i0 i0 - M i0 i1 := fun M => rfl
  -- φ vanishes on the whole projector span
  have hφS : Submodule.span ℂ S ≤ LinearMap.ker φ := by
    rw [Submodule.span_le]
    intro M hM
    obtain ⟨q, hq⟩ := hM
    rw [SetLike.mem_coe, LinearMap.mem_ker, hφeval, hq, hq]
    rw [Subsingleton.elim (cayleyS_n.cells n i1) (cayleyS_n.cells n i0), sub_self]
  -- but φ does not vanish on `A`: `A i0 i0 - A i0 i1 = 0 - 1 = -1 ≠ 0`.
  have hφA : φ (cayleyS_n.G n).adj ≠ 0 := by
    -- the two witness vertices, viewed in `Equiv.Perm (Fin (n+1))`
    set p0 : Equiv.Perm (Fin (n + 1)) := (1 : Equiv.Perm (Fin (n + 1))) with hp0
    set p1 : Equiv.Perm (Fin (n + 1)) := Equiv.swap (0 : Fin (n + 1)) (1 : Fin (n + 1)) with hp1
    have hadj : ∀ g h : Equiv.Perm (Fin (n + 1)),
        (cayleyS_n.G n).adj g h
          = (if (g⁻¹ * h).support.card = 2 then (1 : ℂ) else 0) := fun g h => rfl
    have hev : φ (cayleyS_n.G n).adj
        = (cayleyS_n.G n).adj p0 p0 - (cayleyS_n.G n).adj p0 p1 := rfl
    rw [hev, hadj p0 p0, hadj p0 p1]
    -- diagonal: `p0⁻¹ * p0 = 1`, support card `0 ≠ 2`.
    have hdiag : ¬ ((p0⁻¹ * p0).support.card = 2) := by simp [hp0]
    -- off-diagonal: `p0⁻¹ * p1 = swap 0 1`, support card `2`.
    have hoff : (p0⁻¹ * p1).support.card = 2 := by
      rw [hp0, hp1]; simp [Equiv.Perm.card_support_swap hpt]
    rw [if_neg hdiag, if_pos hoff]
    norm_num
  -- conclude inequality of the two submodules
  intro hEq
  apply hφA
  -- `adj ∈ span{adj} ⊔ span S = span S` (by hEq), hence in ker φ
  have hAmem : (cayleyS_n.G n).adj
      ∈ Submodule.span ℂ {(cayleyS_n.G n).adj} ⊔ Submodule.span ℂ S :=
    Submodule.mem_sup_left (Submodule.subset_span (Set.mem_singleton _))
  rw [← hEq] at hAmem
  exact hφS hAmem

/-- And the chiral half also fails — making both sides of the iff false.
Closed via `fin1Cell_no_chiral_speedup`: a cross-constant signing on the single
`Fin 1` cell is forced trivial, so no chiral speedup exists. -/
theorem cayleyS_n_no_chiral_speedup :
    ¬ admitsChiralSpeedupOnPartition cayleyS_n :=
  fin1Cell_no_chiral_speedup _

/-- **Test family 6 (tight counterexample-shaped), proven GENUINELY.** The
Cayley-`S_n` family satisfies the weak conjecture `Conjecture93_weak` because
**both sides of the iff are false** — not by hollow application of the (sorried)
`conjecture93_weak_iff`.  The LHS fails because its chiral conjunct fails
(`cayleyS_n_no_chiral_speedup`); the RHS `eventuallyAlgebraCoincidence` fails
because the genuine Cayley Bose–Mesner algebra is strictly larger than the
single-cell projector algebra at infinitely many stages
(`cayleyS_n_algebra_strictly_larger` ⟹ `rhs_blocked_if_algebra_strictly_larger`).
A `False ↔ False` biconditional. -/
theorem cayleyS_n_satisfies_conj93 :
    Conjecture93_weak cayleyS_n := by
  have hlhs : ¬ (admitsGraphonLimit cayleyS_n ∧ admitsChiralSpeedupOnPartition cayleyS_n) :=
    fun h => cayleyS_n_no_chiral_speedup h.2
  have hrhs : ¬ eventuallyAlgebraCoincidence cayleyS_n :=
    rhs_blocked_if_algebra_strictly_larger _ cayleyS_n_algebra_strictly_larger
  exact iff_of_false hlhs hrhs

/-! ## 9. The strong-vs-weak gap

We isolate the gap between the **strong** and **weak** versions: any
counterexample to the strong version (LHS holds, RHS fails) must use a
*non-cross-constant* unitary signing.
-/

/-- A **cross-constant** chiral speedup is in particular a chiral speedup by
*some* unitary signing: the weak chiral half implies the strong chiral half.
This is the easy half of the strong-vs-weak comparison. -/
theorem crossConstant_speedup_implies_any
    (𝒮 : Graphon.ConsistentPartitionSequence I) :
    admitsChiralSpeedupOnPartition 𝒮 → admitsAnyChiralSpeedupOnPartition 𝒮 := by
  rintro ⟨s, _, _, hnt, hsp⟩
  exact ⟨s, hnt, hsp⟩

/-- **The strong-vs-weak gap.** Suppose the weak conjecture holds for `𝒮` and
`𝒮` admits a graphon limit.  If `𝒮` witnesses the strong LHS (admits *some*
chiral speedup) yet algebra coincidence *fails* eventually, then `𝒮` cannot
admit a *cross-constant* chiral speedup: any witness to the strong LHS must use
a signing that is **not** cross-constant on the cells of `𝒮.cells n`.  (This is
the precise sense in which any counterexample to the strong conjecture must use
a non-cross-constant unitary signing.) -/
theorem strong_failure_requires_nonCrossConstant
    (𝒮 : Graphon.ConsistentPartitionSequence.{u, v} I)
    (hweak : Conjecture93_weak.{u, v} 𝒮)
    (hlim : @admitsGraphonLimit.{u, v} I _ _ 𝒮)
    (_hany : admitsAnyChiralSpeedupOnPartition 𝒮)
    (hfail : ¬ eventuallyAlgebraCoincidence 𝒮) :
    ¬ admitsChiralSpeedupOnPartition 𝒮 := by
  intro hcc
  exact hfail (hweak.mp ⟨hlim, hcc⟩)

/-! ## 10. Summary table (commented out, for the paper notes)

**Audit-corrected (2026-06).**  The earlier table recorded a "T-T-T conditional
on fwd dir" status for the positive families, routed through
`conjecture93_weak_forward`.  That direction is now known to be **false** as a
universal statement (`weak_forward_not_universal`): on the *cross-constant*
signing model the chiral half is **not** implied by algebra coincidence, and is
in fact *false* for every single-cell carrier.  The Lean status below reflects
only what is genuinely proven.

```
family                    | graphon | cross-const chiral (weak) | alg coinc | Lean status (proven)
--------------------------|---------|---------------------------|-----------|------------------------------
K_n^σ (Unit cell)         | open    | NO (single cell)          | open      | _no_chiral_speedup PROVEN
H(n, q) (Fin 1 cell)      | open    | NO (single cell)          | open      | _no_chiral_speedup PROVEN
K_n + path_n  (Fin 1)     | open    | NO (single cell)          | no        | _no_chiral_speedup PROVEN
K_{n,n,n,n}  (Fin 4)      | open    | YES (sign cross-part −1)  | open      | _admits_chiral_speedup PROVEN
Heawood envelope (Unit)   | open    | NO (single cell)          | open      | _no_chiral_speedup PROVEN
Cayley(S_n) by transp.    | open    | NO (single cell)          | no (>)    | Conjecture93_weak PROVEN (F↔F)
```

The right column records the **honest Lean status**, NOT a hollow application of
the (false-as-universal) forward direction:

* The single-cell families (`K_n^σ`, `H(n,q)`, Heawood, the `K_n+P_n`
  placeholder) have their cross-constant chiral half **disproven** genuinely
  (`subsingletonCell_no_chiral_speedup` / `fin1Cell_no_chiral_speedup`): a
  cross-constant signing on one cell is forced trivial.  (The Levine et al.
  `K_n^σ` speedup uses the *larger* non-cross-constant signing space, not modelled
  by `admitsChiralSpeedupOnPartition`.)
* `K_{n,n,n,n}` (genuine `Fin 4` partition, ≥ 2 cells) has its chiral half
  **proven** constructively (`K4multipartite_admits_chiral_speedup`): the
  sign-cross-part-edges-by-`-1` signing is a genuine nontrivial cross-constant
  edge-changing witness.
* `Cayley(S_n)` is proven **genuinely** as `Conjecture93_weak cayleyS_n`
  (`cayleyS_n_satisfies_conj93`): both sides of the iff are *false* (no chiral
  speedup on the single cell; algebra strictly larger because the genuine Cayley
  adjacency is non-constant), an honest `False ↔ False`.
* `K_n + P_n` is realised by the explicitly-labelled cardinality placeholder
  `Kn_plus_pathn_skeleton`; the genuine Xie–Tamon graph is `knPlusPathWG`, and
  `Kn_plus_pathn_no_chiral_speedup` is proven genuinely.
* The forward/iff *universal* claims are **refuted** (`weak_forward_not_universal`,
  `weak_iff_not_universal`) via the empty single-cell witness `emptySeqFin1`
  (algebra coincidence holds, chiral speedup impossible).  `Conjecture93_weak`
  remains a genuine open conjecture (a `Prop` def), now correctly *not* asserted
  as a theorem for all `𝒮`.

All six families are genuine, distinct objects with honestly-proven equitable
partitions. The conjecture is consistent with `chan2019fractional`
(1907.04729) by design: fractional revival on association schemes is exactly
the algebra-coincidence case.
-/

end Conjecture93
end Graphplay
