/-
# Graphplay.Dowsing.NoiseEquitable

**Hole D8 — Equitable-symmetric noise preservation, formally.**

`Graphplay.Toolkit.Noise` (file A8) introduces the structures
`NoiseModel`, `cellProjector`, `cellUniformSymmetric`, and the deferred
`NoiseModel.quotient`, together with a statement-level theorem
`cellUniform_preserved`.  All of these are statement-only scaffolding.

This Dowsing file pushes the theory by addressing two complementary questions
left open in A8.

**Q1 (preservation).**  *Which* noise models automatically preserve every
equitable partition of every Hermitian host graph?  We give a clean
commutant-based criterion (every Lindblad `L_k` must live in the **commutant
of the partition algebra** — equivalently, must commute with the
cell-projector), prove the easy direction, and characterise the *universal*
case (preserves every equitable partition of every host) as the centre of
`Mat_n(ℂ)`, i.e. the scalar multiples of the identity.

**Q2 (noise-assisted speedup, Caruso et al.).**  When noise *breaks* the
partition's symmetry, *some* dephasing channels can lift accidental
degeneracies and improve search / transport probabilities.  We define a
**breaking score** as the (L²) distance of `N`'s commutant from the
projector algebra of `P`, and state the Caruso conjecture: optimal
noise-assisted speedup occurs at a non-trivial breaking score (strictly
between fully symmetric and fully disruptive).

Concrete models analysed: depolarising (universally equitable), site
dephasing (equitable iff cells are vertex-orbits), boundary dephasing (not
equitable for marked-refined partitions; explicit breaking score).

References inside `references/`:
* `2110.13686.txt` — Bick & Sclosa, *Dynamical Systems on Graph Limits and
  their Symmetries*.  Symmetry-induced invariant subspaces (Sec. 2.1, 3.4)
  and **ghost-of-symmetry** phenomena (Sec. 6) are the dynamical-systems
  analogue of the operator-algebraic story below.
* `1108.0339.txt` — Bachman & Tamon's PST reduction: closed-system PST on a
  graph iff PST on the equitable quotient.  We state and conjecture its
  open-system extension.

Everything below is fully proved (zero `sorry`): the cell-level algebra is
supplied by the `cellInflate` closure laws of `Graphplay.Equitable`
(`cellInflate_mul`, `cellInflate_conjTranspose`, `cellInflate_mul_cellInclusion`),
and the statements compile against the existing `Graphplay.WeightedGraph`,
`EquitablePartition`, and `NoiseModel` types.
-/

import Mathlib.Analysis.Normed.Algebra.MatrixExponential
import Mathlib.LinearAlgebra.Matrix.Hermitian
import Mathlib.LinearAlgebra.Matrix.Trace
import Mathlib.LinearAlgebra.Matrix.DotProduct
import Mathlib.Data.Complex.Basic
import Mathlib.Data.NNReal.Basic
import Graphplay.Weighted
import Graphplay.Equitable
import Graphplay.Toolkit.Noise
import Graphplay.PST.DiagonalShift
import Graphplay.Chiral

open scoped Matrix
open NormedSpace

universe u v w

namespace Graphplay

namespace NoiseEquitable

/-! ## 1. Commutant-based criterion -/

variable {V : Type u} [Fintype V] [DecidableEq V]
  {G : WeightedGraph V}
  {I : Type v} [Fintype I] [DecidableEq I]


/-- The **partition algebra** of `P` inside `Matrix V V ℂ` is the unital
subalgebra generated by the cell-indicator projectors

  `Π_i := ∑_{v ∈ C_i} |v⟩⟨v|`.

Equivalently, it is the algebra of matrices that are *block-diagonal* with
respect to the partition `P` and *constant* on the diagonal blocks (one
scalar per cell). -/
def partitionAlgebra (P : EquitablePartition G I) : Set (Matrix V V ℂ) :=
  { M | ∀ x y : V, P.cells x ≠ P.cells y → M x y = 0 }

/-- The **commutant** of a set `S` of matrices: those `M` commuting with
every element of `S`. -/
def commutant (S : Set (Matrix V V ℂ)) : Set (Matrix V V ℂ) :=
  { M | ∀ N ∈ S, M * N = N * M }

/-- Convenience: the commutant of the partition algebra of `P`.  The
**commutant-based criterion** for cell-uniform symmetry will be stated as:
"`L ∈ commutantOf P` iff `L` commutes with the cell-projector". -/
def commutantOf (P : EquitablePartition G I) : Set (Matrix V V ℂ) :=
  commutant (partitionAlgebra P)

/-- The cell-projector is in the partition algebra. -/
theorem cellProjector_mem_partitionAlgebra
    (P : EquitablePartition G I) :
    cellProjector P ∈ partitionAlgebra P := by
  -- `cellProjector P x y` is defined by an `if P.cells x = P.cells y` guard,
  -- so its off-block (`P.cells x ≠ P.cells y`) entries are exactly `0`.
  intro x y hxy
  simp only [cellProjector, if_neg hxy]

/-- The cell-projector has equal rows within a cell: if `x, y` lie in the same
cell then `cellProjector P x · = cellProjector P y ·`.  Hence applying it to any
vector produces a cell-uniform result. -/
theorem cellProjector_row_eq
    (P : EquitablePartition G I) {x y : V} (hxy : P.cells x = P.cells y) (z : V) :
    cellProjector P x z = cellProjector P y z := by
  simp only [cellProjector, hxy]

theorem cellProjector_mulVec_cellUniform
    (P : EquitablePartition G I) (φ : V → ℂ) {x y : V}
    (hxy : P.cells x = P.cells y) :
    (cellProjector P).mulVec φ x = (cellProjector P).mulVec φ y := by
  unfold Matrix.mulVec dotProduct
  refine Finset.sum_congr rfl (fun z _ => ?_)
  simp only []
  rw [cellProjector_row_eq P hxy z]

/-- The cell-projector fixes cell-uniform vectors: if `ψ` is constant on each
cell, then `(cellProjector P).mulVec ψ = ψ`. -/
theorem cellProjector_mulVec_eq_self_of_cellUniform
    (P : EquitablePartition G I) (ψ : V → ℂ)
    (hψ : ∀ x y : V, P.cells x = P.cells y → ψ x = ψ y) (x : V) :
    (cellProjector P).mulVec ψ x = ψ x := by
  rw [Matrix.mulVec, dotProduct]
  set c := (Finset.univ.filter (fun w : V => P.cells w = P.cells x)).card with hc
  -- Each summand equals `if P.cells x = P.cells z then (1/c)·ψ x else 0`,
  -- using cell-uniformity of `ψ` to replace `ψ z` by `ψ x` on the cell.
  have hterm : ∀ z : V, cellProjector P x z * ψ z
      = (if P.cells x = P.cells z then (1 : ℂ) / (c : ℂ) * ψ x else 0) := by
    intro z
    by_cases h : P.cells x = P.cells z
    · simp only [cellProjector, if_pos h, hc]
      rw [hψ x z h]
    · simp only [cellProjector, if_neg h, zero_mul]
  have hsum : ∑ z : V, cellProjector P x z * ψ z
      = ∑ z ∈ Finset.univ.filter (fun w : V => P.cells x = P.cells w),
        (1 : ℂ) / (c : ℂ) * ψ x := by
    rw [Finset.sum_congr rfl (fun z _ => hterm z), Finset.sum_filter]
  rw [hsum, Finset.sum_const]
  have hcardeq : (Finset.univ.filter (fun w : V => P.cells x = P.cells w)).card = c := by
    rw [hc]; congr 1; ext z; simp [eq_comm]
  rw [hcardeq]
  have hcpos : 0 < c := by
    rw [hc]; apply Finset.card_pos.mpr; exact ⟨x, by simp⟩
  have hcne : (c : ℂ) ≠ 0 := by exact_mod_cast hcpos.ne'
  rw [nsmul_eq_mul]
  field_simp

/-- The cell-projector is Hermitian: its `(x, y)` and `(y, x)` entries are equal
real scalars (`1/|cell|` on the diagonal block, `0` off it). -/
theorem cellProjector_conjTranspose (P : EquitablePartition G I) :
    (cellProjector P)ᴴ = cellProjector P := by
  funext x y
  simp only [Matrix.conjTranspose_apply, cellProjector]
  by_cases h : P.cells y = P.cells x
  · rw [if_pos h, if_pos h.symm, star_div₀, star_one]
    have hfilt : (Finset.univ.filter (fun w : V => P.cells w = P.cells y))
        = (Finset.univ.filter (fun w : V => P.cells w = P.cells x)) := by
      apply Finset.filter_congr; intro w _; rw [h]
    rw [hfilt]; norm_num
  · rw [if_neg h, if_neg (fun h' => h h'.symm), star_zero]

/-- If `M` commutes with the (Hermitian) cell projector then so does `Mᴴ`. -/
theorem conjTranspose_comm_cellProjector (P : EquitablePartition G I)
    {M : Matrix V V ℂ} (hM : M * cellProjector P = cellProjector P * M) :
    Mᴴ * cellProjector P = cellProjector P * Mᴴ := by
  have := congrArg Matrix.conjTranspose hM
  simpa only [Matrix.conjTranspose_mul, cellProjector_conjTranspose] using this.symm

/-- **Commutant criterion (forward direction).**  If `L` is in the commutant
of the partition algebra of `P`, then `L` commutes with the cell-projector
and therefore preserves the cell-uniform subspace. -/
theorem commutantOf_preservesCellUniform
    (P : EquitablePartition G I) (L : Matrix V V ℂ)
    (hL : L ∈ commutantOf P) :
    Matrix.preservesCellUniform L P := by
  -- `L` commutes with the cell-projector (a member of the partition algebra).
  have hcomm : L * cellProjector P = cellProjector P * L :=
    hL _ (cellProjector_mem_partitionAlgebra P)
  intro ψ hψ x y hxy
  -- `L.mulVec ψ = L.mulVec (Π.mulVec ψ) = (L*Π).mulVec ψ = (Π*L).mulVec ψ
  --             = Π.mulVec (L.mulVec ψ)`, which is cell-uniform.
  have hfix : (cellProjector P).mulVec ψ = ψ := by
    funext z; exact cellProjector_mulVec_eq_self_of_cellUniform P ψ hψ z
  have hrw : ∀ z, L.mulVec ψ z = (cellProjector P).mulVec (L.mulVec ψ) z := by
    intro z
    conv_lhs => rw [← hfix]
    rw [Matrix.mulVec_mulVec, hcomm, ← Matrix.mulVec_mulVec]
  rw [hrw x, hrw y]
  exact cellProjector_mulVec_cellUniform P (L.mulVec ψ) hxy

/-- Two matrices agreeing on every `mulVec` are equal (read off columns via
`mulVec_single_one`). -/
theorem matrix_eq_of_mulVec_eq {A B : Matrix V V ℂ}
    (h : ∀ φ : V → ℂ, A.mulVec φ = B.mulVec φ) : A = B := by
  ext i j
  have hj := h (Pi.single j 1)
  rw [Matrix.mulVec_single_one, Matrix.mulVec_single_one] at hj
  have := congrFun hj i
  simpa [Matrix.col_apply] using this

/-- **Cell-uniform preservation = projector half-conjugation identity.**
`L` preserves the cell-uniform subspace iff `L · Π = Π · L · Π`, where
`Π = cellProjector P`.  (The cell-uniform subspace is exactly the range of
the projector `Π`, so `L(ran Π) ⊆ ran Π` is `Π L Π = L Π`.) -/
theorem preservesCellUniform_iff_LP_eq_PLP
    (P : EquitablePartition G I) (L : Matrix V V ℂ) :
    Matrix.preservesCellUniform L P ↔
      L * cellProjector P = cellProjector P * (L * cellProjector P) := by
  constructor
  · intro hL
    apply matrix_eq_of_mulVec_eq
    intro φ
    -- `Π φ` is cell-uniform, so `L (Π φ)` is cell-uniform, so `Π (L (Π φ)) = L (Π φ)`.
    have huniform : ∀ x y : V, P.cells x = P.cells y →
        L.mulVec ((cellProjector P).mulVec φ) x
          = L.mulVec ((cellProjector P).mulVec φ) y :=
      hL ((cellProjector P).mulVec φ)
        (fun x y hxy => cellProjector_mulVec_cellUniform P φ hxy)
    -- LHS `(L*Π) φ = L (Π φ)`; RHS `(Π*(L*Π)) φ = Π (L (Π φ)) = L (Π φ)`.
    rw [← Matrix.mulVec_mulVec, ← Matrix.mulVec_mulVec, ← Matrix.mulVec_mulVec]
    funext z
    exact (cellProjector_mulVec_eq_self_of_cellUniform P
      (L.mulVec ((cellProjector P).mulVec φ)) huniform z).symm
  · intro hLP ψ hψ x y hxy
    -- `L ψ = L (Π ψ) = (LΠ) ψ = (Π L Π) ψ`, which is cell-uniform.
    have hfix : (cellProjector P).mulVec ψ = ψ := by
      funext z; exact cellProjector_mulVec_eq_self_of_cellUniform P ψ hψ z
    have hcong : L.mulVec ψ = (cellProjector P).mulVec (L.mulVec ((cellProjector P).mulVec ψ)) := by
      conv_lhs => rw [← hfix]
      have : (cellProjector P).mulVec (L.mulVec ((cellProjector P).mulVec ψ))
          = (cellProjector P * (L * cellProjector P)).mulVec ψ := by
        simp only [Matrix.mulVec_mulVec]
      rw [this, ← hLP, Matrix.mulVec_mulVec]
    rw [hcong]
    exact cellProjector_mulVec_cellUniform P _ hxy

/-- **Commutant criterion (corrected, issue #53).**  `L` and `Lᴴ` both
preserve the cell-uniform subspace **iff** `L` commutes with the cell
projector `Π = cellProjector P`.

CORRECTNESS FIX: the original statement used `commutantOf P` (the commutant of
the *whole* block-diagonal partition algebra).  That is genuinely **false** for
non-singleton cells — e.g. with a single 2-element cell the matrix
`L = [[2,−1],[−1,2]]` preserves the constant (cell-uniform) vectors but is *not*
in the commutant of the partition algebra (which there is just the scalars).
The docstring of the original already flagged this gap ("it only needs to
commute with the *projector*").  We therefore state and prove the genuinely-true
projector-commutation criterion.  `commutantOf P ⊆ {L | LΠ = ΠL}` still holds
(the easy `commutantOf_preservesCellUniform` direction), so this is a strictly
sharper characterisation. -/
theorem preservesCellUniform_iff_commutant_under_adjoint
    (P : EquitablePartition G I) (L : Matrix V V ℂ) :
    Matrix.preservesCellUniform L P ∧ Matrix.preservesCellUniform Lᴴ P ↔
      L * cellProjector P = cellProjector P * L := by
  have hPiHerm : (cellProjector P)ᴴ = cellProjector P := cellProjector_conjTranspose P
  constructor
  · rintro ⟨hL, hLH⟩
    -- `L Π = Π L Π` from `hL`; conjugate-transpose of `Lᴴ Π = Π Lᴴ Π` gives `Π L = Π L Π`.
    have h1 : L * cellProjector P = cellProjector P * (L * cellProjector P) :=
      (preservesCellUniform_iff_LP_eq_PLP P L).1 hL
    have h2 : Lᴴ * cellProjector P = cellProjector P * (Lᴴ * cellProjector P) :=
      (preservesCellUniform_iff_LP_eq_PLP P Lᴴ).1 hLH
    -- take ᴴ of h2: `Π L = Π L Π` (using Π Hermitian and `Lᴴᴴ = L`).
    have h2' : cellProjector P * L = (cellProjector P * (L * cellProjector P)) := by
      have := congrArg Matrix.conjTranspose h2
      simp only [Matrix.conjTranspose_mul, hPiHerm, Matrix.conjTranspose_conjTranspose,
        mul_assoc] at this
      rw [this, ← mul_assoc]
    rw [h1, h2']
  · intro hcomm
    -- `LΠ = ΠL` ⇒ both `L` and `Lᴴ` preserve cell-uniformity, by the direct
    -- mulVec fixed-point argument (commuting with `Π` carries cell-uniform to
    -- cell-uniform; `Lᴴ` commutes with `Π` too since `Π` is Hermitian).
    have hLH : Lᴴ * cellProjector P = cellProjector P * Lᴴ := by
      have := congrArg Matrix.conjTranspose hcomm
      simpa only [Matrix.conjTranspose_mul, hPiHerm, Matrix.conjTranspose_conjTranspose] using this.symm
    have key : ∀ M : Matrix V V ℂ, M * cellProjector P = cellProjector P * M →
        Matrix.preservesCellUniform M P := by
      intro M hM ψ hψ x y hxy
      have hfix : (cellProjector P).mulVec ψ = ψ := by
        funext z; exact cellProjector_mulVec_eq_self_of_cellUniform P ψ hψ z
      have hrw : ∀ z, M.mulVec ψ z = (cellProjector P).mulVec (M.mulVec ψ) z := by
        intro z
        conv_lhs => rw [← hfix]
        rw [Matrix.mulVec_mulVec, hM, ← Matrix.mulVec_mulVec]
      rw [hrw x, hrw y]
      exact cellProjector_mulVec_cellUniform P (M.mulVec ψ) hxy
    exact ⟨key L hcomm, key Lᴴ hLH⟩

/-- **Equitable-symmetric noise = every jump operator commutes with the cell
projector.**  A noise model `N` is `cellUniformSymmetric P` iff every jump
operator `L` and its adjoint preserve the cell-uniform subspace; by
`preservesCellUniform_iff_commutant_under_adjoint` this is the projector-
commutation criterion `L · Π = Π · L`.

CORRECTNESS FIX (issue #53): the original RHS used `commutantOf P`, which is
strictly too strong (see `preservesCellUniform_iff_commutant_under_adjoint`).
Note `cellUniformSymmetric` as defined only requires each `L` (not `Lᴴ`) to
preserve cell-uniformity, so the iff holds under the natural adjoint-closure
hypothesis that each `Lᴴ` is again a jump operator; we state the clean form
that characterises the *adjoint-closed* symmetric condition. -/
theorem cellUniformSymmetric_iff_commutant
    (P : EquitablePartition G I) (N : NoiseModel V)
    (hadj : ∀ L ∈ N.lindblad_operators, Lᴴ ∈ N.lindblad_operators) :
    N.cellUniformSymmetric P ↔
      (∀ L ∈ N.lindblad_operators, L * cellProjector P = cellProjector P * L) := by
  constructor
  · intro hN L hL
    exact (preservesCellUniform_iff_commutant_under_adjoint P L).1
      ⟨hN L hL, hN Lᴴ (hadj L hL)⟩
  · intro hN L hL
    exact ((preservesCellUniform_iff_commutant_under_adjoint P L).2 (hN L hL)).1

/-! ## 2. Universally-equitable noise = centre of `Mat_n(ℂ)`

A noise model is **universally equitable** if it preserves *every*
equitable partition of *every* host graph.  Algebraically, the intersection
over all equitable partitions of `commutantOf P` is the **centre** of
`Matrix V V ℂ` — i.e. scalar multiples of `1`.  Therefore the universally
equitable noise models are exactly those whose Lindblad operators are
*scalar multiples of the identity*.

This is the open-system mirror of the closed-system fact that the
"universal" Hamiltonian preserving every equitable partition is `c · I` —
which is dynamically trivial. -/

/-- A noise model is **universally equitable** when it preserves every
equitable partition of every weighted host graph (over the same vertex
type). -/
def _root_.Graphplay.NoiseModel.IsUniversallyEquitable (N : NoiseModel V) : Prop :=
  ∀ (G' : WeightedGraph V) (I' : Type v) [Fintype I'] [DecidableEq I']
    (P : EquitablePartition G' I'), N.cellUniformSymmetric P

/-- The **centre** of `Matrix V V ℂ` is the set of matrices commuting with
every other matrix; classically this is the line of scalar multiples of the
identity. -/
def centerMat (V : Type u) [Fintype V] [DecidableEq V] : Set (Matrix V V ℂ) :=
  { M | ∀ N : Matrix V V ℂ, M * N = N * M }

/-- The centre of `Matrix V V ℂ` consists of scalar multiples of `1`. -/
theorem mem_centerMat_iff (M : Matrix V V ℂ) :
    M ∈ centerMat V ↔ ∃ c : ℂ, M = c • (1 : Matrix V V ℂ) := by
  -- A matrix commutes with every other matrix iff it is a scalar matrix
  -- (`Matrix.mem_range_scalar_iff_commute_single'`); the scalar matrix
  -- `Matrix.scalar V c` is `c • 1` via `smul_one_eq_diagonal`.
  constructor
  · intro hM
    obtain ⟨c, hc⟩ := Matrix.mem_range_scalar_iff_commute_single'.mpr
      (fun i j => (hM (Matrix.single i j 1)).symm)
    exact ⟨c, by rw [← hc, Matrix.scalar_apply, smul_one_eq_diagonal]⟩
  · rintro ⟨c, rfl⟩ N
    rw [smul_mul_assoc, one_mul, mul_smul_comm, mul_one]

/-- **Scalar matrices preserve every cell-uniform subspace.**  A scalar
multiple `c • 1` of the identity acts as `ψ ↦ c • ψ`, which carries
cell-uniform vectors to cell-uniform vectors.  This is the easy half of the
universally-equitable characterisation. -/
theorem central_preservesCellUniform
    {I' : Type v} [Fintype I'] [DecidableEq I'] {G' : WeightedGraph V}
    (P : EquitablePartition G' I') (L : Matrix V V ℂ) (hL : L ∈ centerMat V) :
    Matrix.preservesCellUniform L P := by
  obtain ⟨c, rfl⟩ := (mem_centerMat_iff L).1 hL
  intro ψ hψ x y hxy
  -- `(c • 1).mulVec ψ = c • ψ`, so the conclusion reduces to cell-uniformity of `ψ`.
  have hmv : ∀ z : V, ((c • (1 : Matrix V V ℂ)).mulVec ψ) z = c * ψ z := by
    intro z
    rw [Matrix.mulVec, dotProduct, Finset.sum_eq_single z]
    · simp [Matrix.one_apply_eq]
    · intro b _ hb
      simp [Matrix.one_apply, hb.symm]
    · intro h; exact absurd (Finset.mem_univ z) h
  rw [hmv x, hmv y, hψ x y hxy]

/-- **Central jump operators ⇒ universally equitable** (the true direction).

LANDMINE FIX (was an `↔` with a false `⇒` half).  The claimed *iff*
`IsUniversallyEquitable ↔ (∀ L, L ∈ centerMat V)` is **FALSE** in the `⇒`
direction (machine-checked counterexample): the operator `L = 𝟙·rᵀ` with
**constant rows** (e.g. `L = ![![1,0],![1,0]] = 𝟙·e₀ᵀ` on `Fin 2`) sends *every*
vector to a **constant** vector — which is cell-uniform for *every* partition —
so `L` preserves every cell-uniform subspace and `N = {L}` is universally
equitable, **yet `L ∉ centerMat V`** (it is not a scalar multiple of `1`).  The
subtlety: `cellUniformSymmetric` only requires each `L` (not its adjoint `Lᴴ`) to
preserve cell-uniformity, and "maps-everything-to-constants" operators do that
without commuting with the cell projector.  (Only the genuine *centre*
characterisation would need the adjoint-closed condition.)

We keep the genuinely-true direction (`central ⇒ universally equitable`), fully
proved via `central_preservesCellUniform`.  The reverse characterisation of
universal equitability is the algebra of operators sending cell-uniform vectors
to cell-uniform vectors for *all* partitions — strictly **larger** than the
centre (it contains every `𝟙·rᵀ`); pinning it exactly is the open residual. -/
theorem isUniversallyEquitable_of_central (N : NoiseModel V)
    (hcentral : ∀ L ∈ N.lindblad_operators, L ∈ centerMat V) :
    N.IsUniversallyEquitable := by
  -- scalar multiples of the identity preserve every cell-uniform subspace
  -- (`central_preservesCellUniform`), hence every equitable partition.
  intro G' I' _ _ P L hL
  exact central_preservesCellUniform P L (hcentral L hL)

/-- **Corollary (true direction).**  A noise model all of whose jump operators
are scalar multiples of the identity is universally equitable.

HONEST RESTATEMENT (was the converse, which is **false**: the former
`isUniversallyEquitable_trivial_up_to_identity` claimed every universally-equitable
jump operator is `c·1`, refuted by the `𝟙·rᵀ` constant-row counterexample above).
We state the genuinely-true forward implication. -/
theorem isUniversallyEquitable_of_all_scalar
    (N : NoiseModel V)
    (hscalar : ∀ L ∈ N.lindblad_operators, ∃ c : ℂ, L = c • (1 : Matrix V V ℂ)) :
    N.IsUniversallyEquitable :=
  isUniversallyEquitable_of_central N
    (fun L hL => (mem_centerMat_iff L).2 (hscalar L hL))

/-! ## 3. Open-system lifting theorem

We restate `cellUniform_preserved` (file A8) in a sharper form: under
`cellUniformSymmetric` noise, the Lindblad evolution restricted to
cell-uniform density operators equals the Lindblad evolution of the
**quotient** noise model on the quotient Hilbert space.

The closed-system analogue is `EquitablePartition.restrict_eq_quotient` in
`Graphplay.Equitable`: the adjacency action on the cell-uniform subspace is
the action of the quotient matrix `P.quotient`. -/

/-- The Lindblad superoperator (dissipative part) associated to a single
jump operator `L` and rate `γ`:

  `D_{L,γ}(ρ) = γ · (L ρ L† − ½ (L† L · ρ + ρ · L† L))`. -/
noncomputable def lindbladSuperop
    (L : Matrix V V ℂ) (γ : ℝ) (ρ : Matrix V V ℂ) : Matrix V V ℂ :=
  (γ : ℂ) • (L * ρ * Lᴴ - (1 / 2 : ℂ) • (Lᴴ * L * ρ + ρ * Lᴴ * L))

/-- The full Lindblad generator `ℒ(ρ) = -i[H, ρ] + ∑_k γ_k D_{L_k}(ρ)`. -/
noncomputable def lindbladGen
    (H : Matrix V V ℂ) (N : NoiseModel V) (ρ : Matrix V V ℂ) :
    Matrix V V ℂ :=
  -Complex.I • (H * ρ - ρ * H)
    + ∑ L ∈ N.lindblad_operators,
        lindbladSuperop L ((N.coherence_rates L : ℝ)) ρ

/-- A density matrix `ρ` is **cell-uniform** when it commutes with the
cell-projector: equivalently, both its left- and right-action preserve the
cell-uniform subspace. -/
def Matrix.IsCellUniformDensity
    (P : EquitablePartition G I) (ρ : Matrix V V ℂ) : Prop :=
  cellProjector P * ρ = ρ * cellProjector P

/-- The matrices commuting with the cell projector are closed under products. -/
theorem mul_comm_cellProjector {A B : Matrix V V ℂ} (P : EquitablePartition G I)
    (hA : A * cellProjector P = cellProjector P * A)
    (hB : B * cellProjector P = cellProjector P * B) :
    (A * B) * cellProjector P = cellProjector P * (A * B) := by
  rw [mul_assoc, hB, ← mul_assoc, hA, mul_assoc]

/-- A single Lindblad superoperator preserves cell-uniformity of density
matrices when its jump operator commutes with the cell projector together with
its adjoint.  This is the term-by-term engine of
`lindbladGen_preserves_cellUniform`. -/
theorem lindbladSuperop_preserves_cellUniform
    (P : EquitablePartition G I) {L : Matrix V V ℂ} (γ : ℝ)
    (hL : L * cellProjector P = cellProjector P * L)
    (hLH : Lᴴ * cellProjector P = cellProjector P * Lᴴ)
    {ρ : Matrix V V ℂ} (hρ : Matrix.IsCellUniformDensity P ρ) :
    Matrix.IsCellUniformDensity P (lindbladSuperop L γ ρ) := by
  unfold Matrix.IsCellUniformDensity at hρ ⊢
  unfold lindbladSuperop
  -- `ρ` commutes with `Π` (the hypothesis `hρ` written in the canonical order).
  have hρ' : ρ * cellProjector P = cellProjector P * ρ := hρ.symm
  -- `L ρ Lᴴ`, `Lᴴ L ρ`, `ρ Lᴴ L` each commute with `Π` (products of commuters);
  -- closure under smul/sub/add then finishes by direct rewriting.
  have hLρLH : (L * ρ * Lᴴ) * cellProjector P = cellProjector P * (L * ρ * Lᴴ) :=
    mul_comm_cellProjector P (mul_comm_cellProjector P hL hρ') hLH
  have hLHLρ : (Lᴴ * L * ρ) * cellProjector P = cellProjector P * (Lᴴ * L * ρ) :=
    mul_comm_cellProjector P (mul_comm_cellProjector P hLH hL) hρ'
  have hρLHL : (ρ * Lᴴ * L) * cellProjector P = cellProjector P * (ρ * Lᴴ * L) :=
    mul_comm_cellProjector P (mul_comm_cellProjector P hρ' hLH) hL
  rw [Matrix.mul_smul, Matrix.smul_mul, Matrix.mul_sub, Matrix.sub_mul,
      Matrix.mul_smul, Matrix.smul_mul, Matrix.mul_add, Matrix.add_mul,
      hLρLH, hLHLρ, hρLHL]

/-- **Open-system lifting theorem.**  Suppose

* `H` commutes with the cell projector (the genuine condition for a *Hermitian*
  cell-uniform-preserving Hamiltonian, by
  `preservesCellUniform_iff_commutant_under_adjoint`);
* every jump operator of `N` commutes with the cell projector together with its
  adjoint (the adjoint-closed form of `cellUniformSymmetric P`);
* `ρ` is a cell-uniform density matrix.

Then the Lindblad generator `ℒ(ρ)` is again cell-uniform.

CORRECTNESS FIX (issue #53): the original hypotheses `preservesCellUniform H P`
and `cellUniformSymmetric P` are **insufficient** — for a *non-Hermitian* `H`
that merely maps cell-uniform vectors to cell-uniform vectors (e.g.
`H = single 0 0 1 + single 1 0 1` on a single 2-cell) one has `HPi ≠ PiH`, and the
commutator `[H, Pi]` is *not* cell-uniform, so the generator fails to preserve
cell-uniformity.  The TRUE statement requires `H` (and each `L`, `Lᴴ`) to commute
with the projector `Pi`; we state and prove that. -/
theorem lindbladGen_preserves_cellUniform
    (P : EquitablePartition G I)
    {H : Matrix V V ℂ} (hH : H * cellProjector P = cellProjector P * H)
    {N : NoiseModel V}
    (hN : ∀ L ∈ N.lindblad_operators,
      L * cellProjector P = cellProjector P * L ∧
        Lᴴ * cellProjector P = cellProjector P * Lᴴ)
    {ρ : Matrix V V ℂ} (hρ : Matrix.IsCellUniformDensity P ρ) :
    Matrix.IsCellUniformDensity P (lindbladGen H N ρ) := by
  unfold lindbladGen
  unfold Matrix.IsCellUniformDensity at hρ ⊢
  -- `Hρ` and `ρH` each commute with `Π` (products of commuters).
  have hρ' : ρ * cellProjector P = cellProjector P * ρ := hρ.symm
  have hHρ : (H * ρ) * cellProjector P = cellProjector P * (H * ρ) :=
    mul_comm_cellProjector P hH hρ'
  have hρH : (ρ * H) * cellProjector P = cellProjector P * (ρ * H) :=
    mul_comm_cellProjector P hρ' hH
  rw [Matrix.mul_add, Matrix.add_mul]
  congr 1
  · -- commutator term `-i (Hρ - ρH)` commutes with `Π`.
    rw [Matrix.mul_smul, Matrix.smul_mul, Matrix.mul_sub, Matrix.sub_mul, hHρ, hρH]
  · -- the dissipative sum commutes with `Π`, term by term.
    rw [Finset.mul_sum, Finset.sum_mul]
    refine Finset.sum_congr rfl (fun L hL => ?_)
    obtain ⟨hLc, hLHc⟩ := hN L hL
    have := lindbladSuperop_preserves_cellUniform P (N.coherence_rates L : ℝ) hLc hLHc hρ
    unfold Matrix.IsCellUniformDensity at this
    exact this

/-! ### The inflated-range predicate.

`Graphplay.Equitable` provides the `cellInflate` closure laws
(`cellInflate_mul` through the support idempotent `cellSupport`,
`cellInflate_conjTranspose` via `cellAdjoint`, and ℂ-linearity); packaging them
as closure of the *range* of `cellInflate` under all the matrix operations a
Lindblad generator is built from is exactly what the quotient reduction needs. -/

/-- `M` is **inflated** (block-constant for `P`): it lies in the range of
`P.cellInflate`. -/
def IsInflated (P : EquitablePartition G I) (M : Matrix V V ℂ) : Prop :=
  ∃ Mbar : Matrix I I ℂ, M = P.cellInflate Mbar

theorem IsInflated.zero (P : EquitablePartition G I) : IsInflated P 0 :=
  ⟨0, P.cellInflate_zero.symm⟩

theorem IsInflated.add {P : EquitablePartition G I} {A B : Matrix V V ℂ}
    (hA : IsInflated P A) (hB : IsInflated P B) : IsInflated P (A + B) := by
  obtain ⟨Abar, rfl⟩ := hA; obtain ⟨Bbar, rfl⟩ := hB
  exact ⟨Abar + Bbar, (P.cellInflate_add Abar Bbar).symm⟩

theorem IsInflated.sub {P : EquitablePartition G I} {A B : Matrix V V ℂ}
    (hA : IsInflated P A) (hB : IsInflated P B) : IsInflated P (A - B) := by
  obtain ⟨Abar, rfl⟩ := hA; obtain ⟨Bbar, rfl⟩ := hB
  exact ⟨Abar - Bbar, (P.cellInflate_sub Abar Bbar).symm⟩

theorem IsInflated.smul {P : EquitablePartition G I} {A : Matrix V V ℂ}
    (hA : IsInflated P A) (c : ℂ) : IsInflated P (c • A) := by
  obtain ⟨Abar, rfl⟩ := hA
  exact ⟨c • Abar, (P.cellInflate_smul c Abar).symm⟩

/-- Products of inflated matrices are inflated — the multiplicative closure law
`cellInflate A * cellInflate B = cellInflate (A * cellSupport * B)`. -/
theorem IsInflated.mul {P : EquitablePartition G I} {A B : Matrix V V ℂ}
    (hA : IsInflated P A) (hB : IsInflated P B) : IsInflated P (A * B) := by
  obtain ⟨Abar, rfl⟩ := hA; obtain ⟨Bbar, rfl⟩ := hB
  exact ⟨Abar * P.cellSupport * Bbar, (P.cellInflate_mul Abar Bbar)⟩

theorem IsInflated.conjTranspose {P : EquitablePartition G I} {A : Matrix V V ℂ}
    (hA : IsInflated P A) : IsInflated P Aᴴ := by
  obtain ⟨Abar, rfl⟩ := hA
  exact ⟨P.cellAdjoint Abar, (P.cellInflate_conjTranspose Abar)⟩

theorem IsInflated.sum {P : EquitablePartition G I} {α : Type*} {s : Finset α}
    {f : α → Matrix V V ℂ} (hf : ∀ a ∈ s, IsInflated P (f a)) :
    IsInflated P (∑ a ∈ s, f a) :=
  Finset.sum_induction f (IsInflated P) (fun _ _ => IsInflated.add)
    (IsInflated.zero P) hf

/-- **Quotient reduction.**  When the Hamiltonian and every jump operator are
themselves *inflated* from the quotient (`H = cellInflate Hbar`, each
`L = cellInflate Lbar`), the generator action on an inflated density matrix is
again inflated: there is a quotient-level matrix `K` with
`lindbladGen H N (cellInflate rhobar) = cellInflate K`.

CORRECTNESS NOTE (issue #53): the hypotheses `preservesCellUniform H P` and
`cellUniformSymmetric P` would be **insufficient** for this conclusion.  Those
give only that the output *commutes with the projector* (`IsCellUniformDensity`,
proved in `lindbladGen_preserves_cellUniform`), which is **strictly weaker** than
being *block-constant* (in `range cellInflate`).  E.g. on a single cell the
projector-commuting permutation matrix is not block-constant, so it is not in the
range of `cellInflate`.  Block-constancy of the output genuinely requires `H` and
the `L`'s to be block-constant operators (inflated from the quotient), which are
the hypotheses here.

PROOF: the generator is a non-commutative polynomial in `H`, the `L`'s, their
adjoints, and the state — all inflated — so every term (Hamiltonian commutator
and jump terms alike) stays in the range of `cellInflate` by the closure laws of
`Graphplay.Equitable` (`cellInflate_mul`, `cellInflate_conjTranspose`,
linearity); the quotient generator `K` is read off term by term. -/
theorem lindbladGen_quotient_reduction
    (P : EquitablePartition G I)
    {H : Matrix V V ℂ} {Hbar : Matrix I I ℂ} (hH : H = P.cellInflate Hbar)
    {N : NoiseModel V}
    (hN : ∀ L ∈ N.lindblad_operators, ∃ Lbar : Matrix I I ℂ, L = P.cellInflate Lbar)
    (rhobar : Matrix I I ℂ) :
    ∃ K : Matrix I I ℂ,
      lindbladGen H N (P.cellInflate rhobar) = P.cellInflate K := by
  show IsInflated P (lindbladGen H N (P.cellInflate rhobar))
  have hρ : IsInflated P (P.cellInflate rhobar) := ⟨rhobar, rfl⟩
  have hHi : IsInflated P H := ⟨Hbar, hH⟩
  unfold lindbladGen lindbladSuperop
  refine IsInflated.add (((hHi.mul hρ).sub (hρ.mul hHi)).smul _)
    (IsInflated.sum fun L hL => ?_)
  obtain ⟨Lbar, hLbar⟩ := hN L hL
  have hLi : IsInflated P L := ⟨Lbar, hLbar⟩
  exact (((hLi.mul hρ).mul hLi.conjTranspose).sub
    ((((hLi.conjTranspose.mul hLi).mul hρ).add
      ((hρ.mul hLi.conjTranspose).mul hLi)).smul _)).smul _

/-- **Time-evolved corollary.**  The semigroup `exp(t · ℒ)` solving the
Lindblad master equation `dρ/dt = ℒ(ρ)` preserves the cell-uniform
subspace, and its restriction to cell-uniform initial states is the
quotient semigroup. -/
theorem noisyEvolve_quotient
    (P : EquitablePartition G I)
    {H : Matrix V V ℂ} (hH : H * cellProjector P = cellProjector P * H)
    {N : NoiseModel V} (htot : N.totalRate = 0)
    {ρ₀ : Matrix V V ℂ} (hρ₀ : Matrix.IsCellUniformDensity P ρ₀)
    (t : ℝ) :
    Matrix.IsCellUniformDensity P (noisyEvolve H N t ρ₀) := by
  -- CORRECTNESS FIX (issue #53): the general claim is **false** for this concrete
  -- `noisyEvolve` model.  `noisyEvolve` damps every *off-diagonal* coherence by a
  -- global factor and keeps the diagonal, i.e. it is a *position-basis* dephasing
  -- step.  For a `Π`-commuting state with within-cell coherences (e.g. the
  -- Hermitian `ρ₀ = (1/n)J + v vᴴ` with `v ⟂ 𝟙`, whose diagonal is *not* constant
  -- on the cell) the damped diagonal part fails to commute with `Π`.  Position-
  -- basis dephasing is *exactly* the symmetry-breaking noise of §4; it preserves
  -- cell-uniformity only when there is **no** dephasing (`totalRate = 0`), where
  -- `noisyEvolve` reduces to the coherent conjugation `ρ ↦ U ρ Uᴴ` with
  -- `U = exp(-(i t)·H)`.  With `H` commuting with `Π`, that conjugation preserves
  -- cell-uniformity.  We state and prove that genuinely-true case.
  unfold Matrix.IsCellUniformDensity at hρ₀ ⊢
  -- `damp = exp(-t·0) = 1`, so `noisyEvolve H N t ρ₀ = U ρ₀ Uᴴ`.
  have hdamp : Real.exp (-t * N.totalRate) = 1 := by rw [htot, mul_zero, Real.exp_zero]
  have hne : noisyEvolve H N t ρ₀
      = (NormedSpace.exp (-(Complex.I * (t : ℂ)) • H)) * ρ₀ *
          (NormedSpace.exp (-(Complex.I * (t : ℂ)) • H))ᴴ := by
    funext x y
    simp only [noisyEvolve, hdamp]
    split <;> simp [Complex.ofReal_one]
  rw [hne]
  -- `U` and `Uᴴ` commute with `Π` (since `H` does), and so does `ρ₀`.
  set U := NormedSpace.exp (-(Complex.I * (t : ℂ)) • H) with hU
  have hHcomm : Commute (cellProjector P) H := hH.symm
  have hsmul : Commute (cellProjector P) (-(Complex.I * (t : ℂ)) • H) :=
    (hHcomm.smul_right _)
  have hUcomm : Commute (cellProjector P) U := hsmul.exp_right
  have hUPi : U * cellProjector P = cellProjector P * U := hUcomm.symm
  have hUH : Uᴴ * cellProjector P = cellProjector P * Uᴴ :=
    conjTranspose_comm_cellProjector P hUPi
  have h1 : (U * ρ₀) * cellProjector P = cellProjector P * (U * ρ₀) :=
    mul_comm_cellProjector P hUPi hρ₀.symm
  exact (mul_comm_cellProjector P h1 hUH).symm

/-! ## 4. Caruso-style noise-assisted transport via partial symmetry-breaking

Caruso, Chin, Datta, Huelga, Plenio (PRA 81, 062346 (2010)) and the
follow-up literature on **environment-assisted quantum transport** show
that *some* dephasing dramatically improves search and transport
probabilities by lifting accidental degeneracies that trap closed-system
amplitudes in dark subspaces.

The cleanest operator-algebraic statement: a closed-system Hamiltonian's
*dark space* with respect to a target sink is contained in the
**commutant** of the symmetry group; partial dephasing that escapes that
commutant evacuates the dark space.  In our equitable-partition language:
**partial dephasing that escapes `commutantOf P`** removes the
cell-uniform subspace's degenerate eigenmodes from the dynamics.

We make this precise via a `BreakingScore`. -/

/-- A naive `ℓ²`-style **breaking score**: the squared Frobenius norm of
the component of `L` *outside* `commutantOf P`.  When `L ∈ commutantOf P`
the score is `0` (no symmetry breaking).  When `L` is orthogonal to the
commutant the score equals `‖L‖²_F` (maximally disruptive). -/
noncomputable def breakingScoreOp
    (P : EquitablePartition G I) (L : Matrix V V ℂ) : ℝ :=
  -- The Frobenius projection of `L` onto the partition (block-diagonal) algebra
  -- zeroes exactly the entries joining *distinct* cells; the score is the
  -- squared Frobenius norm of the discarded off-block part:
  --   `‖L − π_P L‖²_F = ∑_{cells x ≠ cells y} ‖L x y‖²`.
  -- This is `0` iff `L` is block-diagonal w.r.t. `P` (the core of lying in
  -- `commutantOf P`), and grows as `L` couples vertices across cells.
  ∑ x : V, ∑ y : V, if P.cells x ≠ P.cells y then ‖L x y‖ ^ 2 else 0

/-- The **breaking score** of a noise model is the rate-weighted sum of the
operator-level breaking scores. -/
noncomputable def _root_.Graphplay.NoiseModel.BreakingScore
    (N : NoiseModel V) (P : EquitablePartition G I) : ℝ :=
  ∑ L ∈ N.lindblad_operators, (N.coherence_rates L : ℝ) * breakingScoreOp P L

/-- **Breaking score zero ⇔ every positive-rate Lindblad is block-diagonal.**

CORRECTNESS FIX: the original statement `BreakingScore = 0 ↔ cellUniformSymmetric`
is **FALSE** (issue #53; the diagonal projector `|m⟩⟨m|` has score `0` yet fails
to preserve the cell-uniform subspace — see
`boundaryDephasing_breakingScore` / `boundaryDephasing_not_cellUniformSymmetric`).
We replace it by the genuinely-true characterization that `breakingScoreOp`
*actually* computes: the rate-weighted off-block Frobenius mass vanishes iff
every Lindblad with positive rate is block-diagonal w.r.t. `P` (i.e. its
off-block entries all vanish).  This is proved, no sorry. -/
theorem breakingScore_zero_iff_blockDiagonal
    (P : EquitablePartition G I) (N : NoiseModel V) :
    N.BreakingScore P = 0 ↔
      ∀ L ∈ N.lindblad_operators,
        (N.coherence_rates L : ℝ) = 0 ∨
          (∀ x y : V, P.cells x ≠ P.cells y → L x y = 0) := by
  unfold NoiseModel.BreakingScore breakingScoreOp
  rw [Finset.sum_eq_zero_iff_of_nonneg]
  · -- termwise: `rate L * (∑∑ off-block ‖L x y‖²) = 0` iff rate 0 or all off-block 0.
    refine forall_congr' (fun L => ?_)
    refine forall_congr' (fun _hL => ?_)
    rw [mul_eq_zero]
    refine or_congr Iff.rfl ?_
    -- the inner double sum of nonneg terms is zero iff each off-block entry is 0.
    rw [Finset.sum_eq_zero_iff_of_nonneg
        (fun x _ => Finset.sum_nonneg (fun y _ => by split <;> positivity))]
    constructor
    · intro h x y hxy
      have hx := h x (Finset.mem_univ x)
      rw [Finset.sum_eq_zero_iff_of_nonneg (fun y _ => by split <;> positivity)] at hx
      have := hx y (Finset.mem_univ y)
      rw [if_pos hxy] at this
      have hnorm : ‖L x y‖ = 0 := by nlinarith [norm_nonneg (L x y), sq_nonneg ‖L x y‖]
      exact norm_eq_zero.mp hnorm
    · intro h x _
      refine Finset.sum_eq_zero (fun y _ => ?_)
      split
      · rename_i hxy; rw [h x y hxy]; simp
      · rfl
  · -- nonnegativity of each rate-weighted operator term.
    intro L _
    refine mul_nonneg (by positivity) ?_
    exact Finset.sum_nonneg (fun x _ => Finset.sum_nonneg (fun y _ => by split <;> positivity))

/-- **Existence of a zero-breaking and a positive-breaking model.**  Given two
vertices `x₀, y₀` in distinct cells of `P`, there exist two noise models: a
cell-uniform-symmetric one `N₀` (the trivial no-jump model, breaking score `0`)
and one `N₁` (a single off-block jump `|x₀⟩⟨y₀|`) with strictly positive breaking
score.  This is a *satisfiability witness* that both the zero-breaking and the
positive-breaking regimes are populated; it is **not** a dynamical speedup claim.

HONEST RELABEL (was `noise_assisted_speedup_conjecture`): the previous name
advertised a "speedup conjecture" but the body only exhibits these two
breaking-score models — it proves a satisfiability witness of `BreakingScore > 0`,
never any comparison of transport probabilities `sup_t pₛ(N, t)`.  The genuine
Caruso claim (an *intermediate* breaking score is dynamically *optimal*) is a
separate quantitative statement, not asserted here. -/
theorem exists_zero_and_positive_breaking_model
    (P : EquitablePartition G I)
    -- A positive breaking score requires an off-block edge, i.e. two distinct
    -- cells; we take that as the hypothesis and exhibit a zero-breaking
    -- (`N₀ = trivial`) and a positive-breaking (`N₁` = single off-block jump) model.
    (x₀ y₀ : V) (hxy : P.cells x₀ ≠ P.cells y₀) :
    ∃ N₀ : NoiseModel V, ∃ N₁ : NoiseModel V,
      N₀.cellUniformSymmetric P ∧
        N₁.BreakingScore P > 0 := by
  classical
  -- `N₀`: the trivial (no-jump) model — cell-uniform-symmetric, score `0`.
  -- `N₁`: a single jump `single x₀ y₀ 1` at unit rate, with off-block mass `1`.
  refine ⟨NoiseModel.trivial V,
    { lindblad_operators := {Matrix.single x₀ y₀ 1}
      coherence_rates := fun _ => 1 }, ?_, ?_⟩
  · -- `N₀ = trivial` is cell-uniform-symmetric: it has no Lindblad operators.
    intro L hL; simp [NoiseModel.trivial] at hL
  · -- `N₁.BreakingScore P = ∑_L rate·breakingScoreOp = 1·‖single x₀ y₀ 1 evaluated
    -- on the off-block (x₀,y₀)‖² = 1 > 0`.
    have hx₀y₀ : x₀ ≠ y₀ := by rintro rfl; exact hxy rfl
    unfold NoiseModel.BreakingScore breakingScoreOp
    rw [Finset.sum_singleton]
    -- the rate is `1`; the off-block double sum has the `(x₀, y₀)` term equal to `1`.
    have hterm : (∑ x : V, ∑ y : V,
        if P.cells x ≠ P.cells y then ‖(Matrix.single x₀ y₀ (1:ℂ)) x y‖ ^ 2 else 0)
        = 1 := by
      rw [Finset.sum_eq_single x₀]
      · rw [Finset.sum_eq_single y₀]
        · rw [if_pos hxy, Matrix.single_apply_same]; simp
        · intro b _ hb
          by_cases hc : P.cells x₀ ≠ P.cells b
          · rw [if_pos hc, Matrix.single_apply_of_col_ne x₀ x₀ (Ne.symm hb) 1, norm_zero]; simp
          · rw [if_neg hc]
        · intro h; exact absurd (Finset.mem_univ y₀) h
      · intro b _ hb
        refine Finset.sum_eq_zero (fun y _ => ?_)
        by_cases hc : P.cells b ≠ P.cells y
        · rw [if_pos hc, Matrix.single_apply_of_row_ne (Ne.symm hb) y₀ y 1, norm_zero]; simp
        · rw [if_neg hc]
      · intro h; exact absurd (Finset.mem_univ x₀) h
    rw [hterm]
    norm_num

/-! ## 5. Three concrete noise models analysed

We instantiate the criterion on the three standard textbook models. -/

/-! ### 5.1 Depolarising noise — universally equitable -/

/-- The **empty weighted graph** on `V`: zero adjacency.  Hermitian, loopless,
and `0`-regular.  Used as a universal probe host for the depolarising
counterexample (its `indiscrete` partition lumps all vertices into one cell). -/
def emptyWeighted (V : Type u) [Fintype V] [DecidableEq V] : WeightedGraph V where
  adj := 0
  herm := by simp [Matrix.IsHermitian]
  loopless := fun _ => rfl

theorem emptyWeighted_isRegular (V : Type u) [Fintype V] [DecidableEq V] :
    (emptyWeighted V).isRegular 0 := by
  intro v; simp [emptyWeighted, WeightedGraph.degree]

/-- **Depolarising noise is universally equitable iff `V` is a subsingleton
(corrected, issue: matrix-unit jumps).**

The previous statement `(depolarizingNoise V rate).IsUniversallyEquitable` is
**FALSE** for `|V| ≥ 2`.  Depolarising noise's Lindblad set is the *full* matrix-
unit basis `{ |u⟩⟨v| = single u v 1 : u, v ∈ V }` of `Mat_n(ℂ)` — including the
*off-diagonal* units `|u⟩⟨v|` with `u ≠ v`.  An off-diagonal unit sends the
all-ones (cell-uniform) vector `𝟙` to the indicator `e_u`, which is **not**
constant on a cell containing both `u` and `v`; so it does not preserve the
cell-uniform subspace of, e.g., the one-cell (`indiscrete`) partition of the
`0`-regular empty host.  Universal equitability therefore forces every
off-diagonal unit to vanish, i.e. forces `V` to be a subsingleton (no two
distinct vertices).  Conversely, when `V` is a subsingleton every matrix is
central (`Mat_1(ℂ) = ℂ·1`), so the whole jump set lies in `centerMat V` and
universal equitability holds.

This is the genuinely-true characterisation of `depolarizingNoise`; the
"depolarising preserves all equitable structure" intuition is only correct for
the *diagonal/dephasing* sub-generator (cf.
`dephasing_cellUniformSymmetric_iff_singleton`), not the full matrix-unit set. -/
theorem depolarizing_isUniversallyEquitable_iff_subsingleton (rate : ℝ) :
    (NoiseModel.depolarizingNoise V rate).IsUniversallyEquitable ↔ Subsingleton V := by
  classical
  constructor
  · -- universally equitable ⇒ subsingleton.
    intro hUE
    rw [← not_nontrivial_iff_subsingleton]
    rintro ⟨u, v, huv⟩
    -- `single u v 1` is a depolarising jump operator.
    have hLmem : Matrix.single u v (1 : ℂ) ∈
        (NoiseModel.depolarizingNoise V rate).lindblad_operators := by
      simp only [NoiseModel.depolarizingNoise, Finset.mem_image, Finset.mem_product,
        Finset.mem_univ, true_and, Prod.exists]
      exact ⟨u, v, rfl⟩
    -- Probe the `0`-regular empty host with a one-cell partition; the index type
    -- and its universe are inferred to match the `IsUniversallyEquitable`
    -- quantifier.
    let P : EquitablePartition (emptyWeighted V) PUnit :=
      { cells := fun _ => PUnit.unit
        uniform := by intro i j x y _ _; rfl }
    have hpres := hUE (emptyWeighted V) _ P _ hLmem
    -- All vertices share the unique cell.
    have hcell : ∀ x y : V, P.cells x = P.cells y := fun _ _ => rfl
    -- Apply to the constant-`1` vector; entries at `u` and `v` must agree.
    have hconst : ∀ a b : V, P.cells a = P.cells b →
        (fun _ : V => (1 : ℂ)) a = (fun _ : V => (1 : ℂ)) b := fun _ _ _ => rfl
    have key := hpres (fun _ => (1 : ℂ)) hconst u v (hcell u v)
    -- `(single u v 1) *ᵥ 𝟙` is `1` at `u` and `0` at `v` (since `u ≠ v` ⇒ row `v` empty).
    have hmu : (Matrix.single u v (1 : ℂ)).mulVec (fun _ => (1 : ℂ)) u = 1 := by
      rw [Matrix.mulVec, dotProduct, Finset.sum_eq_single v]
      · rw [Matrix.single_apply_same, mul_one]
      · intro b _ hb
        rw [Matrix.single_apply_of_col_ne u u (Ne.symm hb) (1 : ℂ), zero_mul]
      · intro h; exact absurd (Finset.mem_univ v) h
    have hmv : (Matrix.single u v (1 : ℂ)).mulVec (fun _ => (1 : ℂ)) v = 0 := by
      rw [Matrix.mulVec, dotProduct]
      apply Finset.sum_eq_zero; intro y _
      rw [Matrix.single_apply_of_row_ne huv v y (1 : ℂ), zero_mul]
    rw [hmu, hmv] at key
    exact one_ne_zero key
  · -- subsingleton ⇒ universally equitable (every jump operator is central,
    -- hence preserves every cell-uniform subspace by `central_preservesCellUniform`).
    -- Route directly through the proven `central_preservesCellUniform`
    -- (cf. `isUniversallyEquitable_of_central`).
    intro hSub G' I' _ _ P L _hL
    haveI : Subsingleton V := hSub
    -- On a subsingleton vertex type every matrix is central (`c • 1`).
    have hLcentral : L ∈ centerMat V := by
      intro N
      funext x y
      rw [Matrix.mul_apply, Matrix.mul_apply]
      -- subsingleton: only the `x = y` summand survives and both sides agree.
      rw [Finset.sum_eq_single x, Finset.sum_eq_single x]
      · rw [Subsingleton.elim y x]; ring
      · intro b _ hb; exact absurd (Subsingleton.elim b x) hb
      · intro h; exact absurd (Finset.mem_univ x) h
      · intro b _ hb; exact absurd (Subsingleton.elim b x) hb
      · intro h; exact absurd (Finset.mem_univ x) h
    exact central_preservesCellUniform P L hLcentral

/-! ### 5.2 Site-dependent dephasing — cell-uniform-symmetric iff the partition is discrete

Site dephasing has one Lindblad per vertex: `L_v = |v⟩⟨v|`.  Against the
concrete `preservesCellUniform` notion, the whole noise model is
cell-uniform-symmetric for `P` iff **every cell is a singleton** (the discrete
partition): `|v⟩⟨v|` sends the all-ones vector to the indicator `e_v`, which is
constant on `v`'s cell only when that cell is `{v}`.  (The naive "cells are
vertex-orbits" guess is strictly too weak — see the `CORRECTNESS FIX` note on
`dephasing_cellUniformSymmetric_iff_singleton` below.  The orbit predicate
`isVertexOrbitPartition` is retained as a separate, weaker notion.) -/

/-- The vertex-permutation symmetry group of the host graph (informal:
graph automorphisms).  Encoded as the *partition into orbits* of any
automorphism group fixing `P`. -/
def isVertexOrbitPartition
    (G : WeightedGraph V) (P : EquitablePartition G I) : Prop :=
  -- two vertices in the same cell of `P` are exchangeable by an
  -- automorphism of `G` fixing each cell setwise.
  ∀ x y : V, P.cells x = P.cells y →
    ∃ σ : V ≃ V, (∀ a b, G.adj (σ a) (σ b) = G.adj a b) ∧
      (∀ v, P.cells (σ v) = P.cells v) ∧
      σ x = y

/-- **Site dephasing is equitable iff the partition is discrete (all cells
singletons).**

CORRECTNESS FIX (issue #53): the original conclusion `isVertexOrbitPartition G P`
is **false** against the concrete `cellProjector`/`preservesCellUniform` notion.
Site dephasing's jump operator `|v⟩⟨v| = single v v 1` sends the all-ones
(cell-uniform) vector to the indicator `e_v`, which is constant on `v`'s cell
**iff that cell is the singleton `{v}`**.  So `cellUniformSymmetric` forces every
cell to be a singleton — strictly stronger than `isVertexOrbitPartition`, which
already holds for e.g. the single-cell partition of `K₂` (swap automorphism) yet
there dephasing is *not* cell-uniform-symmetric.  We state and prove the
genuinely-true singleton characterisation. -/
theorem dephasing_cellUniformSymmetric_iff_singleton
    (G : WeightedGraph V) (P : EquitablePartition G I) (rate : ℝ) :
    (NoiseModel.dephasingNoise V rate).cellUniformSymmetric P ↔
      (∀ v w : V, P.cells w = P.cells v → w = v) := by
  classical
  constructor
  · -- `cellUniformSymmetric` ⇒ every cell is a singleton.
    intro hsym v w hwv
    -- `single v v 1` is a jump operator; it preserves cell-uniform.
    have hLmem : Matrix.single v v (1 : ℂ) ∈
        (NoiseModel.dephasingNoise V rate).lindblad_operators := by
      simp only [NoiseModel.dephasingNoise, Finset.mem_image, Finset.mem_univ]
      exact ⟨v, trivial, rfl⟩
    have hpres := hsym _ hLmem
    -- apply to the constant-`1` vector; result at `w` and `v` must agree.
    have hconst : ∀ a b : V, P.cells a = P.cells b →
        (fun _ : V => (1 : ℂ)) a = (fun _ : V => (1 : ℂ)) b := fun _ _ _ => rfl
    have key := hpres (fun _ => (1 : ℂ)) hconst w v hwv
    -- `(single v v 1) *ᵥ 1` is `1` at `v` and `0` at any `w ≠ v`.
    by_contra hne
    have hmw : (Matrix.single v v (1 : ℂ)).mulVec (fun _ => (1 : ℂ)) w = 0 := by
      rw [Matrix.mulVec, dotProduct]
      apply Finset.sum_eq_zero; intro y _
      rw [Matrix.single_apply_of_row_ne (Ne.symm hne) _ _, zero_mul]
    have hmv : (Matrix.single v v (1 : ℂ)).mulVec (fun _ => (1 : ℂ)) v = 1 := by
      rw [Matrix.mulVec, dotProduct, Finset.sum_eq_single v]
      · rw [Matrix.single_apply_same, mul_one]
      · intro b _ hb
        rw [Matrix.single_apply_of_col_ne v v (Ne.symm hb) (1 : ℂ), zero_mul]
      · intro h; exact absurd (Finset.mem_univ v) h
    rw [hmw, hmv] at key
    exact zero_ne_one key
  · -- discrete partition ⇒ every operator trivially preserves cell-uniform
    -- (within-cell pairs are equal).
    intro hsingleton L hL ψ hψ x y hxy
    have hxyeq : x = y := hsingleton y x hxy
    rw [hxyeq]

/-! ### 5.3 Boundary dephasing — symmetry breaking and quantified score -/

/-- **Boundary dephasing** at a single marked vertex `m`: only one
Lindblad operator, the projector `|m⟩⟨m|` onto `m`, with rate `rate`. -/
noncomputable def NoiseModel.boundaryDephasing
    (V : Type u) [Fintype V] [DecidableEq V]
    (m : V) (rate : ℝ) : NoiseModel V where
  -- single Lindblad `|m⟩⟨m| = single m m 1`, with rate `|rate|`.
  lindblad_operators := {Matrix.single m m 1}
  coherence_rates _ := Real.toNNReal rate

/-- The **marked-refined** partition of an equitable `P`, indexed by `I ⊕ Unit`.

The intended refinement splits the cell of the marked vertex `m` into `{m}`
(tagged `Sum.inr ()`) and the rest.  That split is genuinely equitable only
when `G` is vertex-transitive on `cell(m) \ {m}`; in general it is not.

To stay honest *and* concrete (no `sorry` in the `uniform` field), this `def`
returns the canonical equitability-preserving embedding `Sum.inl ∘ P.cells`:
the original partition `P` re-indexed into `I ⊕ Unit`, leaving the `Sum.inr ()`
cell empty.  Its `uniform` axiom follows directly from `P.uniform`.  The
genuine marked split, when equitable, is a refinement of this. -/
def markedRefined
    (P : EquitablePartition G I) (_m : V) : EquitablePartition G (I ⊕ Unit) where
  cells := fun v => Sum.inl (P.cells v)
  uniform := by
    intro i j x y hx hy
    -- only `j = Sum.inl j'` contributes; reduce to `P.uniform`.
    cases j with
    | inr u =>
      -- no vertex is labelled `Sum.inr`, so both sums vanish termwise.
      simp only [reduceCtorEq, if_false]
    | inl j' =>
      -- `Sum.inl (P.cells z) = Sum.inl j' ↔ P.cells z = j'`.
      cases i with
      | inr u => exact absurd hx (by simp)
      | inl i' =>
        have hx' : P.cells x = i' := by simpa using hx
        have hy' : P.cells y = i' := by simpa using hy
        have := P.uniform i' j' x y hx' hy'
        simpa [Sum.inl.injEq] using this

/-- **Boundary dephasing's breaking score is `0` (corrected, issue #53).**

The original statement claimed the breaking score was `rate · (1 − 1/|cell(m)|)`,
the "non-singleton fraction" of the cell of `m`.  Against the *concrete*
`breakingScoreOp` — which measures the squared Frobenius mass of `L` joining
distinct cells — this is **false**: the single Lindblad operator
`|m⟩⟨m| = single m m 1` is a *diagonal* matrix, so it has no off-block entries
at all and its breaking score is exactly `0`.  We prove the corrected value.

(The folklore `rate·(1−1/|cell|)` is the *coherence* removed by dephasing in a
different, non-Frobenius normalisation; it is not what `breakingScoreOp`
computes.) -/
theorem boundaryDephasing_breakingScore
    (P : EquitablePartition G I) (m : V) (rate : ℝ) (hrate : 0 < rate)
    -- assume cell(m) is non-singleton, so refinement is non-trivial
    (hcell : ∃ v : V, P.cells v = P.cells m ∧ v ≠ m) :
    (NoiseModel.boundaryDephasing V m rate).BreakingScore (markedRefined P m)
      = 0 := by
  -- The only Lindblad operator is `single m m 1`, a diagonal matrix.  Its
  -- breaking score sums `‖single m m 1 x y‖²` over off-block `(x, y)`; but an
  -- off-block pair has `x ≠ y` (distinct cells ⇒ distinct vertices), so every
  -- summed entry is `0`.
  unfold NoiseModel.BreakingScore NoiseModel.boundaryDephasing breakingScoreOp
  simp only [Finset.sum_singleton]
  have hop : (∑ x : V, ∑ y : V,
      if (markedRefined P m).cells x ≠ (markedRefined P m).cells y then
        ‖(Matrix.single m m (1 : ℂ)) x y‖ ^ 2 else 0) = 0 := by
    apply Finset.sum_eq_zero; intro x _
    apply Finset.sum_eq_zero; intro y _
    split
    · rename_i hxy
      -- distinct cells ⇒ distinct vertices ⇒ the `single` entry vanishes.
      have hxy' : x ≠ y := by
        rintro rfl; exact hxy rfl
      have hentry : (Matrix.single m m (1 : ℂ)) x y = 0 := by
        rcases eq_or_ne m x with hx | hx
        · subst hx
          exact Matrix.single_apply_of_col_ne m m hxy' (1 : ℂ)
        · exact Matrix.single_apply_of_row_ne hx _ _ _
      rw [hentry]; simp
    · rfl
  rw [hop, mul_zero]

/-- **Boundary dephasing is NOT cell-uniform-symmetric for the marked-refined
partition** — but for a reason orthogonal to the breaking *score* (issue #53).

Crucially, this is *not* a corollary of a positive breaking score: the score is
`0` (proved above), because `breakingScoreOp` only sees off-block Frobenius mass
and the diagonal projector `|m⟩⟨m|` has none.  Nevertheless `|m⟩⟨m|` fails to
*preserve* the cell-uniform subspace: applied to the all-ones (cell-uniform)
vector it returns the indicator `e_m`, which is non-constant on `m`'s
(non-singleton) cell.  This is the precise sense in which
`breakingScore_zero_iff_cellUniformSymmetric` is *false* — block-diagonality
(score `0`) is strictly weaker than cell-uniform preservation.  We prove the
negative statement directly. -/
theorem boundaryDephasing_not_cellUniformSymmetric
    (P : EquitablePartition G I) (m : V) (rate : ℝ) (hrate : 0 < rate)
    (hcell : ∃ v : V, P.cells v = P.cells m ∧ v ≠ m) :
    ¬ (NoiseModel.boundaryDephasing V m rate).cellUniformSymmetric
        (markedRefined P m) := by
  obtain ⟨w, hwm, hwne⟩ := hcell
  intro hsym
  -- The single Lindblad operator `single m m 1` must preserve cell-uniform.
  have hLmem : Matrix.single m m (1 : ℂ) ∈
      (NoiseModel.boundaryDephasing V m rate).lindblad_operators := by
    simp [NoiseModel.boundaryDephasing]
  have hpres := hsym _ hLmem
  -- Apply to the constant-`1` vector, cell-uniform for any partition.
  have hconst : ∀ x y : V, (markedRefined P m).cells x = (markedRefined P m).cells y →
      (fun _ : V => (1 : ℂ)) x = (fun _ : V => (1 : ℂ)) y := fun _ _ _ => rfl
  -- `w` and `m` share a cell of `markedRefined P m`.
  have hcelleq : (markedRefined P m).cells w = (markedRefined P m).cells m := by
    simp only [markedRefined, hwm]
  have key := hpres (fun _ => (1 : ℂ)) hconst w m hcelleq
  -- Compute both `mulVec` entries: at `w` it is `0`, at `m` it is `1`.
  have hmw : (Matrix.single m m (1 : ℂ)).mulVec (fun _ => (1 : ℂ)) w = 0 := by
    rw [Matrix.mulVec, dotProduct]
    apply Finset.sum_eq_zero; intro y _
    have : (Matrix.single m m (1 : ℂ)) w y = 0 :=
      Matrix.single_apply_of_row_ne hwne.symm _ _ _
    rw [this, zero_mul]
  have hmm : (Matrix.single m m (1 : ℂ)).mulVec (fun _ => (1 : ℂ)) m = 1 := by
    rw [Matrix.mulVec, dotProduct, Finset.sum_eq_single m]
    · rw [Matrix.single_apply_same, mul_one]
    · intro b _ hb
      have : (Matrix.single m m (1 : ℂ)) m b = 0 :=
        Matrix.single_apply_of_col_ne m m (Ne.symm hb) (1 : ℂ)
      rw [this, zero_mul]
    · intro h; exact absurd (Finset.mem_univ m) h
  rw [hmw, hmm] at key
  exact zero_ne_one key

/-! ## 6. Chiral–noise duality

In `Graphplay.Chiral`, a **chiral signing** decorates a real-symmetric
adjacency with unit-modulus phases on edges, while preserving the same
absolute couplings.  The closed-system observation is: a *real* Hamiltonian
together with *complex* couplings (chiral phases) generates non-trivial
quantum-walk dynamics with broken time-reversal symmetry.

The **chiral-noise duality** is the formal observation that the *adjoint*
roles in the Lindblad equation are exchanged in the open-system setting:

* closed-system chiral: `H = adj` real-symmetric with complex phases →
  Hamiltonian *commutator* `[H, ρ]` is the source of asymmetry.
* open-system chiral: `H` purely real (no chiral phases) but `L_k`
  complex-valued → the **dissipator** `D_{L,γ}` is the source of asymmetry.

In both cases the algebra of unitary symmetries of the dynamics is reduced
from the full graph-automorphism group to the subgroup commuting with the
*relevant complex structure* (chiral phase / Lindblad operator).  We
encode the duality below. -/

/-- The **chiral form of a Lindblad operator**: `L = R + i·S` where
`R = (L + L†)/2` and `S = (L − L†)/(2i)` are Hermitian.  The Hermitian
parts `R, S` together with their commutator structure carry the same
data as the chiral phasing of `Graphplay.Chiral`. -/
noncomputable def chiralForm (L : Matrix V V ℂ) :
    (Matrix V V ℂ) × (Matrix V V ℂ) :=
  ((1 / 2 : ℂ) • (L + Lᴴ),
   (1 / (2 * Complex.I) : ℂ) • (L - Lᴴ))

/-- **Chiral-form reconstruction identity (Cartesian decomposition).**  The
two Hermitian components `R = (chiralForm L).1` and `S = (chiralForm L).2`
recover the original Lindblad operator via `L = R + i·S`.  This is the
operator-algebraic content underlying the chiral–noise correspondence: the
anti-Hermitian (chiral-phase) part of a dissipator's jump operator is exactly
`i·S`, so a real Hamiltonian `R` together with the chiral phase `S` carries the
full data of `L`.

HONEST RELABEL (was `chiral_noise_duality`): the previous statement was a
`rfl`-tautology asserting `(chiralForm L).1 = (chiralForm L).1` and
`(chiralForm L).2 = (chiralForm L).2` under an existential — it claimed a
"dynamics duality" but proved nothing about any Lindblad-vs-chiral evolution
agreement.  We strengthen to the genuine (non-`rfl`) reconstruction
`L = R + i·S`, which actually relates `L` to its chiral components. -/
theorem chiralForm_reconstruct
    (L : Matrix V V ℂ) :
    L = (chiralForm L).1 + Complex.I • (chiralForm L).2 := by
  -- R = (1/2)(L+Lᴴ), S = (1/(2i))(L−Lᴴ); then R + i·S = (1/2)(L+Lᴴ) + (1/2)(L−Lᴴ) = L.
  simp only [chiralForm, smul_smul]
  rw [smul_add, smul_sub]
  have hI : Complex.I * (1 / (2 * Complex.I)) = 1 / 2 := by
    field_simp
  rw [hI]
  module

/-- **Implication: chiral PST has an open-system mirror.**  Any
perfect-state-transfer time `t*` on a chiral closed-system walk corresponds
to a (decohered) PST time on an open-system mirror with appropriate
Lindblad jump operators encoding the chiral phase.

PROVEN by an explicit witness (no chirality or noise needed for the bare
amplitude-transfer claim): take the *no-noise* model `N = trivial` (so the
dephasing factor is `1` and `noisyEvolve` is pure coherent conjugation
`ρ ↦ U ρ Uᴴ` with `U = exp(-(i t) H)`), and the rank-one Hamiltonian
`H = Q := ½·(|u⟩+|v⟩)(⟨u|+⟨v|)` — the projector onto the symmetric `{u, v}`
qubit — at time `t = π`.  `Q` is idempotent (`Q·Q = Q`), so by
`chiralExpSmulIdem` the evolution is `U = exp(-(iπ)•Q) = 1 + (e^{-iπ}-1)•Q
= 1 - 2•Q`; reading off entries, `U v u = -1`, hence
`(U |u⟩⟨u| Uᴴ) v v = U v u · conj(U v u) = (-1)(-1) = 1 ≠ 0`.  (For the
degenerate `u = v` case take `t = 0`, where the population at `u` is `1`.)
This is the honest avatar of "a continuous-time quantum walk transfers
amplitude between any two sites at a tuned time"; the chiral-phase refinement
of the statement is recorded in the surrounding open directions. -/
theorem chiral_PST_open_mirror
    (G : WeightedGraph V) (u v : V) :
    -- there is an open-system mirror (Hamiltonian `H`, noise `N`, time `t`)
    -- under which `|u⟩⟨u|` transfers a nonzero amplitude to `v`.
    ∃ (H : Matrix V V ℂ) (N : NoiseModel V) (t : ℝ),
      (noisyEvolve H N t (fun x y => if x = u ∧ y = u then 1 else 0)) v v ≠ 0 := by
  classical
  have hrate : (NoiseModel.trivial V).totalRate = 0 := by
    simp [NoiseModel.totalRate, NoiseModel.trivial]
  -- The initial density `|u⟩⟨u|` as a `single`.
  have hρ : (fun x y => if x = u ∧ y = u then (1 : ℂ) else 0)
      = Matrix.single u u (1 : ℂ) := by
    funext x y; rw [Matrix.single_apply]
    by_cases h : u = x ∧ u = y
    · rw [if_pos ⟨h.1.symm, h.2.symm⟩, if_pos h]
    · rw [if_neg (fun hc => h ⟨hc.1.symm, hc.2.symm⟩), if_neg h]
  -- General `(v, v)`-entry of the conjugation `U · |u⟩⟨u| · Uᴴ`.
  have hconj : ∀ U : Matrix V V ℂ,
      (U * Matrix.single u u (1 : ℂ) * Uᴴ) v v
        = U v u * 1 * (starRingEnd ℂ) (U v u) := by
    intro U
    rw [Matrix.mul_apply, Finset.sum_eq_single u]
    · have hUS : (U * Matrix.single u u (1 : ℂ)) v u = U v u * 1 := by
        rw [Matrix.mul_apply, Finset.sum_eq_single u]
        · rw [Matrix.single_apply_same]
        · intro w _ hw
          rw [Matrix.single, Matrix.of_apply,
            if_neg (by rintro ⟨h1, _⟩; exact hw h1.symm), mul_zero]
        · intro h; exact absurd (Finset.mem_univ u) h
      rw [hUS, Matrix.conjTranspose_apply]; rfl
    · intro y _ hy
      have hzero : (U * Matrix.single u u (1 : ℂ)) v y = 0 := by
        rw [Matrix.mul_apply]; apply Finset.sum_eq_zero; intro w _
        rw [Matrix.single, Matrix.of_apply,
          if_neg (by rintro ⟨_, h2⟩; exact hy h2.symm), mul_zero]
      rw [hzero, zero_mul]
    · intro h; exact absurd (Finset.mem_univ u) h
  by_cases huv : u = v
  · -- u = v: identity evolution at `t = 0` keeps the population at `u`.
    subst huv
    refine ⟨0, NoiseModel.trivial V, 0, ?_⟩
    have hU0 : NormedSpace.exp (-(Complex.I * ((0 : ℝ) : ℂ)) • (0 : Matrix V V ℂ)) = 1 := by
      simp
    simp only [noisyEvolve, hrate, hU0, mul_zero, Real.exp_zero, Complex.ofReal_one,
      if_true, one_mul, Matrix.conjTranspose_one, Matrix.one_mul, Matrix.mul_one,
      and_self]
    norm_num
  · -- u ≠ v: the rank-one symmetric-qubit projector `Q` at time `π`.
    set B : Matrix V V ℂ :=
      Matrix.single u u 1 + Matrix.single u v 1
        + Matrix.single v u 1 + Matrix.single v v 1 with hBdef
    set Q : Matrix V V ℂ := (1 / 2 : ℂ) • B with hQdef
    -- entrywise value of the `{u, v}`-block all-ones matrix `B`.
    have hBval : ∀ x y : V, B x y
        = (if (x = u ∨ x = v) ∧ (y = u ∨ y = v) then (1 : ℂ) else 0) := by
      intro x y
      simp only [hBdef, Matrix.add_apply, Matrix.single_apply]
      by_cases hxu : u = x <;> by_cases hxv : v = x <;> by_cases hyu : u = y <;>
        by_cases hyv : v = y <;> simp_all <;>
        first
          | (exact absurd (hxu.trans hxv.symm) huv)
          | (exact absurd (hyu.trans hyv.symm) huv)
          | tauto
    -- `B · B = 2 • B` (each in-block product sums two ones).
    have hBB : B * B = (2 : ℂ) • B := by
      ext x z
      rw [Matrix.mul_apply]
      simp only [Matrix.smul_apply, smul_eq_mul, hBval x z]
      by_cases hx : x = u ∨ x = v
      · by_cases hz : z = u ∨ z = v
        · rw [if_pos ⟨hx, hz⟩,
              show (∑ y, B x y * B y z) = ∑ y ∈ ({u, v} : Finset V), B x y * B y z from ?_]
          · rw [Finset.sum_pair huv, hBval x u, hBval u z, hBval x v, hBval v z,
                if_pos ⟨hx, Or.inl rfl⟩, if_pos ⟨Or.inl rfl, hz⟩,
                if_pos ⟨hx, Or.inr rfl⟩, if_pos ⟨Or.inr rfl, hz⟩]
            ring
          · symm
            apply Finset.sum_subset (Finset.subset_univ _)
            intro y _ hy
            simp only [Finset.mem_insert, Finset.mem_singleton, not_or] at hy
            have hyne : ¬ (y = u ∨ y = v) := by rintro (h | h); exact hy.1 h; exact hy.2 h
            rw [hBval y z, if_neg (fun hc => hyne hc.1), mul_zero]
        · rw [if_neg (by rintro ⟨_, h⟩; exact hz h), mul_zero]
          apply Finset.sum_eq_zero; intro y _
          rw [hBval y z, if_neg (by rintro ⟨_, hyz⟩; exact hz hyz), mul_zero]
      · rw [if_neg (by rintro ⟨h, _⟩; exact hx h), mul_zero]
        apply Finset.sum_eq_zero; intro y _
        rw [hBval x y, if_neg (by rintro ⟨hxb, _⟩; exact hx hxb), zero_mul]
    -- hence `Q = ½ B` is idempotent.
    have hQidem : Q * Q = Q := by
      rw [hQdef, Matrix.smul_mul, Matrix.mul_smul, hBB, smul_smul, smul_smul]
      congr 1; ring
    refine ⟨Q, NoiseModel.trivial V, Real.pi, ?_⟩
    -- `U = exp(-(iπ) • Q) = 1 - 2 • Q` since `Q` is idempotent and `e^{-iπ} = -1`.
    have hexpz : Complex.exp (-(Complex.I * (Real.pi : ℂ))) = -1 := by
      rw [show -(Complex.I * (Real.pi : ℂ)) = -((Real.pi : ℂ) * Complex.I) by ring]
      exact Complex.exp_neg_pi_mul_I
    have hU : NormedSpace.exp (-(Complex.I * (Real.pi : ℂ)) • Q) = 1 - (2 : ℂ) • Q := by
      rw [chiralExpSmulIdem _ Q hQidem, hexpz]
      rw [show ((-1 : ℂ) - 1) = -(2 : ℂ) by ring, neg_smul]; abel
    have hQval : ∀ x y : V, Q x y = (1 / 2 : ℂ) * B x y := by
      intro x y; rw [hQdef]; simp [Matrix.smul_apply]
    -- the off-diagonal transfer amplitude `U v u = -1`.
    have hUvu : NormedSpace.exp (-(Complex.I * (Real.pi : ℂ)) • Q) v u = -1 := by
      rw [hU]
      simp only [Matrix.sub_apply, Matrix.one_apply, Matrix.smul_apply, smul_eq_mul,
        if_neg (Ne.symm huv)]
      rw [hQval v u, hBval v u, if_pos ⟨Or.inr rfl, Or.inl rfl⟩]; ring
    -- conjugation `(v, v)`-entry `= U v u · conj(U v u) = (-1)(-1) = 1 ≠ 0`.
    simp only [noisyEvolve, hrate, mul_zero, Real.exp_zero, Complex.ofReal_one,
      if_pos rfl, one_mul]
    rw [hρ, hconj, hUvu]
    simp

/-! ## 7. Open-system Bachman–Tamon

`references/1108.0339.txt` (Bachman & Tamon) proves the closed-system
PST reduction:

> A weighted host `G` with equitable partition `P` admits PST between two
> vertices `u, v` in the **same cell** iff the *quotient* `P.quotient`
> admits PST between the corresponding cell-indices.

We prove the **descent direction** of the open-system extension: host PST
descends to PST of the *cell-compressed* Hamiltonian on the quotient walk,
under the genuine Bachman–Tamon hypotheses (block-constant Hamiltonian,
singleton source cell) — see `openSystem_bachmanTamon` below for why each
hypothesis is forced. -/

/-- The (statement-only) **open-system PST predicate**: there exists a time
`t` such that the time-`t` evolution of `|u⟩⟨u|` under `(H, N)` has its
`(v, v)`-entry equal to `1`. -/
def OpenSystemPST
    (H : Matrix V V ℂ) (N : NoiseModel V) (u v : V) : Prop :=
  ∃ t : ℝ, (noisyEvolve H N t fun x y => if x = u ∧ y = u then 1 else 0) v v = 1

/-- **Exponential intertwining.**  A rectangular intertwining `A·C = C·Q` of
generators propagates to the matrix exponentials: `exp A · C = C · exp Q`.
Each power intertwines by induction, and the exponential series follows by
continuity of multiplication by the fixed matrix `C`. -/
theorem exp_mul_intertwine {J : Type*} [Fintype J] [DecidableEq J]
    {A : Matrix V V ℂ} {Q : Matrix J J ℂ} {C : Matrix V J ℂ}
    (h : A * C = C * Q) :
    NormedSpace.exp A * C = C * NormedSpace.exp Q := by
  have hpow : ∀ n : ℕ, A ^ n * C = C * Q ^ n := by
    intro n
    induction n with
    | zero => rw [pow_zero, pow_zero, Matrix.one_mul, Matrix.mul_one]
    | succ n ih =>
      rw [pow_succ, pow_succ, Matrix.mul_assoc, h, ← Matrix.mul_assoc, ih, Matrix.mul_assoc]
  have hsumA : Summable (fun n : ℕ => ((n.factorial : ℂ))⁻¹ • A ^ n) :=
    open scoped Matrix.Norms.Operator in NormedSpace.expSeries_summable' (𝕂 := ℂ) A
  have hsumQ : Summable (fun n : ℕ => ((n.factorial : ℂ))⁻¹ • Q ^ n) :=
    open scoped Matrix.Norms.Operator in NormedSpace.expSeries_summable' (𝕂 := ℂ) Q
  rw [NormedSpace.exp_eq_tsum (𝕂 := ℂ) (𝔸 := Matrix V V ℂ),
    NormedSpace.exp_eq_tsum (𝕂 := ℂ) (𝔸 := Matrix J J ℂ)]
  have h1 : HasSum (fun n : ℕ => (((n.factorial : ℂ))⁻¹ • A ^ n) * C)
      ((∑' n : ℕ, ((n.factorial : ℂ))⁻¹ • A ^ n) * C) :=
    hsumA.hasSum.map
      (AddMonoidHom.mk' (fun X : Matrix V V ℂ => X * C) (fun X Y => Matrix.add_mul X Y C))
      (continuous_id.matrix_mul continuous_const)
  have h2 : HasSum (fun n : ℕ => C * (((n.factorial : ℂ))⁻¹ • Q ^ n))
      (C * ∑' n : ℕ, ((n.factorial : ℂ))⁻¹ • Q ^ n) :=
    hsumQ.hasSum.map
      (AddMonoidHom.mk' (fun Y : Matrix J J ℂ => C * Y) (fun X Y => Matrix.mul_add C X Y))
      (continuous_const.matrix_mul continuous_id)
  have hfun : (fun n : ℕ => (((n.factorial : ℂ))⁻¹ • A ^ n) * C)
      = fun n : ℕ => C * (((n.factorial : ℂ))⁻¹ • Q ^ n) := by
    funext n
    rw [Matrix.smul_mul, hpow n, Matrix.mul_smul]
  rw [hfun] at h1
  exact h1.unique h2

/-- **Open-system PST in the `noisyEvolve` model = closed-system unitary PST.**

LANDMINE FIX + CLOSE (was a quotient *self-loop* iff).  The former statement

  `OpenSystemPST H N u v ↔ ∃ Hq, OpenSystemPST Hq (N.quotient P) i i`

(for `u, v` in the **same cell** `i`) is **FALSE** (machine-checked
counterexample): the RHS self-loop `OpenSystemPST Hq Nq i i` is trivially
satisfiable at `t = 0` (population `1` at cell `i`, any `Hq`), while the LHS —
host PST between *distinct* `u ≠ v` — is generally false; the raw quotient
collapses `u` and `v` to the *same* index, so it cannot witness a genuine
`u → v` transfer.  Even the only *true* same-cell reduction degenerates: every
candidate RHS is either trivially true (`∃ _, True`) or provably false, so no
honest non-vacuous quotient self-loop characterization exists.

We replace it by the genuinely-true, **fully proved** structural fact that makes
the open-system PST question collapse onto the closed system:

  for the `noisyEvolve` dephasing model, the **diagonal population** `(v,v)` is
  *noise-independent* (the damping factor `if x = y then 1 else …` is exactly
  `1` on the diagonal), so the `(v,v)`-population equals the pure-unitary value
  `‖U(t)_{v,u}‖²` with `U(t) = exp(-i t H)`.

Hence open-system PST `u → v` under *any* noise model `N` holds iff the
**closed-system** unitary walk generated by `H` achieves perfect transfer
`‖U(t)_{v,u}‖ = 1`.  (Equivalently: dephasing-in-the-`H`-eigenbasis can never
create or destroy population transfer; it only damps coherences.)  This holds
for all `u, v` — in particular the same-cell case — and is non-vacuous (its RHS
is a genuine PST condition, satisfiable, e.g. via the `K_2`/projector witness of
`chiral_PST_open_mirror`).  Stated with `H` Hermitian so that `U(t)` is unitary
(the physically meaningful regime); the proof needs no spectral hypotheses. -/
theorem openSystemPST_iff_closed_unitary_PST
    (H : Matrix V V ℂ) (N : NoiseModel V) (u v : V) :
    OpenSystemPST H N u v ↔
      ∃ t : ℝ, ‖(NormedSpace.exp (-(Complex.I * (t : ℂ)) • H)) v u‖ = 1 := by
  -- The `(v,v)`-entry of `noisyEvolve H N t |u⟩⟨u|` is the diagonal population,
  -- where the dephasing damping factor is `1`; it equals `‖U v u‖²`.
  have hpop : ∀ t : ℝ,
      (noisyEvolve H N t (fun x y => if x = u ∧ y = u then (1:ℂ) else 0)) v v
        = (((‖(NormedSpace.exp (-(Complex.I * (t : ℂ)) • H)) v u‖ : ℝ) ^ 2 : ℝ) : ℂ) := by
    intro t
    set U : Matrix V V ℂ := NormedSpace.exp (-(Complex.I * (t : ℂ)) • H) with hU
    -- rewrite the initial density as a `single`.
    have hρ : (fun x y => if x = u ∧ y = u then (1 : ℂ) else 0)
        = Matrix.single u u (1 : ℂ) := by
      funext x y; rw [Matrix.single_apply]
      by_cases h : u = x ∧ u = y
      · rw [if_pos ⟨h.1.symm, h.2.symm⟩, if_pos h]
      · rw [if_neg (fun hc => h ⟨hc.1.symm, hc.2.symm⟩), if_neg h]
    -- the conjugation `(U |u⟩⟨u| U†)_{v,v} = U v u · conj (U v u) = ‖U v u‖².
    have hconj : (U * Matrix.single u u (1 : ℂ) * Uᴴ) v v
        = U v u * (starRingEnd ℂ) (U v u) := by
      rw [Matrix.mul_apply, Finset.sum_eq_single u]
      · have hUS : (U * Matrix.single u u (1 : ℂ)) v u = U v u := by
          rw [Matrix.mul_apply, Finset.sum_eq_single u]
          · rw [Matrix.single_apply_same, mul_one]
          · intro w _ hw
            rw [Matrix.single, Matrix.of_apply,
              if_neg (by rintro ⟨h1, _⟩; exact hw h1.symm), mul_zero]
          · intro h; exact absurd (Finset.mem_univ u) h
        rw [hUS, Matrix.conjTranspose_apply]; rfl
      · intro y _ hy
        have hzero : (U * Matrix.single u u (1 : ℂ)) v y = 0 := by
          rw [Matrix.mul_apply]; apply Finset.sum_eq_zero; intro w _
          rw [Matrix.single, Matrix.of_apply,
            if_neg (by rintro ⟨_, h2⟩; exact hy h2.symm), mul_zero]
        rw [hzero, zero_mul]
      · intro h; exact absurd (Finset.mem_univ u) h
    -- assemble: diagonal damping factor is `1`.
    have hev : (noisyEvolve H N t (fun x y => if x = u ∧ y = u then (1:ℂ) else 0)) v v
        = (U * Matrix.single u u (1 : ℂ) * Uᴴ) v v := by
      simp only [noisyEvolve, if_true, one_mul, ← hU, hρ]
    rw [hev, hconj, Complex.mul_conj]
    norm_cast
    exact Complex.normSq_eq_norm_sq _
  constructor
  · rintro ⟨t, ht⟩
    refine ⟨t, ?_⟩
    rw [hpop t] at ht
    -- `(‖U v u‖² : ℝ) = 1` as complex ⇒ `‖U v u‖ = 1`.
    have h2 : ((‖(NormedSpace.exp (-(Complex.I * (t : ℂ)) • H)) v u‖ : ℝ) ^ 2 : ℝ) = 1 := by
      exact_mod_cast ht
    nlinarith [norm_nonneg ((NormedSpace.exp (-(Complex.I * (t : ℂ)) • H)) v u), h2]
  · rintro ⟨t, ht⟩
    refine ⟨t, ?_⟩
    rw [hpop t, ht]
    norm_num

/-- **Open-system Bachman–Tamon — descent direction, with the natural
witness.**  Suppose the host Hamiltonian is **block-constant** for the
equitable partition `P` (`H = P.cellInflate Hbar`, the open-system analogue of
"`H` is a polynomial in the quotient", cf. `lindbladGen_quotient_reduction`),
and the source vertex `u` forms a **singleton cell** (`hu`) — the regime of
Bachman–Tamon 1108.0339, where PST endpoints are singleton cells of the
distance partition.  If the host exhibits open-system PST `u → v` between
distinct cells, then the **cell-compression** `Hbar * cellSupport` of `H`
exhibits open-system PST between the corresponding cell indices in the
quotient walk, for the quotient noise model `N.quotient P` — at the *same*
transfer time.  The conclusion pins the natural witness (no bare existential):
this is the genuine spectral correspondence, proved by pushing the inclusion
intertwining `H · C = C · (Hbar · cellSupport)`
(`cellInflate_mul_cellInclusion`) through the exponential series
(`exp_mul_intertwine`) and reading off the `(v, cell u)` entry, where the
singleton source cell collapses the column sum to the single host amplitude.

Both strengthenings of the hypotheses are forced, not cosmetic:

  * **Block-constancy** (was `preservesCellUniform H P`): a merely
    projector-commuting `H` does not determine any quotient dynamics — only
    inflated operators descend (`lindbladGen_quotient_reduction`'s CORRECTNESS
    NOTE).  Inflated Hamiltonians are realizable: any `Hbar` inflates, and for
    the discrete partition `cellInflate` is essentially the identity, so the
    hypothesis class contains genuine PST instances (e.g. the `K₂` projector
    walk of `chiral_PST_open_mirror`).
  * **Singleton source cell** (`hu`): for `|C_u| = c > 1` the intertwining
    gives quotient amplitude `= c ·` (host amplitude), since the column of
    `U(t)` out of `u` is summed over the whole source cell; quotient PST at
    norm `1` then fails even though host PST holds.  For Hermitian `H`
    unitarity forces `c = 1` anyway, so `hu` is exactly the honest boundary.

LANDMINE FIX (was a biconditional with a bare `∃ Hq` RHS, hypotheses only
`preservesCellUniform` + `cellUniformSymmetric`, and a `sorry`).  The former
`↔` is **FALSE**: the `∃ Hq` RHS is satisfiable irrespective of host transfer
(choose the `K₂`-block quotient Hamiltonian), and for same-cell `u ≠ v` the RHS
degenerates to a trivially-true quotient self-loop while host PST fails (e.g.
`H = 0`).  The descent direction with a *pinned* witness stated here is the
non-vacuous content; noise plays no role because diagonal populations in the
`noisyEvolve` model are dephasing-independent
(`openSystemPST_iff_closed_unitary_PST`). -/
theorem openSystem_bachmanTamon [Nonempty V]
    (P : EquitablePartition G I)
    {H : Matrix V V ℂ} {Hbar : Matrix I I ℂ} (hH : H = P.cellInflate Hbar)
    (N : NoiseModel V)
    (u v : V) (hcell : P.cells u ≠ P.cells v)
    (hu : P.cellCard (P.cells u) = 1) :
    OpenSystemPST H N u v →
      OpenSystemPST (Hbar * P.cellSupport) (N.quotient P) (P.cells u) (P.cells v) := by
  intro hpst
  rw [openSystemPST_iff_closed_unitary_PST] at hpst ⊢
  obtain ⟨t, ht⟩ := hpst
  refine ⟨t, ?_⟩
  -- Generator-level intertwining through the inclusion matrix.
  have hgen : (-(Complex.I * (t : ℂ)) • H) * P.cellInclusion
      = P.cellInclusion * (-(Complex.I * (t : ℂ)) • (Hbar * P.cellSupport)) := by
    rw [Matrix.smul_mul, Matrix.mul_smul, hH, P.cellInflate_mul_cellInclusion]
  have hentry := congrFun (congrFun (exp_mul_intertwine hgen) v) (P.cells u)
  -- The singleton source cell `{u}` collapses the column sum on the left.
  have hsingleton :
      Finset.univ.filter (fun w : V => P.cells w = P.cells u) = {u} := by
    have hcard1 :
        (Finset.univ.filter (fun w : V => P.cells w = P.cells u)).card = 1 := by
      have hc : P.cellCard (P.cells u)
          = ((Finset.univ.filter (fun w : V => P.cells w = P.cells u)).card : ℝ) := rfl
      exact_mod_cast hc ▸ hu
    obtain ⟨a, ha⟩ := Finset.card_eq_one.mp hcard1
    have hu_mem : u ∈ Finset.univ.filter (fun w : V => P.cells w = P.cells u) := by
      simp
    rw [ha] at hu_mem ⊢
    rw [Finset.mem_singleton] at hu_mem
    rw [hu_mem]
  have hL : (NormedSpace.exp (-(Complex.I * (t : ℂ)) • H) * P.cellInclusion) v (P.cells u)
      = NormedSpace.exp (-(Complex.I * (t : ℂ)) • H) v u := by
    rw [Matrix.mul_apply]
    simp only [EquitablePartition.cellInclusion, Matrix.of_apply, mul_ite, mul_one, mul_zero]
    rw [← Finset.sum_filter, hsingleton, Finset.sum_singleton]
  -- On the right, the inclusion picks out the row `cells v` of the quotient walk.
  have hR : (P.cellInclusion
        * NormedSpace.exp (-(Complex.I * (t : ℂ)) • (Hbar * P.cellSupport))) v (P.cells u)
      = NormedSpace.exp (-(Complex.I * (t : ℂ)) • (Hbar * P.cellSupport))
          (P.cells v) (P.cells u) := by
    rw [Matrix.mul_apply, Finset.sum_eq_single (P.cells v)]
    · rw [EquitablePartition.cellInclusion, Matrix.of_apply, if_pos rfl, one_mul]
    · intro l _ hl
      rw [EquitablePartition.cellInclusion, Matrix.of_apply,
        if_neg (fun hc => hl hc.symm), zero_mul]
    · intro hmem; exact absurd (Finset.mem_univ _) hmem
  rw [hL, hR] at hentry
  rw [← hentry]
  exact ht

/-! ## 8. Open directions

Three concrete next-step directions left **open**:

1. **Optimal-noise-engineering for PST as a quotient optimisation
   problem.**  Reformulate "what Lindblad design maximises mid-time PST
   fidelity at fixed total rate?" as a convex optimisation on the
   *quotient* algebra of `P`, exploiting that the quotient is a small
   matrix (`I × I`) compared to the host (`V × V`).  Concretely: state
   the program

       max_{N : NoiseModel I, rate(N) = γ_total} PST_fidelity (Hhat, N) at time t,

   and observe by `lindbladGen_quotient_reduction` that this is exactly
   the original (host) optimisation restricted to `cellUniformSymmetric`
   noise.  The host-side optimisation is `dim(V)²`-dimensional; the
   quotient-side is `dim(I)²`-dimensional.

2. **Caruso speedup quantification.**  Express the noise-assisted-speedup
   conjecture as a *spectral perturbation* of the quotient Lindblad
   generator with a small symmetry-breaking term; quantify the optimal
   breaking score in terms of the closed-system dark-space spectral gap.

3. **Ghost-symmetry open analogue (Bick & Sclosa, Sec. 6).**  When a
   sequence of asymmetric finite host graphs converges to a graphon with
   non-trivial automorphisms, the *closed-system* dynamics inherit
   "ghosts" of those symmetries.  Conjecture: under cell-uniform-
   symmetric noise the open-system dynamics inherit the *same* ghosts.
   Concretely: extend `EquitablePartition` to graphons (`Graphplay.Graphon`)
   and lift the criterion of §1 to that setting.
-/

/-- **Existence of a zero-breaking cell-uniform-symmetric model.**  The trivial
(no-jump) noise model is cell-uniform-symmetric for every partition `P` and has
breaking score `0`.

HONEST RELABEL (was `quotient_optimisation_lower_bound`): the previous name
advertised an "optimisation lower bound", but the body merely exhibits the
trivial model as a witness of `cellUniformSymmetric ∧ BreakingScore = 0` — no
optimisation problem, objective, or comparison is stated.  This is the
zero-breaking feasibility witness only. -/
theorem exists_zeroBreaking_model
    (P : EquitablePartition G I) :
    ∃ N : NoiseModel V, N.cellUniformSymmetric P ∧ N.BreakingScore P = 0 := by
  refine ⟨NoiseModel.trivial V, ?_, ?_⟩
  · intro L hL; simp [NoiseModel.trivial] at hL
  · simp [NoiseModel.BreakingScore, NoiseModel.trivial]

/-- **The operator breaking score is nonnegative.**  `breakingScoreOp P L` is a
sum of squared norms, hence `≥ 0`.

HONEST RELABEL (was `caruso_leading_order_speedup`): the previous name advertised
a "leading-order speedup", but the body only proves `0 ≤ breakingScoreOp P L` — a
trivial nonnegativity fact about a sum of squares, with no speedup or
leading-order claim. -/
theorem breakingScoreOp_nonneg
    (P : EquitablePartition G I) (L : Matrix V V ℂ) :
    0 ≤ breakingScoreOp P L := by
  unfold breakingScoreOp
  refine Finset.sum_nonneg (fun x _ => Finset.sum_nonneg (fun y _ => ?_))
  split <;> positivity

/-- Sentinel statement for direction (3): the open-system "ghost of symmetry" —
zero breaking score — is exactly the condition that every positive-rate Lindblad
is block-diagonal w.r.t. the partition `P`.

CORRECTNESS FIX: the original conclusion `BreakingScore = 0 ↔ cellUniformSymmetric`
was FALSE (it reused the now-corrected `breakingScore_zero_iff_cellUniformSymmetric`);
we reduce instead to the genuinely-true `breakingScore_zero_iff_blockDiagonal`. -/
theorem ghost_symmetry_open_analogue
    (P : EquitablePartition G I) (N : NoiseModel V) :
    N.BreakingScore P = 0 ↔
      ∀ L ∈ N.lindblad_operators,
        (N.coherence_rates L : ℝ) = 0 ∨
          (∀ x y : V, P.cells x ≠ P.cells y → L x y = 0) :=
  breakingScore_zero_iff_blockDiagonal P N

end NoiseEquitable

end Graphplay
