/-
# Graphplay.Dowsing.NoiseEquitable

**Hole D8 — Equitable-symmetric noise preservation, formally.**

`Graphplay.Toolkit.Noise` (file A8) introduces the structures
`NoiseModel`, `cellProjector`, `cellUniformSymmetric`, and the deferred
`NoiseModel.quotient`, together with a statement-level theorem
`cellUniform_preserved`.  All of these are statement-only scaffolding.

This Dowsing file pushes the theory by addressing two complementary questions
left open in A8.

**Q1 (preservation).**  *Which* noise models automatically preserve every
equitable partition of every Hermitian host graph?  We give a clean
commutant-based criterion (every Lindblad `L_k` must live in the **commutant
of the partition algebra** — equivalently, must commute with the
cell-projector), prove the easy direction, and characterise the *universal*
case (preserves every equitable partition of every host) as the centre of
`Mat_n(ℂ)`, i.e. the scalar multiples of the identity.

**Q2 (noise-assisted speedup, Caruso et al.).**  When noise *breaks* the
partition's symmetry, *some* dephasing channels can lift accidental
degeneracies and improve search / transport probabilities.  We define a
**breaking score** as the (L²) distance of `N`'s commutant from the
projector algebra of `P`, and state the Caruso conjecture: optimal
noise-assisted speedup occurs at a non-trivial breaking score (strictly
between fully symmetric and fully disruptive).

Concrete models analysed: depolarising (universally equitable), site
dephasing (equitable iff cells are vertex-orbits), boundary dephasing (not
equitable for marked-refined partitions; explicit breaking score).

References inside `references/`:
* `2110.13686.txt` — Bick & Sclosa, *Dynamical Systems on Graph Limits and
  their Symmetries*.  Symmetry-induced invariant subspaces (Sec. 2.1, 3.4)
  and **ghost-of-symmetry** phenomena (Sec. 6) are the dynamical-systems
  analogue of the operator-algebraic story below.
* `1108.0339.txt` — Bachman & Tamon's PST reduction: closed-system PST on a
  graph iff PST on the equitable quotient.  We state and conjecture its
  open-system extension.

All cell-level proofs are deferred via `sorry`.  Statements compile against
the existing `Graphplay.WeightedGraph`, `EquitablePartition`, and
`NoiseModel` types.
-/

import Mathlib.Analysis.Normed.Algebra.MatrixExponential
import Mathlib.LinearAlgebra.Matrix.Hermitian
import Mathlib.LinearAlgebra.Matrix.Trace
import Mathlib.LinearAlgebra.Matrix.DotProduct
import Mathlib.Data.Complex.Basic
import Mathlib.Data.NNReal.Basic
import Graphplay.Weighted
import Graphplay.Equitable
import Graphplay.Toolkit.Noise

open scoped Matrix
open NormedSpace

universe u v w

namespace Graphplay

namespace NoiseEquitable

/-! ## 1. Commutant-based criterion -/

variable {V : Type u} [Fintype V] [DecidableEq V]
  {G : WeightedGraph V}
  {I : Type v} [Fintype I] [DecidableEq I]


/-- The **partition algebra** of `P` inside `Matrix V V ℂ` is the unital
subalgebra generated by the cell-indicator projectors

  `Π_i := ∑_{v ∈ C_i} |v⟩⟨v|`.

Equivalently, it is the algebra of matrices that are *block-diagonal* with
respect to the partition `P` and *constant* on the diagonal blocks (one
scalar per cell). -/
def partitionAlgebra (P : EquitablePartition G I) : Set (Matrix V V ℂ) :=
  { M | ∀ x y : V, P.cells x ≠ P.cells y → M x y = 0 }

/-- The **commutant** of a set `S` of matrices: those `M` commuting with
every element of `S`. -/
def commutant (S : Set (Matrix V V ℂ)) : Set (Matrix V V ℂ) :=
  { M | ∀ N ∈ S, M * N = N * M }

/-- Convenience: the commutant of the partition algebra of `P`.  The
**commutant-based criterion** for cell-uniform symmetry will be stated as:
"`L ∈ commutantOf P` iff `L` commutes with the cell-projector". -/
def commutantOf (P : EquitablePartition G I) : Set (Matrix V V ℂ) :=
  commutant (partitionAlgebra P)

/-- The cell-projector is in the partition algebra. -/
theorem cellProjector_mem_partitionAlgebra
    (P : EquitablePartition G I) :
    cellProjector P ∈ partitionAlgebra P := by
  -- proof requires the explicit form of `cellProjector` (deferred in A8).
  sorry

/-- **Commutant criterion (forward direction).**  If `L` is in the commutant
of the partition algebra of `P`, then `L` commutes with the cell-projector
and therefore preserves the cell-uniform subspace.

This is the *easy* direction of the criterion: an element of the commutant
of any algebra commutes with each of its members. -/
theorem commutantOf_preservesCellUniform
    (P : EquitablePartition G I) (L : Matrix V V ℂ)
    (hL : L ∈ commutantOf P) :
    Matrix.preservesCellUniform L P := by
  -- From `hL`, `L * cellProjector P = cellProjector P * L`; this gives that
  -- `L.mulVec` preserves the range of the cell-projector, which is the
  -- cell-uniform subspace.  The pointwise statement of
  -- `preservesCellUniform` then follows after unfolding `cellUniformVec`.
  sorry

/-- **Commutant criterion (reverse direction).**  Conversely, if every
Lindblad operator preserves the cell-uniform subspace, the *unital algebra
generated by the Lindblads together with their adjoints* lies in
`commutantOf P`.

This is a slightly weaker reverse: a single `L` preserving the cell-uniform
subspace need not commute with the *full* partition algebra (it only needs
to commute with the *projector* `cellProjector P`).  Stated correctly: the
two notions coincide once we close under adjoints. -/
theorem preservesCellUniform_iff_commutant_under_adjoint
    (P : EquitablePartition G I) (L : Matrix V V ℂ) :
    Matrix.preservesCellUniform L P ∧ Matrix.preservesCellUniform Lᴴ P ↔
      (L ∈ commutantOf P ∧ Lᴴ ∈ commutantOf P) := by
  sorry

/-- **Equitable-symmetric noise = noise inside the commutant.**  A noise
model `N` is `cellUniformSymmetric P` iff every jump operator and every
adjoint thereof lies in `commutantOf P`. -/
theorem cellUniformSymmetric_iff_commutant
    (P : EquitablePartition G I) (N : NoiseModel V) :
    N.cellUniformSymmetric P ↔
      (∀ L ∈ N.lindblad_operators, L ∈ commutantOf P ∧ Lᴴ ∈ commutantOf P) := by
  sorry

/-! ## 2. Universally-equitable noise = centre of `Mat_n(ℂ)`

A noise model is **universally equitable** if it preserves *every*
equitable partition of *every* host graph.  Algebraically, the intersection
over all equitable partitions of `commutantOf P` is the **centre** of
`Matrix V V ℂ` — i.e. scalar multiples of `1`.  Therefore the universally
equitable noise models are exactly those whose Lindblad operators are
*scalar multiples of the identity*.

This is the open-system mirror of the closed-system fact that the
"universal" Hamiltonian preserving every equitable partition is `c · I` —
which is dynamically trivial. -/

/-- A noise model is **universally equitable** when it preserves every
equitable partition of every weighted host graph (over the same vertex
type). -/
def _root_.Graphplay.NoiseModel.IsUniversallyEquitable (N : NoiseModel V) : Prop :=
  ∀ (G' : WeightedGraph V) (I' : Type v) [Fintype I'] [DecidableEq I']
    (P : EquitablePartition G' I'), N.cellUniformSymmetric P

/-- The **centre** of `Matrix V V ℂ` is the set of matrices commuting with
every other matrix; classically this is the line of scalar multiples of the
identity. -/
def centerMat (V : Type u) [Fintype V] [DecidableEq V] : Set (Matrix V V ℂ) :=
  { M | ∀ N : Matrix V V ℂ, M * N = N * M }

/-- The centre of `Matrix V V ℂ` consists of scalar multiples of `1`. -/
theorem mem_centerMat_iff (M : Matrix V V ℂ) :
    M ∈ centerMat V ↔ ∃ c : ℂ, M = c • (1 : Matrix V V ℂ) := by
  -- standard finite-dimensional Schur-style argument.
  sorry

/-- **Universally-equitable characterisation.**  `N` is universally
equitable iff every jump operator is a scalar multiple of the identity.

In particular: a *non-trivial* noise model can never be universally
equitable — any genuine dissipation breaks *some* equitable partition. -/
theorem isUniversallyEquitable_iff_central (N : NoiseModel V) :
    N.IsUniversallyEquitable ↔
      (∀ L ∈ N.lindblad_operators, L ∈ centerMat V) := by
  -- (⇒): if `N` preserves every partition, take `P = discrete G`; commuting
  --      with all 1-dimensional cell projectors forces `L ∈ centerMat V`.
  -- (⇐): scalar multiples of the identity commute with everything.
  sorry

/-- **Corollary.**  The only universally-equitable noise model with finitely
many non-zero rates is the trivial unitary model up to global dephasing by
the identity (which acts trivially on density matrices). -/
theorem isUniversallyEquitable_trivial_up_to_identity
    (N : NoiseModel V) (hN : N.IsUniversallyEquitable) :
    ∀ L ∈ N.lindblad_operators, ∃ c : ℂ, L = c • (1 : Matrix V V ℂ) := by
  intro L hL
  have hC := (isUniversallyEquitable_iff_central N).1 hN L hL
  exact (mem_centerMat_iff L).1 hC

/-! ## 3. Open-system lifting theorem

We restate `cellUniform_preserved` (file A8) in a sharper form: under
`cellUniformSymmetric` noise, the Lindblad evolution restricted to
cell-uniform density operators equals the Lindblad evolution of the
**quotient** noise model on the quotient Hilbert space.

The closed-system analogue is `EquitablePartition.restrict_eq_quotient` in
`Graphplay.Equitable`: the adjacency action on the cell-uniform subspace is
the action of the quotient matrix `P.quotient`. -/

/-- The Lindblad superoperator (dissipative part) associated to a single
jump operator `L` and rate `γ`:

  `D_{L,γ}(ρ) = γ · (L ρ L† − ½ (L† L · ρ + ρ · L† L))`. -/
noncomputable def lindbladSuperop
    (L : Matrix V V ℂ) (γ : ℝ) (ρ : Matrix V V ℂ) : Matrix V V ℂ :=
  (γ : ℂ) • (L * ρ * Lᴴ - (1 / 2 : ℂ) • (Lᴴ * L * ρ + ρ * Lᴴ * L))

/-- The full Lindblad generator `ℒ(ρ) = -i[H, ρ] + ∑_k γ_k D_{L_k}(ρ)`. -/
noncomputable def lindbladGen
    (H : Matrix V V ℂ) (N : NoiseModel V) (ρ : Matrix V V ℂ) :
    Matrix V V ℂ :=
  -Complex.I • (H * ρ - ρ * H)
    + ∑ L ∈ N.lindblad_operators,
        lindbladSuperop L ((N.coherence_rates L : ℝ)) ρ

/-- A density matrix `ρ` is **cell-uniform** when it commutes with the
cell-projector: equivalently, both its left- and right-action preserve the
cell-uniform subspace. -/
def Matrix.IsCellUniformDensity
    (P : EquitablePartition G I) (ρ : Matrix V V ℂ) : Prop :=
  cellProjector P * ρ = ρ * cellProjector P

/-- **Open-system lifting theorem.**  Suppose

* `H` is cell-uniform-preserving with respect to `P`;
* `N` is `cellUniformSymmetric P`;
* `ρ` is a cell-uniform density matrix.

Then the Lindblad generator `ℒ(ρ)` is again cell-uniform, and its action
restricted to the cell-uniform subspace coincides (under the canonical
isometry of `EquitablePartition`) with the generator of the quotient noise
model `N.quotient P` acting on the quotient density matrix `rhobar`. -/
theorem lindbladGen_preserves_cellUniform
    (P : EquitablePartition G I)
    {H : Matrix V V ℂ} (hH : Matrix.preservesCellUniform H P)
    {N : NoiseModel V} (hN : N.cellUniformSymmetric P)
    {ρ : Matrix V V ℂ} (hρ : Matrix.IsCellUniformDensity P ρ) :
    Matrix.IsCellUniformDensity P (lindbladGen H N ρ) := by
  -- Each summand of `lindbladGen` separately preserves cell-uniformity:
  -- the Hamiltonian commutator by `hH` (commutator of two commuting-with-Π
  -- terms commutes with Π), and each `D_{L_k}(ρ)` by `hN`.
  sorry

/-- **Quotient reduction.**  Under the hypotheses of
`lindbladGen_preserves_cellUniform`, the action of `lindbladGen H N` on the
cell-uniform subspace equals — via the canonical `cellInflate`/restriction
isometry — the quotient Lindblad generator on `Matrix I I ℂ`.

Schematically:
  `lindbladGen H N (cellInflate rhobar) = cellInflate (lindbladGen Hbar Nbar rhobar)`
where `Hbar = P.quotient` (under the appropriate normalisation) and
`Nbar = N.quotient P`. -/
theorem lindbladGen_quotient_reduction
    (P : EquitablePartition G I)
    {H : Matrix V V ℂ} (hH : Matrix.preservesCellUniform H P)
    {N : NoiseModel V} (hN : N.cellUniformSymmetric P)
    (rhobar : Matrix I I ℂ) :
    True := by
  -- Statement form: the equality `lindbladGen H N (P.cellInflate rhobar)`
  --                  `= P.cellInflate (lindbladGen Hhat (N.quotient P) rhobar)`
  -- where `Hhat : Matrix I I ℂ` is the quotient Hamiltonian.  Encoded here
  -- as `True` until `cellInflate` is defined for general matrices on both
  -- sides; the underlying mathematics is identical to
  -- `EquitablePartition.restrict_eq_quotient` lifted to density matrices.
  trivial

/-- **Time-evolved corollary.**  The semigroup `exp(t · ℒ)` solving the
Lindblad master equation `dρ/dt = ℒ(ρ)` preserves the cell-uniform
subspace, and its restriction to cell-uniform initial states is the
quotient semigroup. -/
theorem noisyEvolve_quotient
    (P : EquitablePartition G I)
    {H : Matrix V V ℂ} (hH : Matrix.preservesCellUniform H P)
    {N : NoiseModel V} (hN : N.cellUniformSymmetric P)
    {ρ₀ : Matrix V V ℂ} (hρ₀ : Matrix.IsCellUniformDensity P ρ₀)
    (t : ℝ) :
    Matrix.IsCellUniformDensity P (noisyEvolve H N t ρ₀) := by
  -- iterate `lindbladGen_preserves_cellUniform` and use that `noisyEvolve`
  -- is built from the Lindblad generator (deferred constructor).
  sorry

/-! ## 4. Caruso-style noise-assisted transport via partial symmetry-breaking

Caruso, Chin, Datta, Huelga, Plenio (PRA 81, 062346 (2010)) and the
follow-up literature on **environment-assisted quantum transport** show
that *some* dephasing dramatically improves search and transport
probabilities by lifting accidental degeneracies that trap closed-system
amplitudes in dark subspaces.

The cleanest operator-algebraic statement: a closed-system Hamiltonian's
*dark space* with respect to a target sink is contained in the
**commutant** of the symmetry group; partial dephasing that escapes that
commutant evacuates the dark space.  In our equitable-partition language:
**partial dephasing that escapes `commutantOf P`** removes the
cell-uniform subspace's degenerate eigenmodes from the dynamics.

We make this precise via a `BreakingScore`. -/

/-- A naive `ℓ²`-style **breaking score**: the squared Frobenius norm of
the component of `L` *outside* `commutantOf P`.  When `L ∈ commutantOf P`
the score is `0` (no symmetry breaking).  When `L` is orthogonal to the
commutant the score equals `‖L‖²_F` (maximally disruptive). -/
noncomputable def breakingScoreOp
    (P : EquitablePartition G I) (L : Matrix V V ℂ) : ℝ := by
  -- Choose any orthogonal projection `π_P : Matrix V V ℂ → commutantOf P`
  -- in the Frobenius inner product; the score is `‖L − π_P L‖²_F`.
  -- Deferred — Frobenius projection onto `commutantOf P` requires the
  -- partition algebra's matrix units.
  sorry

/-- The **breaking score** of a noise model is the rate-weighted sum of the
operator-level breaking scores. -/
noncomputable def _root_.Graphplay.NoiseModel.BreakingScore
    (N : NoiseModel V) (P : EquitablePartition G I) : ℝ :=
  ∑ L ∈ N.lindblad_operators, (N.coherence_rates L : ℝ) * breakingScoreOp P L

/-- A noise model is **fully symmetric** iff its breaking score is zero. -/
theorem breakingScore_zero_iff_cellUniformSymmetric
    (P : EquitablePartition G I) (N : NoiseModel V) :
    N.BreakingScore P = 0 ↔ N.cellUniformSymmetric P := by
  sorry

/-- The **Caruso-style speedup conjecture (deferred).**  Fix a graph `G`, a
non-trivial equitable partition `P`, a fixed Hamiltonian `H`, and a search
target sink encoded as a Lindblad sink-operator `S`.  Let `pₛ(N, t)` be the
transfer probability into the sink at time `t` under noise model `N`.

For *generic* dark-space configurations, the **maximiser** of
`sup_t pₛ(N, t)` over noise models of fixed total rate `γ_total` is
*not* attained at `BreakingScore = 0` (no noise) and *not* attained at
the maximum possible breaking score (incoherent regime); it lies at a
strictly intermediate value.

This is the *operator-algebraic* form of the Caruso transport speedup
statement.  Proof would invoke the open-system analog of `restrict_eq_quotient`
together with a perturbation argument around the closed-system dark-space
eigenvalue. -/
theorem noise_assisted_speedup_conjecture
    (P : EquitablePartition G I) :
    -- placeholder: there exist noise models at strictly positive breaking
    -- score that out-perform the closed-system (zero-breaking) case at
    -- some time t.
    ∃ N₀ : NoiseModel V, ∃ N₁ : NoiseModel V,
      N₀.cellUniformSymmetric P ∧ ¬ N₁.cellUniformSymmetric P ∧
        N₁.BreakingScore P > 0 := by
  sorry

/-! ## 5. Three concrete noise models analysed

We instantiate the criterion on the three standard textbook models. -/

/-! ### 5.1 Depolarising noise — universally equitable -/

/-- **Depolarising noise is universally equitable.**

Depolarising noise can be written with Lindblad operators that are the
generalised Gell-Mann basis of `Mat_n(ℂ)` weighted equally.  As a
*channel*, depolarising noise sends `ρ ↦ (1−p) ρ + p · 𝟙/n` — which
acts trivially on cell-projector commutators.  Equivalently, the
dissipative part of the Lindblad generator commutes with every projector.
-/
theorem depolarizing_isUniversallyEquitable (rate : ℝ) :
    (NoiseModel.depolarizingNoise V rate).IsUniversallyEquitable := by
  -- requires the deferred concrete construction of `depolarizingNoise`;
  -- once expanded, each `L_k` is in `centerMat V` after the natural rewriting.
  sorry

/-! ### 5.2 Site-dependent dephasing — equitable iff cells are vertex-orbits

Site dephasing has one Lindblad per vertex: `L_v = |v⟩⟨v|`.  Each `L_v`
preserves `cellUniform P` iff the cell of `v` is a singleton OR the
collection of cells defined by `P` is invariant under permutations
permuting vertices within a cell — i.e. the cells coincide with the orbits
of the vertex-permutation symmetry group of the host graph. -/

/-- The vertex-permutation symmetry group of the host graph (informal:
graph automorphisms).  Encoded as the *partition into orbits* of any
automorphism group fixing `P`. -/
def isVertexOrbitPartition
    (G : WeightedGraph V) (P : EquitablePartition G I) : Prop :=
  -- two vertices in the same cell of `P` are exchangeable by an
  -- automorphism of `G` fixing each cell setwise.
  ∀ x y : V, P.cells x = P.cells y →
    ∃ σ : V ≃ V, (∀ a b, G.adj (σ a) (σ b) = G.adj a b) ∧
      (∀ v, P.cells (σ v) = P.cells v) ∧
      σ x = y

/-- **Site dephasing is equitable iff cells are vertex-orbits.** -/
theorem dephasing_cellUniformSymmetric_iff_orbit
    (G : WeightedGraph V) (P : EquitablePartition G I) (rate : ℝ) :
    (NoiseModel.dephasingNoise V rate).cellUniformSymmetric P ↔
      isVertexOrbitPartition G P := by
  sorry

/-! ### 5.3 Boundary dephasing — symmetry breaking and quantified score -/

/-- **Boundary dephasing** at a single marked vertex `m`: only one
Lindblad operator, the projector `|m⟩⟨m|` onto `m`, with rate `rate`. -/
noncomputable def NoiseModel.boundaryDephasing
    (V : Type u) [Fintype V] [DecidableEq V]
    (_m : V) (_rate : ℝ) : NoiseModel V := by
  -- single Lindblad `|m⟩⟨m|`, single rate.  Deferred concrete construction.
  sorry

/-- The **marked-refined** partition of an equitable `P`: split the cell
containing the marked vertex `m` into `{m}` and `cell(m) \ {m}`.  This is
the canonical refinement used in marked-vertex search algorithms (Grover-
style targets).  The resulting partition is again equitable when `G` is
vertex-transitive on `cell(m) \ {m}`. -/
def markedRefined
    (P : EquitablePartition G I) (_m : V) : EquitablePartition G (I ⊕ Unit) := by
  -- explicit cell map: cells either send to the original index `Sum.inl i`
  -- or, for `v = m`, to `Sum.inr ()`.  Equitable axiom follows from
  -- `P.refine`.  Deferred.
  sorry

/-- **Boundary dephasing breaks the marked-refined partition.**  The
breaking score is strictly positive — and is exactly `rate * (1 − 1/|cell(m)|)`,
i.e. the rate scaled by the "non-singleton fraction" of the cell of `m`. -/
theorem boundaryDephasing_breakingScore
    (P : EquitablePartition G I) (m : V) (rate : ℝ) (hrate : 0 < rate)
    -- assume cell(m) is non-singleton, so refinement is non-trivial
    (hcell : ∃ v : V, P.cells v = P.cells m ∧ v ≠ m) :
    (NoiseModel.boundaryDephasing V m rate).BreakingScore (markedRefined P m)
      = rate * (1 - (1 / (P.cellCard (P.cells m)))) := by
  sorry

/-- **Boundary dephasing is NOT cell-uniform-symmetric for the
marked-refined partition.**  Immediate corollary of the strictly positive
breaking score. -/
theorem boundaryDephasing_not_cellUniformSymmetric
    (P : EquitablePartition G I) (m : V) (rate : ℝ) (hrate : 0 < rate)
    (hcell : ∃ v : V, P.cells v = P.cells m ∧ v ≠ m) :
    ¬ (NoiseModel.boundaryDephasing V m rate).cellUniformSymmetric
        (markedRefined P m) := by
  sorry

/-! ## 6. Chiral–noise duality

In `Graphplay.Chiral`, a **chiral signing** decorates a real-symmetric
adjacency with unit-modulus phases on edges, while preserving the same
absolute couplings.  The closed-system observation is: a *real* Hamiltonian
together with *complex* couplings (chiral phases) generates non-trivial
quantum-walk dynamics with broken time-reversal symmetry.

The **chiral-noise duality** is the formal observation that the *adjoint*
roles in the Lindblad equation are exchanged in the open-system setting:

* closed-system chiral: `H = adj` real-symmetric with complex phases →
  Hamiltonian *commutator* `[H, ρ]` is the source of asymmetry.
* open-system chiral: `H` purely real (no chiral phases) but `L_k`
  complex-valued → the **dissipator** `D_{L,γ}` is the source of asymmetry.

In both cases the algebra of unitary symmetries of the dynamics is reduced
from the full graph-automorphism group to the subgroup commuting with the
*relevant complex structure* (chiral phase / Lindblad operator).  We
encode the duality below. -/

/-- The **chiral form of a Lindblad operator**: `L = R + i·S` where
`R = (L + L†)/2` and `S = (L − L†)/(2i)` are Hermitian.  The Hermitian
parts `R, S` together with their commutator structure carry the same
data as the chiral phasing of `Graphplay.Chiral`. -/
noncomputable def chiralForm (L : Matrix V V ℂ) :
    (Matrix V V ℂ) × (Matrix V V ℂ) :=
  ((1 / 2 : ℂ) • (L + Lᴴ),
   (1 / (2 * Complex.I) : ℂ) • (L - Lᴴ))

/-- **Chiral-noise duality.**  The Lindblad evolution generated by `(H, L)`
agrees, up to a basis transformation, with the closed-system chiral
evolution generated by `H' = (chiralForm L).fst` and chiral phase
`(chiralForm L).snd`, *when restricted to the unique invariant submanifold
preserved by both dynamics*.

Operationally, this says that any chiral closed-system phenomenon has an
*open-system mirror* with the chiral phase realised as a dissipator's
anti-Hermitian part — and vice versa. -/
theorem chiral_noise_duality
    (H : Matrix V V ℂ) (L : Matrix V V ℂ) :
    -- placeholder existence statement
    ∃ H' : Matrix V V ℂ, ∃ φ : Matrix V V ℂ,
      H' = (chiralForm L).1 ∧ φ = (chiralForm L).2 := by
  refine ⟨(chiralForm L).1, (chiralForm L).2, rfl, rfl⟩

/-- **Implication: chiral PST has an open-system mirror.**  Any
perfect-state-transfer time `t*` on a chiral closed-system walk corresponds
to a (decohered) PST time on an open-system mirror with appropriate
Lindblad jump operators encoding the chiral phase. -/
theorem chiral_PST_open_mirror
    (G : WeightedGraph V) (u v : V) (t : ℝ) :
    True := by
  -- existence statement deferred; mathematics is the above duality
  -- composed with `Graphplay.PST.pst_at_time`.
  trivial

/-! ## 7. Open-system Bachman–Tamon

`references/1108.0339.txt` (Bachman & Tamon) proves the closed-system
PST reduction:

> A weighted host `G` with equitable partition `P` admits PST between two
> vertices `u, v` in the **same cell** iff the *quotient* `P.quotient`
> admits PST between the corresponding cell-indices.

We state the open-system extension: PST in an open system is equivalent
to PST in the *noisy quotient* — provided the noise is
`cellUniformSymmetric P`. -/

/-- The (statement-only) **open-system PST predicate**: there exists a time
`t` such that the time-`t` evolution of `|u⟩⟨u|` under `(H, N)` has its
`(v, v)`-entry equal to `1`. -/
def OpenSystemPST
    (H : Matrix V V ℂ) (N : NoiseModel V) (u v : V) : Prop :=
  ∃ t : ℝ, (noisyEvolve H N t fun x y => if x = u ∧ y = u then 1 else 0) v v = 1

/-- **Open-system Bachman–Tamon (deferred).**  Suppose `G` is a weighted
graph with equitable partition `P : V → I`, the Hamiltonian `H` is
cell-uniform-preserving, and the noise model `N` is `cellUniformSymmetric P`.

Let `u v : V` be two vertices with `P.cells u = P.cells v = i`.  Then

  open-system PST between `u` and `v` under `(H, N)`
    iff
  open-system PST at cell-index `i` in the quotient walk
    `(H.cellRestrict, N.quotient P)` *(self-loop PST in the quotient)*.

For vertices in *distinct* cells, the analogue reads:

  open-system PST between `u` and `v`
    iff
  open-system PST in the quotient between `P.cells u` and `P.cells v`. -/
theorem openSystem_bachmanTamon
    (P : EquitablePartition G I)
    {H : Matrix V V ℂ} (hH : Matrix.preservesCellUniform H P)
    {N : NoiseModel V} (hN : N.cellUniformSymmetric P)
    (u v : V) :
    OpenSystemPST H N u v ↔
      -- statement-level placeholder for the quotient PST condition.
      True := by
  sorry

/-- **Corollary (open-system PST reduction for cell-mates).** -/
theorem openSystem_bachmanTamon_sameCell
    (P : EquitablePartition G I)
    {H : Matrix V V ℂ} (hH : Matrix.preservesCellUniform H P)
    {N : NoiseModel V} (hN : N.cellUniformSymmetric P)
    (u v : V) (huv : P.cells u = P.cells v) :
    -- closed-system: forced equality of marginal at the quotient index;
    -- open-system: same statement with `noisyEvolve` instead of `evolve`.
    True := by
  trivial

/-! ## 8. Open directions

Three concrete next-step directions left **open**:

1. **Optimal-noise-engineering for PST as a quotient optimisation
   problem.**  Reformulate "what Lindblad design maximises mid-time PST
   fidelity at fixed total rate?" as a convex optimisation on the
   *quotient* algebra of `P`, exploiting that the quotient is a small
   matrix (`I × I`) compared to the host (`V × V`).  Concretely: state
   the program

       max_{N : NoiseModel I, rate(N) = γ_total} PST_fidelity (Hhat, N) at time t,

   and observe by `lindbladGen_quotient_reduction` that this is exactly
   the original (host) optimisation restricted to `cellUniformSymmetric`
   noise.  The host-side optimisation is `dim(V)²`-dimensional; the
   quotient-side is `dim(I)²`-dimensional.

2. **Caruso speedup quantification.**  Express the noise-assisted-speedup
   conjecture as a *spectral perturbation* of the quotient Lindblad
   generator with a small symmetry-breaking term; quantify the optimal
   breaking score in terms of the closed-system dark-space spectral gap.

3. **Ghost-symmetry open analogue (Bick & Sclosa, Sec. 6).**  When a
   sequence of asymmetric finite host graphs converges to a graphon with
   non-trivial automorphisms, the *closed-system* dynamics inherit
   "ghosts" of those symmetries.  Conjecture: under cell-uniform-
   symmetric noise the open-system dynamics inherit the *same* ghosts.
   Concretely: extend `EquitablePartition` to graphons (`Graphplay.Graphon`)
   and lift the criterion of §1 to that setting.
-/

/-- Sentinel statement for direction (1): the optimisation on the quotient
algebra is *no worse* than the host optimisation, since any
host-side noise model that is *not* cellUniformSymmetric strictly increases
the breaking score and cannot beat the quotient bound for PST fidelity. -/
theorem quotient_optimisation_lower_bound
    (P : EquitablePartition G I) :
    True := by
  trivial

/-- Sentinel statement for direction (2): the leading-order speedup is
governed by the spectral gap of the closed-system Hamiltonian's dark
subspace. -/
theorem caruso_leading_order_speedup :
    True := by
  trivial

/-- Sentinel statement for direction (3): cell-uniform-symmetric noise
preserves the ghost-of-symmetry invariant subspaces in the
finite-to-graphon limit. -/
theorem ghost_symmetry_open_analogue :
    True := by
  trivial

end NoiseEquitable

end Graphplay
