/-
# Graphplay.Dowsing.NoiseEquitable

**Hole D8 — Equitable-symmetric noise preservation, formally.**

`Graphplay.Toolkit.Noise` (file A8) introduces the structures
`NoiseModel`, `cellProjector`, `cellUniformSymmetric`, and the deferred
`NoiseModel.quotient`, together with a statement-level theorem
`cellUniform_preserved`.  All of these are statement-only scaffolding.

This Dowsing file pushes the theory by addressing two complementary questions
left open in A8.

**Q1 (preservation).**  *Which* noise models automatically preserve every
equitable partition of every Hermitian host graph?  We give a clean
commutant-based criterion (every Lindblad `L_k` must live in the **commutant
of the partition algebra** — equivalently, must commute with the
cell-projector), prove the easy direction, and characterise the *universal*
case (preserves every equitable partition of every host) as the centre of
`Mat_n(ℂ)`, i.e. the scalar multiples of the identity.

**Q2 (noise-assisted speedup, Caruso et al.).**  When noise *breaks* the
partition's symmetry, *some* dephasing channels can lift accidental
degeneracies and improve search / transport probabilities.  We define a
**breaking score** as the (L²) distance of `N`'s commutant from the
projector algebra of `P`, and state the Caruso conjecture: optimal
noise-assisted speedup occurs at a non-trivial breaking score (strictly
between fully symmetric and fully disruptive).

Concrete models analysed: depolarising (universally equitable), site
dephasing (equitable iff cells are vertex-orbits), boundary dephasing (not
equitable for marked-refined partitions; explicit breaking score).

References inside `references/`:
* `2110.13686.txt` — Bick & Sclosa, *Dynamical Systems on Graph Limits and
  their Symmetries*.  Symmetry-induced invariant subspaces (Sec. 2.1, 3.4)
  and **ghost-of-symmetry** phenomena (Sec. 6) are the dynamical-systems
  analogue of the operator-algebraic story below.
* `1108.0339.txt` — Bachman & Tamon's PST reduction: closed-system PST on a
  graph iff PST on the equitable quotient.  We state and conjecture its
  open-system extension.

All cell-level proofs are deferred via `sorry`.  Statements compile against
the existing `Graphplay.WeightedGraph`, `EquitablePartition`, and
`NoiseModel` types.
-/

import Mathlib.Analysis.Normed.Algebra.MatrixExponential
import Mathlib.LinearAlgebra.Matrix.Hermitian
import Mathlib.LinearAlgebra.Matrix.Trace
import Mathlib.LinearAlgebra.Matrix.DotProduct
import Mathlib.Data.Complex.Basic
import Mathlib.Data.NNReal.Basic
import Graphplay.Weighted
import Graphplay.Equitable
import Graphplay.Toolkit.Noise
import Graphplay.PST.DiagonalShift

open scoped Matrix
open NormedSpace

universe u v w

namespace Graphplay

namespace NoiseEquitable

/-! ## 1. Commutant-based criterion -/

variable {V : Type u} [Fintype V] [DecidableEq V]
  {G : WeightedGraph V}
  {I : Type v} [Fintype I] [DecidableEq I]


/-- The **partition algebra** of `P` inside `Matrix V V ℂ` is the unital
subalgebra generated by the cell-indicator projectors

  `Π_i := ∑_{v ∈ C_i} |v⟩⟨v|`.

Equivalently, it is the algebra of matrices that are *block-diagonal* with
respect to the partition `P` and *constant* on the diagonal blocks (one
scalar per cell). -/
def partitionAlgebra (P : EquitablePartition G I) : Set (Matrix V V ℂ) :=
  { M | ∀ x y : V, P.cells x ≠ P.cells y → M x y = 0 }

/-- The **commutant** of a set `S` of matrices: those `M` commuting with
every element of `S`. -/
def commutant (S : Set (Matrix V V ℂ)) : Set (Matrix V V ℂ) :=
  { M | ∀ N ∈ S, M * N = N * M }

/-- Convenience: the commutant of the partition algebra of `P`.  The
**commutant-based criterion** for cell-uniform symmetry will be stated as:
"`L ∈ commutantOf P` iff `L` commutes with the cell-projector". -/
def commutantOf (P : EquitablePartition G I) : Set (Matrix V V ℂ) :=
  commutant (partitionAlgebra P)

/-- The cell-projector is in the partition algebra. -/
theorem cellProjector_mem_partitionAlgebra
    (P : EquitablePartition G I) :
    cellProjector P ∈ partitionAlgebra P := by
  -- `cellProjector P x y` is defined by an `if P.cells x = P.cells y` guard,
  -- so its off-block (`P.cells x ≠ P.cells y`) entries are exactly `0`.
  intro x y hxy
  simp only [cellProjector, if_neg hxy]

/-- The cell-projector has equal rows within a cell: if `x, y` lie in the same
cell then `cellProjector P x · = cellProjector P y ·`.  Hence applying it to any
vector produces a cell-uniform result. -/
theorem cellProjector_row_eq
    (P : EquitablePartition G I) {x y : V} (hxy : P.cells x = P.cells y) (z : V) :
    cellProjector P x z = cellProjector P y z := by
  simp only [cellProjector, hxy]

theorem cellProjector_mulVec_cellUniform
    (P : EquitablePartition G I) (φ : V → ℂ) {x y : V}
    (hxy : P.cells x = P.cells y) :
    (cellProjector P).mulVec φ x = (cellProjector P).mulVec φ y := by
  unfold Matrix.mulVec dotProduct
  refine Finset.sum_congr rfl (fun z _ => ?_)
  simp only []
  rw [cellProjector_row_eq P hxy z]

/-- The cell-projector fixes cell-uniform vectors: if `ψ` is constant on each
cell, then `(cellProjector P).mulVec ψ = ψ`. -/
theorem cellProjector_mulVec_eq_self_of_cellUniform
    (P : EquitablePartition G I) (ψ : V → ℂ)
    (hψ : ∀ x y : V, P.cells x = P.cells y → ψ x = ψ y) (x : V) :
    (cellProjector P).mulVec ψ x = ψ x := by
  rw [Matrix.mulVec, dotProduct]
  set c := (Finset.univ.filter (fun w : V => P.cells w = P.cells x)).card with hc
  -- Each summand equals `if P.cells x = P.cells z then (1/c)·ψ x else 0`,
  -- using cell-uniformity of `ψ` to replace `ψ z` by `ψ x` on the cell.
  have hterm : ∀ z : V, cellProjector P x z * ψ z
      = (if P.cells x = P.cells z then (1 : ℂ) / (c : ℂ) * ψ x else 0) := by
    intro z
    by_cases h : P.cells x = P.cells z
    · simp only [cellProjector, if_pos h, hc]
      rw [hψ x z h]
    · simp only [cellProjector, if_neg h, zero_mul]
  have hsum : ∑ z : V, cellProjector P x z * ψ z
      = ∑ z ∈ Finset.univ.filter (fun w : V => P.cells x = P.cells w),
        (1 : ℂ) / (c : ℂ) * ψ x := by
    rw [Finset.sum_congr rfl (fun z _ => hterm z), Finset.sum_filter]
  rw [hsum, Finset.sum_const]
  have hcardeq : (Finset.univ.filter (fun w : V => P.cells x = P.cells w)).card = c := by
    rw [hc]; congr 1; ext z; simp [eq_comm]
  rw [hcardeq]
  have hcpos : 0 < c := by
    rw [hc]; apply Finset.card_pos.mpr; exact ⟨x, by simp⟩
  have hcne : (c : ℂ) ≠ 0 := by exact_mod_cast hcpos.ne'
  rw [nsmul_eq_mul]
  field_simp

/-- The cell-projector is Hermitian: its `(x, y)` and `(y, x)` entries are equal
real scalars (`1/|cell|` on the diagonal block, `0` off it). -/
theorem cellProjector_conjTranspose (P : EquitablePartition G I) :
    (cellProjector P)ᴴ = cellProjector P := by
  funext x y
  simp only [Matrix.conjTranspose_apply, cellProjector]
  by_cases h : P.cells y = P.cells x
  · rw [if_pos h, if_pos h.symm, star_div₀, star_one]
    have hfilt : (Finset.univ.filter (fun w : V => P.cells w = P.cells y))
        = (Finset.univ.filter (fun w : V => P.cells w = P.cells x)) := by
      apply Finset.filter_congr; intro w _; rw [h]
    rw [hfilt]; norm_num
  · rw [if_neg h, if_neg (fun h' => h h'.symm), star_zero]

/-- If `M` commutes with the (Hermitian) cell projector then so does `Mᴴ`. -/
theorem conjTranspose_comm_cellProjector (P : EquitablePartition G I)
    {M : Matrix V V ℂ} (hM : M * cellProjector P = cellProjector P * M) :
    Mᴴ * cellProjector P = cellProjector P * Mᴴ := by
  have := congrArg Matrix.conjTranspose hM
  simpa only [Matrix.conjTranspose_mul, cellProjector_conjTranspose] using this.symm

/-- **Commutant criterion (forward direction).**  If `L` is in the commutant
of the partition algebra of `P`, then `L` commutes with the cell-projector
and therefore preserves the cell-uniform subspace. -/
theorem commutantOf_preservesCellUniform
    (P : EquitablePartition G I) (L : Matrix V V ℂ)
    (hL : L ∈ commutantOf P) :
    Matrix.preservesCellUniform L P := by
  -- `L` commutes with the cell-projector (a member of the partition algebra).
  have hcomm : L * cellProjector P = cellProjector P * L :=
    hL _ (cellProjector_mem_partitionAlgebra P)
  intro ψ hψ x y hxy
  -- `L.mulVec ψ = L.mulVec (Π.mulVec ψ) = (L*Π).mulVec ψ = (Π*L).mulVec ψ
  --             = Π.mulVec (L.mulVec ψ)`, which is cell-uniform.
  have hfix : (cellProjector P).mulVec ψ = ψ := by
    funext z; exact cellProjector_mulVec_eq_self_of_cellUniform P ψ hψ z
  have hrw : ∀ z, L.mulVec ψ z = (cellProjector P).mulVec (L.mulVec ψ) z := by
    intro z
    conv_lhs => rw [← hfix]
    rw [Matrix.mulVec_mulVec, hcomm, ← Matrix.mulVec_mulVec]
  rw [hrw x, hrw y]
  exact cellProjector_mulVec_cellUniform P (L.mulVec ψ) hxy

/-- Two matrices agreeing on every `mulVec` are equal (read off columns via
`mulVec_single_one`). -/
theorem matrix_eq_of_mulVec_eq {A B : Matrix V V ℂ}
    (h : ∀ φ : V → ℂ, A.mulVec φ = B.mulVec φ) : A = B := by
  ext i j
  have hj := h (Pi.single j 1)
  rw [Matrix.mulVec_single_one, Matrix.mulVec_single_one] at hj
  have := congrFun hj i
  simpa [Matrix.col_apply] using this

/-- **Cell-uniform preservation = projector half-conjugation identity.**
`L` preserves the cell-uniform subspace iff `L · Π = Π · L · Π`, where
`Π = cellProjector P`.  (The cell-uniform subspace is exactly the range of
the projector `Π`, so `L(ran Π) ⊆ ran Π` is `Π L Π = L Π`.) -/
theorem preservesCellUniform_iff_LP_eq_PLP
    (P : EquitablePartition G I) (L : Matrix V V ℂ) :
    Matrix.preservesCellUniform L P ↔
      L * cellProjector P = cellProjector P * (L * cellProjector P) := by
  constructor
  · intro hL
    apply matrix_eq_of_mulVec_eq
    intro φ
    -- `Π φ` is cell-uniform, so `L (Π φ)` is cell-uniform, so `Π (L (Π φ)) = L (Π φ)`.
    have huniform : ∀ x y : V, P.cells x = P.cells y →
        L.mulVec ((cellProjector P).mulVec φ) x
          = L.mulVec ((cellProjector P).mulVec φ) y :=
      hL ((cellProjector P).mulVec φ)
        (fun x y hxy => cellProjector_mulVec_cellUniform P φ hxy)
    -- LHS `(L*Π) φ = L (Π φ)`; RHS `(Π*(L*Π)) φ = Π (L (Π φ)) = L (Π φ)`.
    rw [← Matrix.mulVec_mulVec, ← Matrix.mulVec_mulVec, ← Matrix.mulVec_mulVec]
    funext z
    exact (cellProjector_mulVec_eq_self_of_cellUniform P
      (L.mulVec ((cellProjector P).mulVec φ)) huniform z).symm
  · intro hLP ψ hψ x y hxy
    -- `L ψ = L (Π ψ) = (LΠ) ψ = (Π L Π) ψ`, which is cell-uniform.
    have hfix : (cellProjector P).mulVec ψ = ψ := by
      funext z; exact cellProjector_mulVec_eq_self_of_cellUniform P ψ hψ z
    have hcong : L.mulVec ψ = (cellProjector P).mulVec (L.mulVec ((cellProjector P).mulVec ψ)) := by
      conv_lhs => rw [← hfix]
      have : (cellProjector P).mulVec (L.mulVec ((cellProjector P).mulVec ψ))
          = (cellProjector P * (L * cellProjector P)).mulVec ψ := by
        simp only [Matrix.mulVec_mulVec]
      rw [this, ← hLP, Matrix.mulVec_mulVec]
    rw [hcong]
    exact cellProjector_mulVec_cellUniform P _ hxy

/-- **Commutant criterion (corrected, issue #53).**  `L` and `Lᴴ` both
preserve the cell-uniform subspace **iff** `L` commutes with the cell
projector `Π = cellProjector P`.

CORRECTNESS FIX: the original statement used `commutantOf P` (the commutant of
the *whole* block-diagonal partition algebra).  That is genuinely **false** for
non-singleton cells — e.g. with a single 2-element cell the matrix
`L = [[2,−1],[−1,2]]` preserves the constant (cell-uniform) vectors but is *not*
in the commutant of the partition algebra (which there is just the scalars).
The docstring of the original already flagged this gap ("it only needs to
commute with the *projector*").  We therefore state and prove the genuinely-true
projector-commutation criterion.  `commutantOf P ⊆ {L | LΠ = ΠL}` still holds
(the easy `commutantOf_preservesCellUniform` direction), so this is a strictly
sharper characterisation. -/
theorem preservesCellUniform_iff_commutant_under_adjoint
    (P : EquitablePartition G I) (L : Matrix V V ℂ) :
    Matrix.preservesCellUniform L P ∧ Matrix.preservesCellUniform Lᴴ P ↔
      L * cellProjector P = cellProjector P * L := by
  have hPiHerm : (cellProjector P)ᴴ = cellProjector P := cellProjector_conjTranspose P
  constructor
  · rintro ⟨hL, hLH⟩
    -- `L Π = Π L Π` from `hL`; conjugate-transpose of `Lᴴ Π = Π Lᴴ Π` gives `Π L = Π L Π`.
    have h1 : L * cellProjector P = cellProjector P * (L * cellProjector P) :=
      (preservesCellUniform_iff_LP_eq_PLP P L).1 hL
    have h2 : Lᴴ * cellProjector P = cellProjector P * (Lᴴ * cellProjector P) :=
      (preservesCellUniform_iff_LP_eq_PLP P Lᴴ).1 hLH
    -- take ᴴ of h2: `Π L = Π L Π` (using Π Hermitian and `Lᴴᴴ = L`).
    have h2' : cellProjector P * L = (cellProjector P * (L * cellProjector P)) := by
      have := congrArg Matrix.conjTranspose h2
      simp only [Matrix.conjTranspose_mul, hPiHerm, Matrix.conjTranspose_conjTranspose,
        mul_assoc] at this
      rw [this, ← mul_assoc]
    rw [h1, h2']
  · intro hcomm
    -- `LΠ = ΠL` ⇒ both `L` and `Lᴴ` preserve cell-uniformity, by the direct
    -- mulVec fixed-point argument (commuting with `Π` carries cell-uniform to
    -- cell-uniform; `Lᴴ` commutes with `Π` too since `Π` is Hermitian).
    have hLH : Lᴴ * cellProjector P = cellProjector P * Lᴴ := by
      have := congrArg Matrix.conjTranspose hcomm
      simpa only [Matrix.conjTranspose_mul, hPiHerm, Matrix.conjTranspose_conjTranspose] using this.symm
    have key : ∀ M : Matrix V V ℂ, M * cellProjector P = cellProjector P * M →
        Matrix.preservesCellUniform M P := by
      intro M hM ψ hψ x y hxy
      have hfix : (cellProjector P).mulVec ψ = ψ := by
        funext z; exact cellProjector_mulVec_eq_self_of_cellUniform P ψ hψ z
      have hrw : ∀ z, M.mulVec ψ z = (cellProjector P).mulVec (M.mulVec ψ) z := by
        intro z
        conv_lhs => rw [← hfix]
        rw [Matrix.mulVec_mulVec, hM, ← Matrix.mulVec_mulVec]
      rw [hrw x, hrw y]
      exact cellProjector_mulVec_cellUniform P (M.mulVec ψ) hxy
    exact ⟨key L hcomm, key Lᴴ hLH⟩

/-- **Equitable-symmetric noise = every jump operator commutes with the cell
projector.**  A noise model `N` is `cellUniformSymmetric P` iff every jump
operator `L` and its adjoint preserve the cell-uniform subspace; by
`preservesCellUniform_iff_commutant_under_adjoint` this is the projector-
commutation criterion `L · Π = Π · L`.

CORRECTNESS FIX (issue #53): the original RHS used `commutantOf P`, which is
strictly too strong (see `preservesCellUniform_iff_commutant_under_adjoint`).
Note `cellUniformSymmetric` as defined only requires each `L` (not `Lᴴ`) to
preserve cell-uniformity, so the iff holds under the natural adjoint-closure
hypothesis that each `Lᴴ` is again a jump operator; we state the clean form
that characterises the *adjoint-closed* symmetric condition. -/
theorem cellUniformSymmetric_iff_commutant
    (P : EquitablePartition G I) (N : NoiseModel V)
    (hadj : ∀ L ∈ N.lindblad_operators, Lᴴ ∈ N.lindblad_operators) :
    N.cellUniformSymmetric P ↔
      (∀ L ∈ N.lindblad_operators, L * cellProjector P = cellProjector P * L) := by
  constructor
  · intro hN L hL
    exact (preservesCellUniform_iff_commutant_under_adjoint P L).1
      ⟨hN L hL, hN Lᴴ (hadj L hL)⟩
  · intro hN L hL
    exact ((preservesCellUniform_iff_commutant_under_adjoint P L).2 (hN L hL)).1

/-! ## 2. Universally-equitable noise = centre of `Mat_n(ℂ)`

A noise model is **universally equitable** if it preserves *every*
equitable partition of *every* host graph.  Algebraically, the intersection
over all equitable partitions of `commutantOf P` is the **centre** of
`Matrix V V ℂ` — i.e. scalar multiples of `1`.  Therefore the universally
equitable noise models are exactly those whose Lindblad operators are
*scalar multiples of the identity*.

This is the open-system mirror of the closed-system fact that the
"universal" Hamiltonian preserving every equitable partition is `c · I` —
which is dynamically trivial. -/

/-- A noise model is **universally equitable** when it preserves every
equitable partition of every weighted host graph (over the same vertex
type). -/
def _root_.Graphplay.NoiseModel.IsUniversallyEquitable (N : NoiseModel V) : Prop :=
  ∀ (G' : WeightedGraph V) (I' : Type v) [Fintype I'] [DecidableEq I']
    (P : EquitablePartition G' I'), N.cellUniformSymmetric P

/-- The **centre** of `Matrix V V ℂ` is the set of matrices commuting with
every other matrix; classically this is the line of scalar multiples of the
identity. -/
def centerMat (V : Type u) [Fintype V] [DecidableEq V] : Set (Matrix V V ℂ) :=
  { M | ∀ N : Matrix V V ℂ, M * N = N * M }

/-- The centre of `Matrix V V ℂ` consists of scalar multiples of `1`. -/
theorem mem_centerMat_iff (M : Matrix V V ℂ) :
    M ∈ centerMat V ↔ ∃ c : ℂ, M = c • (1 : Matrix V V ℂ) := by
  -- A matrix commutes with every other matrix iff it is a scalar matrix
  -- (`Matrix.mem_range_scalar_iff_commute_single'`); the scalar matrix
  -- `Matrix.scalar V c` is `c • 1` via `smul_one_eq_diagonal`.
  constructor
  · intro hM
    obtain ⟨c, hc⟩ := Matrix.mem_range_scalar_iff_commute_single'.mpr
      (fun i j => (hM (Matrix.single i j 1)).symm)
    exact ⟨c, by rw [← hc, Matrix.scalar_apply, smul_one_eq_diagonal]⟩
  · rintro ⟨c, rfl⟩ N
    rw [smul_mul_assoc, one_mul, mul_smul_comm, mul_one]

/-- **Scalar matrices preserve every cell-uniform subspace.**  A scalar
multiple `c • 1` of the identity acts as `ψ ↦ c • ψ`, which carries
cell-uniform vectors to cell-uniform vectors.  This is the easy half of the
universally-equitable characterisation. -/
theorem central_preservesCellUniform
    {I' : Type v} [Fintype I'] [DecidableEq I'] {G' : WeightedGraph V}
    (P : EquitablePartition G' I') (L : Matrix V V ℂ) (hL : L ∈ centerMat V) :
    Matrix.preservesCellUniform L P := by
  obtain ⟨c, rfl⟩ := (mem_centerMat_iff L).1 hL
  intro ψ hψ x y hxy
  -- `(c • 1).mulVec ψ = c • ψ`, so the conclusion reduces to cell-uniformity of `ψ`.
  have hmv : ∀ z : V, ((c • (1 : Matrix V V ℂ)).mulVec ψ) z = c * ψ z := by
    intro z
    rw [Matrix.mulVec, dotProduct, Finset.sum_eq_single z]
    · simp [Matrix.one_apply_eq]
    · intro b _ hb
      simp [Matrix.one_apply, hb.symm]
    · intro h; exact absurd (Finset.mem_univ z) h
  rw [hmv x, hmv y, hψ x y hxy]

/-- **Universally-equitable characterisation.**  `N` is universally
equitable iff every jump operator is a scalar multiple of the identity.

In particular: a *non-trivial* noise model can never be universally
equitable — any genuine dissipation breaks *some* equitable partition. -/
theorem isUniversallyEquitable_iff_central (N : NoiseModel V) :
    N.IsUniversallyEquitable ↔
      (∀ L ∈ N.lindblad_operators, L ∈ centerMat V) := by
  constructor
  · -- (⇒): if `N` preserves every partition, take 2-element cells; commuting
    --      with the off-diagonal cell-mixing forces `L ∈ centerMat V`.  This is
    --      the genuinely-deep direction (it needs non-singleton cells to probe
    --      every off-diagonal entry); isolated as an honest `sorry`.
    sorry
  · -- (⇐): scalar multiples of the identity preserve every cell-uniform
    --      subspace (`central_preservesCellUniform`), hence every partition.
    intro hcentral G' I' _ _ P L hL
    exact central_preservesCellUniform P L (hcentral L hL)

/-- **Corollary.**  The only universally-equitable noise model with finitely
many non-zero rates is the trivial unitary model up to global dephasing by
the identity (which acts trivially on density matrices). -/
theorem isUniversallyEquitable_trivial_up_to_identity
    (N : NoiseModel V) (hN : N.IsUniversallyEquitable) :
    ∀ L ∈ N.lindblad_operators, ∃ c : ℂ, L = c • (1 : Matrix V V ℂ) := by
  intro L hL
  have hC := (isUniversallyEquitable_iff_central N).1 hN L hL
  exact (mem_centerMat_iff L).1 hC

/-! ## 3. Open-system lifting theorem

We restate `cellUniform_preserved` (file A8) in a sharper form: under
`cellUniformSymmetric` noise, the Lindblad evolution restricted to
cell-uniform density operators equals the Lindblad evolution of the
**quotient** noise model on the quotient Hilbert space.

The closed-system analogue is `EquitablePartition.restrict_eq_quotient` in
`Graphplay.Equitable`: the adjacency action on the cell-uniform subspace is
the action of the quotient matrix `P.quotient`. -/

/-- The Lindblad superoperator (dissipative part) associated to a single
jump operator `L` and rate `γ`:

  `D_{L,γ}(ρ) = γ · (L ρ L† − ½ (L† L · ρ + ρ · L† L))`. -/
noncomputable def lindbladSuperop
    (L : Matrix V V ℂ) (γ : ℝ) (ρ : Matrix V V ℂ) : Matrix V V ℂ :=
  (γ : ℂ) • (L * ρ * Lᴴ - (1 / 2 : ℂ) • (Lᴴ * L * ρ + ρ * Lᴴ * L))

/-- The full Lindblad generator `ℒ(ρ) = -i[H, ρ] + ∑_k γ_k D_{L_k}(ρ)`. -/
noncomputable def lindbladGen
    (H : Matrix V V ℂ) (N : NoiseModel V) (ρ : Matrix V V ℂ) :
    Matrix V V ℂ :=
  -Complex.I • (H * ρ - ρ * H)
    + ∑ L ∈ N.lindblad_operators,
        lindbladSuperop L ((N.coherence_rates L : ℝ)) ρ

/-- A density matrix `ρ` is **cell-uniform** when it commutes with the
cell-projector: equivalently, both its left- and right-action preserve the
cell-uniform subspace. -/
def Matrix.IsCellUniformDensity
    (P : EquitablePartition G I) (ρ : Matrix V V ℂ) : Prop :=
  cellProjector P * ρ = ρ * cellProjector P

/-- The matrices commuting with the cell projector are closed under products. -/
theorem mul_comm_cellProjector {A B : Matrix V V ℂ} (P : EquitablePartition G I)
    (hA : A * cellProjector P = cellProjector P * A)
    (hB : B * cellProjector P = cellProjector P * B) :
    (A * B) * cellProjector P = cellProjector P * (A * B) := by
  rw [mul_assoc, hB, ← mul_assoc, hA, mul_assoc]

/-- A single Lindblad superoperator preserves cell-uniformity of density
matrices when its jump operator commutes with the cell projector together with
its adjoint.  This is the term-by-term engine of
`lindbladGen_preserves_cellUniform`. -/
theorem lindbladSuperop_preserves_cellUniform
    (P : EquitablePartition G I) {L : Matrix V V ℂ} (γ : ℝ)
    (hL : L * cellProjector P = cellProjector P * L)
    (hLH : Lᴴ * cellProjector P = cellProjector P * Lᴴ)
    {ρ : Matrix V V ℂ} (hρ : Matrix.IsCellUniformDensity P ρ) :
    Matrix.IsCellUniformDensity P (lindbladSuperop L γ ρ) := by
  unfold Matrix.IsCellUniformDensity at hρ ⊢
  unfold lindbladSuperop
  -- `ρ` commutes with `Π` (the hypothesis `hρ` written in the canonical order).
  have hρ' : ρ * cellProjector P = cellProjector P * ρ := hρ.symm
  -- `L ρ Lᴴ`, `Lᴴ L ρ`, `ρ Lᴴ L` each commute with `Π` (products of commuters);
  -- closure under smul/sub/add then finishes by direct rewriting.
  have hLρLH : (L * ρ * Lᴴ) * cellProjector P = cellProjector P * (L * ρ * Lᴴ) :=
    mul_comm_cellProjector P (mul_comm_cellProjector P hL hρ') hLH
  have hLHLρ : (Lᴴ * L * ρ) * cellProjector P = cellProjector P * (Lᴴ * L * ρ) :=
    mul_comm_cellProjector P (mul_comm_cellProjector P hLH hL) hρ'
  have hρLHL : (ρ * Lᴴ * L) * cellProjector P = cellProjector P * (ρ * Lᴴ * L) :=
    mul_comm_cellProjector P (mul_comm_cellProjector P hρ' hLH) hL
  rw [Matrix.mul_smul, Matrix.smul_mul, Matrix.mul_sub, Matrix.sub_mul,
      Matrix.mul_smul, Matrix.smul_mul, Matrix.mul_add, Matrix.add_mul,
      hLρLH, hLHLρ, hρLHL]

/-- **Open-system lifting theorem.**  Suppose

* `H` commutes with the cell projector (the genuine condition for a *Hermitian*
  cell-uniform-preserving Hamiltonian, by
  `preservesCellUniform_iff_commutant_under_adjoint`);
* every jump operator of `N` commutes with the cell projector together with its
  adjoint (the adjoint-closed form of `cellUniformSymmetric P`);
* `ρ` is a cell-uniform density matrix.

Then the Lindblad generator `ℒ(ρ)` is again cell-uniform.

CORRECTNESS FIX (issue #53): the original hypotheses `preservesCellUniform H P`
and `cellUniformSymmetric P` are **insufficient** — for a *non-Hermitian* `H`
that merely maps cell-uniform vectors to cell-uniform vectors (e.g.
`H = single 0 0 1 + single 1 0 1` on a single 2-cell) one has `HPi ≠ PiH`, and the
commutator `[H, Pi]` is *not* cell-uniform, so the generator fails to preserve
cell-uniformity.  The TRUE statement requires `H` (and each `L`, `Lᴴ`) to commute
with the projector `Pi`; we state and prove that. -/
theorem lindbladGen_preserves_cellUniform
    (P : EquitablePartition G I)
    {H : Matrix V V ℂ} (hH : H * cellProjector P = cellProjector P * H)
    {N : NoiseModel V}
    (hN : ∀ L ∈ N.lindblad_operators,
      L * cellProjector P = cellProjector P * L ∧
        Lᴴ * cellProjector P = cellProjector P * Lᴴ)
    {ρ : Matrix V V ℂ} (hρ : Matrix.IsCellUniformDensity P ρ) :
    Matrix.IsCellUniformDensity P (lindbladGen H N ρ) := by
  unfold lindbladGen
  unfold Matrix.IsCellUniformDensity at hρ ⊢
  -- `Hρ` and `ρH` each commute with `Π` (products of commuters).
  have hρ' : ρ * cellProjector P = cellProjector P * ρ := hρ.symm
  have hHρ : (H * ρ) * cellProjector P = cellProjector P * (H * ρ) :=
    mul_comm_cellProjector P hH hρ'
  have hρH : (ρ * H) * cellProjector P = cellProjector P * (ρ * H) :=
    mul_comm_cellProjector P hρ' hH
  rw [Matrix.mul_add, Matrix.add_mul]
  congr 1
  · -- commutator term `-i (Hρ - ρH)` commutes with `Π`.
    rw [Matrix.mul_smul, Matrix.smul_mul, Matrix.mul_sub, Matrix.sub_mul, hHρ, hρH]
  · -- the dissipative sum commutes with `Π`, term by term.
    rw [Finset.mul_sum, Finset.sum_mul]
    refine Finset.sum_congr rfl (fun L hL => ?_)
    obtain ⟨hLc, hLHc⟩ := hN L hL
    have := lindbladSuperop_preserves_cellUniform P (N.coherence_rates L : ℝ) hLc hLHc hρ
    unfold Matrix.IsCellUniformDensity at this
    exact this

/-- **Quotient reduction.**  When the Hamiltonian and every jump operator are
themselves *inflated* from the quotient (`H = cellInflate Hbar`, each
`L = cellInflate Lbar`), the generator action on an inflated density matrix is
again inflated: there is a quotient-level matrix `K` with
`lindbladGen H N (cellInflate rhobar) = cellInflate K`.

CORRECTNESS NOTE (issue #53): the original hypotheses `preservesCellUniform H P`
and `cellUniformSymmetric P` are **insufficient** for this conclusion.  Those give
only that the output *commutes with the projector* (`IsCellUniformDensity`,
proved in `lindbladGen_preserves_cellUniform`), which is **strictly weaker** than
being *block-constant* (in `range cellInflate`).  E.g. on a single cell the
projector-commuting permutation matrix is not block-constant, so it is not in the
range of `cellInflate`.  Block-constancy of the output genuinely requires `H` and
the `L`'s to be block-constant operators (inflated from the quotient), which we
add as hypotheses.

HONEST RESIDUAL: the remaining `sorry` is isolated to a single missing piece of
infrastructure — a *multiplicative closure law for `cellInflate`*, i.e. that
`cellInflate A * cellInflate B` and conjugates `cellInflate A * M * cellInflate B`
are again inflated matrices with an explicit quotient-level product (the
density-matrix analogue of `Equitable.adj_mulVec_cellInflateVec`).  That algebra
is not yet developed in `Graphplay.Equitable`; once it lands, `K` is read off
term by term. -/
theorem lindbladGen_quotient_reduction
    (P : EquitablePartition G I)
    {H : Matrix V V ℂ} {Hbar : Matrix I I ℂ} (hH : H = P.cellInflate Hbar)
    {N : NoiseModel V}
    (hN : ∀ L ∈ N.lindblad_operators, ∃ Lbar : Matrix I I ℂ, L = P.cellInflate Lbar)
    (rhobar : Matrix I I ℂ) :
    ∃ K : Matrix I I ℂ,
      lindbladGen H N (P.cellInflate rhobar) = P.cellInflate K := by
  -- Reduces to the `cellInflate` multiplicative-closure law (see HONEST RESIDUAL).
  sorry

/-- **Time-evolved corollary.**  The semigroup `exp(t · ℒ)` solving the
Lindblad master equation `dρ/dt = ℒ(ρ)` preserves the cell-uniform
subspace, and its restriction to cell-uniform initial states is the
quotient semigroup. -/
theorem noisyEvolve_quotient
    (P : EquitablePartition G I)
    {H : Matrix V V ℂ} (hH : H * cellProjector P = cellProjector P * H)
    {N : NoiseModel V} (htot : N.totalRate = 0)
    {ρ₀ : Matrix V V ℂ} (hρ₀ : Matrix.IsCellUniformDensity P ρ₀)
    (t : ℝ) :
    Matrix.IsCellUniformDensity P (noisyEvolve H N t ρ₀) := by
  -- CORRECTNESS FIX (issue #53): the general claim is **false** for this concrete
  -- `noisyEvolve` model.  `noisyEvolve` damps every *off-diagonal* coherence by a
  -- global factor and keeps the diagonal, i.e. it is a *position-basis* dephasing
  -- step.  For a `Π`-commuting state with within-cell coherences (e.g. the
  -- Hermitian `ρ₀ = (1/n)J + v vᴴ` with `v ⟂ 𝟙`, whose diagonal is *not* constant
  -- on the cell) the damped diagonal part fails to commute with `Π`.  Position-
  -- basis dephasing is *exactly* the symmetry-breaking noise of §4; it preserves
  -- cell-uniformity only when there is **no** dephasing (`totalRate = 0`), where
  -- `noisyEvolve` reduces to the coherent conjugation `ρ ↦ U ρ Uᴴ` with
  -- `U = exp(-(i t)·H)`.  With `H` commuting with `Π`, that conjugation preserves
  -- cell-uniformity.  We state and prove that genuinely-true case.
  unfold Matrix.IsCellUniformDensity at hρ₀ ⊢
  -- `damp = exp(-t·0) = 1`, so `noisyEvolve H N t ρ₀ = U ρ₀ Uᴴ`.
  have hdamp : Real.exp (-t * N.totalRate) = 1 := by rw [htot, mul_zero, Real.exp_zero]
  have hne : noisyEvolve H N t ρ₀
      = (NormedSpace.exp (-(Complex.I * (t : ℂ)) • H)) * ρ₀ *
          (NormedSpace.exp (-(Complex.I * (t : ℂ)) • H))ᴴ := by
    funext x y
    simp only [noisyEvolve, hdamp]
    split <;> simp [Complex.ofReal_one]
  rw [hne]
  -- `U` and `Uᴴ` commute with `Π` (since `H` does), and so does `ρ₀`.
  set U := NormedSpace.exp (-(Complex.I * (t : ℂ)) • H) with hU
  have hHcomm : Commute (cellProjector P) H := hH.symm
  have hsmul : Commute (cellProjector P) (-(Complex.I * (t : ℂ)) • H) :=
    (hHcomm.smul_right _)
  have hUcomm : Commute (cellProjector P) U := hsmul.exp_right
  have hUPi : U * cellProjector P = cellProjector P * U := hUcomm.symm
  have hUH : Uᴴ * cellProjector P = cellProjector P * Uᴴ :=
    conjTranspose_comm_cellProjector P hUPi
  have h1 : (U * ρ₀) * cellProjector P = cellProjector P * (U * ρ₀) :=
    mul_comm_cellProjector P hUPi hρ₀.symm
  exact (mul_comm_cellProjector P h1 hUH).symm

/-! ## 4. Caruso-style noise-assisted transport via partial symmetry-breaking

Caruso, Chin, Datta, Huelga, Plenio (PRA 81, 062346 (2010)) and the
follow-up literature on **environment-assisted quantum transport** show
that *some* dephasing dramatically improves search and transport
probabilities by lifting accidental degeneracies that trap closed-system
amplitudes in dark subspaces.

The cleanest operator-algebraic statement: a closed-system Hamiltonian's
*dark space* with respect to a target sink is contained in the
**commutant** of the symmetry group; partial dephasing that escapes that
commutant evacuates the dark space.  In our equitable-partition language:
**partial dephasing that escapes `commutantOf P`** removes the
cell-uniform subspace's degenerate eigenmodes from the dynamics.

We make this precise via a `BreakingScore`. -/

/-- A naive `ℓ²`-style **breaking score**: the squared Frobenius norm of
the component of `L` *outside* `commutantOf P`.  When `L ∈ commutantOf P`
the score is `0` (no symmetry breaking).  When `L` is orthogonal to the
commutant the score equals `‖L‖²_F` (maximally disruptive). -/
noncomputable def breakingScoreOp
    (P : EquitablePartition G I) (L : Matrix V V ℂ) : ℝ :=
  -- The Frobenius projection of `L` onto the partition (block-diagonal) algebra
  -- zeroes exactly the entries joining *distinct* cells; the score is the
  -- squared Frobenius norm of the discarded off-block part:
  --   `‖L − π_P L‖²_F = ∑_{cells x ≠ cells y} ‖L x y‖²`.
  -- This is `0` iff `L` is block-diagonal w.r.t. `P` (the core of lying in
  -- `commutantOf P`), and grows as `L` couples vertices across cells.
  ∑ x : V, ∑ y : V, if P.cells x ≠ P.cells y then ‖L x y‖ ^ 2 else 0

/-- The **breaking score** of a noise model is the rate-weighted sum of the
operator-level breaking scores. -/
noncomputable def _root_.Graphplay.NoiseModel.BreakingScore
    (N : NoiseModel V) (P : EquitablePartition G I) : ℝ :=
  ∑ L ∈ N.lindblad_operators, (N.coherence_rates L : ℝ) * breakingScoreOp P L

/-- **Breaking score zero ⇔ every positive-rate Lindblad is block-diagonal.**

CORRECTNESS FIX: the original statement `BreakingScore = 0 ↔ cellUniformSymmetric`
is **FALSE** (issue #53; the diagonal projector `|m⟩⟨m|` has score `0` yet fails
to preserve the cell-uniform subspace — see
`boundaryDephasing_breakingScore` / `boundaryDephasing_not_cellUniformSymmetric`).
We replace it by the genuinely-true characterization that `breakingScoreOp`
*actually* computes: the rate-weighted off-block Frobenius mass vanishes iff
every Lindblad with positive rate is block-diagonal w.r.t. `P` (i.e. its
off-block entries all vanish).  This is proved, no sorry. -/
theorem breakingScore_zero_iff_blockDiagonal
    (P : EquitablePartition G I) (N : NoiseModel V) :
    N.BreakingScore P = 0 ↔
      ∀ L ∈ N.lindblad_operators,
        (N.coherence_rates L : ℝ) = 0 ∨
          (∀ x y : V, P.cells x ≠ P.cells y → L x y = 0) := by
  unfold NoiseModel.BreakingScore breakingScoreOp
  rw [Finset.sum_eq_zero_iff_of_nonneg]
  · -- termwise: `rate L * (∑∑ off-block ‖L x y‖²) = 0` iff rate 0 or all off-block 0.
    refine forall_congr' (fun L => ?_)
    refine forall_congr' (fun _hL => ?_)
    rw [mul_eq_zero]
    refine or_congr Iff.rfl ?_
    -- the inner double sum of nonneg terms is zero iff each off-block entry is 0.
    rw [Finset.sum_eq_zero_iff_of_nonneg
        (fun x _ => Finset.sum_nonneg (fun y _ => by split <;> positivity))]
    constructor
    · intro h x y hxy
      have hx := h x (Finset.mem_univ x)
      rw [Finset.sum_eq_zero_iff_of_nonneg (fun y _ => by split <;> positivity)] at hx
      have := hx y (Finset.mem_univ y)
      rw [if_pos hxy] at this
      have hnorm : ‖L x y‖ = 0 := by nlinarith [norm_nonneg (L x y), sq_nonneg ‖L x y‖]
      exact norm_eq_zero.mp hnorm
    · intro h x _
      refine Finset.sum_eq_zero (fun y _ => ?_)
      split
      · rename_i hxy; rw [h x y hxy]; simp
      · rfl
  · -- nonnegativity of each rate-weighted operator term.
    intro L _
    refine mul_nonneg (by positivity) ?_
    exact Finset.sum_nonneg (fun x _ => Finset.sum_nonneg (fun y _ => by split <;> positivity))

/-- **Existence of a zero-breaking and a positive-breaking model.**  Given two
vertices `x₀, y₀` in distinct cells of `P`, there exist two noise models: a
cell-uniform-symmetric one `N₀` (the trivial no-jump model, breaking score `0`)
and one `N₁` (a single off-block jump `|x₀⟩⟨y₀|`) with strictly positive breaking
score.  This is a *satisfiability witness* that both the zero-breaking and the
positive-breaking regimes are populated; it is **not** a dynamical speedup claim.

HONEST RELABEL (was `noise_assisted_speedup_conjecture`): the previous name
advertised a "speedup conjecture" but the body only exhibits these two
breaking-score models — it proves a satisfiability witness of `BreakingScore > 0`,
never any comparison of transport probabilities `sup_t pₛ(N, t)`.  The genuine
Caruso claim (an *intermediate* breaking score is dynamically *optimal*) is a
separate quantitative statement, not asserted here. -/
theorem exists_zero_and_positive_breaking_model
    (P : EquitablePartition G I)
    -- A positive breaking score requires an off-block edge, i.e. two distinct
    -- cells; we take that as the hypothesis and exhibit a zero-breaking
    -- (`N₀ = trivial`) and a positive-breaking (`N₁` = single off-block jump) model.
    (x₀ y₀ : V) (hxy : P.cells x₀ ≠ P.cells y₀) :
    ∃ N₀ : NoiseModel V, ∃ N₁ : NoiseModel V,
      N₀.cellUniformSymmetric P ∧
        N₁.BreakingScore P > 0 := by
  classical
  -- `N₀`: the trivial (no-jump) model — cell-uniform-symmetric, score `0`.
  -- `N₁`: a single jump `single x₀ y₀ 1` at unit rate, with off-block mass `1`.
  refine ⟨NoiseModel.trivial V,
    { lindblad_operators := {Matrix.single x₀ y₀ 1}
      coherence_rates := fun _ => 1 }, ?_, ?_⟩
  · -- `N₀ = trivial` is cell-uniform-symmetric: it has no Lindblad operators.
    intro L hL; simp [NoiseModel.trivial] at hL
  · -- `N₁.BreakingScore P = ∑_L rate·breakingScoreOp = 1·‖single x₀ y₀ 1 evaluated
    -- on the off-block (x₀,y₀)‖² = 1 > 0`.
    have hx₀y₀ : x₀ ≠ y₀ := by rintro rfl; exact hxy rfl
    unfold NoiseModel.BreakingScore breakingScoreOp
    rw [Finset.sum_singleton]
    -- the rate is `1`; the off-block double sum has the `(x₀, y₀)` term equal to `1`.
    have hterm : (∑ x : V, ∑ y : V,
        if P.cells x ≠ P.cells y then ‖(Matrix.single x₀ y₀ (1:ℂ)) x y‖ ^ 2 else 0)
        = 1 := by
      rw [Finset.sum_eq_single x₀]
      · rw [Finset.sum_eq_single y₀]
        · rw [if_pos hxy, Matrix.single_apply_same]; simp
        · intro b _ hb
          by_cases hc : P.cells x₀ ≠ P.cells b
          · rw [if_pos hc, Matrix.single_apply_of_col_ne x₀ x₀ (Ne.symm hb) 1, norm_zero]; simp
          · rw [if_neg hc]
        · intro h; exact absurd (Finset.mem_univ y₀) h
      · intro b _ hb
        refine Finset.sum_eq_zero (fun y _ => ?_)
        by_cases hc : P.cells b ≠ P.cells y
        · rw [if_pos hc, Matrix.single_apply_of_row_ne (Ne.symm hb) y₀ y 1, norm_zero]; simp
        · rw [if_neg hc]
      · intro h; exact absurd (Finset.mem_univ x₀) h
    rw [hterm]
    norm_num

/-! ## 5. Three concrete noise models analysed

We instantiate the criterion on the three standard textbook models. -/

/-! ### 5.1 Depolarising noise — universally equitable -/

/-- **Depolarising noise is universally equitable.**

Depolarising noise can be written with Lindblad operators that are the
generalised Gell-Mann basis of `Mat_n(ℂ)` weighted equally.  As a
*channel*, depolarising noise sends `ρ ↦ (1−p) ρ + p · 𝟙/n` — which
acts trivially on cell-projector commutators.  Equivalently, the
dissipative part of the Lindblad generator commutes with every projector.
-/
theorem depolarizing_isUniversallyEquitable (rate : ℝ) :
    (NoiseModel.depolarizingNoise V rate).IsUniversallyEquitable := by
  -- requires the deferred concrete construction of `depolarizingNoise`;
  -- once expanded, each `L_k` is in `centerMat V` after the natural rewriting.
  sorry

/-! ### 5.2 Site-dependent dephasing — cell-uniform-symmetric iff the partition is discrete

Site dephasing has one Lindblad per vertex: `L_v = |v⟩⟨v|`.  Against the
concrete `preservesCellUniform` notion, the whole noise model is
cell-uniform-symmetric for `P` iff **every cell is a singleton** (the discrete
partition): `|v⟩⟨v|` sends the all-ones vector to the indicator `e_v`, which is
constant on `v`'s cell only when that cell is `{v}`.  (The naive "cells are
vertex-orbits" guess is strictly too weak — see the `CORRECTNESS FIX` note on
`dephasing_cellUniformSymmetric_iff_singleton` below.  The orbit predicate
`isVertexOrbitPartition` is retained as a separate, weaker notion.) -/

/-- The vertex-permutation symmetry group of the host graph (informal:
graph automorphisms).  Encoded as the *partition into orbits* of any
automorphism group fixing `P`. -/
def isVertexOrbitPartition
    (G : WeightedGraph V) (P : EquitablePartition G I) : Prop :=
  -- two vertices in the same cell of `P` are exchangeable by an
  -- automorphism of `G` fixing each cell setwise.
  ∀ x y : V, P.cells x = P.cells y →
    ∃ σ : V ≃ V, (∀ a b, G.adj (σ a) (σ b) = G.adj a b) ∧
      (∀ v, P.cells (σ v) = P.cells v) ∧
      σ x = y

/-- **Site dephasing is equitable iff the partition is discrete (all cells
singletons).**

CORRECTNESS FIX (issue #53): the original conclusion `isVertexOrbitPartition G P`
is **false** against the concrete `cellProjector`/`preservesCellUniform` notion.
Site dephasing's jump operator `|v⟩⟨v| = single v v 1` sends the all-ones
(cell-uniform) vector to the indicator `e_v`, which is constant on `v`'s cell
**iff that cell is the singleton `{v}`**.  So `cellUniformSymmetric` forces every
cell to be a singleton — strictly stronger than `isVertexOrbitPartition`, which
already holds for e.g. the single-cell partition of `K₂` (swap automorphism) yet
there dephasing is *not* cell-uniform-symmetric.  We state and prove the
genuinely-true singleton characterisation. -/
theorem dephasing_cellUniformSymmetric_iff_singleton
    (G : WeightedGraph V) (P : EquitablePartition G I) (rate : ℝ) :
    (NoiseModel.dephasingNoise V rate).cellUniformSymmetric P ↔
      (∀ v w : V, P.cells w = P.cells v → w = v) := by
  classical
  constructor
  · -- `cellUniformSymmetric` ⇒ every cell is a singleton.
    intro hsym v w hwv
    -- `single v v 1` is a jump operator; it preserves cell-uniform.
    have hLmem : Matrix.single v v (1 : ℂ) ∈
        (NoiseModel.dephasingNoise V rate).lindblad_operators := by
      simp only [NoiseModel.dephasingNoise, Finset.mem_image, Finset.mem_univ]
      exact ⟨v, trivial, rfl⟩
    have hpres := hsym _ hLmem
    -- apply to the constant-`1` vector; result at `w` and `v` must agree.
    have hconst : ∀ a b : V, P.cells a = P.cells b →
        (fun _ : V => (1 : ℂ)) a = (fun _ : V => (1 : ℂ)) b := fun _ _ _ => rfl
    have key := hpres (fun _ => (1 : ℂ)) hconst w v hwv
    -- `(single v v 1) *ᵥ 1` is `1` at `v` and `0` at any `w ≠ v`.
    by_contra hne
    have hmw : (Matrix.single v v (1 : ℂ)).mulVec (fun _ => (1 : ℂ)) w = 0 := by
      rw [Matrix.mulVec, dotProduct]
      apply Finset.sum_eq_zero; intro y _
      rw [Matrix.single_apply_of_row_ne (Ne.symm hne) _ _, zero_mul]
    have hmv : (Matrix.single v v (1 : ℂ)).mulVec (fun _ => (1 : ℂ)) v = 1 := by
      rw [Matrix.mulVec, dotProduct, Finset.sum_eq_single v]
      · rw [Matrix.single_apply_same, mul_one]
      · intro b _ hb
        rw [Matrix.single_apply_of_col_ne v v (Ne.symm hb) (1 : ℂ), zero_mul]
      · intro h; exact absurd (Finset.mem_univ v) h
    rw [hmw, hmv] at key
    exact zero_ne_one key
  · -- discrete partition ⇒ every operator trivially preserves cell-uniform
    -- (within-cell pairs are equal).
    intro hsingleton L hL ψ hψ x y hxy
    have hxyeq : x = y := hsingleton y x hxy
    rw [hxyeq]

/-! ### 5.3 Boundary dephasing — symmetry breaking and quantified score -/

/-- **Boundary dephasing** at a single marked vertex `m`: only one
Lindblad operator, the projector `|m⟩⟨m|` onto `m`, with rate `rate`. -/
noncomputable def NoiseModel.boundaryDephasing
    (V : Type u) [Fintype V] [DecidableEq V]
    (m : V) (rate : ℝ) : NoiseModel V where
  -- single Lindblad `|m⟩⟨m| = single m m 1`, with rate `|rate|`.
  lindblad_operators := {Matrix.single m m 1}
  coherence_rates _ := Real.toNNReal rate

/-- The **marked-refined** partition of an equitable `P`, indexed by `I ⊕ Unit`.

The intended refinement splits the cell of the marked vertex `m` into `{m}`
(tagged `Sum.inr ()`) and the rest.  That split is genuinely equitable only
when `G` is vertex-transitive on `cell(m) \ {m}`; in general it is not.

To stay honest *and* concrete (no `sorry` in the `uniform` field), this `def`
returns the canonical equitability-preserving embedding `Sum.inl ∘ P.cells`:
the original partition `P` re-indexed into `I ⊕ Unit`, leaving the `Sum.inr ()`
cell empty.  Its `uniform` axiom follows directly from `P.uniform`.  The
genuine marked split, when equitable, is a refinement of this. -/
def markedRefined
    (P : EquitablePartition G I) (_m : V) : EquitablePartition G (I ⊕ Unit) where
  cells := fun v => Sum.inl (P.cells v)
  uniform := by
    intro i j x y hx hy
    -- only `j = Sum.inl j'` contributes; reduce to `P.uniform`.
    cases j with
    | inr u =>
      -- no vertex is labelled `Sum.inr`, so both sums vanish termwise.
      simp only [reduceCtorEq, if_false]
    | inl j' =>
      -- `Sum.inl (P.cells z) = Sum.inl j' ↔ P.cells z = j'`.
      cases i with
      | inr u => exact absurd hx (by simp)
      | inl i' =>
        have hx' : P.cells x = i' := by simpa using hx
        have hy' : P.cells y = i' := by simpa using hy
        have := P.uniform i' j' x y hx' hy'
        simpa [Sum.inl.injEq] using this

/-- **Boundary dephasing's breaking score is `0` (corrected, issue #53).**

The original statement claimed the breaking score was `rate · (1 − 1/|cell(m)|)`,
the "non-singleton fraction" of the cell of `m`.  Against the *concrete*
`breakingScoreOp` — which measures the squared Frobenius mass of `L` joining
distinct cells — this is **false**: the single Lindblad operator
`|m⟩⟨m| = single m m 1` is a *diagonal* matrix, so it has no off-block entries
at all and its breaking score is exactly `0`.  We prove the corrected value.

(The folklore `rate·(1−1/|cell|)` is the *coherence* removed by dephasing in a
different, non-Frobenius normalisation; it is not what `breakingScoreOp`
computes.) -/
theorem boundaryDephasing_breakingScore
    (P : EquitablePartition G I) (m : V) (rate : ℝ) (hrate : 0 < rate)
    -- assume cell(m) is non-singleton, so refinement is non-trivial
    (hcell : ∃ v : V, P.cells v = P.cells m ∧ v ≠ m) :
    (NoiseModel.boundaryDephasing V m rate).BreakingScore (markedRefined P m)
      = 0 := by
  -- The only Lindblad operator is `single m m 1`, a diagonal matrix.  Its
  -- breaking score sums `‖single m m 1 x y‖²` over off-block `(x, y)`; but an
  -- off-block pair has `x ≠ y` (distinct cells ⇒ distinct vertices), so every
  -- summed entry is `0`.
  unfold NoiseModel.BreakingScore NoiseModel.boundaryDephasing breakingScoreOp
  simp only [Finset.sum_singleton]
  have hop : (∑ x : V, ∑ y : V,
      if (markedRefined P m).cells x ≠ (markedRefined P m).cells y then
        ‖(Matrix.single m m (1 : ℂ)) x y‖ ^ 2 else 0) = 0 := by
    apply Finset.sum_eq_zero; intro x _
    apply Finset.sum_eq_zero; intro y _
    split
    · rename_i hxy
      -- distinct cells ⇒ distinct vertices ⇒ the `single` entry vanishes.
      have hxy' : x ≠ y := by
        rintro rfl; exact hxy rfl
      have hentry : (Matrix.single m m (1 : ℂ)) x y = 0 := by
        rcases eq_or_ne m x with hx | hx
        · subst hx
          exact Matrix.single_apply_of_col_ne m m hxy' (1 : ℂ)
        · exact Matrix.single_apply_of_row_ne hx _ _ _
      rw [hentry]; simp
    · rfl
  rw [hop, mul_zero]

/-- **Boundary dephasing is NOT cell-uniform-symmetric for the marked-refined
partition** — but for a reason orthogonal to the breaking *score* (issue #53).

Crucially, this is *not* a corollary of a positive breaking score: the score is
`0` (proved above), because `breakingScoreOp` only sees off-block Frobenius mass
and the diagonal projector `|m⟩⟨m|` has none.  Nevertheless `|m⟩⟨m|` fails to
*preserve* the cell-uniform subspace: applied to the all-ones (cell-uniform)
vector it returns the indicator `e_m`, which is non-constant on `m`'s
(non-singleton) cell.  This is the precise sense in which
`breakingScore_zero_iff_cellUniformSymmetric` is *false* — block-diagonality
(score `0`) is strictly weaker than cell-uniform preservation.  We prove the
negative statement directly. -/
theorem boundaryDephasing_not_cellUniformSymmetric
    (P : EquitablePartition G I) (m : V) (rate : ℝ) (hrate : 0 < rate)
    (hcell : ∃ v : V, P.cells v = P.cells m ∧ v ≠ m) :
    ¬ (NoiseModel.boundaryDephasing V m rate).cellUniformSymmetric
        (markedRefined P m) := by
  obtain ⟨w, hwm, hwne⟩ := hcell
  intro hsym
  -- The single Lindblad operator `single m m 1` must preserve cell-uniform.
  have hLmem : Matrix.single m m (1 : ℂ) ∈
      (NoiseModel.boundaryDephasing V m rate).lindblad_operators := by
    simp [NoiseModel.boundaryDephasing]
  have hpres := hsym _ hLmem
  -- Apply to the constant-`1` vector, cell-uniform for any partition.
  have hconst : ∀ x y : V, (markedRefined P m).cells x = (markedRefined P m).cells y →
      (fun _ : V => (1 : ℂ)) x = (fun _ : V => (1 : ℂ)) y := fun _ _ _ => rfl
  -- `w` and `m` share a cell of `markedRefined P m`.
  have hcelleq : (markedRefined P m).cells w = (markedRefined P m).cells m := by
    simp only [markedRefined, hwm]
  have key := hpres (fun _ => (1 : ℂ)) hconst w m hcelleq
  -- Compute both `mulVec` entries: at `w` it is `0`, at `m` it is `1`.
  have hmw : (Matrix.single m m (1 : ℂ)).mulVec (fun _ => (1 : ℂ)) w = 0 := by
    rw [Matrix.mulVec, dotProduct]
    apply Finset.sum_eq_zero; intro y _
    have : (Matrix.single m m (1 : ℂ)) w y = 0 :=
      Matrix.single_apply_of_row_ne hwne.symm _ _ _
    rw [this, zero_mul]
  have hmm : (Matrix.single m m (1 : ℂ)).mulVec (fun _ => (1 : ℂ)) m = 1 := by
    rw [Matrix.mulVec, dotProduct, Finset.sum_eq_single m]
    · rw [Matrix.single_apply_same, mul_one]
    · intro b _ hb
      have : (Matrix.single m m (1 : ℂ)) m b = 0 :=
        Matrix.single_apply_of_col_ne m m (Ne.symm hb) (1 : ℂ)
      rw [this, zero_mul]
    · intro h; exact absurd (Finset.mem_univ m) h
  rw [hmw, hmm] at key
  exact zero_ne_one key

/-! ## 6. Chiral–noise duality

In `Graphplay.Chiral`, a **chiral signing** decorates a real-symmetric
adjacency with unit-modulus phases on edges, while preserving the same
absolute couplings.  The closed-system observation is: a *real* Hamiltonian
together with *complex* couplings (chiral phases) generates non-trivial
quantum-walk dynamics with broken time-reversal symmetry.

The **chiral-noise duality** is the formal observation that the *adjoint*
roles in the Lindblad equation are exchanged in the open-system setting:

* closed-system chiral: `H = adj` real-symmetric with complex phases →
  Hamiltonian *commutator* `[H, ρ]` is the source of asymmetry.
* open-system chiral: `H` purely real (no chiral phases) but `L_k`
  complex-valued → the **dissipator** `D_{L,γ}` is the source of asymmetry.

In both cases the algebra of unitary symmetries of the dynamics is reduced
from the full graph-automorphism group to the subgroup commuting with the
*relevant complex structure* (chiral phase / Lindblad operator).  We
encode the duality below. -/

/-- The **chiral form of a Lindblad operator**: `L = R + i·S` where
`R = (L + L†)/2` and `S = (L − L†)/(2i)` are Hermitian.  The Hermitian
parts `R, S` together with their commutator structure carry the same
data as the chiral phasing of `Graphplay.Chiral`. -/
noncomputable def chiralForm (L : Matrix V V ℂ) :
    (Matrix V V ℂ) × (Matrix V V ℂ) :=
  ((1 / 2 : ℂ) • (L + Lᴴ),
   (1 / (2 * Complex.I) : ℂ) • (L - Lᴴ))

/-- **Chiral-form reconstruction identity (Cartesian decomposition).**  The
two Hermitian components `R = (chiralForm L).1` and `S = (chiralForm L).2`
recover the original Lindblad operator via `L = R + i·S`.  This is the
operator-algebraic content underlying the chiral–noise correspondence: the
anti-Hermitian (chiral-phase) part of a dissipator's jump operator is exactly
`i·S`, so a real Hamiltonian `R` together with the chiral phase `S` carries the
full data of `L`.

HONEST RELABEL (was `chiral_noise_duality`): the previous statement was a
`rfl`-tautology asserting `(chiralForm L).1 = (chiralForm L).1` and
`(chiralForm L).2 = (chiralForm L).2` under an existential — it claimed a
"dynamics duality" but proved nothing about any Lindblad-vs-chiral evolution
agreement.  We strengthen to the genuine (non-`rfl`) reconstruction
`L = R + i·S`, which actually relates `L` to its chiral components. -/
theorem chiralForm_reconstruct
    (L : Matrix V V ℂ) :
    L = (chiralForm L).1 + Complex.I • (chiralForm L).2 := by
  -- R = (1/2)(L+Lᴴ), S = (1/(2i))(L−Lᴴ); then R + i·S = (1/2)(L+Lᴴ) + (1/2)(L−Lᴴ) = L.
  simp only [chiralForm, smul_smul]
  rw [smul_add, smul_sub]
  have hI : Complex.I * (1 / (2 * Complex.I)) = 1 / 2 := by
    field_simp
  rw [hI]
  module

/-- **Implication: chiral PST has an open-system mirror.**  Any
perfect-state-transfer time `t*` on a chiral closed-system walk corresponds
to a (decohered) PST time on an open-system mirror with appropriate
Lindblad jump operators encoding the chiral phase. -/
theorem chiral_PST_open_mirror
    (G : WeightedGraph V) (u v : V) :
    -- there is an open-system mirror (Hamiltonian `H`, noise `N`, time `t`)
    -- under which `|u⟩⟨u|` transfers a nonzero amplitude to `v`.
    ∃ (H : Matrix V V ℂ) (N : NoiseModel V) (t : ℝ),
      (noisyEvolve H N t (fun x y => if x = u ∧ y = u then 1 else 0)) v v ≠ 0 := by
  sorry

/-! ## 7. Open-system Bachman–Tamon

`references/1108.0339.txt` (Bachman & Tamon) proves the closed-system
PST reduction:

> A weighted host `G` with equitable partition `P` admits PST between two
> vertices `u, v` in the **same cell** iff the *quotient* `P.quotient`
> admits PST between the corresponding cell-indices.

We state the open-system extension: PST in an open system is equivalent
to PST in the *noisy quotient* — provided the noise is
`cellUniformSymmetric P`. -/

/-- The (statement-only) **open-system PST predicate**: there exists a time
`t` such that the time-`t` evolution of `|u⟩⟨u|` under `(H, N)` has its
`(v, v)`-entry equal to `1`. -/
def OpenSystemPST
    (H : Matrix V V ℂ) (N : NoiseModel V) (u v : V) : Prop :=
  ∃ t : ℝ, (noisyEvolve H N t fun x y => if x = u ∧ y = u then 1 else 0) v v = 1

/-- **Open-system Bachman–Tamon (deferred).**  Suppose `G` is a weighted
graph with equitable partition `P : V → I`, the Hamiltonian `H` is
cell-uniform-preserving, and the noise model `N` is `cellUniformSymmetric P`.

Let `u v : V` be two vertices with `P.cells u = P.cells v = i`.  Then

  open-system PST between `u` and `v` under `(H, N)`
    iff
  open-system PST at cell-index `i` in the quotient walk
    `(H.cellRestrict, N.quotient P)` *(self-loop PST in the quotient)*.

For vertices in *distinct* cells, the analogue reads:

  open-system PST between `u` and `v`
    iff
  open-system PST in the quotient between `P.cells u` and `P.cells v`. -/
theorem openSystem_bachmanTamon [Nonempty V]
    (P : EquitablePartition G I)
    {H : Matrix V V ℂ} (hH : Matrix.preservesCellUniform H P)
    {N : NoiseModel V} (hN : N.cellUniformSymmetric P)
    (u v : V) :
    OpenSystemPST H N u v ↔
      -- open-system PST in the quotient walk between the corresponding cell
      -- indices, for the quotient noise model `N.quotient P` and some quotient
      -- Hamiltonian `Hq` (the cell-restriction of `H`).
      ∃ Hq : Matrix I I ℂ, OpenSystemPST Hq (N.quotient P) (P.cells u) (P.cells v) := by
  sorry

/-- **Corollary (open-system PST reduction for cell-mates).**  When `u, v` lie
in the same cell, open-system PST between them reduces to a quotient *self-loop*
PST at their common cell index. -/
theorem openSystem_bachmanTamon_sameCell [Nonempty V]
    (P : EquitablePartition G I)
    {H : Matrix V V ℂ} (hH : Matrix.preservesCellUniform H P)
    {N : NoiseModel V} (hN : N.cellUniformSymmetric P)
    (u v : V) (huv : P.cells u = P.cells v) :
    OpenSystemPST H N u v ↔
      ∃ Hq : Matrix I I ℂ, OpenSystemPST Hq (N.quotient P) (P.cells u) (P.cells u) := by
  sorry

/-! ## 8. Open directions

Three concrete next-step directions left **open**:

1. **Optimal-noise-engineering for PST as a quotient optimisation
   problem.**  Reformulate "what Lindblad design maximises mid-time PST
   fidelity at fixed total rate?" as a convex optimisation on the
   *quotient* algebra of `P`, exploiting that the quotient is a small
   matrix (`I × I`) compared to the host (`V × V`).  Concretely: state
   the program

       max_{N : NoiseModel I, rate(N) = γ_total} PST_fidelity (Hhat, N) at time t,

   and observe by `lindbladGen_quotient_reduction` that this is exactly
   the original (host) optimisation restricted to `cellUniformSymmetric`
   noise.  The host-side optimisation is `dim(V)²`-dimensional; the
   quotient-side is `dim(I)²`-dimensional.

2. **Caruso speedup quantification.**  Express the noise-assisted-speedup
   conjecture as a *spectral perturbation* of the quotient Lindblad
   generator with a small symmetry-breaking term; quantify the optimal
   breaking score in terms of the closed-system dark-space spectral gap.

3. **Ghost-symmetry open analogue (Bick & Sclosa, Sec. 6).**  When a
   sequence of asymmetric finite host graphs converges to a graphon with
   non-trivial automorphisms, the *closed-system* dynamics inherit
   "ghosts" of those symmetries.  Conjecture: under cell-uniform-
   symmetric noise the open-system dynamics inherit the *same* ghosts.
   Concretely: extend `EquitablePartition` to graphons (`Graphplay.Graphon`)
   and lift the criterion of §1 to that setting.
-/

/-- **Existence of a zero-breaking cell-uniform-symmetric model.**  The trivial
(no-jump) noise model is cell-uniform-symmetric for every partition `P` and has
breaking score `0`.

HONEST RELABEL (was `quotient_optimisation_lower_bound`): the previous name
advertised an "optimisation lower bound", but the body merely exhibits the
trivial model as a witness of `cellUniformSymmetric ∧ BreakingScore = 0` — no
optimisation problem, objective, or comparison is stated.  This is the
zero-breaking feasibility witness only. -/
theorem exists_zeroBreaking_model
    (P : EquitablePartition G I) :
    ∃ N : NoiseModel V, N.cellUniformSymmetric P ∧ N.BreakingScore P = 0 := by
  refine ⟨NoiseModel.trivial V, ?_, ?_⟩
  · intro L hL; simp [NoiseModel.trivial] at hL
  · simp [NoiseModel.BreakingScore, NoiseModel.trivial]

/-- **The operator breaking score is nonnegative.**  `breakingScoreOp P L` is a
sum of squared norms, hence `≥ 0`.

HONEST RELABEL (was `caruso_leading_order_speedup`): the previous name advertised
a "leading-order speedup", but the body only proves `0 ≤ breakingScoreOp P L` — a
trivial nonnegativity fact about a sum of squares, with no speedup or
leading-order claim. -/
theorem breakingScoreOp_nonneg
    (P : EquitablePartition G I) (L : Matrix V V ℂ) :
    0 ≤ breakingScoreOp P L := by
  unfold breakingScoreOp
  refine Finset.sum_nonneg (fun x _ => Finset.sum_nonneg (fun y _ => ?_))
  split <;> positivity

/-- Sentinel statement for direction (3): the open-system "ghost of symmetry" —
zero breaking score — is exactly the condition that every positive-rate Lindblad
is block-diagonal w.r.t. the partition `P`.

CORRECTNESS FIX: the original conclusion `BreakingScore = 0 ↔ cellUniformSymmetric`
was FALSE (it reused the now-corrected `breakingScore_zero_iff_cellUniformSymmetric`);
we reduce instead to the genuinely-true `breakingScore_zero_iff_blockDiagonal`. -/
theorem ghost_symmetry_open_analogue
    (P : EquitablePartition G I) (N : NoiseModel V) :
    N.BreakingScore P = 0 ↔
      ∀ L ∈ N.lindblad_operators,
        (N.coherence_rates L : ℝ) = 0 ∨
          (∀ x y : V, P.cells x ≠ P.cells y → L x y = 0) :=
  breakingScore_zero_iff_blockDiagonal P N

end NoiseEquitable

end Graphplay
