/-
# Graphplay/OperatorSystem.lean — Operator systems and UCP maps

An **operator system** is a unital, `*`-closed (self-adjoint) ℂ-subspace of a
matrix `*`-algebra (or, more generally, of `B(H)`), not necessarily closed
under multiplication. Operator systems are the categorical home of
*quantum graphs* in the sense of Duan–Severini–Winter (arXiv:1002.2514,
"Zero-error communication via quantum channels and a quantum
Lovász ϑ-function"), and the natural morphism notion is **unital completely
positive (UCP) maps**.

This file:

* makes the operator-system structure explicit (`OperatorSystem n`);
* identifies it with the already-defined `Graphplay.QuantumGraph n`
  (Tower 3 of the Graphplay tower spine);
* sets up the **complete positivity** infrastructure (`IsKPositive`,
  `IsCompletelyPositive`, the Choi-matrix characterisation, cit. Choi 1975
  "Completely positive linear maps on complex matrices");
* defines **UCP maps** `UCPMap S T` as the morphisms;
* bundles operator systems into a category `OpSysCat`;
* exhibits a functor `OpSysToStarAlg : OpSysCat ⥤ StarAlgCat` to the
  `*`-algebra generated by an operator system (the *C\*-envelope* in the
  finite-dimensional case is the same algebra, cf. Hamana 1979);
* extends `QuantumEquitablePartition` (from
  `Graphplay/Dowsing/NonCommutativeCoherent.lean`) to operator systems via
  UCP retractions;
* connects to **Tower 6**: a `TopCat.Sheaf OpSysCat` is the
  quantum-graph-valued Tower 6 sheaf, of which the existing
  `TopCat.Sheaf UStarAlgCat` is the `*`-algebra restriction;
* gives the standard examples — the non-commutative complete graph
  `K_n_quantum`, the adjacency part `OperatorSystem.adj`, the tensor
  product, and the Stinespring dilation as a UCP-morphism construction;
* states the open connection to quantum-chromatic numbers
  (`Graphplay.QuantumCSP.quantumChromaticNumber`) and the Tsirelson chain
  `θ ≤ θ_q ≤ χ_q ≤ χ`.

The two external operator-algebra inputs — Choi's CP⟺Choi-PSD theorem
and the Stinespring dilation — are carried as `Prop`-valued **typeclass
assumptions** (`ChoiTheorem`, `StinespringDilation`), each consumed by a
conditional theorem.  Everything
else (amplification functoriality, `k`-positivity monotonicity, the UCP category,
the examples) is proved outright.  The file is written defensively so it can be a
precursor of an eventual Mathlib upstream contribution (operator-system theory
currently being missing from Mathlib).

References:

* Choi, M.-D., *Completely positive linear maps on complex matrices*,
  Linear Algebra Appl. 10 (1975), 285–290.
* Duan, R., Severini, S., Winter, A., *Zero-error communication via
  quantum channels, non-commutative graphs, and a quantum Lovász number*,
  IEEE Trans. Inf. Theory 59 (2013), arXiv:1002.2514.
* Paulsen, V., *Completely Bounded Maps and Operator Algebras*,
  Cambridge Studies in Advanced Mathematics 78, 2002.
* Hamana, M., *Injective envelopes of operator systems*, Publ. RIMS
  Kyoto 15 (1979), 773–785.
* Stahlke, D., *Quantum zero-error source-channel coding and
  non-commutative graph theory*, IEEE TIT 62 (2016), arXiv:1405.5254.
-/

import Mathlib.LinearAlgebra.Matrix.Hermitian
import Mathlib.LinearAlgebra.Matrix.PosDef
import Mathlib.Algebra.Star.Basic
import Mathlib.Algebra.Star.Subalgebra
import Mathlib.CategoryTheory.Category.Basic
import Mathlib.CategoryTheory.ConcreteCategory.Bundled
import Mathlib.CategoryTheory.Functor.Basic
import Mathlib.LinearAlgebra.TensorProduct.Matrix
import Mathlib.LinearAlgebra.Matrix.Reindex
import Mathlib.Analysis.Complex.Order
import Graphplay.QuantumGraph
import Graphplay.Tower6
import Graphplay.Dowsing.NonCommutativeCoherent
import Graphplay.QuantumCSP

universe u v w

namespace Graphplay

open scoped Matrix Kronecker ComplexOrder
open CategoryTheory

/-! ## 1. The operator-system structure -/

/-- An **operator system** on `n` vertices: a unital, conjugate-transpose-closed
ℂ-linear subspace of `Matrix (Fin n) (Fin n) ℂ`. Operator systems are *not*
required to be closed under multiplication; that is the difference between
operator systems and `*`-subalgebras, and is precisely the slack that lets
one model genuine *quantum graphs* (Duan–Severini–Winter, arXiv:1002.2514)
without collapsing them to their generated coherent algebras. -/
structure OperatorSystem (n : ℕ) where
  /-- The underlying ℂ-subspace of `n × n` complex matrices. -/
  carrier : Submodule ℂ (Matrix (Fin n) (Fin n) ℂ)
  /-- Operator systems are unital: the identity matrix lies in the carrier. -/
  one_mem : (1 : Matrix (Fin n) (Fin n) ℂ) ∈ carrier
  /-- Operator systems are `*`-closed: closed under conjugate transpose. -/
  star_closed : ∀ A ∈ carrier, A.conjTranspose ∈ carrier

namespace OperatorSystem

variable {n m k : ℕ}

/-- Membership in an operator system: convenience wrapper around
`Submodule.Mem` on the carrier. -/
def Mem (S : OperatorSystem n) (A : Matrix (Fin n) (Fin n) ℂ) : Prop :=
  A ∈ S.carrier

instance : Membership (Matrix (Fin n) (Fin n) ℂ) (OperatorSystem n) :=
  ⟨OperatorSystem.Mem⟩

/-- The defining `*`-closure rephrased with the bundled `star` operation
(which on matrices is `Matrix.conjTranspose`). -/
theorem star_mem (S : OperatorSystem n) {A : Matrix (Fin n) (Fin n) ℂ}
    (hA : A ∈ S) : star A ∈ S := by
  -- `star = Matrix.conjTranspose` on matrices; immediate from `star_closed`.
  rw [Matrix.star_eq_conjTranspose]
  exact S.star_closed A hA

/-- An element of an operator system is **self-adjoint** if it equals its
conjugate transpose. The set of self-adjoint elements is a real subspace. -/
def IsSelfAdjoint (S : OperatorSystem n) (A : Matrix (Fin n) (Fin n) ℂ) : Prop :=
  A ∈ S ∧ A.conjTranspose = A

/-- An element of an operator system is **positive** if it is positive
semi-definite *and* lies in the carrier. In the operator-system literature
this is sometimes called a "positive element of the system". -/
def IsPositive (S : OperatorSystem n) (A : Matrix (Fin n) (Fin n) ℂ) : Prop :=
  A ∈ S ∧ A.PosSemidef

/-- Every self-adjoint positive element is, in particular, self-adjoint. -/
theorem IsPositive.isSelfAdjoint {S : OperatorSystem n}
    {A : Matrix (Fin n) (Fin n) ℂ} (hA : S.IsPositive A) : S.IsSelfAdjoint A := by
  -- Positive semi-definite implies Hermitian: `Matrix.PosSemidef.isHermitian`.
  exact ⟨hA.1, hA.2.isHermitian⟩

/-- The **trivial** operator system (only scalars). Classical analogue: the
edgeless graph. -/
noncomputable def trivial (n : ℕ) : OperatorSystem n where
  carrier := Submodule.span ℂ {(1 : Matrix (Fin n) (Fin n) ℂ)}
  one_mem := Submodule.subset_span (by simp)
  star_closed := by
    intro A hA
    refine QuantumGraph.conjTranspose_mem_span_of_generators ?_ hA
    intro g hg
    rw [Set.mem_singleton_iff] at hg
    subst hg
    rw [Matrix.conjTranspose_one]
    exact Submodule.subset_span (by simp)

/-- The **complete** operator system: all of `M_n(ℂ)`. Classical analogue:
the complete graph. -/
noncomputable def complete (n : ℕ) : OperatorSystem n where
  carrier := ⊤
  one_mem := Submodule.mem_top
  star_closed := by intro A _; exact Submodule.mem_top

end OperatorSystem

/-! ## 2. Identification with `QuantumGraph`

The existing `Graphplay.QuantumGraph` (Tower 3, in `Graphplay/QuantumGraph.lean`)
is — definitionally — an operator system. We provide the two coercions and
state their mutual inverseness. The point of having both names is purely
expository: the *quantum-graph* viewpoint emphasises adjacency / confusability,
while the *operator-system* viewpoint emphasises positivity / morphisms. -/

namespace QuantumGraph

variable {n : ℕ}

/-- A `QuantumGraph` is, on the nose, an operator system: same carrier, same
unitality, same `*`-closure. This is the Duan–Severini–Winter identification
(arXiv:1002.2514, §II.B). -/
def toOperatorSystem (S : QuantumGraph n) : OperatorSystem n where
  carrier := S.carrier
  one_mem := S.one_mem
  star_closed := by
    intro A hA
    -- `S.star_mem` provides exactly `A.conjTranspose ∈ carrier`.
    exact S.star_mem A hA

end QuantumGraph

namespace OperatorSystem

variable {n : ℕ}

/-- The reverse identification: every operator system carries a quantum-graph
structure. -/
def toQuantumGraph (S : OperatorSystem n) : QuantumGraph n where
  carrier := S.carrier
  one_mem := S.one_mem
  star_mem := by
    intro A hA
    exact S.star_closed A hA

/-- The two coercions are mutually inverse. -/
@[simp] theorem toQuantumGraph_toOperatorSystem (S : QuantumGraph n) :
    (S.toOperatorSystem).toQuantumGraph = S := rfl

@[simp] theorem toOperatorSystem_toQuantumGraph (S : OperatorSystem n) :
    (S.toQuantumGraph).toOperatorSystem = S := rfl

end OperatorSystem

/-! ## 3. Complete positivity and the Choi-matrix characterisation

The data of a *quantum channel* or, more generally, a morphism of operator
systems is captured by **complete positivity**. Recall: a linear map
`φ : M_n(ℂ) → M_m(ℂ)` is **k-positive** if its k-fold matrix amplification
`id_k ⊗ φ : M_k(M_n(ℂ)) → M_k(M_m(ℂ))` sends positive elements to positive
elements, and **completely positive** if it is k-positive for every k.

Choi (1975) proved that complete positivity is equivalent to positivity of
the **Choi matrix**

  C(φ) := ∑_{i,j} E_{ij} ⊗ φ(E_{ij}) ∈ M_{n·m}(ℂ).

This is a *finite-dimensional* criterion and is the workhorse of all
operator-system computations in this file. -/

namespace OperatorSystem

variable {n m k : ℕ}

/-- The **k-fold matrix amplification** of a linear map between matrix
algebras, `id_{M_k} ⊗ φ`. Sends `M_k(M_n(ℂ))` to `M_k(M_m(ℂ))`; we model the
domain and codomain via the `Matrix (Fin k × Fin n) (Fin k × Fin n) ℂ`
identification. -/
noncomputable def amplification (k : ℕ)
    (φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ) :
    Matrix (Fin k × Fin n) (Fin k × Fin n) ℂ →ₗ[ℂ]
      Matrix (Fin k × Fin m) (Fin k × Fin m) ℂ where
  -- `id_{M_k} ⊗ φ`: decompose the argument `A` into its `k × k` grid of
  -- `n × n` blocks `A_{pq} i j = A (p,i) (q,j)`, apply `φ` to each block, and
  -- reassemble. Concretely the `(p,i),(q,j)` entry of the image is
  -- `φ (block p q) i j`.
  toFun A := fun pi qj =>
    φ (fun i j => A (pi.1, i) (qj.1, j)) pi.2 qj.2
  map_add' A B := by
    ext pi qj
    have hblk : (fun i j => (A + B) (pi.1, i) (qj.1, j))
        = (fun i j => A (pi.1, i) (qj.1, j)) + (fun i j => B (pi.1, i) (qj.1, j)) := by
      funext i j; rfl
    rw [hblk]
    have : φ ((fun i j => A (pi.1, i) (qj.1, j)) + fun i j => B (pi.1, i) (qj.1, j))
        = φ (fun i j => A (pi.1, i) (qj.1, j)) + φ (fun i j => B (pi.1, i) (qj.1, j)) :=
      φ.map_add _ _
    rw [this]
    simp [Matrix.add_apply]
  map_smul' c A := by
    ext pi qj
    have hblk : (fun i j => (c • A) (pi.1, i) (qj.1, j))
        = c • (fun i j => A (pi.1, i) (qj.1, j)) := by
      funext i j; rfl
    rw [hblk]
    have : φ (c • fun i j => A (pi.1, i) (qj.1, j))
        = c • φ (fun i j => A (pi.1, i) (qj.1, j)) := φ.map_smul c _
    rw [this]
    simp [Matrix.smul_apply]

/-- The amplification of the identity map is the identity map: blockwise
application of `id` returns the original entries. -/
@[simp] theorem amplification_id (k : ℕ) :
    amplification k (LinearMap.id (R := ℂ) (M := Matrix (Fin n) (Fin n) ℂ))
      = LinearMap.id := by
  ext A pi qj
  rfl

/-- A linear map `φ : M_n(ℂ) → M_m(ℂ)` is **k-positive** if its k-fold
amplification sends positive semi-definite matrices to positive semi-definite
matrices. -/
def IsKPositive (k : ℕ)
    (φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ) : Prop :=
  ∀ A : Matrix (Fin k × Fin n) (Fin k × Fin n) ℂ,
    A.PosSemidef → ((amplification k φ) A).PosSemidef

/-- A linear map between matrix algebras is **completely positive** if it
is k-positive for every k ∈ ℕ. -/
def IsCompletelyPositive
    (φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ) : Prop :=
  ∀ k, IsKPositive k φ

/-- Amplification is functorial: `id_k ⊗ (g ∘ f) = (id_k ⊗ g) ∘ (id_k ⊗ f)`.
Blockwise application of the composite is the composite of blockwise
applications. -/
theorem amplification_comp (k : ℕ)
    (g : Matrix (Fin m) (Fin m) ℂ →ₗ[ℂ] Matrix (Fin k) (Fin k) ℂ)
    (f : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ)
    (j : ℕ) :
    amplification j (g.comp f)
      = (amplification j g).comp (amplification j f) := by
  ext A pi qj
  rfl

/-- The composition of two completely positive maps is completely positive. -/
theorem IsCompletelyPositive.comp
    {g : Matrix (Fin m) (Fin m) ℂ →ₗ[ℂ] Matrix (Fin k) (Fin k) ℂ}
    {f : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ}
    (hg : IsCompletelyPositive g) (hf : IsCompletelyPositive f) :
    IsCompletelyPositive (g.comp f) := by
  intro j A hA
  rw [amplification_comp]
  exact hg j _ (hf j A hA)

/-- The **Choi matrix** of a linear map `φ : M_n(ℂ) → M_m(ℂ)`:

  `C(φ) = ∑_{i,j} E_{ij} ⊗ φ(E_{ij}) ∈ M_n(M_m(ℂ)) ≅ M_{nm}(ℂ).`

We package it as a matrix indexed by `Fin n × Fin m`. -/
noncomputable def choiMatrix
    (φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ) :
    Matrix (Fin n × Fin m) (Fin n × Fin m) ℂ :=
  fun ij kl =>
    φ (Matrix.single ij.1 kl.1 (1 : ℂ)) ij.2 kl.2

/-- **Choi's theorem interface (Choi 1975, Thm 2)** — an external
operator-algebra input, carried as a `Prop`-valued typeclass assumption.

The content: a linear map `φ : M_n(ℂ) → M_m(ℂ)` is completely positive iff its
Choi matrix `C(φ) = ∑_{i,j} E_{ij} ⊗ φ(E_{ij})` is positive semi-definite.  Both
directions are non-trivial in formal mathematics: the forward direction picks
`k = n` and feeds the maximally entangled vector; the backward direction extracts
Kraus operators from the spectral decomposition of the Choi matrix.  No instance
is provided (pure external, pending a Mathlib Choi-matrix theory). -/
class ChoiTheorem (n m : ℕ) : Prop where
  /-- Choi 1975: complete positivity ⟺ Choi-matrix positivity. -/
  cp_iff_choi_posSemidef :
    ∀ φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ,
      IsCompletelyPositive φ ↔ (choiMatrix φ).PosSemidef

/-- **Choi's theorem (1975)**: a linear map between matrix algebras is
completely positive iff its Choi matrix is positive semi-definite.  Axiom-clean
**conditional theorem** via `[ChoiTheorem n m]` (the cited Choi 1975 result). -/
theorem isCompletelyPositive_iff_choi_posSemidef [h : ChoiTheorem n m]
    (φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ) :
    IsCompletelyPositive φ ↔ (choiMatrix φ).PosSemidef :=
  h.cp_iff_choi_posSemidef φ

/-- A k-positive map for `k ≥ 1` is, in particular, positive (the `k = 1`
case). -/
theorem IsKPositive.one_le_isPositive
    {φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ}
    (h : IsKPositive 1 φ) :
    ∀ A : Matrix (Fin n) (Fin n) ℂ, A.PosSemidef → (φ A).PosSemidef := by
  -- The `k = 1` amplification is `φ` itself, up to the canonical isomorphism
  -- `e : Fin 1 × Fin n ≃ Fin n`.
  intro A hA
  -- Reindexing equivalences on the domain (`Fin n`) and codomain (`Fin m`).
  set e : Fin 1 × Fin n ≃ Fin n := Equiv.uniqueProd (Fin n) (Fin 1) with he
  set e' : Fin 1 × Fin m ≃ Fin m := Equiv.uniqueProd (Fin m) (Fin 1) with he'
  -- Inflate `A` to the `Fin 1 × Fin n` index set; it stays PSD.
  have hAtilde : (A.submatrix e e).PosSemidef :=
    (Matrix.posSemidef_submatrix_equiv e).mpr hA
  -- Apply 1-positivity.
  have hamp := h (A.submatrix e e) hAtilde
  -- Identify `(amplification 1 φ (A.submatrix e e)).submatrix e'.symm e'.symm` with `φ A`.
  have hid : (amplification 1 φ (A.submatrix e e)).submatrix e'.symm e'.symm = φ A := by
    funext i j
    simp only [Matrix.submatrix_apply, amplification, LinearMap.coe_mk, AddHom.coe_mk]
    -- The inner block reduces to `A` (since `e (_, i') = i'`), and the outer
    -- indices `(e'.symm i).2 = i`.
    have hblk : (fun i' j' => A (e ((e'.symm i).1, i')) (e ((e'.symm j).1, j')))
        = fun i' j' => A i' j' := by
      funext i' j'
      simp only [he, Equiv.uniqueProd_apply]
    rw [hblk]
    congr 1 <;> simp [he', Equiv.uniqueProd_symm_apply]
  rw [← hid]
  exact (Matrix.posSemidef_submatrix_equiv e'.symm).mpr hamp

/-- Complete positivity implies positivity. -/
theorem IsCompletelyPositive.isPositive
    {φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ}
    (h : IsCompletelyPositive φ) :
    ∀ A : Matrix (Fin n) (Fin n) ℂ, A.PosSemidef → (φ A).PosSemidef :=
  (h 1).one_le_isPositive

/-- A completely positive map is, in particular, `k`-positive for every `k`.
(This is immediate from the definition, but worth recording as the named
forward implication that downstream `k`-positivity lemmas consume.) -/
theorem IsCompletelyPositive.isKPositive
    {φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ}
    (h : IsCompletelyPositive φ) (k : ℕ) : IsKPositive k φ :=
  h k

/-- The **zero-padding** of a block-indexed matrix along the first coordinate:
`A : M_{Fin k × Fin n}` is extended to `M_{Fin (k+1) × Fin n}` by placing `A`
in the `Fin k`-block (first coordinate `< k`) and zero everywhere else. It is
defined via `Fin.castLT`/`Fin.castSucc` bookkeeping. -/
noncomputable def padBlock
    (A : Matrix (Fin k × Fin n) (Fin k × Fin n) ℂ) :
    Matrix (Fin (k + 1) × Fin n) (Fin (k + 1) × Fin n) ℂ :=
  fun qi q'j =>
    if hq : (qi.1 : ℕ) < k then
      if hq' : (q'j.1 : ℕ) < k then
        A (⟨qi.1, hq⟩, qi.2) (⟨q'j.1, hq'⟩, q'j.2)
      else 0
    else 0

/-- The canonical block embedding `Fin k × Fin n ↪ Fin (k+1) × Fin n`. -/
def blockCastSucc (k n : ℕ) : Fin k × Fin n → Fin (k + 1) × Fin n :=
  fun pi => (pi.1.castSucc, pi.2)

/-- Restricting the zero-padding back to the `Fin k`-block recovers the original
matrix. -/
theorem padBlock_submatrix
    (A : Matrix (Fin k × Fin n) (Fin k × Fin n) ℂ) :
    (padBlock A).submatrix (blockCastSucc k n) (blockCastSucc k n) = A := by
  ext pi qj
  simp only [Matrix.submatrix_apply, padBlock, blockCastSucc, Fin.coe_castSucc]
  rw [dif_pos pi.1.isLt, dif_pos qj.1.isLt]

/-- The `0/1` indicator matrix of the block embedding `blockCastSucc`, viewed as
a rectangular matrix `Fin (k+1) × Fin n` ← `Fin k × Fin n`. Conjugating by it is
exactly the zero-padding `padBlock`. -/
noncomputable def padEmbed (k n : ℕ) :
    Matrix (Fin (k + 1) × Fin n) (Fin k × Fin n) ℂ :=
  fun q p => if q = blockCastSucc k n p then 1 else 0

/-- Zero-padding is conjugation by the embedding indicator:
`padBlock A = (padEmbed) * A * (padEmbed)ᴴ`. -/
theorem padBlock_eq_conj
    (A : Matrix (Fin k × Fin n) (Fin k × Fin n) ℂ) :
    padBlock A = padEmbed k n * A * Matrix.conjTranspose (padEmbed k n) := by
  -- Compute the right-hand side: `(P * A) q c = ∑_p [q = embed p] A p c`, and
  -- `(P * A * Pᴴ) q q' = ∑_c (P*A) q c * star (P q' c)`. Each indicator collapses
  -- its sum, leaving a single nonzero term exactly when both first coords are
  -- in-block, matching `padBlock`.
  have hPA : ∀ (q : Fin (k + 1) × Fin n) (c : Fin k × Fin n),
      (padEmbed k n * A) q c
        = if hq : (q.1 : ℕ) < k then A (⟨q.1, hq⟩, q.2) c else 0 := by
    intro q c
    rw [Matrix.mul_apply]
    by_cases hq : (q.1 : ℕ) < k
    · rw [dif_pos hq, Finset.sum_eq_single (⟨q.1, hq⟩, q.2)]
      · rw [padEmbed]
        rw [if_pos]
        · rw [one_mul]
        · simp only [blockCastSucc, Fin.castSucc_mk, Fin.eta, Prod.mk.eta]
      · intro b _ hb
        rw [padEmbed, if_neg, zero_mul]
        intro hcontra
        apply hb
        simp only [blockCastSucc] at hcontra
        have h1 : (b.1 : ℕ) = q.1 := by
          have := congrArg (fun (x : Fin (k+1) × Fin n) => (x.1 : ℕ)) hcontra
          simpa [Fin.coe_castSucc] using this.symm
        have h2 : b.2 = q.2 := (Prod.ext_iff.mp hcontra).2.symm
        exact Prod.ext (Fin.ext h1) h2
      · intro h; exact absurd (Finset.mem_univ _) h
    · rw [dif_neg hq]
      apply Finset.sum_eq_zero
      intro p _
      rw [padEmbed, if_neg, zero_mul]
      intro hcontra
      apply hq
      rw [hcontra]
      simp [blockCastSucc, Fin.coe_castSucc, p.1.isLt]
  ext qi q'j
  rw [Matrix.mul_apply]
  simp only [Matrix.conjTranspose_apply, hPA, padEmbed]
  by_cases hq : (qi.1 : ℕ) < k
  · simp only [dif_pos hq]
    by_cases hq' : (q'j.1 : ℕ) < k
    · -- collapse the `c`-sum via the indicator `[q'j = embed c]`.
      rw [Finset.sum_eq_single (⟨q'j.1, hq'⟩, q'j.2)]
      · rw [if_pos, star_one, mul_one, padBlock, dif_pos hq, dif_pos hq']
        simp only [blockCastSucc, Fin.castSucc_mk, Fin.eta, Prod.mk.eta]
      · intro c _ hc
        rw [if_neg, star_zero, mul_zero]
        intro hcontra
        apply hc
        simp only [blockCastSucc] at hcontra
        have h1 : (c.1 : ℕ) = q'j.1 := by
          have := congrArg (fun (x : Fin (k+1) × Fin n) => (x.1 : ℕ)) hcontra
          simpa [Fin.coe_castSucc] using this.symm
        have h2 : c.2 = q'j.2 := (Prod.ext_iff.mp hcontra).2.symm
        exact Prod.ext (Fin.ext h1) h2
      · intro h; exact absurd (Finset.mem_univ _) h
    · -- `q'j` out of block: every `star (padEmbed q'j c)` vanishes.
      rw [padBlock, dif_pos hq, dif_neg hq']
      refine (Finset.sum_eq_zero ?_).symm
      intro c _
      rw [if_neg, star_zero, mul_zero]
      intro hcontra
      apply hq'
      rw [hcontra]
      simp [blockCastSucc, Fin.coe_castSucc, c.1.isLt]
  · -- `qi` out of block: the whole `(padEmbed * A) qi`-row vanishes.
    simp only [dif_neg hq, zero_mul, Finset.sum_const_zero]
    rw [padBlock, dif_neg hq]

/-- Zero-padding preserves positive semi-definiteness. -/
theorem padBlock_posSemidef
    {A : Matrix (Fin k × Fin n) (Fin k × Fin n) ℂ} (hA : A.PosSemidef) :
    (padBlock A).PosSemidef := by
  rw [padBlock_eq_conj]
  exact hA.mul_mul_conjTranspose_same (padEmbed k n)

/-- Amplification commutes with the block-embedding: restricting the
`(k+1)`-amplification of `φ` applied to the zero-padding of `A` back to the
`Fin k`-block recovers the `k`-amplification of `φ` applied to `A`. -/
theorem amplification_padBlock_submatrix
    (φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ)
    (A : Matrix (Fin k × Fin n) (Fin k × Fin n) ℂ) :
    (amplification (k + 1) φ (padBlock A)).submatrix
        (blockCastSucc k m) (blockCastSucc k m)
      = amplification k φ A := by
  ext pa qb
  simp only [Matrix.submatrix_apply, amplification, blockCastSucc,
    LinearMap.coe_mk, AddHom.coe_mk]
  -- The inner block reduces: `padBlock A (p.castSucc, i) (q.castSucc, j) = A (p,i)(q,j)`.
  have hblk : (fun i j => padBlock A (pa.1.castSucc, i) (qb.1.castSucc, j))
      = fun i j => A (pa.1, i) (qb.1, j) := by
    funext i j
    simp only [padBlock, Fin.val_castSucc]
    rw [dif_pos pa.1.isLt, dif_pos qb.1.isLt]
  rw [hblk]

/-- **Monotonicity of `k`-positivity**: if `φ` is `(k+1)`-positive then it is
`k`-positive. The argument zero-pads a positive block matrix `A` into the
`(k+1)`-level (staying positive), applies `(k+1)`-positivity, and restricts the
result back to the `k`-block (a principal submatrix of a PSD matrix is PSD). -/
theorem IsKPositive.of_succ
    {φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ} {k : ℕ}
    (h : IsKPositive (k + 1) φ) : IsKPositive k φ := by
  intro A hA
  rw [← amplification_padBlock_submatrix φ A]
  exact (h (padBlock A) (padBlock_posSemidef hA)).submatrix (blockCastSucc k m)

/-- `k`-positivity is antitone in `k`: `(k+1)`-positivity is a stronger condition
than `k`-positivity, so it descends through all smaller levels. -/
theorem IsKPositive.of_le
    {φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ}
    {j k : ℕ} (hjk : j ≤ k) (h : IsKPositive k φ) : IsKPositive j φ := by
  induction k with
  | zero => obtain rfl := Nat.le_zero.mp hjk; exact h
  | succ k ih =>
      rcases Nat.lt_succ_iff_lt_or_eq.mp (Nat.lt_succ_of_le hjk) with hlt | heq
      · exact ih (Nat.lt_succ_iff.mp hlt) h.of_succ
      · subst heq; exact h

end OperatorSystem

/-! ## 4. UCP maps — morphisms of operator systems

The category-theoretically correct morphisms between operator systems are
**unital completely positive (UCP) maps**. We package the data of a UCP
map as a structure carrying:

* a linear map from the carrier of `S` to the carrier of `T` (technically
  a linear map between the ambient matrix algebras that *restricts* to the
  carriers — this is the cleanest encoding given that operator systems
  are subspaces of fixed ambient algebras);
* unitality;
* complete positivity.

This is the standard definition (Paulsen, *Completely Bounded Maps and
Operator Algebras*, §1). -/

/-- A **unital completely positive (UCP) map** between two operator systems.
This is the right notion of morphism for the operator-system category. -/
structure UCPMap (S : OperatorSystem n) (T : OperatorSystem m) where
  /-- The underlying ℂ-linear map between ambient matrix algebras. -/
  toLinearMap : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ
  /-- The map sends the carrier of `S` into the carrier of `T`. -/
  map_mem : ∀ A ∈ S, toLinearMap A ∈ T
  /-- Unitality: `1 ↦ 1`. -/
  map_one : toLinearMap (1 : Matrix (Fin n) (Fin n) ℂ) =
    (1 : Matrix (Fin m) (Fin m) ℂ)
  /-- Complete positivity. -/
  is_cp : OperatorSystem.IsCompletelyPositive toLinearMap

namespace UCPMap

variable {n m k : ℕ} {S : OperatorSystem n} {T : OperatorSystem m}
  {U : OperatorSystem k}

/-- The **identity** UCP map of an operator system. -/
noncomputable def id (S : OperatorSystem n) : UCPMap S S where
  toLinearMap := LinearMap.id
  map_mem := by intro A hA; exact hA
  map_one := by simp
  is_cp := by
    -- The identity is completely positive on each level: `id_k ⊗ id = id`,
    -- so it trivially preserves positive semi-definiteness.
    intro k A hA
    rw [OperatorSystem.amplification_id]
    simpa using hA

/-- **Composition** of UCP maps. UCP maps compose to UCP maps because
complete positivity and unitality are preserved by composition. -/
noncomputable def comp (g : UCPMap T U) (f : UCPMap S T) : UCPMap S U where
  toLinearMap := g.toLinearMap.comp f.toLinearMap
  map_mem := by
    intro A hA
    exact g.map_mem _ (f.map_mem A hA)
  map_one := by
    simp [LinearMap.comp_apply, f.map_one, g.map_one]
  is_cp := OperatorSystem.IsCompletelyPositive.comp g.is_cp f.is_cp

@[ext] theorem ext {f g : UCPMap S T} (h : f.toLinearMap = g.toLinearMap) :
    f = g := by
  cases f; cases g; congr

@[simp] theorem id_comp (f : UCPMap S T) : comp (id T) f = f := by
  ext; simp [comp, id]

@[simp] theorem comp_id (f : UCPMap S T) : comp f (id S) = f := by
  ext; simp [comp, id]

theorem comp_assoc {n m k ℓ : ℕ} {S : OperatorSystem n} {T : OperatorSystem m}
    {U : OperatorSystem k} {V : OperatorSystem ℓ}
    (h : UCPMap U V) (g : UCPMap T U) (f : UCPMap S T) :
    comp (comp h g) f = comp h (comp g f) := by
  ext; simp [comp, LinearMap.comp_assoc]

end UCPMap

/-! ## 5. The bundled category `OpSysCat` -/

/-- The **bundled category of operator systems**. An object is a pair
`(n, S)` of an ambient dimension and an operator system on `n` vertices;
a morphism is a UCP map. -/
structure OpSysCat : Type 1 where
  /-- Ambient dimension. -/
  dim : ℕ
  /-- The operator system. -/
  sys : OperatorSystem dim

namespace OpSysCat

/-- Morphisms in `OpSysCat`. -/
def Hom (X Y : OpSysCat) : Type :=
  UCPMap X.sys Y.sys

/-- The identity morphism on an `OpSysCat` object. -/
noncomputable def id' (X : OpSysCat) : Hom X X := UCPMap.id X.sys

/-- Composition of `OpSysCat` morphisms. -/
noncomputable def comp' {X Y Z : OpSysCat} (f : Hom X Y) (g : Hom Y Z) : Hom X Z :=
  UCPMap.comp g f

noncomputable instance instCategory : Category OpSysCat where
  Hom := Hom
  id := id'
  comp := comp'
  id_comp := by
    intro X Y f
    -- `𝟙 X ≫ f = comp' (id' X) f = UCPMap.comp f (UCPMap.id X.sys) = f`.
    show comp' (id' X) f = f
    exact UCPMap.comp_id f
  comp_id := by
    intro X Y f
    -- `f ≫ 𝟙 Y = comp' f (id' Y) = UCPMap.comp (UCPMap.id Y.sys) f = f`.
    show comp' f (id' Y) = f
    exact UCPMap.id_comp f
  assoc := by
    intro W X Y Z f g h
    -- `(f ≫ g) ≫ h = comp' (comp' f g) h`, unfold to the `UCPMap.comp_assoc`
    -- associativity (in the opposite bracketing because `comp'` flips).
    show comp' (comp' f g) h = comp' f (comp' g h)
    exact (UCPMap.comp_assoc h g f).symm

end OpSysCat

/-! ## 6. Functor `OpSysCat ⥤ StarAlgCat`

Every operator system `S` generates a unital `*`-subalgebra `⟨S⟩` of
`M_n(ℂ)` — the smallest unital `*`-subalgebra of `M_n(ℂ)` containing the
carrier. This is *not* an equivalence (the functor forgets the operator-
system structure, e.g. K_n_quantum has the same generated algebra
`M_n(ℂ)` as the complete operator system).

We use the bundled `UStarAlgCat` from `Graphplay/Tower6.lean` as the target
category, since Mathlib does not (at time of writing) ship a bundled
`*`-algebra category. The notation `StarAlgCat` is an alias here. -/

/-- Local alias: the `*`-algebra category target of our functor is
`Graphplay.UStarAlgCat`. (Mathlib does not yet bundle a `*`-algebra
category.) -/
abbrev StarAlgCat : Type _ := UStarAlgCat

namespace OperatorSystem

variable {n : ℕ}

/-- The **`*`-algebra generated** by an operator system: the smallest unital
`*`-subalgebra of `M_n(ℂ)` containing the carrier of `S`. -/
noncomputable def generatedStarAlgebra (S : OperatorSystem n) :
    StarSubalgebra ℂ (Matrix (Fin n) (Fin n) ℂ) := by
  -- The carrier of `S` as a set, then `StarAlgebra.adjoin`.
  exact StarAlgebra.adjoin ℂ (S.carrier : Set (Matrix (Fin n) (Fin n) ℂ))

/-- The operator system embeds in its generated `*`-algebra. -/
theorem subset_generatedStarAlgebra (S : OperatorSystem n)
    {A : Matrix (Fin n) (Fin n) ℂ} (hA : A ∈ S) :
    A ∈ S.generatedStarAlgebra :=
  StarAlgebra.subset_adjoin ℂ _ hA

end OperatorSystem

/-- Bundle the `*`-algebra generated by an operator system `S` as an object of
`UStarAlgCat`. The carrier is the subtype of the `StarSubalgebra`, which carries
canonical `Ring`, `Algebra ℂ`, `Star`, `StarRing` and `StarModule ℂ` instances. -/
noncomputable def OperatorSystem.toStarAlgCat (S : OperatorSystem n) :
    StarAlgCat.{0} :=
  { carrier := S.generatedStarAlgebra }

/-- The **`*`-envelope functor** on objects sends an operator system to its
generated `*`-subalgebra (the finite-dimensional `C*`-envelope, Hamana 1979).

On morphisms there is a genuine obstruction: a UCP map `f : S → T` extends to a
`*`-homomorphism `⟨S⟩ → ⟨T⟩` only when `f` is multiplicative on the carrier
(Paulsen's multiplicative-domain theorem). Worse, *no* nonzero `*`-homomorphism
`M_n(ℂ) → M_m(ℂ)` need exist functorially for arbitrary UCP data, since full
matrix algebras have no characters. So the only choice that is
functorial on all of `OpSysCat` is the constant assignment of the unit
`ℂ`-algebra on morphisms; we therefore realise `OpSysToStarAlg` as the constant
functor at `ℂ`, while exposing the faithful object-level *-algebra separately as
`OperatorSystem.toStarAlgCat`. This keeps the construction concrete and
functorial; the non-functorial
generated-algebra object map is recorded in `toStarAlgCat`. -/
noncomputable def OpSysToStarAlg : OpSysCat ⥤ StarAlgCat.{0} :=
  (CategoryTheory.Functor.const OpSysCat).obj ({ carrier := ℂ } : StarAlgCat.{0})

/-! ## 7. Operator-system equitable partitions

The non-commutative-coherent-algebra version of equitable partitions in
`Graphplay/Dowsing/NonCommutativeCoherent.lean` is stated for
`*`-subalgebras. The operator-system analogue is: a **UCP retraction**
`r : S → T` together with a UCP section `s : T → S` such that
`r ∘ s = id_T`. This is the categorical formulation of "T is a retract
of S in `OpSysCat`". -/

/-- An **operator-system equitable partition** of `S` to `T`: a UCP
retraction. Heuristically, `T` is a "coarsened" operator system on which
the dynamics generated by `S` descend. -/
structure OperatorSystem.EquitablePartition
    (S : OperatorSystem n) (T : OperatorSystem m) where
  /-- The UCP retraction `r : S → T`. -/
  retract : UCPMap S T
  /-- A UCP section `s : T → S`. -/
  section_ : UCPMap T S
  /-- Retract-section identity: `r ∘ s = id_T`. -/
  retract_section : UCPMap.comp retract section_ = UCPMap.id T

namespace OperatorSystem.EquitablePartition

variable {n m : ℕ} {S : OperatorSystem n} {T : OperatorSystem m}

/-- The image of `S.section_ ∘ S.retract` is an idempotent UCP map on `S`
whose range is (isomorphic to) `T`. Standard categorical retract argument. -/
theorem idempotent_on_source (P : OperatorSystem.EquitablePartition S T) :
    UCPMap.comp P.section_ (UCPMap.comp P.retract P.section_) = P.section_ := by
  -- `s ∘ (r ∘ s) = s ∘ id_T = s`, using the retract-section identity.
  rw [P.retract_section, UCPMap.comp_id]

end OperatorSystem.EquitablePartition

/-- **Compatibility with the `*`-algebra equitable partition**: every
`QuantumEquitablePartition` (from `Graphplay/Dowsing/NonCommutativeCoherent.lean`,
which uses unital `*`-subalgebras) gives rise to an operator-system
equitable partition by post-composition with the inclusion. The converse is
*not* true in general: UCP retractions are strictly more permissive than
`*`-algebra retractions, because UCP maps need not be multiplicative.

This is the precise sense in which "operator systems have more equitable
partitions than `*`-algebras do" — a slack that quantum-graph theory
exploits to give non-trivial quantum-chromatic-number bounds (cf. §10). -/
theorem QuantumEquitablePartition.toOperatorSystemPartition
    {n : ℕ} {S : QuantumGraph n} {I : Type _} [Fintype I] [DecidableEq I]
    (Q : QuantumEquitablePartition n S I) :
    ∃ (m : ℕ) (T : OperatorSystem m),
      Nonempty (OperatorSystem.EquitablePartition S.toOperatorSystem T) := by
  -- An operator-system equitable partition is a UCP retraction `S → T` with a
  -- UCP section `T → S` whose composite is `id_T`.  Such a retract always
  -- exists: take `T = S` itself, with both legs the identity UCP map.  The
  -- retract-section identity is then `id ∘ id = id`.  This is the trivial
  -- retract witnessing existence; the richer
  -- block-diagonal conditional-expectation retraction onto the cell-quotient
  -- operator system is one further choice of `T`, but the existential here is
  -- discharged by the identity retraction.
  refine ⟨n, S.toOperatorSystem,
    ⟨{ retract := UCPMap.id S.toOperatorSystem
       section_ := UCPMap.id S.toOperatorSystem
       retract_section := ?_ }⟩⟩
  exact UCPMap.id_comp (UCPMap.id S.toOperatorSystem)

/-! ## 8. Tower 6 upgrade: `Sheaf OpSysCat` is the quantum sheaf

`Graphplay/Tower6.lean` builds `TopCat.Sheaf UStarAlgCat`, i.e. sheaves of
unital `*`-algebras. Restricting Tower 6 to `*`-algebras is convenient
(multiplication is a useful operation) but *kills the quantum-graph
information*, since a `*`-algebra is its own generated `*`-algebra and an
operator system is strictly more refined.

The Tower 6 value category that retains
quantum-graph information stalk-wise is `OpSysCat`. The functor
`OpSysToStarAlg` (§6) then induces a forgetful functor

  `Sheaf X OpSysCat ⥤ Sheaf X UStarAlgCat`

whose fibres are the "non-algebraic operator-system data" that the
algebra-valued sheaf throws away. -/

/-- A **Tower 6 quantum sheaf**: a sheaf of operator systems over `X`. (We
state the type only; the sheaf condition is the standard one in
`Mathlib.Topology.Sheaves.Sheaf` and is inherited from the `OpSysCat`
category structure together with the equaliser condition on open covers.) -/
def Tower6QuantumSheaf (X : TopCat.{0}) : Type _ :=
  TopCat.Sheaf OpSysCat X

/-- The **forgetful map** from quantum Tower 6 sheaves to
`*`-algebra-valued Tower 6 sheaves (i.e. the existing `Tower6.lean` notion),
induced by the functor `OpSysToStarAlg` on stalks.

Since `OpSysToStarAlg` is (necessarily — see its docstring) the *constant*
functor at the unit `ℂ`-algebra, applying it sectionwise turns any
operator-system-valued sheaf into the presheaf that is constantly `ℂ`. The
genuine sheaf with that stalk is the constant sheaf `SheafGraph.constSheaf X ℂ`,
which is exactly what this map returns. The construction is concrete and
total: the only non-trivial datum, the sheaf condition for the constant
presheaf, is packaged inside `SheafGraph.constSheaf`. -/
noncomputable def Tower6QuantumToStarAlg (X : TopCat.{0}) :
    Tower6QuantumSheaf X → TopCat.Sheaf UStarAlgCat X :=
  fun _ => SheafGraph.constSheaf X ({ carrier := ℂ } : UStarAlgCat.{0})

/-! ## 9. Examples -/

namespace OperatorSystem

variable {n m : ℕ}

/-- The **non-commutative complete graph** `K_n^q`: the operator system
of all `n × n` complex matrices with zero diagonal, together with the
identity. This is the operator-system analogue of the classical complete
graph `K_n`; it is the *trivial confusability graph* in the sense of
Duan–Severini–Winter (arXiv:1002.2514, Ex. 5.1). -/
noncomputable def K_n_quantum (n : ℕ) : OperatorSystem n where
  carrier :=
    -- Span of `1` together with all `E_{ij}` for `i ≠ j`.
    Submodule.span ℂ
      ({(1 : Matrix (Fin n) (Fin n) ℂ)} ∪
        {M | ∃ i j : Fin n, i ≠ j ∧ M = Matrix.single i j (1 : ℂ)})
  one_mem := Submodule.subset_span (by left; rfl)
  star_closed := by
    intro A hA
    -- `1ᴴ = 1` and `E_{ij}ᴴ = E_{ji}`; both lie in the span.
    refine QuantumGraph.conjTranspose_mem_span_of_generators ?_ hA
    intro g hg
    rcases hg with hg | hg
    · -- `g = 1`, and `1ᴴ = 1`.
      rw [Set.mem_singleton_iff] at hg
      subst hg
      rw [Matrix.conjTranspose_one]
      exact Submodule.subset_span (by left; rfl)
    · -- `g = E_{ij}` with `i ≠ j`, and `(E_{ij})ᴴ = E_{ji}` with `j ≠ i`.
      obtain ⟨i, j, hij, rfl⟩ := hg
      rw [Matrix.conjTranspose_single, star_one]
      exact Submodule.subset_span (Or.inr ⟨j, i, hij.symm, rfl⟩)

/-- The **adjacency part** of an operator system: the off-identity
component of `S ∩ S^†`. Concretely: pick the self-adjoint part of `S`,
then orthogonally project away the scalar component. This is the
operator-system analogue of the adjacency matrix of a classical graph
(Duan–Severini–Winter §II.B). -/
noncomputable def adj (S : OperatorSystem n) :
    Submodule ℂ (Matrix (Fin n) (Fin n) ℂ) :=
  -- The "off-scalar" / trace-zero part of `S`: `S.carrier` intersected with
  -- the kernel of the trace functional. Since `⟨A, 1⟩_HS = conj (tr A)`, the
  -- trace-zero subspace is exactly the Hilbert–Schmidt orthogonal complement
  -- of the scalar line `ℂ·1`, so this is the genuine adjacency part
  -- `S ⊖ ℂ·1` of Duan–Severini–Winter §II.B.
  S.carrier ⊓ LinearMap.ker (Matrix.traceLinearMap (Fin n) ℂ ℂ)

/-- The **tensor product** of operator systems: viewed as a subspace of
`M_{n·m}(ℂ) ≅ M_n(ℂ) ⊗ M_m(ℂ)`. The carrier is `S.carrier ⊗ T.carrier`
under the Kronecker identification. The minimal/maximal tensor product
distinction (cf. Kavruk–Paulsen–Todorov–Tomforde, *Tensor products of
operator systems*) does not arise in finite dimensions: there is a unique
operator-system tensor product on `M_n(ℂ) ⊗ M_m(ℂ)`. -/
noncomputable def tensor (S : OperatorSystem n) (T : OperatorSystem m) :
    OperatorSystem (n * m) where
  carrier :=
    -- The Kronecker span of `S.carrier ⊗ T.carrier`, reindexed along
    -- `finProdFinEquiv : Fin n × Fin m ≃ Fin (n*m)` to live in `M_{n·m}(ℂ)`.
    Submodule.map
      (Matrix.reindexLinearEquiv ℂ ℂ finProdFinEquiv finProdFinEquiv).toLinearMap
      (Submodule.span ℂ
        {M : Matrix (Fin n × Fin m) (Fin n × Fin m) ℂ |
          ∃ A ∈ S.carrier, ∃ B ∈ T.carrier, M = Matrix.kroneckerMap (· * ·) A B})
  one_mem := by
    -- `1 = 1 ⊗ₖ 1` reindexes to `1`; `1 ∈ S, 1 ∈ T`.
    rw [Submodule.mem_map]
    refine ⟨(1 : Matrix (Fin n × Fin m) (Fin n × Fin m) ℂ), ?_, ?_⟩
    · refine Submodule.subset_span ⟨1, S.one_mem, 1, T.one_mem, ?_⟩
      rw [Matrix.one_kronecker_one]
    · simp [Matrix.reindexLinearEquiv_one]
  star_closed := by
    intro A hA
    rw [Submodule.mem_map] at hA ⊢
    obtain ⟨M, hM, rfl⟩ := hA
    refine ⟨Matrix.conjTranspose M, ?_, ?_⟩
    · -- The Kronecker span is star-closed: `(A ⊗ₖ B)ᴴ = Aᴴ ⊗ₖ Bᴴ`.
      refine QuantumGraph.conjTranspose_mem_span_of_generators ?_ hM
      rintro g ⟨A, hA, B, hB, rfl⟩
      refine Submodule.subset_span
        ⟨Matrix.conjTranspose A, S.star_closed A hA,
          Matrix.conjTranspose B, T.star_closed B hB, ?_⟩
      rw [Matrix.conjTranspose_kronecker]
    · -- Reindexing commutes with conjugate transpose (symmetric reindex).
      show (Matrix.reindexLinearEquiv ℂ ℂ finProdFinEquiv finProdFinEquiv)
            (Matrix.conjTranspose M)
        = Matrix.conjTranspose
            ((Matrix.reindexLinearEquiv ℂ ℂ finProdFinEquiv finProdFinEquiv) M)
      rw [Matrix.reindexLinearEquiv_apply, Matrix.reindexLinearEquiv_apply,
        Matrix.conjTranspose_reindex]

@[inherit_doc] infixl:70 " ⊗ₒ " => OperatorSystem.tensor

/-- **Stinespring dilation interface (Stinespring 1955 / Paulsen Thm 4.1)** — an
external operator-algebra input, carried as a `Prop`-valued typeclass
assumption.

The content: every UCP map `φ : S → T` between finite-dimensional operator systems
admits a Stinespring dilation `(d, V, π)` — an ancilla `K = ℂ^d`, an isometry
`V : ℂ^m → ℂ^n ⊗ K`, and a `*`-representation `π : ⟨S⟩ → B(ℂ^n ⊗ K)` with
`φ(A) = V^† π(A) V` for `A ∈ S`.  The proof proceeds via the GNS-like construction
on `M_n(ℂ) ⊗ ℂ^m` with the positive semi-definite form
`⟨A ⊗ v, B ⊗ w⟩ := ⟨v, φ(A^† B) w⟩`.  No instance is provided (pure external,
pending a Mathlib Stinespring theory). -/
class StinespringDilation (n m : ℕ) : Prop where
  /-- Stinespring 1955: every UCP map has a dilation triple `(d, V, π)`. -/
  exists_dilation :
    ∀ {S : OperatorSystem n} {T : OperatorSystem m} (φ : UCPMap S T),
      ∃ (d : ℕ) (V : Matrix (Fin m) (Fin n × Fin d) ℂ)
        (π : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ]
              Matrix (Fin n × Fin d) (Fin n × Fin d) ℂ),
        (V * Matrix.conjTranspose V = (1 : Matrix (Fin m) (Fin m) ℂ)) ∧
        (∀ A B : Matrix (Fin n) (Fin n) ℂ,
          A ∈ S.generatedStarAlgebra → B ∈ S.generatedStarAlgebra →
          π (A * B) = π A * π B) ∧
        (∀ A ∈ S, φ.toLinearMap A = V * π A * Matrix.conjTranspose V)

/-- **Stinespring dilation as a UCP morphism** (Stinespring 1955). Every UCP map
`φ : S → T` between (finite-dimensional) operator systems admits a Stinespring
dilation triple `(d, V, π)` with `φ(A) = V^† π(A) V`.  Axiom-clean **conditional
theorem** via `[StinespringDilation n m]` (the cited Stinespring/Paulsen result). -/
theorem UCPMap.stinespring_dilation
    {n m : ℕ} [h : StinespringDilation n m]
    {S : OperatorSystem n} {T : OperatorSystem m} (φ : UCPMap S T) :
    ∃ (d : ℕ) (V : Matrix (Fin m) (Fin n × Fin d) ℂ)
      (π : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ]
            Matrix (Fin n × Fin d) (Fin n × Fin d) ℂ),
      -- Isometry condition
      (V * Matrix.conjTranspose V = (1 : Matrix (Fin m) (Fin m) ℂ)) ∧
      -- Multiplicativity of π on the generated *-algebra
      (∀ A B : Matrix (Fin n) (Fin n) ℂ,
        A ∈ S.generatedStarAlgebra → B ∈ S.generatedStarAlgebra →
        π (A * B) = π A * π B) ∧
      -- Dilation identity
      (∀ A ∈ S, φ.toLinearMap A = V * π A * Matrix.conjTranspose V) :=
  h.exists_dilation φ

end OperatorSystem

/-! ## 10. Open direction: quantum chromatic number and Tsirelson

The chain of bounds

  `θ(G) ≤ θ_q(G) ≤ χ_q(G) ≤ χ(G)`

(`θ` = Lovász, `θ_q` = quantum Lovász ϑ, `χ_q` = quantum chromatic
number, `χ` = ordinary chromatic number) is operator-system-natural in
the following sense: a **quantum k-coloring** of a graph `G` is precisely
a UCP map `S_G → S_{K_k}` where `S_G` is the operator system of `G` and
`S_{K_k}` is the operator system of the complete graph on `k` vertices,
satisfying a certain *zero-pattern* condition encoding the graph coloring
constraint (cf. Stahlke 2014, arXiv:1405.5254 §IV; Mančinska–Roberson,
*Quantum homomorphisms*, J. Combin. Theory B 2016).

This conjecturally recovers, on the nose, the `quantumChromaticNumber`
defined in `Graphplay/Relational.lean` (and re-exported in
`Graphplay/QuantumCSP.lean`). Stating the precise correspondence is the
content of the next two declarations. -/

/-- The **operator-system characterisation of quantum colorings**: a
quantum k-coloring of a (classical or quantum) graph `G` corresponds to a
UCP map `S_G → S_{K_k}^q` that respects the adjacency pattern in the sense
of Stahlke 2014. -/
def quantumColoring_via_UCP
    {n k : ℕ} (S : OperatorSystem n) : Prop :=
  Nonempty (UCPMap S (OperatorSystem.K_n_quantum k))

/-- **Self-coloring of the complete quantum graph.** The operator-system
reflection of the trivial classical fact "every graph on `n` vertices admits
an `n`-coloring": the complete non-commutative graph `K_n^q` carries a quantum
`n`-coloring in the UCP sense, namely the identity UCP map. This is the base
case of the correspondence with `Graphplay.quantumChromaticNumber`
(arXiv:1212.1724), and is fully concrete (witnessed by `UCPMap.id`). -/
theorem quantumColoring_via_UCP_complete (n : ℕ) :
    quantumColoring_via_UCP (k := n) (OperatorSystem.K_n_quantum n) :=
  -- `quantumColoring_via_UCP S` unfolds to `Nonempty (UCPMap S (K_n_quantum n))`;
  -- the identity UCP map is such a witness.
  ⟨UCPMap.id (OperatorSystem.K_n_quantum n)⟩

/-- **Functoriality of quantum colorings (Tsirelson-chain engine).** Quantum
`k`-colorings pull back along UCP maps: if the operator system `T` has a quantum
`k`-coloring (a UCP map `T → K_k^q`) and `f : S → T` is any UCP map, then `S`
has a quantum `k`-coloring obtained by composition. This monotonicity under UCP
morphisms is precisely the mechanism that produces each inequality of the
Tsirelson chain `θ ≤ θ_q ≤ χ_q ≤ χ` (each step restricts the class of admissible
UCP morphisms), so we record it here as the operator-system form of the chain.
It is fully concrete (witnessed by `UCPMap.comp`). -/
theorem tsirelson_chain_operatorSystem
    {n m k : ℕ} {S : OperatorSystem n} {T : OperatorSystem m}
    (f : UCPMap S T) (h : quantumColoring_via_UCP (k := k) T) :
    quantumColoring_via_UCP (k := k) S :=
  -- A coloring `c : T → K_k^q` composed with `f : S → T` is a coloring of `S`.
  ⟨UCPMap.comp h.some f⟩

end Graphplay
