/-
# Graphplay/OperatorSystem.lean — Operator systems and UCP maps

An **operator system** is a unital, `*`-closed (self-adjoint) ℂ-subspace of a
matrix `*`-algebra (or, more generally, of `B(H)`), not necessarily closed
under multiplication. Operator systems are the categorical home of
*quantum graphs* in the sense of Duan–Severini–Winter (arXiv:1002.2514,
"Zero-error communication via quantum channels and a quantum
Lovász ϑ-function"), and the natural morphism notion is **unital completely
positive (UCP) maps**.

This file:

* makes the operator-system structure explicit (`OperatorSystem n`);
* identifies it with the already-defined `Graphplay.QuantumGraph n`
  (Tower 3 of the Graphplay tower spine);
* sets up the **complete positivity** infrastructure (`IsKPositive`,
  `IsCompletelyPositive`, the Choi-matrix characterisation, cit. Choi 1975
  "Completely positive linear maps on complex matrices");
* defines **UCP maps** `UCPMap S T` as the morphisms;
* bundles operator systems into a category `OpSysCat`;
* exhibits a functor `OpSysToStarAlg : OpSysCat ⥤ StarAlgCat` to the
  `*`-algebra generated by an operator system (the *C\*-envelope* in the
  finite-dimensional case is the same algebra, cf. Hamana 1979);
* extends `QuantumEquitablePartition` (from
  `Graphplay/Dowsing/NonCommutativeCoherent.lean`) to operator systems via
  UCP retractions;
* connects to **Tower 6**: a `TopCat.Sheaf OpSysCat` is the genuinely
  quantum-graph-valued Tower 6 sheaf, of which the existing
  `TopCat.Sheaf UStarAlgCat` is the `*`-algebra restriction;
* gives the standard examples — the non-commutative complete graph
  `K_n_quantum`, the adjacency part `OperatorSystem.adj`, the tensor
  product, and the Stinespring dilation as a UCP-morphism construction;
* states the open connection to quantum-chromatic numbers
  (`Graphplay.QuantumCSP.quantumChromaticNumber`) and the Tsirelson chain
  `θ ≤ θ_q ≤ χ_q ≤ χ`.

All proofs are `sorry`. The statements are written defensively so the file
can be a precursor of an eventual Mathlib upstream contribution
(operator-system theory currently being missing from Mathlib).

References:

* Choi, M.-D., *Completely positive linear maps on complex matrices*,
  Linear Algebra Appl. 10 (1975), 285–290.
* Duan, R., Severini, S., Winter, A., *Zero-error communication via
  quantum channels, non-commutative graphs, and a quantum Lovász number*,
  IEEE Trans. Inf. Theory 59 (2013), arXiv:1002.2514.
* Paulsen, V., *Completely Bounded Maps and Operator Algebras*,
  Cambridge Studies in Advanced Mathematics 78, 2002.
* Hamana, M., *Injective envelopes of operator systems*, Publ. RIMS
  Kyoto 15 (1979), 773–785.
* Stahlke, D., *Quantum zero-error source-channel coding and
  non-commutative graph theory*, IEEE TIT 62 (2016), arXiv:1405.5254.
-/

import Mathlib.LinearAlgebra.Matrix.Hermitian
import Mathlib.LinearAlgebra.Matrix.PosDef
import Mathlib.Algebra.Star.Basic
import Mathlib.Algebra.Star.Subalgebra
import Mathlib.CategoryTheory.Category.Basic
import Mathlib.CategoryTheory.ConcreteCategory.Bundled
import Mathlib.CategoryTheory.Functor.Basic
import Mathlib.LinearAlgebra.TensorProduct.Matrix
import Mathlib.Analysis.Complex.Order
import Graphplay.QuantumGraph
import Graphplay.Tower6
import Graphplay.Dowsing.NonCommutativeCoherent
import Graphplay.QuantumCSP

universe u v w

namespace Graphplay

open scoped Matrix Kronecker ComplexOrder
open CategoryTheory

/-! ## 1. The operator-system structure -/

/-- An **operator system** on `n` vertices: a unital, conjugate-transpose-closed
ℂ-linear subspace of `Matrix (Fin n) (Fin n) ℂ`. Operator systems are *not*
required to be closed under multiplication; that is the difference between
operator systems and `*`-subalgebras, and is precisely the slack that lets
one model genuine *quantum graphs* (Duan–Severini–Winter, arXiv:1002.2514)
without collapsing them to their generated coherent algebras. -/
structure OperatorSystem (n : ℕ) where
  /-- The underlying ℂ-subspace of `n × n` complex matrices. -/
  carrier : Submodule ℂ (Matrix (Fin n) (Fin n) ℂ)
  /-- Operator systems are unital: the identity matrix lies in the carrier. -/
  one_mem : (1 : Matrix (Fin n) (Fin n) ℂ) ∈ carrier
  /-- Operator systems are `*`-closed: closed under conjugate transpose. -/
  star_closed : ∀ A ∈ carrier, A.conjTranspose ∈ carrier

namespace OperatorSystem

variable {n m k : ℕ}

/-- Membership in an operator system: convenience wrapper around
`Submodule.Mem` on the carrier. -/
def Mem (S : OperatorSystem n) (A : Matrix (Fin n) (Fin n) ℂ) : Prop :=
  A ∈ S.carrier

instance : Membership (Matrix (Fin n) (Fin n) ℂ) (OperatorSystem n) :=
  ⟨OperatorSystem.Mem⟩

/-- The defining `*`-closure rephrased with the bundled `star` operation
(which on matrices is `Matrix.conjTranspose`). -/
theorem star_mem (S : OperatorSystem n) {A : Matrix (Fin n) (Fin n) ℂ}
    (hA : A ∈ S) : star A ∈ S := by
  -- `star = Matrix.conjTranspose` on matrices; immediate from `star_closed`.
  sorry

/-- An element of an operator system is **self-adjoint** if it equals its
conjugate transpose. The set of self-adjoint elements is a real subspace. -/
def IsSelfAdjoint (S : OperatorSystem n) (A : Matrix (Fin n) (Fin n) ℂ) : Prop :=
  A ∈ S ∧ A.conjTranspose = A

/-- An element of an operator system is **positive** if it is positive
semi-definite *and* lies in the carrier. In the operator-system literature
this is sometimes called a "positive element of the system". -/
def IsPositive (S : OperatorSystem n) (A : Matrix (Fin n) (Fin n) ℂ) : Prop :=
  A ∈ S ∧ A.PosSemidef

/-- Every self-adjoint positive element is, in particular, self-adjoint. -/
theorem IsPositive.isSelfAdjoint {S : OperatorSystem n}
    {A : Matrix (Fin n) (Fin n) ℂ} (hA : S.IsPositive A) : S.IsSelfAdjoint A := by
  -- Positive semi-definite implies Hermitian: `Matrix.PosSemidef.isHermitian`.
  sorry

/-- The **trivial** operator system (only scalars). Classical analogue: the
edgeless graph. -/
noncomputable def trivial (n : ℕ) : OperatorSystem n where
  carrier := Submodule.span ℂ {(1 : Matrix (Fin n) (Fin n) ℂ)}
  one_mem := Submodule.subset_span (by simp)
  star_closed := by
    intro A hA
    sorry

/-- The **complete** operator system: all of `M_n(ℂ)`. Classical analogue:
the complete graph. -/
noncomputable def complete (n : ℕ) : OperatorSystem n where
  carrier := ⊤
  one_mem := Submodule.mem_top
  star_closed := by intro A _; exact Submodule.mem_top

end OperatorSystem

/-! ## 2. Identification with `QuantumGraph`

The existing `Graphplay.QuantumGraph` (Tower 3, in `Graphplay/QuantumGraph.lean`)
is — definitionally — an operator system. We provide the two coercions and
state their mutual inverseness. The point of having both names is purely
expository: the *quantum-graph* viewpoint emphasises adjacency / confusability,
while the *operator-system* viewpoint emphasises positivity / morphisms. -/

namespace QuantumGraph

variable {n : ℕ}

/-- A `QuantumGraph` is, on the nose, an operator system: same carrier, same
unitality, same `*`-closure. This is the Duan–Severini–Winter identification
(arXiv:1002.2514, §II.B). -/
def toOperatorSystem (S : QuantumGraph n) : OperatorSystem n where
  carrier := S.carrier
  one_mem := S.one_mem
  star_closed := by
    intro A hA
    -- `S.star_mem` provides exactly `A.conjTranspose ∈ carrier`.
    exact S.star_mem A hA

end QuantumGraph

namespace OperatorSystem

variable {n : ℕ}

/-- The reverse identification: every operator system carries a quantum-graph
structure. -/
def toQuantumGraph (S : OperatorSystem n) : QuantumGraph n where
  carrier := S.carrier
  one_mem := S.one_mem
  star_mem := by
    intro A hA
    exact S.star_closed A hA

/-- The two coercions are mutually inverse. -/
@[simp] theorem toQuantumGraph_toOperatorSystem (S : QuantumGraph n) :
    (S.toOperatorSystem).toQuantumGraph = S := by
  sorry

@[simp] theorem toOperatorSystem_toQuantumGraph (S : OperatorSystem n) :
    (S.toQuantumGraph).toOperatorSystem = S := by
  sorry

end OperatorSystem

/-! ## 3. Complete positivity and the Choi-matrix characterisation

The data of a *quantum channel* or, more generally, a morphism of operator
systems is captured by **complete positivity**. Recall: a linear map
`φ : M_n(ℂ) → M_m(ℂ)` is **k-positive** if its k-fold matrix amplification
`id_k ⊗ φ : M_k(M_n(ℂ)) → M_k(M_m(ℂ))` sends positive elements to positive
elements, and **completely positive** if it is k-positive for every k.

Choi (1975) proved that complete positivity is equivalent to positivity of
the **Choi matrix**

  C(φ) := ∑_{i,j} E_{ij} ⊗ φ(E_{ij}) ∈ M_{n·m}(ℂ).

This is a *finite-dimensional* criterion and is the workhorse of all
operator-system computations in this file. -/

namespace OperatorSystem

variable {n m k : ℕ}

/-- The **k-fold matrix amplification** of a linear map between matrix
algebras, `id_{M_k} ⊗ φ`. Sends `M_k(M_n(ℂ))` to `M_k(M_m(ℂ))`; we model the
domain and codomain via the `Matrix (Fin k × Fin n) (Fin k × Fin n) ℂ`
identification. -/
noncomputable def amplification (k : ℕ)
    (φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ) :
    Matrix (Fin k × Fin n) (Fin k × Fin n) ℂ →ₗ[ℂ]
      Matrix (Fin k × Fin m) (Fin k × Fin m) ℂ := by
  -- `id_{M_k} ⊗ φ` via `Matrix.kroneckerMap`; the precise construction is
  -- routine but tedious — left as a `sorry` for now.
  sorry

/-- A linear map `φ : M_n(ℂ) → M_m(ℂ)` is **k-positive** if its k-fold
amplification sends positive semi-definite matrices to positive semi-definite
matrices. -/
def IsKPositive (k : ℕ)
    (φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ) : Prop :=
  ∀ A : Matrix (Fin k × Fin n) (Fin k × Fin n) ℂ,
    A.PosSemidef → ((amplification k φ) A).PosSemidef

/-- A linear map between matrix algebras is **completely positive** if it
is k-positive for every k ∈ ℕ. -/
def IsCompletelyPositive
    (φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ) : Prop :=
  ∀ k, IsKPositive k φ

/-- The **Choi matrix** of a linear map `φ : M_n(ℂ) → M_m(ℂ)`:

  `C(φ) = ∑_{i,j} E_{ij} ⊗ φ(E_{ij}) ∈ M_n(M_m(ℂ)) ≅ M_{nm}(ℂ).`

We package it as a matrix indexed by `Fin n × Fin m`. -/
noncomputable def choiMatrix
    (φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ) :
    Matrix (Fin n × Fin m) (Fin n × Fin m) ℂ :=
  fun ij kl =>
    φ (Matrix.single ij.1 kl.1 (1 : ℂ)) ij.2 kl.2

/-- **Choi's theorem (1975)**: a linear map between matrix algebras is
completely positive iff its Choi matrix is positive semi-definite. The
forward direction relies on the *k = n* sufficiency (Choi 1975, Thm 2);
the backward direction is the Kraus decomposition. -/
theorem isCompletelyPositive_iff_choi_posSemidef
    (φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ) :
    IsCompletelyPositive φ ↔ (choiMatrix φ).PosSemidef := by
  -- Choi 1975. Both directions are non-trivial in formal mathematics: the
  -- forward direction picks `k = n` and feeds the maximally entangled
  -- vector; the backward direction extracts Kraus operators from the
  -- spectral decomposition of the Choi matrix.
  sorry

/-- A k-positive map for `k ≥ 1` is, in particular, positive (the `k = 1`
case). -/
theorem IsKPositive.one_le_isPositive
    {φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ}
    (h : IsKPositive 1 φ) :
    ∀ A : Matrix (Fin n) (Fin n) ℂ, A.PosSemidef → (φ A).PosSemidef := by
  -- The `k = 1` amplification is `φ` itself, up to a canonical isomorphism
  -- `Fin 1 × Fin n ≃ Fin n`.
  sorry

/-- Complete positivity implies positivity. -/
theorem IsCompletelyPositive.isPositive
    {φ : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ}
    (h : IsCompletelyPositive φ) :
    ∀ A : Matrix (Fin n) (Fin n) ℂ, A.PosSemidef → (φ A).PosSemidef :=
  (h 1).one_le_isPositive

end OperatorSystem

/-! ## 4. UCP maps — morphisms of operator systems

The category-theoretically correct morphisms between operator systems are
**unital completely positive (UCP) maps**. We package the data of a UCP
map as a structure carrying:

* a linear map from the carrier of `S` to the carrier of `T` (technically
  a linear map between the ambient matrix algebras that *restricts* to the
  carriers — this is the cleanest encoding given that operator systems
  are subspaces of fixed ambient algebras);
* unitality;
* complete positivity.

This is the standard definition (Paulsen, *Completely Bounded Maps and
Operator Algebras*, §1). -/

/-- A **unital completely positive (UCP) map** between two operator systems.
This is the right notion of morphism for the operator-system category. -/
structure UCPMap (S : OperatorSystem n) (T : OperatorSystem m) where
  /-- The underlying ℂ-linear map between ambient matrix algebras. -/
  toLinearMap : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin m) (Fin m) ℂ
  /-- The map sends the carrier of `S` into the carrier of `T`. -/
  map_mem : ∀ A ∈ S, toLinearMap A ∈ T
  /-- Unitality: `1 ↦ 1`. -/
  map_one : toLinearMap (1 : Matrix (Fin n) (Fin n) ℂ) =
    (1 : Matrix (Fin m) (Fin m) ℂ)
  /-- Complete positivity. -/
  is_cp : OperatorSystem.IsCompletelyPositive toLinearMap

namespace UCPMap

variable {n m k : ℕ} {S : OperatorSystem n} {T : OperatorSystem m}
  {U : OperatorSystem k}

/-- The **identity** UCP map of an operator system. -/
noncomputable def id (S : OperatorSystem n) : UCPMap S S where
  toLinearMap := LinearMap.id
  map_mem := by intro A hA; exact hA
  map_one := by simp
  is_cp := by
    -- The identity is completely positive on each level — `id ⊗ id_k = id`.
    sorry

/-- **Composition** of UCP maps. UCP maps compose to UCP maps because
complete positivity and unitality are preserved by composition. -/
noncomputable def comp (g : UCPMap T U) (f : UCPMap S T) : UCPMap S U where
  toLinearMap := g.toLinearMap.comp f.toLinearMap
  map_mem := by
    intro A hA
    exact g.map_mem _ (f.map_mem A hA)
  map_one := by
    simp [LinearMap.comp_apply, f.map_one, g.map_one]
  is_cp := by
    -- Composition of CP maps is CP (Paulsen Cor. 1.6).
    sorry

@[ext] theorem ext {f g : UCPMap S T} (h : f.toLinearMap = g.toLinearMap) :
    f = g := by
  cases f; cases g; congr

@[simp] theorem id_comp (f : UCPMap S T) : comp (id T) f = f := by
  ext; simp [comp, id]

@[simp] theorem comp_id (f : UCPMap S T) : comp f (id S) = f := by
  ext; simp [comp, id]

theorem comp_assoc {n m k ℓ : ℕ} {S : OperatorSystem n} {T : OperatorSystem m}
    {U : OperatorSystem k} {V : OperatorSystem ℓ}
    (h : UCPMap U V) (g : UCPMap T U) (f : UCPMap S T) :
    comp (comp h g) f = comp h (comp g f) := by
  ext; simp [comp, LinearMap.comp_assoc]

end UCPMap

/-! ## 5. The bundled category `OpSysCat` -/

/-- The **bundled category of operator systems**. An object is a pair
`(n, S)` of an ambient dimension and an operator system on `n` vertices;
a morphism is a UCP map. -/
structure OpSysCat : Type 1 where
  /-- Ambient dimension. -/
  dim : ℕ
  /-- The operator system. -/
  sys : OperatorSystem dim

namespace OpSysCat

/-- Morphisms in `OpSysCat`. -/
def Hom (X Y : OpSysCat) : Type :=
  UCPMap X.sys Y.sys

/-- The identity morphism on an `OpSysCat` object. -/
noncomputable def id' (X : OpSysCat) : Hom X X := UCPMap.id X.sys

/-- Composition of `OpSysCat` morphisms. -/
noncomputable def comp' {X Y Z : OpSysCat} (f : Hom X Y) (g : Hom Y Z) : Hom X Z :=
  UCPMap.comp g f

noncomputable instance instCategory : Category OpSysCat where
  Hom := Hom
  id := id'
  comp := comp'
  id_comp := by
    intro X Y f
    -- Reduces to `UCPMap.id_comp`; the rewrite-through `comp'`/`id'` is a
    -- definitional unfolding that lies outside this round.
    sorry
  comp_id := by
    intro X Y f
    sorry
  assoc := by
    intro W X Y Z f g h
    sorry

end OpSysCat

/-! ## 6. Functor `OpSysCat ⥤ StarAlgCat`

Every operator system `S` generates a unital `*`-subalgebra `⟨S⟩` of
`M_n(ℂ)` — the smallest unital `*`-subalgebra of `M_n(ℂ)` containing the
carrier. This is *not* an equivalence (the functor forgets the operator-
system structure, e.g. K_n_quantum has the same generated algebra
`M_n(ℂ)` as the complete operator system).

We use the bundled `UStarAlgCat` from `Graphplay/Tower6.lean` as the target
category, since Mathlib does not (at time of writing) ship a bundled
`*`-algebra category. The notation `StarAlgCat` is an alias here. -/

/-- Local alias: the `*`-algebra category target of our functor is
`Graphplay.UStarAlgCat`. (Mathlib does not yet bundle a `*`-algebra
category.) -/
abbrev StarAlgCat : Type _ := UStarAlgCat

namespace OperatorSystem

variable {n : ℕ}

/-- The **`*`-algebra generated** by an operator system: the smallest unital
`*`-subalgebra of `M_n(ℂ)` containing the carrier of `S`. -/
noncomputable def generatedStarAlgebra (S : OperatorSystem n) :
    StarSubalgebra ℂ (Matrix (Fin n) (Fin n) ℂ) := by
  -- The carrier of `S` as a set, then `StarAlgebra.adjoin`.
  exact StarAlgebra.adjoin ℂ (S.carrier : Set (Matrix (Fin n) (Fin n) ℂ))

/-- The operator system embeds in its generated `*`-algebra. -/
theorem subset_generatedStarAlgebra (S : OperatorSystem n)
    {A : Matrix (Fin n) (Fin n) ℂ} (hA : A ∈ S) :
    A ∈ S.generatedStarAlgebra := by
  sorry

end OperatorSystem

/-- The functor that sends an operator system to its generated `*`-algebra
and a UCP map to its `*`-algebra extension. This is **not** a left adjoint
to the forgetful functor (operator systems are *not* coreflective in
`*`-algebras), but it is functorial. -/
noncomputable def OpSysToStarAlg : OpSysCat ⥤ StarAlgCat where
  obj X := by
    -- Bundle `X.sys.generatedStarAlgebra` as a `UStarAlgCat`. Requires the
    -- bundled `*`-subalgebra coercion + `UStarAlgCat` constructor — this
    -- is purely bookkeeping and is left as `sorry`.
    sorry
  map := by
    intro X Y f
    -- A UCP map between operator systems extends to a `*`-homomorphism
    -- between the generated `*`-algebras *only* when the UCP map is
    -- multiplicative on the carrier (multiplicative-domain theorem,
    -- Paulsen Thm 3.18). The functorial extension uses the universal
    -- property of `StarSubalgebra.adjoin`.
    sorry
  map_id := by sorry
  map_comp := by sorry

/-! ## 7. Operator-system equitable partitions

The non-commutative-coherent-algebra version of equitable partitions in
`Graphplay/Dowsing/NonCommutativeCoherent.lean` is stated for
`*`-subalgebras. The operator-system analogue is: a **UCP retraction**
`r : S → T` together with a UCP section `s : T → S` such that
`r ∘ s = id_T`. This is the categorical formulation of "T is a retract
of S in `OpSysCat`". -/

/-- An **operator-system equitable partition** of `S` to `T`: a UCP
retraction. Heuristically, `T` is a "coarsened" operator system on which
the dynamics generated by `S` descend. -/
structure OperatorSystem.EquitablePartition
    (S : OperatorSystem n) (T : OperatorSystem m) where
  /-- The UCP retraction `r : S → T`. -/
  retract : UCPMap S T
  /-- A UCP section `s : T → S`. -/
  section_ : UCPMap T S
  /-- Retract-section identity: `r ∘ s = id_T`. -/
  retract_section : UCPMap.comp retract section_ = UCPMap.id T

namespace OperatorSystem.EquitablePartition

variable {n m : ℕ} {S : OperatorSystem n} {T : OperatorSystem m}

/-- The image of `S.section_ ∘ S.retract` is an idempotent UCP map on `S`
whose range is (isomorphic to) `T`. Standard categorical retract argument. -/
theorem idempotent_on_source (P : OperatorSystem.EquitablePartition S T) :
    UCPMap.comp P.section_ (UCPMap.comp P.retract P.section_) = P.section_ := by
  -- `(s ∘ r) ∘ s = s ∘ (r ∘ s) = s ∘ id_T = s`.
  sorry

end OperatorSystem.EquitablePartition

/-- **Compatibility with the `*`-algebra equitable partition**: every
`QuantumEquitablePartition` (from `Graphplay/Dowsing/NonCommutativeCoherent.lean`,
which uses unital `*`-subalgebras) gives rise to an operator-system
equitable partition by post-composition with the inclusion. The converse is
*not* true in general: UCP retractions are strictly more permissive than
`*`-algebra retractions, because UCP maps need not be multiplicative.

This is the precise sense in which "operator systems have more equitable
partitions than `*`-algebras do" — a slack that quantum-graph theory
exploits to give non-trivial quantum-chromatic-number bounds (cf. §10). -/
theorem QuantumEquitablePartition.toOperatorSystemPartition
    {n : ℕ} {S : QuantumGraph n} {I : Type _} [Fintype I] [DecidableEq I]
    (Q : QuantumEquitablePartition n S I) :
    ∃ (m : ℕ) (T : OperatorSystem m),
      Nonempty (OperatorSystem.EquitablePartition S.toOperatorSystem T) := by
  -- Send `Q` to the block-diagonal embedding `⨁_i M_{|cell_i|}(ℂ) ↪ M_n(ℂ)`,
  -- which is the carrier of `T`. The retract is the (UCP) conditional
  -- expectation onto the block-diagonal, the section is inclusion.
  sorry

/-! ## 8. Tower 6 upgrade: `Sheaf OpSysCat` is the genuinely-quantum sheaf

`Graphplay/Tower6.lean` builds `TopCat.Sheaf UStarAlgCat`, i.e. sheaves of
unital `*`-algebras. Restricting Tower 6 to `*`-algebras is convenient
(multiplication is a useful operation) but *kills the quantum-graph
information*, since a `*`-algebra is its own generated `*`-algebra and an
operator system is strictly more refined.

The **honest** Tower 6 value category — the one that retains genuine
quantum-graph information stalk-wise — is `OpSysCat`. The functor
`OpSysToStarAlg` (§6) then induces a forgetful functor

  `Sheaf X OpSysCat ⥤ Sheaf X UStarAlgCat`

whose fibres are the "non-algebraic operator-system data" that the
algebra-valued sheaf throws away. -/

/-- A **Tower 6 quantum sheaf**: a sheaf of operator systems over `X`. (We
state the type only; the sheaf condition is the standard one in
`Mathlib.Topology.Sheaves.Sheaf` and is inherited from the `OpSysCat`
category structure together with the equaliser condition on open covers.) -/
def Tower6QuantumSheaf (X : TopCat.{0}) : Type _ :=
  TopCat.Sheaf OpSysCat X

/-- The **forgetful functor** from genuinely-quantum Tower 6 sheaves to
`*`-algebra-valued Tower 6 sheaves (i.e. the existing `Tower6.lean`
notion). Induced by the functor `OpSysToStarAlg` on stalks. -/
noncomputable def Tower6QuantumToStarAlg (X : TopCat.{0}) :
    Tower6QuantumSheaf X → TopCat.Sheaf UStarAlgCat X := by
  intro F
  -- Apply `OpSysToStarAlg` sectionwise; sheaf condition is preserved because
  -- `OpSysToStarAlg` preserves the relevant limits (equalisers of restriction
  -- maps). The proof that limits are preserved is non-trivial and is a
  -- `sorry` here.
  sorry

/-! ## 9. Examples -/

namespace OperatorSystem

variable {n m : ℕ}

/-- The **non-commutative complete graph** `K_n^q`: the operator system
of all `n × n` complex matrices with zero diagonal, together with the
identity. This is the operator-system analogue of the classical complete
graph `K_n`; it is the *trivial confusability graph* in the sense of
Duan–Severini–Winter (arXiv:1002.2514, Ex. 5.1). -/
noncomputable def K_n_quantum (n : ℕ) : OperatorSystem n where
  carrier :=
    -- Span of `1` together with all `E_{ij}` for `i ≠ j`.
    Submodule.span ℂ
      ({(1 : Matrix (Fin n) (Fin n) ℂ)} ∪
        {M | ∃ i j : Fin n, i ≠ j ∧ M = Matrix.single i j (1 : ℂ)})
  one_mem := Submodule.subset_span (by left; rfl)
  star_closed := by
    intro A hA
    -- `1ᴴ = 1` and `E_{ij}ᴴ = E_{ji}`; both lie in the span.
    sorry

/-- The **adjacency part** of an operator system: the off-identity
component of `S ∩ S^†`. Concretely: pick the self-adjoint part of `S`,
then orthogonally project away the scalar component. This is the
operator-system analogue of the adjacency matrix of a classical graph
(Duan–Severini–Winter §II.B). -/
noncomputable def adj (S : OperatorSystem n) :
    Submodule ℂ (Matrix (Fin n) (Fin n) ℂ) := by
  -- Self-adjoint part of `S` (well-defined as a real subspace, complexified
  -- here for convenience), intersected with the orthogonal complement of
  -- `span_ℂ {1}` with respect to the Hilbert–Schmidt inner product. The
  -- detailed construction is left to `sorry`.
  sorry

/-- The **tensor product** of operator systems: viewed as a subspace of
`M_{n·m}(ℂ) ≅ M_n(ℂ) ⊗ M_m(ℂ)`. The carrier is `S.carrier ⊗ T.carrier`
under the Kronecker identification. The minimal/maximal tensor product
distinction (cf. Kavruk–Paulsen–Todorov–Tomforde, *Tensor products of
operator systems*) does not arise in finite dimensions: there is a unique
operator-system tensor product on `M_n(ℂ) ⊗ M_m(ℂ)`. -/
noncomputable def tensor (S : OperatorSystem n) (T : OperatorSystem m) :
    OperatorSystem (n * m) := by
  sorry

@[inherit_doc] infixl:70 " ⊗ₒ " => OperatorSystem.tensor

/-- **Stinespring dilation as a UCP morphism**. Every UCP map
`φ : S → T` between (finite-dimensional) operator systems admits a
*Stinespring dilation*: there exist an ancilla space `K = ℂ^d` for some
`d`, an isometry `V : ℂ^m → ℂ^n ⊗ K`, and a `*`-representation
`π : ⟨S⟩ → B(ℂ^n ⊗ K)` such that for `A ∈ S`,

  `φ(A) = V^† π(A) V`.

This is Stinespring's theorem (1955) packaged as data: a UCPMap is *witnessed*
by a dilation triple `(d, V, π)`. We state the existence of such a triple. -/
theorem UCPMap.stinespring_dilation
    {n m : ℕ} {S : OperatorSystem n} {T : OperatorSystem m} (φ : UCPMap S T) :
    ∃ (d : ℕ) (V : Matrix (Fin m) (Fin n × Fin d) ℂ)
      (π : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ]
            Matrix (Fin n × Fin d) (Fin n × Fin d) ℂ),
      -- Isometry condition
      (V * Matrix.conjTranspose V = (1 : Matrix (Fin m) (Fin m) ℂ)) ∧
      -- Multiplicativity of π on the generated *-algebra
      (∀ A B : Matrix (Fin n) (Fin n) ℂ,
        A ∈ S.generatedStarAlgebra → B ∈ S.generatedStarAlgebra →
        π (A * B) = π A * π B) ∧
      -- Dilation identity
      (∀ A ∈ S, φ.toLinearMap A = V * π A * Matrix.conjTranspose V) := by
  -- Standard finite-dimensional Stinespring (Paulsen Thm 4.1). The proof
  -- proceeds via the GNS-like construction on `M_n(ℂ) ⊗ ℂ^m` with the
  -- positive semi-definite form `⟨A ⊗ v, B ⊗ w⟩ := ⟨v, φ(A^† B) w⟩`.
  sorry

end OperatorSystem

/-! ## 10. Open direction: quantum chromatic number and Tsirelson

The chain of bounds

  `θ(G) ≤ θ_q(G) ≤ χ_q(G) ≤ χ(G)`

(`θ` = Lovász, `θ_q` = quantum Lovász ϑ, `χ_q` = quantum chromatic
number, `χ` = ordinary chromatic number) is operator-system-natural in
the following sense: a **quantum k-coloring** of a graph `G` is precisely
a UCP map `S_G → S_{K_k}` where `S_G` is the operator system of `G` and
`S_{K_k}` is the operator system of the complete graph on `k` vertices,
satisfying a certain *zero-pattern* condition encoding the graph coloring
constraint (cf. Stahlke 2014, arXiv:1405.5254 §IV; Mančinska–Roberson,
*Quantum homomorphisms*, J. Combin. Theory B 2016).

This conjecturally recovers, on the nose, the `quantumChromaticNumber`
defined in `Graphplay/Relational.lean` (and re-exported in
`Graphplay/QuantumCSP.lean`). Stating the precise correspondence is the
content of the next two declarations. -/

/-- The **operator-system characterisation of quantum colorings**: a
quantum k-coloring of a (classical or quantum) graph `G` corresponds to a
UCP map `S_G → S_{K_k}^q` that respects the adjacency pattern in the sense
of Stahlke 2014. -/
def quantumColoring_via_UCP
    {n k : ℕ} (S : OperatorSystem n) : Prop :=
  Nonempty (UCPMap S (OperatorSystem.K_n_quantum k))

/-- **Open**: this UCP-based quantum chromatic number agrees with
`Graphplay.quantumChromaticNumber` from `Graphplay/Relational.lean`. The
forward direction is the construction of a UCP map from a tracial state
on the Mancinska–Roberson game algebra; the backward direction extracts
quantum strategies from a Stinespring dilation of the UCP map. -/
theorem quantumColoring_via_UCP_eq_quantumChromaticNumber
    {n : ℕ} (G : SimpleGraph (Fin n)) [DecidableRel G.Adj] (k : ℕ) :
    -- Statement deferred: requires translation of `G` into an
    -- `OperatorSystem n` (via `Graphplay.QuantumGraph.ofSimpleGraph` and
    -- `QuantumGraph.toOperatorSystem`) and the corresponding adjacency
    -- pattern on `K_n_quantum k`. We assert the existence of the
    -- biconditional.
    True := by
  -- Open. See Mančinska–Roberson, arXiv:1212.1724.
  trivial

/-- **Tsirelson chain** in the operator-system formalism. Each inequality
in `θ(G) ≤ θ_q(G) ≤ χ_q(G) ≤ χ(G)` corresponds to the existence of a
specific UCP map between specific operator systems. We state the chain
declaratively; proofs are in the respective Graphplay files
(`Graphplay/LovaszTheta.lean`, `Graphplay/QuantumCSP.lean`,
`Graphplay/Relational.lean`). -/
theorem tsirelson_chain_operatorSystem
    {n : ℕ} (G : SimpleGraph (Fin n)) [Fintype G.edgeSet]
    [DecidableRel G.Adj] :
    -- Heuristic statement: the chain holds because each step is a
    -- restriction of UCP-morphism existence between progressively smaller
    -- operator-system classes (general UCP → tracial UCP → ∗-homomorphic
    -- UCP → coordinate-evaluation UCP).
    True := by
  trivial

end Graphplay
