/-
# Graphplay.Loopy.Laplacian

**Laplacian and self-loop (lackadaisical) continuous-time quantum walks on the
loopy Hermitian layer.**

For a `d`-regular weighted graph `G` the (combinatorial) Laplacian is
`L = D − A` with `D = diag (degree v)`.  Regularity collapses the diagonal to a
*constant* `D = d·I = d•1`, so

  `L = d•1 − A = (−A) + d•1`.

The continuous-time quantum walk (CTQW) generated by `L` therefore differs from
the one generated by `A` only by

* the **sign** of the adjacency part (`−A` vs `A`), which is a time reversal
  `U_{−A}(τ) = U_A(−τ) = U_A(τ)ᴴ`, and
* a **global phase** `e^{-iτ d}` coming from the scalar shift `d•1` (real `d`,
  so the phase has unit modulus).

Neither operation changes any transfer **modulus** `‖U(τ) · ·‖`.  Consequently a
regular graph exhibits perfect state transfer (PST) under its Laplacian walk
**iff** it does under its adjacency walk — a standard, citable fact underlying
the Laplacian-walk PST literature (Bose–Casaccino–Mancini–Wimberger and
especially arXiv:1409.5840).  The only bookkeeping subtlety is the time-reversal
index swap `(u,v) ↦ (v,u)` produced by the `−A` sign; we prove and state the
headline with that swap made explicit so the statement is exactly what is shown.

As a clean bonus we also record the **lackadaisical / self-loop** walk
`A + γ•1` (uniform self-loop weight `γ : ℝ`, cf. Wong arXiv:1706.06939): adding
a uniform self-loop is a pure global phase, invisible to every transfer modulus.

References: Laplacian-walk PST arXiv:1409.5840; lackadaisical walk Wong
arXiv:1706.06939; the diagonal-shift global-phase machinery is in
`Graphplay.PST.DiagonalShift`.
-/

import Mathlib.LinearAlgebra.Matrix.Hermitian
import Mathlib.Analysis.Normed.Algebra.MatrixExponential
import Graphplay.Loopy
import Graphplay.PST
import Graphplay.PST.DiagonalShift

open scoped Matrix
open NormedSpace

universe u

namespace Graphplay

variable {V : Type u} [Fintype V] [DecidableEq V]

/-! ## 1. The regular Laplacian as a scalar-shifted negative adjacency. -/

/-- **Regular Laplacian = constant shift of `−A`.**  For a `d`-regular weighted
graph (with the regularity eigenvalue `d : ℂ`, automatically real for a
Hermitian graph), the Laplacian adjacency matrix equals `(d.re) • 1 − A`.
Regularity forces the diagonal `diag (Re (degree v))` to be the constant
`d.re`, i.e. the scalar matrix `(d.re) • 1`. -/
theorem laplacian_adj_eq_of_regular (G : WeightedGraph V) (d : ℂ)
    (hreg : G.isRegular d) :
    (WeightedGraph.laplacian G).adj
      = ((d.re : ℂ)) • (1 : Matrix V V ℂ) - G.adj := by
  show Matrix.diagonal (fun v => ((G.degree v).re : ℂ)) - G.adj
      = ((d.re : ℂ)) • (1 : Matrix V V ℂ) - G.adj
  congr 1
  -- The diagonal of real degrees is the constant `d.re`, hence `(d.re)•1`.
  rw [smul_one_eq_diagonal]
  congr 1
  funext v
  rw [hreg v]

/-- The regular Laplacian written in the `(−A) + shift` form expected by the
diagonal-shift machinery: `L.adj = (−A) + (d.re)•1`. -/
theorem laplacian_adj_eq_neg_add_of_regular (G : WeightedGraph V) (d : ℂ)
    (hreg : G.isRegular d) :
    (WeightedGraph.laplacian G).adj
      = (-G.adj) + ((d.re : ℂ)) • (1 : Matrix V V ℂ) := by
  rw [laplacian_adj_eq_of_regular G d hreg]
  abel

/-! ## 2. Headline: Laplacian and adjacency walks share all transfer moduli. -/

/-- The CTQW generated by `−A` is the time-reversed adjacency walk, hence the
adjoint of the forward one:
`exp(-(iτ)•(−A)) = exp(-(i(−τ))•A) = G.evolve (−τ) = (G.evolve τ)ᴴ`. -/
theorem exp_neg_adj_eq_evolve_conjTranspose (G : WeightedGraph V) (τ : ℝ) :
    NormedSpace.exp (-(Complex.I * (τ : ℂ)) • (-G.adj)) = (G.evolve τ)ᴴ := by
  rw [G.evolve_conjTranspose]
  show NormedSpace.exp (-(Complex.I * (τ : ℂ)) • (-G.adj))
      = NormedSpace.exp (-(Complex.I * ((-τ : ℝ) : ℂ)) • G.adj)
  congr 1
  push_cast
  module

/-- **Headline (modulus equality).**  For a `d`-regular weighted graph the
`(u, v)`-entry modulus of the Laplacian walk equals the `(v, u)`-entry modulus
of the adjacency walk at the same time:

  `‖(WeightedGraph.laplacian G).evolve τ u v‖ = ‖G.evolve τ v u‖`.

The index swap `(u,v) ↦ (v,u)` is the effect of the `−A` time reversal
(`U_{−A}(τ) = U_A(τ)ᴴ`); the scalar `d•1` shift contributes only a unit-modulus
global phase.  No symmetry of the unitary is assumed. -/
theorem norm_evolve_laplacian_eq_of_regular (G : WeightedGraph V) (d : ℂ)
    (hreg : G.isRegular d) (τ : ℝ) (u v : V) :
    ‖(WeightedGraph.laplacian G).evolve τ u v‖ = ‖G.evolve τ v u‖ := by
  -- Unfold the loopy evolution and rewrite `L.adj = (−A) + (d.re)•1`.
  show ‖NormedSpace.exp (-(Complex.I * (τ : ℂ)) • (WeightedGraph.laplacian G).adj) u v‖
      = ‖G.evolve τ v u‖
  rw [laplacian_adj_eq_neg_add_of_regular G d hreg]
  -- Strip the global phase from the `(d.re)•1` shift (apply at indices `v u`
  -- to land on the `(u, v)` entry, matching `norm_exp_shifted_entry_eq`).
  rw [norm_exp_shifted_entry_eq (-G.adj) τ d.re v u]
  -- The remaining matrix is `exp(-(iτ)•(−A)) = (G.evolve τ)ᴴ`.
  rw [exp_neg_adj_eq_evolve_conjTranspose G τ]
  -- `(G.evolve τ)ᴴ u v = star (G.evolve τ v u)`, whose modulus is `‖G.evolve τ v u‖`.
  rw [Matrix.conjTranspose_apply, norm_star]

/-! ## 3. PST equivalence (regular graphs): Laplacian ↔ adjacency. -/

/-- **Laplacian PST ⟺ adjacency PST on regular graphs.**  For a `d`-regular
weighted graph, the Laplacian walk has perfect state transfer `u → v` at time
`τ` iff the adjacency walk has perfect state transfer `v → u` at the same time.

The `(u,v) ↦ (v,u)` swap is the time-reversal bookkeeping of step 2; it is
harmless for PST since one usually transfers between a fixed pair and the
adjacency-walk PST predicate is invoked at the matching index order. -/
theorem isLoopyPST_laplacian_iff_adjacency_of_regular (G : WeightedGraph V) (d : ℂ)
    (hreg : G.isRegular d) (u v : V) (τ : ℝ) :
    (WeightedGraph.laplacian G).IsLoopyPST u v τ ↔ IsPST G v u τ := by
  unfold LoopyWeightedGraph.IsLoopyPST IsPST
  rw [norm_evolve_laplacian_eq_of_regular G d hreg τ u v]

/-! ## 4. Lackadaisical / self-loop walk (Wong arXiv:1706.06939).

Adding a *uniform* self-loop weight `γ : ℝ` to a graph augments the Hamiltonian
by `γ•1`.  By the diagonal-shift / global-phase machinery this is invisible to
every transfer modulus, so the lackadaisical walk has exactly the same PST /
fractional-revival profile as the loopless walk. -/

/-- The **self-loop augmentation** `A + γ•1` of a loopy weighted graph, with
uniform self-loop weight `γ : ℝ`.  Hermitian because `γ•1` is Hermitian. -/
noncomputable def LoopyWeightedGraph.addSelfLoop (G : LoopyWeightedGraph V) (γ : ℝ) :
    LoopyWeightedGraph V where
  adj := G.adj + (γ : ℂ) • (1 : Matrix V V ℂ)
  herm := by
    refine G.herm.add ?_
    rw [smul_one_eq_diagonal]
    apply Matrix.isHermitian_diagonal_iff.mpr
    intro v
    rw [isSelfAdjoint_iff, Complex.star_def, Complex.conj_ofReal]

/-- **Lackadaisical-walk modulus invariance (Wong arXiv:1706.06939).**  Adding a
uniform self-loop of (real) weight `γ` leaves every transfer modulus unchanged:

  `‖(G.addSelfLoop γ).evolve τ u v‖ = ‖G.evolve τ u v‖`.

A pure global phase `e^{-iτγ}` of unit modulus — a one-line consequence of the
diagonal-shift lemma. -/
theorem norm_evolve_addSelfLoop_eq (G : LoopyWeightedGraph V) (γ : ℝ) (τ : ℝ)
    (u v : V) :
    ‖(G.addSelfLoop γ).evolve τ u v‖ = ‖G.evolve τ u v‖ := by
  show ‖NormedSpace.exp (-(Complex.I * (τ : ℂ)) •
        (G.adj + (γ : ℂ) • (1 : Matrix V V ℂ))) u v‖
      = ‖NormedSpace.exp (-(Complex.I * (τ : ℂ)) • G.adj) u v‖
  exact norm_exp_shifted_entry_eq G.adj τ γ v u

/-- The self-loop walk has the same PST as the loopless walk: a uniform
self-loop is invisible to PST. -/
theorem isLoopyPST_addSelfLoop_iff (G : LoopyWeightedGraph V) (γ : ℝ)
    (u v : V) (τ : ℝ) :
    (G.addSelfLoop γ).IsLoopyPST u v τ ↔ G.IsLoopyPST u v τ := by
  unfold LoopyWeightedGraph.IsLoopyPST
  rw [norm_evolve_addSelfLoop_eq G γ τ u v]

end Graphplay
