/-
# Graphplay.Integrations.GQACertSmolLM2 — **kernel-checked certificate** that
SmolLM2-135M's grouped-query attention head-tying induces an equitable
partition of the head-axis weight graph.

GENERATED by `experiments/export_gqa_cert.py` from the released weights of
`HuggingFaceTB/SmolLM2-135M` (Allal et al., arXiv 2502.02737), layer 0;
do not edit by hand — regenerate instead.

SmolLM2 uses grouped-query attention (Ainslie et al., GQA, arXiv 2305.13245):
9 query heads share 3 KV heads (3 per group), so within a group the
K/V projection weights are *bit-identical by construction*.
`experiments/run_gqa_defect.py` measured the resulting head-axis equitability
defect to be exactly 0 on all 30 layers; the exporter re-verified the
within-group bit-identity of the K/V rows on all 30 layers in exact
arithmetic.  This module is that measurement upgraded to a proof object:

* `gqaGram` — the exact 9×9 head-axis Gram matrix of layer 0:
  entry `(h, h')` is `⟨W_h, W_h'⟩` where `W_h` is head `h`'s K∥V projection
  weight vector (73728 float32 entries, each an exact dyadic rational
  `m/2^149`), computed in big-integer arithmetic — *no float round-off
  anywhere* — with the diagonal zeroed (`WeightedGraph` is loopless).
  Cross-group entries are genuine learned inner products, so this matrix is
  data, not a pattern.

* `gqa_head_tying_isEquitable` — `decide`-proved: the head → KV-group
  partition is equitable for `gqaGram`.  This holds *because* the within-group
  vectors are identical — it is the exact-arithmetic shadow of GQA tying.

* `gqa_misaligned_not_equitable` — `decide`-proved negative control: shifting
  the group boundaries by one head destroys equitability.  The certificate
  depends on the actual weight values; no degenerate matrix could pass both
  verdicts.

* `gqaHeadPartition` / `gqa_head_collapse` — the verdict transported through
  `certifiedPartition` into an `EquitablePartition` of the head-axis
  `WeightedGraph`, to which the spectral collapse
  (`restrict_eq_symmQuotient`) applies: the 9×9 head-axis operator acts on
  the cell-uniform subspace as its 3×3 symmetric quotient.  That 3× collapse
  of the head axis is the formal content of "GQA defect ≡ 0".
-/

import Graphplay.Integrations.EquitableCertChecker

namespace Graphplay
namespace Integrations
namespace EquitableCert

open scoped BigOperators

/-- Row-major entries of the exact head-axis Gram matrix of layer 0
(numerators over powers of two — every float32 is a dyadic rational). -/
def gqaGramRows : List (List ℚ) :=
  [[0, mkRat 37263487299832006313 (2 ^ 53), mkRat 37263487299832006313 (2 ^ 53), mkRat 6778018130374091 (2 ^ 45), mkRat 6778018130374091 (2 ^ 45), mkRat 6778018130374091 (2 ^ 45), mkRat 1457277056123279 (2 ^ 44), mkRat 1457277056123279 (2 ^ 44), mkRat 1457277056123279 (2 ^ 44)],
   [mkRat 37263487299832006313 (2 ^ 53), 0, mkRat 37263487299832006313 (2 ^ 53), mkRat 6778018130374091 (2 ^ 45), mkRat 6778018130374091 (2 ^ 45), mkRat 6778018130374091 (2 ^ 45), mkRat 1457277056123279 (2 ^ 44), mkRat 1457277056123279 (2 ^ 44), mkRat 1457277056123279 (2 ^ 44)],
   [mkRat 37263487299832006313 (2 ^ 53), mkRat 37263487299832006313 (2 ^ 53), 0, mkRat 6778018130374091 (2 ^ 45), mkRat 6778018130374091 (2 ^ 45), mkRat 6778018130374091 (2 ^ 45), mkRat 1457277056123279 (2 ^ 44), mkRat 1457277056123279 (2 ^ 44), mkRat 1457277056123279 (2 ^ 44)],
   [mkRat 6778018130374091 (2 ^ 45), mkRat 6778018130374091 (2 ^ 45), mkRat 6778018130374091 (2 ^ 45), 0, mkRat 294213076221790101325 (2 ^ 55), mkRat 294213076221790101325 (2 ^ 55), mkRat (-177365079169323) (2 ^ 40), mkRat (-177365079169323) (2 ^ 40), mkRat (-177365079169323) (2 ^ 40)],
   [mkRat 6778018130374091 (2 ^ 45), mkRat 6778018130374091 (2 ^ 45), mkRat 6778018130374091 (2 ^ 45), mkRat 294213076221790101325 (2 ^ 55), 0, mkRat 294213076221790101325 (2 ^ 55), mkRat (-177365079169323) (2 ^ 40), mkRat (-177365079169323) (2 ^ 40), mkRat (-177365079169323) (2 ^ 40)],
   [mkRat 6778018130374091 (2 ^ 45), mkRat 6778018130374091 (2 ^ 45), mkRat 6778018130374091 (2 ^ 45), mkRat 294213076221790101325 (2 ^ 55), mkRat 294213076221790101325 (2 ^ 55), 0, mkRat (-177365079169323) (2 ^ 40), mkRat (-177365079169323) (2 ^ 40), mkRat (-177365079169323) (2 ^ 40)],
   [mkRat 1457277056123279 (2 ^ 44), mkRat 1457277056123279 (2 ^ 44), mkRat 1457277056123279 (2 ^ 44), mkRat (-177365079169323) (2 ^ 40), mkRat (-177365079169323) (2 ^ 40), mkRat (-177365079169323) (2 ^ 40), 0, mkRat 5838133876061791809 (2 ^ 50), mkRat 5838133876061791809 (2 ^ 50)],
   [mkRat 1457277056123279 (2 ^ 44), mkRat 1457277056123279 (2 ^ 44), mkRat 1457277056123279 (2 ^ 44), mkRat (-177365079169323) (2 ^ 40), mkRat (-177365079169323) (2 ^ 40), mkRat (-177365079169323) (2 ^ 40), mkRat 5838133876061791809 (2 ^ 50), 0, mkRat 5838133876061791809 (2 ^ 50)],
   [mkRat 1457277056123279 (2 ^ 44), mkRat 1457277056123279 (2 ^ 44), mkRat 1457277056123279 (2 ^ 44), mkRat (-177365079169323) (2 ^ 40), mkRat (-177365079169323) (2 ^ 40), mkRat (-177365079169323) (2 ^ 40), mkRat 5838133876061791809 (2 ^ 50), mkRat 5838133876061791809 (2 ^ 50), 0]]

/-- The exact 9×9 head-axis K∥V Gram matrix of SmolLM2-135M layer 0,
diagonal zeroed. -/
def gqaGram : Matrix (Fin 9) (Fin 9) ℚ := matOfLists 9 gqaGramRows

/-- The GQA head → KV-group partition: heads `3g, 3g+1, 3g+2` share KV head `g`. -/
def headToGroup : Fin 9 → Fin 3 := fun h => ⟨h.val / 3, by omega⟩

/-- The negative-control labelling: group boundaries shifted by one head. -/
def headMisaligned : Fin 9 → Fin 3 :=
  fun h => ⟨((h.val + 1) % 9) / 3, by omega⟩

set_option maxRecDepth 1000000

/-- **The certificate.**  The head → KV-group partition is equitable for the
exact head-axis Gram matrix — kernel-computed from the released weights. -/
theorem gqa_head_tying_isEquitable :
    isEquitable? gqaGram headToGroup = true := by decide +kernel

/-- **Negative control.**  Misaligning the groups by one head breaks
equitability: the verdict reads the learned entries, not the block shape. -/
theorem gqa_misaligned_not_equitable :
    isEquitable? gqaGram headMisaligned = false := by decide +kernel

/-- The head-axis weight graph of layer 0 (symmetry of the Gram matrix and
the zeroed diagonal are themselves kernel-checked). -/
def gqaHeadGraph : WeightedGraph (Fin 9) :=
  ratWeightedGraph gqaGram (by decide +kernel) (by decide +kernel)

/-- The certified equitable partition of the head axis. -/
def gqaHeadPartition : EquitablePartition gqaHeadGraph (Fin 3) :=
  certifiedPartition gqaGram headToGroup gqaHeadGraph rfl gqa_head_tying_isEquitable

/-- **The instantiated collapse**: on the cell-uniform subspace of the
certified partition, the 9×9 head-axis operator acts as its 3×3 symmetric
quotient — the head-axis reduction GQA performs, derived rather than assumed. -/
theorem gqa_head_collapse (w : Fin 3 → ℂ) :
    gqaHeadGraph.adj.mulVec (fun v => ∑ i, w i * gqaHeadPartition.cellUniformVec i v)
      = fun v => ∑ i,
          (gqaHeadPartition.symmQuotient.mulVec w) i
            * gqaHeadPartition.cellUniformVec i v :=
  gqaHeadPartition.restrict_eq_symmQuotient w

end EquitableCert
end Integrations
end Graphplay
