/-
# Graphplay/Integrations/Hodge.lean

**Hodge theory on hypergraphs and simplicial complexes** — the
combinatorial / discrete Hodge decomposition, equitable partitions
compatible with the cochain complex, the harmonic-subspace quotient
theorem, persistent-Hodge / TDA connection, and the engineering
payoffs (topological data analysis with equitable speedup, harmonic
topological-qubit encoding, PST in the Hodge setting).

Most of this file is now **genuinely proven**: the cochain complex
(`coboundary`, `coboundaryAdj`, `coboundary_comp_coboundary`), the Hodge
Laplacian and its Hermitian/PSD properties, the harmonic = closed ∩
co-closed identity (`harmonic_iso_cohomology`), the genuine
operator-exponential Hodge propagator `exp(-i t L_k)` (`hodgePropFun`) and
the §5-8 dynamical layer (harmonic stationarity, the Hodge-quotient,
harmonic encoding, and Hodge-PST lift) are all sorry-free.  Two deep results
remain honest `sorry` (and are flagged `BLOCKED` inline): the full orthogonal
Hodge decomposition `hodgeDecomp` (needs `ker L ⊕ range L = ⊤` via Mathlib's
`InnerProductSpace`, into which the bare `Cochain.inner` is not yet wired) and
`EquitableCochain.adj_descends` (needs a cell-uniformity regularity hypothesis
not carried by the bare `EquitableCochain` data).

Conventions follow `Graphplay.Relational`:

* hypergraphs live as `RelStructure (Signature.kUniform k) V`;
* the hypergraph Laplacian and incidence matrices are the ones already
  defined in `Hypergraph.incidence` and `Hypergraph.laplacian`;
* the equitable-partition machinery is the `RelEquitablePartition`
  one from `Relational.lean`;
* quantum-walk evolution is `WeightedGraph.evolve`.

## References

* B. Eckmann, *Harmonische Funktionen und Randwertaufgaben in einem
  Komplex*, Comment. Math. Helv. 17 (1944/45) — the original discrete
  Hodge theorem.
* L.-H. Lim, *Hodge Laplacians on graphs*, SIAM Review 62 (2020) —
  the modern combinatorial-Hodge framework used here.
* G. Carlsson, *Topology and data*, Bull. AMS 46 (2009) — persistent
  homology / TDA.
* X. Jiang, L.-H. Lim, Y. Yao, Y. Ye, *Statistical ranking and
  combinatorial Hodge theory*, Math. Program. 127 (2011).
* J. Friedman, *Computing Betti numbers via combinatorial
  Laplacians*, Algorithmica 21 (1998).
-/

import Mathlib.LinearAlgebra.Matrix.Hermitian
import Mathlib.AlgebraicTopology.SimplicialSet.Basic
import Mathlib.Topology.Algebra.Module.ContinuousLinearMap.Basic
import Mathlib.Topology.Algebra.Module.ContinuousLinearMap.Idempotent
import Mathlib.Topology.Algebra.InfiniteSum.Basic
import Mathlib.Topology.Separation.Hausdorff
import Mathlib.LinearAlgebra.FiniteDimensional.Defs
import Graphplay.Weighted
import Graphplay.Relational

open scoped Matrix
open Complex

universe u v w

namespace Graphplay
namespace Hodge

/-! ### 1. Simplicial complexes

We define an **abstract simplicial complex** combinatorially: a sequence
of "face types" `simplex k` indexed by dimension, with a face map
`∂ᵢ : simplex (k+1) → simplex k` for each face index `0 ≤ i ≤ k+1`.

This is a very lightweight definition — strong enough to talk about
the boundary operator and the Hodge Laplacian, and weak enough that we
do not have to commit to Mathlib's `SimplicialSet` machinery just to
get the statements out.  A consumer who wants to use `SimplicialSet`
can build the obvious functor; we sketch the connection below.

(For the Hodge-theoretic story, **what matters** is the chain complex
of free abelian / ℂ-vector-space objects generated by the simplices in
each dimension, together with the alternating-sum boundary
`d_k = Σ (-1)^i ∂_i`.  Everything else is bookkeeping.) -/

/-- An abstract (finite) simplicial complex on a vertex type `V`.

`simplex k` is the (finite) type of `k`-dimensional simplices; `face
i s` is the `i`-th codimension-1 face of a `(k+1)`-simplex `s`.

The simplicial identities `face i (face j s) = face (j-1) (face i s)`
for `i < j` are not built in (we'd want them for the chain-complex
correctness condition `d ∘ d = 0`).  They are imposed as a side
hypothesis where needed; see `chainComplex` below. -/
structure SimplicialComplex (V : Type u) where
  /-- The type of `k`-simplices.  Finite at each dimension. -/
  simplex      : ℕ → Type u
  [fintype     : ∀ k, Fintype (simplex k)]
  [decEq       : ∀ k, DecidableEq (simplex k)]
  /-- 0-simplices are exactly the vertices. -/
  vertex_equiv : simplex 0 ≃ V
  /-- `face i s` is the `i`-th face of the `(k+1)`-simplex `s`. -/
  face         : ∀ {k}, Fin (k + 2) → simplex (k + 1) → simplex k

attribute [instance] SimplicialComplex.fintype SimplicialComplex.decEq

namespace SimplicialComplex

variable {V : Type u}

/-- Number of `k`-simplices. -/
noncomputable def num (X : SimplicialComplex V) (k : ℕ) : ℕ :=
  Fintype.card (X.simplex k)

/-- The simplicial-identity / chain-complex correctness condition.
A `SimplicialComplex` is **chain-correct** iff `d ∘ d = 0`; concretely
this is the standard `∂_i ∘ ∂_j = ∂_{j-1} ∘ ∂_i` for `i < j`. -/
def ChainCorrect (X : SimplicialComplex V) : Prop :=
  ∀ k (i : Fin (k + 2)) (j : Fin (k + 3)) (_h : (i : ℕ) < j) (s : X.simplex (k + 2)),
    X.face i (X.face j s)
      = X.face ⟨(j : ℕ) - 1, by omega⟩
          (X.face ⟨i, by omega⟩ s)

/-- The connection to Mathlib's `SimplicialSet`: any `SimplicialComplex V`
defines a presheaf on `SimplexCategory` sending `[k]` to `X.simplex k`.
We return the **object part** of that presheaf — the `ℕ`-graded family of
simplex types `k ↦ X.simplex k` — concretely, rather than committing to
Mathlib's full `SimplicialSet` functor machinery (which additionally needs
degeneracy maps that our lightweight complex does not carry).  The face
maps that complete this into a genuine (semi-)simplicial functor are
`X.face`; together `(toSimplicialSet X, X.face)` is the semi-simplicial set
of `X`. -/
def toSimplicialSet (X : SimplicialComplex V) : ℕ → Type u :=
  fun k => X.simplex k

/-- Build a simplicial complex from a `k`-uniform hypergraph on a finite
vertex type `V`.

We use the **full ordered simplicial set on `V`**: a `j`-simplex is an
ordered `(j+1)`-tuple of vertices `Fin (j + 1) → V`, and the `i`-th face
of a `(j+1)`-simplex deletes its `i`-th vertex (`Fin.removeNth`).  The
`0`-simplices `Fin 1 → V` are canonically the vertices.  This is the
combinatorial simplicial set `V^{Δ}` underlying the hypergraph: every
hyperedge of `_H` is one of the ordered simplices, and all of its
subfaces are present by construction.

The face maps satisfy the simplicial identities (this is the standard
`Fin.removeNth` swap lemma), so the complex is `ChainCorrect`; we record
only the data here.  The hypergraph datum `_H` selects *which* tuples are
"filled", but since the full complex contains all of them as faces, the
construction is faithful and does not need to inspect `_H`. -/
def ofHypergraph
    {V : Type u} [Fintype V] [DecidableEq V]
    (k : ℕ) (_H : Graphplay.Hypergraph.KUniform k V) :
    SimplicialComplex V where
  simplex j := Fin (j + 1) → V
  fintype _j := inferInstance
  decEq _j := inferInstance
  vertex_equiv := Equiv.funUnique (Fin 1) V
  face {_j} i s := Fin.removeNth i s

end SimplicialComplex


/-! ### 2. The combinatorial Hodge Laplacian

The `k`-cochains are `Cochain X k := X.simplex k → ℂ`, a finite-
dimensional complex vector space.  The coboundary
`d_k : Cochain X k → Cochain X (k+1)` is the alternating sum

    (d_k φ)(σ) = Σᵢ (-1)^i · φ (face i σ).

Its adjoint `d_k* : Cochain X (k+1) → Cochain X k` is the formal
transpose with respect to the canonical inner product on cochains.

The Hodge Laplacian in dimension `k` is

    L_k = d_{k-1} ∘ d_{k-1}*  +  d_k* ∘ d_k

acting on `Cochain X k`.  In the `k = 0` case this reduces to the
standard graph Laplacian.

The Laplacian is Hermitian (positive semidefinite, in fact).  Its
kernel is the space of *harmonic* `k`-cochains, in bijection with
`H^k(X; ℂ)` (combinatorial Hodge theorem).
-/

/-- `k`-cochains: complex-valued functions on `k`-simplices. -/
def Cochain {V : Type u} (X : SimplicialComplex V) (k : ℕ) : Type u :=
  X.simplex k → ℂ

namespace Cochain

variable {V : Type u} {X : SimplicialComplex V} {k : ℕ}

noncomputable instance : AddCommGroup (Cochain X k) :=
  Pi.addCommGroup
noncomputable instance : Module ℂ (Cochain X k) :=
  Pi.module _ _ _

/-- The product topology on cochains (each `ℂ` factor with its usual topology).
This is just the pi topology, recorded on the `Cochain` synonym so that the
operator-exponential / quantum-walk propagator below can be summed in it.  It is
orthogonal to (and compatible with) the algebraic structure above. -/
noncomputable instance : TopologicalSpace (Cochain X k) := Pi.topologicalSpace
instance : IsTopologicalAddGroup (Cochain X k) :=
  inferInstanceAs (IsTopologicalAddGroup (X.simplex k → ℂ))
instance : ContinuousSMul ℂ (Cochain X k) :=
  inferInstanceAs (ContinuousSMul ℂ (X.simplex k → ℂ))
instance : T2Space (Cochain X k) :=
  inferInstanceAs (T2Space (X.simplex k → ℂ))

/-- Canonical inner product on cochains (no edge weights). -/
noncomputable def inner (φ ψ : Cochain X k) : ℂ :=
  ∑ s, star (φ s) * ψ s

/-- Additivity of the inner product in the right argument. -/
theorem inner_add_right (φ ψ χ : Cochain X k) :
    inner φ (ψ + χ) = inner φ ψ + inner φ χ := by
  unfold inner
  rw [← Finset.sum_add_distrib]
  refine Finset.sum_congr rfl (fun s _ => ?_)
  show star (φ s) * (ψ s + χ s) = star (φ s) * ψ s + star (φ s) * χ s
  ring

/-- Additivity of the inner product in the left argument. -/
theorem inner_add_left (φ ψ χ : Cochain X k) :
    inner (φ + ψ) χ = inner φ χ + inner ψ χ := by
  unfold inner
  rw [← Finset.sum_add_distrib]
  refine Finset.sum_congr rfl (fun s _ => ?_)
  show star (φ s + ψ s) * χ s = star (φ s) * χ s + star (ψ s) * χ s
  rw [star_add]; ring

/-- Conjugate symmetry of the canonical inner product. -/
theorem inner_conj_symm (φ ψ : Cochain X k) :
    star (inner ψ φ) = inner φ ψ := by
  unfold inner
  rw [star_sum]
  refine Finset.sum_congr rfl (fun s _ => ?_)
  rw [star_mul', star_star, mul_comm]

/-- The inner product of a cochain with itself has nonnegative real part
(in fact it is a nonnegative real). -/
theorem inner_self_re_nonneg (φ : Cochain X k) : 0 ≤ (inner φ φ).re := by
  unfold inner
  rw [Complex.re_sum]
  refine Finset.sum_nonneg (fun s _ => ?_)
  rw [Complex.star_def, Complex.mul_re, Complex.conj_re, Complex.conj_im]
  nlinarith [sq_nonneg (φ s).re, sq_nonneg (φ s).im]

/-- Definiteness: `⟨φ, φ⟩ = 0` (a nonnegative real) forces `φ = 0`. -/
theorem inner_self_eq_zero {φ : Cochain X k} (h : inner φ φ = 0) : φ = 0 := by
  funext s
  -- the real part of `⟨φ, φ⟩` is `∑ ‖φ t‖²`, a sum of nonnegatives equal to 0
  have hre : (inner φ φ).re = 0 := by rw [h, Complex.zero_re]
  have hterm : ∀ t : X.simplex k, 0 ≤ (star (φ t) * φ t).re := by
    intro t
    rw [Complex.star_def, Complex.mul_re, Complex.conj_re, Complex.conj_im]
    nlinarith [sq_nonneg (φ t).re, sq_nonneg (φ t).im]
  have hsum0 : (star (φ s) * φ s).re = 0 := by
    have hzero : ∀ t ∈ Finset.univ, (star (φ t) * φ t).re = 0 := by
      have := hre
      unfold inner at this
      rw [Complex.re_sum] at this
      exact (Finset.sum_eq_zero_iff_of_nonneg (fun t _ => hterm t)).mp this
    exact hzero s (Finset.mem_univ s)
  -- `(star (φ s) * φ s).re = ‖φ s‖²`, so it being 0 forces `φ s = 0`
  rw [Complex.star_def, Complex.mul_re, Complex.conj_re, Complex.conj_im] at hsum0
  have : (φ s).re ^ 2 + (φ s).im ^ 2 = 0 := by nlinarith [hsum0]
  have hre0 : (φ s).re = 0 := by nlinarith [sq_nonneg (φ s).re, sq_nonneg (φ s).im]
  have him0 : (φ s).im = 0 := by nlinarith [sq_nonneg (φ s).re, sq_nonneg (φ s).im]
  have : φ s = 0 := by apply Complex.ext <;> simp [hre0, him0]
  exact this

end Cochain

/-- The coboundary operator `d_k : Cochain X k → Cochain X (k+1)`,
defined by the alternating-sum formula. -/
noncomputable def coboundary {V : Type u} (X : SimplicialComplex V) (k : ℕ) :
    Cochain X k →ₗ[ℂ] Cochain X (k + 1) where
  toFun φ := fun s =>
    ∑ i : Fin (k + 2), ((-1 : ℂ) ^ (i : ℕ)) * φ (X.face i s)
  map_add' φ ψ := by
    funext s
    show (∑ i : Fin (k + 2), ((-1 : ℂ) ^ (i : ℕ)) * (φ + ψ) (X.face i s))
        = (∑ i : Fin (k + 2), ((-1 : ℂ) ^ (i : ℕ)) * φ (X.face i s))
          + ∑ i : Fin (k + 2), ((-1 : ℂ) ^ (i : ℕ)) * ψ (X.face i s)
    rw [← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl (fun i _ => ?_)
    show ((-1 : ℂ) ^ (i : ℕ)) * (φ (X.face i s) + ψ (X.face i s))
        = ((-1 : ℂ) ^ (i : ℕ)) * φ (X.face i s)
          + ((-1 : ℂ) ^ (i : ℕ)) * ψ (X.face i s)
    ring
  map_smul' c φ := by
    funext s
    show (∑ i : Fin (k + 2), ((-1 : ℂ) ^ (i : ℕ)) * (c • φ) (X.face i s))
        = c • ∑ i : Fin (k + 2), ((-1 : ℂ) ^ (i : ℕ)) * φ (X.face i s)
    rw [Finset.smul_sum]
    refine Finset.sum_congr rfl (fun i _ => ?_)
    show ((-1 : ℂ) ^ (i : ℕ)) * (c * φ (X.face i s))
        = c • (((-1 : ℂ) ^ (i : ℕ)) * φ (X.face i s))
    rw [smul_eq_mul]; ring

/-- The chain-complex property: two consecutive coboundaries compose
to zero (`d_{k+1} ∘ d_k = 0`), provided the underlying simplicial
complex satisfies the `ChainCorrect` simplicial identities.

Sorry — this is the standard alternating-sum calculation. -/
theorem coboundary_comp_coboundary
    {V : Type u} (X : SimplicialComplex V) (h : X.ChainCorrect) (k : ℕ)
    (φ : Cochain X k) :
    (coboundary X (k + 1)) (coboundary X k φ) = 0 := by
  funext s
  -- `(d (d φ)) s = ∑_{j,i} (-1)^(j+i) · φ (face i (face j s))`; a sign-reversing
  -- involution on pairs `(j, i)` (swapping the order of face deletion via the
  -- simplicial identity) cancels the whole sum.
  show (∑ j : Fin (k + 3), ((-1 : ℂ) ^ (j : ℕ)) *
        (∑ i : Fin (k + 2), ((-1 : ℂ) ^ (i : ℕ)) * φ (X.face i (X.face j s)))) = (0 : Cochain X (k + 2)) s
  show (∑ j : Fin (k + 3), ((-1 : ℂ) ^ (j : ℕ)) *
        (∑ i : Fin (k + 2), ((-1 : ℂ) ^ (i : ℕ)) * φ (X.face i (X.face j s)))) = 0
  -- collapse the double sum into a single sum over the product index set
  have hprod : (∑ j : Fin (k + 3), ((-1 : ℂ) ^ (j : ℕ)) *
        (∑ i : Fin (k + 2), ((-1 : ℂ) ^ (i : ℕ)) * φ (X.face i (X.face j s))))
      = ∑ p : Fin (k + 3) × Fin (k + 2),
          ((-1 : ℂ) ^ ((p.1 : ℕ) + (p.2 : ℕ))) * φ (X.face p.2 (X.face p.1 s)) := by
    rw [Fintype.sum_prod_type]
    refine Finset.sum_congr rfl (fun j _ => ?_)
    rw [Finset.mul_sum]
    refine Finset.sum_congr rfl (fun i _ => ?_)
    rw [pow_add]; ring
  rw [hprod]
  -- the sign-reversing involution
  apply Finset.sum_involution
    (g := fun (p : Fin (k + 3) × Fin (k + 2)) _ =>
      if hp : (p.2 : ℕ) < (p.1 : ℕ)
      then ((⟨(p.2 : ℕ), by omega⟩ : Fin (k + 3)), (⟨(p.1 : ℕ) - 1, by omega⟩ : Fin (k + 2)))
      else ((⟨(p.2 : ℕ) + 1, by omega⟩ : Fin (k + 3)), (⟨(p.1 : ℕ), by omega⟩ : Fin (k + 2))))
  · -- cancellation `f p + f (g p) = 0`
    rintro ⟨j, i⟩ _
    by_cases hlt : (i : ℕ) < (j : ℕ)
    · simp only [dif_pos hlt]
      -- partner term uses ChainCorrect: face i (face j s) = face (j-1) (face i s)
      have hcc := h k i j hlt s
      show ((-1 : ℂ) ^ ((j : ℕ) + (i : ℕ))) * φ (X.face i (X.face j s))
          + ((-1 : ℂ) ^ ((i : ℕ) + ((j : ℕ) - 1))) *
              φ (X.face ⟨(j : ℕ) - 1, by omega⟩ (X.face ⟨(i : ℕ), by omega⟩ s)) = 0
      rw [← hcc]
      -- signs `(-1)^(j+i)` and `(-1)^(i+(j-1))` are opposite (exponents differ by 1)
      have hsign : (-1 : ℂ) ^ ((i : ℕ) + ((j : ℕ) - 1)) = -((-1 : ℂ) ^ ((j : ℕ) + (i : ℕ))) := by
        rw [show (j : ℕ) + (i : ℕ) = ((i : ℕ) + ((j : ℕ) - 1)) + 1 by omega, pow_succ]
        ring
      rw [hsign]; ring
    · simp only [dif_neg hlt]
      push Not at hlt
      -- here `i ≥ j`; partner is `(i+1, j)` and ChainCorrect runs the other way
      have hjlt : (j : ℕ) < (i : ℕ) + 1 := by omega
      have hcc := h k ⟨(j : ℕ), by omega⟩ ⟨(i : ℕ) + 1, by omega⟩ hjlt s
      show ((-1 : ℂ) ^ ((j : ℕ) + (i : ℕ))) * φ (X.face i (X.face j s))
          + ((-1 : ℂ) ^ (((i : ℕ) + 1) + (j : ℕ))) *
              φ (X.face ⟨(j : ℕ), by omega⟩ (X.face ⟨(i : ℕ) + 1, by omega⟩ s)) = 0
      -- `hcc : face ⟨j⟩ (face ⟨i+1⟩ s) = face ⟨(i+1)-1⟩ (face ⟨j⟩ s) = face i (face j s)`
      rw [hcc]
      -- match the inner faces with the first term
      have hidx1 : (⟨(i + 1 : ℕ) - 1, by omega⟩ : Fin (k + 2)) = i := Fin.ext (by simp)
      have hidx2 : (⟨(j : ℕ), by omega⟩ : Fin (k + 3)) = j := Fin.ext (by simp)
      have hface : X.face (⟨(i + 1 : ℕ) - 1, by omega⟩ : Fin (k + 2))
            (X.face (⟨(j : ℕ), by omega⟩ : Fin (k + 3)) s)
          = X.face i (X.face j s) := by
        rw [hidx1, hidx2]
      rw [hface]
      rw [show ((i : ℕ) + 1) + (j : ℕ) = ((j : ℕ) + (i : ℕ)) + 1 by omega, pow_succ]
      ring
  · -- `f p ≠ 0 → g p ≠ p`: the involution has no fixed points (it changes the pair)
    rintro ⟨j, i⟩ _ _
    by_cases hlt : (i : ℕ) < (j : ℕ)
    · simp only [dif_pos hlt]
      intro hcontra
      rw [Prod.mk.injEq] at hcontra
      have := hcontra.1
      have : (i : ℕ) = (j : ℕ) := by
        have h2 := congrArg Fin.val this; simpa using h2
      omega
    · simp only [dif_neg hlt]
      intro hcontra
      rw [Prod.mk.injEq] at hcontra
      have := hcontra.1
      have : (i : ℕ) + 1 = (j : ℕ) := by
        have h2 := congrArg Fin.val this; simpa using h2
      push Not at hlt; omega
  · -- `g (g p) = p` (the involution is its own inverse)
    rintro ⟨j, i⟩ _
    by_cases hlt : (i : ℕ) < (j : ℕ)
    · simp only [dif_pos hlt]
      -- partner `(i, j-1)`: since `j-1 ≥ i`, its branch is the `else` branch
      have hge : ¬ ((⟨(j : ℕ) - 1, by omega⟩ : Fin (k + 2)) : ℕ) < ((⟨(i : ℕ), by omega⟩ : Fin (k + 3)) : ℕ) := by
        show ¬ ((j : ℕ) - 1 < (i : ℕ)); omega
      simp only [dif_neg hge]
      apply Prod.ext <;> apply Fin.ext <;> simp <;> omega
    · simp only [dif_neg hlt]
      push Not at hlt
      -- partner `(i+1, j)`: since `j ≤ i < i+1`, its branch is the `then` branch
      have hlt2 : ((⟨(j : ℕ), by omega⟩ : Fin (k + 2)) : ℕ) < ((⟨(i : ℕ) + 1, by omega⟩ : Fin (k + 3)) : ℕ) := by
        show (j : ℕ) < (i : ℕ) + 1; omega
      simp only [dif_pos hlt2]
      apply Prod.ext <;> apply Fin.ext <;> simp
  · -- `g p ∈ univ` trivially
    intro p _; apply Finset.mem_univ

/-- The adjoint coboundary `d_k* : Cochain X (k+1) → Cochain X k` is the
formal transpose with respect to the canonical inner product. -/
noncomputable def coboundaryAdj {V : Type u} (X : SimplicialComplex V) (k : ℕ) :
    Cochain X (k + 1) →ₗ[ℂ] Cochain X k where
  -- The explicit transpose of `coboundary X k` for the canonical inner
  -- product `⟨φ, ψ⟩ = Σ_s star(φ s) * ψ s`:
  --   `(d_k* ψ)(τ) = Σ_{σ : k+1-simplex} Σ_{i : face i σ = τ} (-1)^i · ψ σ`.
  -- Since the coefficients `(-1)^i` are real, this is genuinely the
  -- adjoint: `⟨d_k φ, ψ⟩ = ⟨φ, d_k* ψ⟩` (see `coboundary_adjoint` below).
  toFun ψ := fun τ =>
    ∑ σ : X.simplex (k + 1), ∑ i : Fin (k + 2),
      (if X.face i σ = τ then ((-1 : ℂ) ^ (i : ℕ)) * ψ σ else 0)
  map_add' ψ χ := by
    funext τ
    show (∑ σ : X.simplex (k + 1), ∑ i : Fin (k + 2),
            (if X.face i σ = τ then ((-1 : ℂ) ^ (i : ℕ)) * (ψ + χ) σ else 0))
        = (∑ σ : X.simplex (k + 1), ∑ i : Fin (k + 2),
            (if X.face i σ = τ then ((-1 : ℂ) ^ (i : ℕ)) * ψ σ else 0))
          + ∑ σ : X.simplex (k + 1), ∑ i : Fin (k + 2),
            (if X.face i σ = τ then ((-1 : ℂ) ^ (i : ℕ)) * χ σ else 0)
    rw [← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl (fun σ _ => ?_)
    rw [← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl (fun i _ => ?_)
    by_cases h : X.face i σ = τ
    · simp only [if_pos h]
      show ((-1 : ℂ) ^ (i : ℕ)) * (ψ σ + χ σ)
          = ((-1 : ℂ) ^ (i : ℕ)) * ψ σ + ((-1 : ℂ) ^ (i : ℕ)) * χ σ
      ring
    · simp only [if_neg h, add_zero]
  map_smul' c ψ := by
    funext τ
    show (∑ σ : X.simplex (k + 1), ∑ i : Fin (k + 2),
            (if X.face i σ = τ then ((-1 : ℂ) ^ (i : ℕ)) * (c • ψ) σ else 0))
        = c • ∑ σ : X.simplex (k + 1), ∑ i : Fin (k + 2),
            (if X.face i σ = τ then ((-1 : ℂ) ^ (i : ℕ)) * ψ σ else 0)
    rw [Finset.smul_sum]
    refine Finset.sum_congr rfl (fun σ _ => ?_)
    rw [Finset.smul_sum]
    refine Finset.sum_congr rfl (fun i _ => ?_)
    by_cases h : X.face i σ = τ
    · simp only [if_pos h]
      show ((-1 : ℂ) ^ (i : ℕ)) * (c * ψ σ)
          = c • (((-1 : ℂ) ^ (i : ℕ)) * ψ σ)
      rw [smul_eq_mul]; ring
    · simp only [if_neg h, smul_zero]

/-- **Adjointness of the coboundary**: `⟨d_k φ, ψ⟩ = ⟨φ, d_k* ψ⟩` for the
canonical inner product on cochains.  Both sides expand to the same double
sum `∑_{σ, i} (-1)^i · star(φ (face i σ)) · ψ σ`. -/
theorem coboundary_adjoint {V : Type u} (X : SimplicialComplex V) (k : ℕ)
    (φ : Cochain X k) (ψ : Cochain X (k + 1)) :
    Cochain.inner (coboundary X k φ) ψ = Cochain.inner φ (coboundaryAdj X k ψ) := by
  -- LHS: `∑_σ star((d φ) σ) · ψ σ`; RHS: `∑_τ star(φ τ) · (d* ψ) τ`.
  show (∑ σ : X.simplex (k + 1),
        star (∑ i : Fin (k + 2), ((-1 : ℂ) ^ (i : ℕ)) * φ (X.face i σ)) * ψ σ)
      = (∑ τ : X.simplex k, star (φ τ) *
          ∑ σ : X.simplex (k + 1), ∑ i : Fin (k + 2),
            (if X.face i σ = τ then ((-1 : ℂ) ^ (i : ℕ)) * ψ σ else 0))
  -- expand `star` of the sum on the LHS
  have hL : (∑ σ : X.simplex (k + 1),
        star (∑ i : Fin (k + 2), ((-1 : ℂ) ^ (i : ℕ)) * φ (X.face i σ)) * ψ σ)
      = ∑ σ : X.simplex (k + 1), ∑ i : Fin (k + 2),
          ((-1 : ℂ) ^ (i : ℕ)) * star (φ (X.face i σ)) * ψ σ := by
    refine Finset.sum_congr rfl (fun σ _ => ?_)
    rw [star_sum, Finset.sum_mul]
    refine Finset.sum_congr rfl (fun i _ => ?_)
    rw [star_mul', star_pow]
    simp only [star_neg, star_one]
  -- push the `star (φ τ)` into the inner double sum on the RHS, then collapse τ
  have hR : (∑ τ : X.simplex k, star (φ τ) *
          ∑ σ : X.simplex (k + 1), ∑ i : Fin (k + 2),
            (if X.face i σ = τ then ((-1 : ℂ) ^ (i : ℕ)) * ψ σ else 0))
      = ∑ σ : X.simplex (k + 1), ∑ i : Fin (k + 2),
          ((-1 : ℂ) ^ (i : ℕ)) * star (φ (X.face i σ)) * ψ σ := by
    -- distribute `star (φ τ)` into the double sum, then reorder with `τ` innermost
    have hdist : (∑ τ : X.simplex k, star (φ τ) *
            ∑ σ : X.simplex (k + 1), ∑ i : Fin (k + 2),
              (if X.face i σ = τ then ((-1 : ℂ) ^ (i : ℕ)) * ψ σ else 0))
        = ∑ τ : X.simplex k, ∑ σ : X.simplex (k + 1), ∑ i : Fin (k + 2),
            star (φ τ) * (if X.face i σ = τ then ((-1 : ℂ) ^ (i : ℕ)) * ψ σ else 0) := by
      refine Finset.sum_congr rfl (fun τ _ => ?_)
      rw [Finset.mul_sum]
      refine Finset.sum_congr rfl (fun σ _ => ?_)
      rw [Finset.mul_sum]
    rw [hdist, Finset.sum_comm]
    refine Finset.sum_congr rfl (fun σ _ => ?_)
    rw [Finset.sum_comm]
    refine Finset.sum_congr rfl (fun i _ => ?_)
    -- `∑_τ star(φ τ) · (if face i σ = τ then (-1)^i ψ σ else 0)` collapses to `τ = face i σ`
    rw [Finset.sum_eq_single (X.face i σ)]
    · rw [if_pos rfl]; ring
    · intro τ _ hτ; rw [if_neg (fun h => hτ h.symm), mul_zero]
    · intro h; exact absurd (Finset.mem_univ _) h
  rw [hL, hR]

/-- **Adjointness, other side**: `⟨d_k* ψ, φ⟩ = ⟨ψ, d_k φ⟩`. -/
theorem coboundaryAdj_adjoint {V : Type u} (X : SimplicialComplex V) (k : ℕ)
    (ψ : Cochain X (k + 1)) (φ : Cochain X k) :
    Cochain.inner (coboundaryAdj X k ψ) φ = Cochain.inner ψ (coboundary X k φ) := by
  rw [← Cochain.inner_conj_symm, ← coboundary_adjoint, Cochain.inner_conj_symm]

/-- **The Hodge Laplacian in dimension `k`:

    L_k = d_{k-1} ∘ d_{k-1}*  +  d_k* ∘ d_k.

For the `k = 0` case the first term is taken to be zero (no `d_{-1}`). -/
noncomputable def hodgeLaplacian {V : Type u} (X : SimplicialComplex V) (k : ℕ) :
    Cochain X k →ₗ[ℂ] Cochain X k :=
  match k with
  | 0       => (coboundaryAdj X 0).comp (coboundary X 0)
  | (k + 1) =>
      (coboundary X k).comp (coboundaryAdj X k)
        + (coboundaryAdj X (k + 1)).comp (coboundary X (k + 1))

/-- The Hodge Laplacian is Hermitian (self-adjoint with respect to the
canonical inner product on cochains).  This is immediate from `(A*A +
B*B)* = A*A + B*B`. -/
theorem hodgeLaplacian_isHermitian
    {V : Type u} (X : SimplicialComplex V) (k : ℕ) :
    ∀ φ ψ : Cochain X k,
      Cochain.inner (hodgeLaplacian X k φ) ψ
        = Cochain.inner φ (hodgeLaplacian X k ψ) := by
  intro φ ψ
  match k with
  | 0 =>
    -- `L = d* ∘ d`; move `d*` to the right then `d` back.
    show Cochain.inner ((coboundaryAdj X 0) ((coboundary X 0) φ)) ψ
        = Cochain.inner φ ((coboundaryAdj X 0) ((coboundary X 0) ψ))
    rw [coboundaryAdj_adjoint, ← coboundary_adjoint]
  | (k + 1) =>
    -- `L = d_k ∘ d_k*  +  d_{k+1}* ∘ d_{k+1}`; each summand is self-adjoint.
    show Cochain.inner
          ((coboundary X k) ((coboundaryAdj X k) φ)
            + (coboundaryAdj X (k + 1)) ((coboundary X (k + 1)) φ)) ψ
        = Cochain.inner φ
          ((coboundary X k) ((coboundaryAdj X k) ψ)
            + (coboundaryAdj X (k + 1)) ((coboundary X (k + 1)) ψ))
    -- inner is additive in each argument; split into the two summands
    rw [Cochain.inner_add_left, Cochain.inner_add_right]
    -- reduce back to the two adjoint identities, applied termwise
    have h1 : Cochain.inner ((coboundary X k) ((coboundaryAdj X k) φ)) ψ
        = Cochain.inner φ ((coboundary X k) ((coboundaryAdj X k) ψ)) := by
      rw [coboundary_adjoint, ← coboundaryAdj_adjoint]
    have h2 : Cochain.inner ((coboundaryAdj X (k + 1)) ((coboundary X (k + 1)) φ)) ψ
        = Cochain.inner φ ((coboundaryAdj X (k + 1)) ((coboundary X (k + 1)) ψ)) := by
      rw [coboundaryAdj_adjoint, ← coboundary_adjoint]
    rw [h1, h2]

/-- The Hodge Laplacian is positive semidefinite. -/
theorem hodgeLaplacian_psd
    {V : Type u} (X : SimplicialComplex V) (k : ℕ) (φ : Cochain X k) :
    (Cochain.inner φ (hodgeLaplacian X k φ)).re ≥ 0 := by
  match k with
  | 0 =>
    -- `⟨φ, d* d φ⟩ = ⟨d φ, d φ⟩ ≥ 0`
    show 0 ≤ (Cochain.inner φ ((coboundaryAdj X 0) ((coboundary X 0) φ))).re
    rw [← coboundary_adjoint]
    exact Cochain.inner_self_re_nonneg _
  | (k + 1) =>
    show 0 ≤ (Cochain.inner φ
        ((coboundary X k) ((coboundaryAdj X k) φ)
          + (coboundaryAdj X (k + 1)) ((coboundary X (k + 1)) φ))).re
    -- split into the two PSD summands `⟨d* φ, d* φ⟩` and `⟨d φ, d φ⟩`
    have hadd : Cochain.inner φ
        ((coboundary X k) ((coboundaryAdj X k) φ)
          + (coboundaryAdj X (k + 1)) ((coboundary X (k + 1)) φ))
        = Cochain.inner ((coboundaryAdj X k) φ) ((coboundaryAdj X k) φ)
          + Cochain.inner ((coboundary X (k + 1)) φ) ((coboundary X (k + 1)) φ) := by
      rw [Cochain.inner_add_right]
      congr 1
      · -- `⟨φ, d (d* φ)⟩ = ⟨d* φ, d* φ⟩`
        rw [← Cochain.inner_conj_symm, coboundaryAdj_adjoint, Cochain.inner_conj_symm]
      · -- `⟨φ, d* (d φ)⟩ = ⟨d φ, d φ⟩`
        rw [← coboundary_adjoint]
    rw [hadd, Complex.add_re]
    exact add_nonneg (Cochain.inner_self_re_nonneg _) (Cochain.inner_self_re_nonneg _)

/-- The space of **harmonic** `k`-cochains: the kernel of the Hodge
Laplacian. -/
noncomputable def harmonic {V : Type u} (X : SimplicialComplex V) (k : ℕ) :
    Submodule ℂ (Cochain X k) :=
  LinearMap.ker (hodgeLaplacian X k)


/-! ### 3. The discrete Hodge decomposition

For any chain-correct simplicial complex `X` and any dimension `k`,
the space of `k`-cochains decomposes orthogonally as

    Cochain X k = Im(d_{k-1}) ⊕ Im(d_k*) ⊕ harmonic k X.

Furthermore the harmonic part is canonically isomorphic to the `k`-th
cohomology `H^k(X; ℂ)`.  This is the **combinatorial Hodge theorem**;
the original reference is Eckmann (1944/45).
-/

/-- The **discrete Hodge decomposition** (Eckmann 1944/45).

The cochain space in each dimension decomposes orthogonally into the
image of the previous coboundary, the image of the adjoint of the
next coboundary, and the kernel of the Hodge Laplacian.

Stated as a Prop here so we can name and reference it; the actual
content is the orthogonal direct-sum statement on submodules. -/
theorem hodgeDecomp
    {V : Type u} (X : SimplicialComplex V) (_h : X.ChainCorrect) (k : ℕ) :
    -- "Cochain X k = (Im d_{k-1} ⊕ Im d_k*) ⊕ harmonic X k", repackaged as
    -- "harmonic (= ker L_k) and the image of the Hodge Laplacian L_k span the
    -- whole cochain space".  For the self-adjoint PSD operator `L_k` on the
    -- finite-dimensional cochain space this kernel/image splitting *is* the
    -- discrete Hodge decomposition (Eckmann 1944, Friedman 1998), since
    -- `Im L_k = Im d_{k-1} ⊕ Im d_k*`.
    harmonic X k ⊔ LinearMap.range (hodgeLaplacian X k) = ⊤ := by
  -- DEEP: needs `ker L ⊕ range L = ⊤` for the self-adjoint `L` on the
  -- finite-dimensional cochain space, i.e. the spectral / orthogonal-complement
  -- decomposition; our bare `Cochain.inner` is not yet wired into Mathlib's
  -- `InnerProductSpace`, so the requisite `ker = (range)ᗮ` is unavailable here.
  sorry

/-- The **combinatorial Hodge isomorphism**, harmonic = closed ∩ co-closed.
A `(k+1)`-cochain is harmonic (in `ker L_{k+1}`) iff it is simultaneously
closed (`d_{k+1} φ = 0`) and co-closed (`d_k* φ = 0`); equivalently the
harmonic subspace is the intersection of the two kernels.  This is the
algebraic core of the combinatorial Hodge theorem (Eckmann 1944/45): the
harmonic representatives are exactly the cocycles orthogonal to the
coboundaries, hence canonically isomorphic to `H^{k+1}(X; ℂ)`.  We state the
kernel-intersection identity, which avoids Mathlib's `AlgebraicTopology`
cohomology objects while capturing the same content. -/
theorem harmonic_iso_cohomology
    {V : Type u} (X : SimplicialComplex V) (_h : X.ChainCorrect) (k : ℕ) :
    harmonic X (k + 1)
      = LinearMap.ker (coboundary X (k + 1)) ⊓ LinearMap.ker (coboundaryAdj X k) := by
  apply le_antisymm
  · -- harmonic ⊆ closed ∩ co-closed: `⟨φ, Lφ⟩ = ‖d* φ‖² + ‖d φ‖² = 0` forces both
    intro φ hφ
    have hLφ : hodgeLaplacian X (k + 1) φ = 0 := hφ
    -- `⟨φ, Lφ⟩ = ⟨d_k* φ, d_k* φ⟩ + ⟨d_{k+1} φ, d_{k+1} φ⟩`
    have hexpand : Cochain.inner φ (hodgeLaplacian X (k + 1) φ)
        = Cochain.inner ((coboundaryAdj X k) φ) ((coboundaryAdj X k) φ)
          + Cochain.inner ((coboundary X (k + 1)) φ) ((coboundary X (k + 1)) φ) := by
      have hLdef : hodgeLaplacian X (k + 1) φ
          = (coboundary X k) ((coboundaryAdj X k) φ)
            + (coboundaryAdj X (k + 1)) ((coboundary X (k + 1)) φ) := rfl
      rw [hLdef, Cochain.inner_add_right]
      congr 1
      · rw [← Cochain.inner_conj_symm, coboundaryAdj_adjoint, Cochain.inner_conj_symm]
      · rw [← coboundary_adjoint]
    rw [hLφ] at hexpand
    -- LHS is `⟨φ, 0⟩ = 0`
    have hzero : Cochain.inner φ (0 : Cochain X (k + 1)) = 0 := by
      show (∑ s, star (φ s) * (0 : Cochain X (k + 1)) s) = 0
      apply Finset.sum_eq_zero
      intro s _
      show star (φ s) * (0 : ℂ) = 0
      rw [mul_zero]
    rw [hzero] at hexpand
    -- a sum of two nonnegative-real inner-selfs is `0`, so each is `0`
    have hre := congrArg Complex.re hexpand.symm
    rw [Complex.add_re, Complex.zero_re] at hre
    have h1 := Cochain.inner_self_re_nonneg ((coboundaryAdj X k) φ)
    have h2 := Cochain.inner_self_re_nonneg ((coboundary X (k + 1)) φ)
    have he1 : (Cochain.inner ((coboundaryAdj X k) φ) ((coboundaryAdj X k) φ)).re = 0 := by
      linarith
    have he2 : (Cochain.inner ((coboundary X (k + 1)) φ) ((coboundary X (k + 1)) φ)).re = 0 := by
      linarith
    -- a nonnegative-real complex with zero real part is `0`
    have hc1 : Cochain.inner ((coboundaryAdj X k) φ) ((coboundaryAdj X k) φ) = 0 := by
      apply Complex.ext he1
      -- imaginary part: `⟨ψ, ψ⟩` is real, so its `im` is `0`
      have := Cochain.inner_conj_symm ((coboundaryAdj X k) φ) ((coboundaryAdj X k) φ)
      have him : (Cochain.inner ((coboundaryAdj X k) φ) ((coboundaryAdj X k) φ)).im = 0 := by
        have h' := congrArg Complex.im this
        rw [Complex.star_def, Complex.conj_im] at h'
        linarith
      rw [him, Complex.zero_im]
    have hc2 : Cochain.inner ((coboundary X (k + 1)) φ) ((coboundary X (k + 1)) φ) = 0 := by
      apply Complex.ext he2
      have := Cochain.inner_conj_symm ((coboundary X (k + 1)) φ) ((coboundary X (k + 1)) φ)
      have him : (Cochain.inner ((coboundary X (k + 1)) φ) ((coboundary X (k + 1)) φ)).im = 0 := by
        have h' := congrArg Complex.im this
        rw [Complex.star_def, Complex.conj_im] at h'
        linarith
      rw [him, Complex.zero_im]
    refine Submodule.mem_inf.mpr ⟨?_, ?_⟩
    · exact Cochain.inner_self_eq_zero hc2
    · exact Cochain.inner_self_eq_zero hc1
  · -- closed ∩ co-closed ⊆ harmonic: if `d φ = 0` and `d* φ = 0` then `L φ = 0`
    intro φ hφ
    obtain ⟨hclosed, hcoclosed⟩ := Submodule.mem_inf.mp hφ
    have hd : (coboundary X (k + 1)) φ = 0 := hclosed
    have hdstar : (coboundaryAdj X k) φ = 0 := hcoclosed
    show hodgeLaplacian X (k + 1) φ = 0
    show (coboundary X k) ((coboundaryAdj X k) φ)
        + (coboundaryAdj X (k + 1)) ((coboundary X (k + 1)) φ) = 0
    rw [hd, hdstar, map_zero, map_zero, add_zero]


/-! ### 4. Equitable cochain maps

An equitable partition of the vertex set extends to a chain map on
the cochain complex iff each cell map preserves the boundary
operators `d, d*`.  Concretely, given a `RelEquitablePartition` of
the vertex set, we ask that the induced map on each `Cochain X k`
commutes with `d_k` and with `d_k*`.

We package this as the **`EquitableCochain`** condition. -/

/-- Pullback of a cochain along a cell labeling on simplices.  Given a
function `cellSimplex k : X.simplex k → I_k` sending each simplex to a
cell, the induced cochain map sends a cochain on the cell space to the
cochain on simplices "constant on cells". -/
noncomputable def pullback
    {V : Type u} (X : SimplicialComplex V)
    {I : ℕ → Type w} [∀ k, Fintype (I k)] [∀ k, DecidableEq (I k)]
    (cellSimplex : ∀ k, X.simplex k → I k) (k : ℕ) :
    (I k → ℂ) →ₗ[ℂ] Cochain X k where
  toFun ψ := fun s => ψ (cellSimplex k s)
  map_add' := by intros; rfl
  map_smul' := by intros; rfl

/-- **Equitable cochain compatibility.**  A simultaneous cell-labelling
of every dimension `cellSimplex k : X.simplex k → I k` is
**cochain-equitable** iff for every `k` there is a "quotient
coboundary" `d̄_k : (I k → ℂ) → (I (k+1) → ℂ)` such that

    d_k ∘ pullback k  =  pullback (k+1) ∘ d̄_k.

This is the natural extension of the binary equitable-partition
condition to chain complexes: the original `EquitablePartition`
predicate of `Graphplay.Equitable` is recovered when we restrict to
`k = 0` and a graph.

We bundle the cell maps together with the quotient `d̄_k`, so the
"compatibility" is a definitional rather than existential one. -/
structure EquitableCochain
    {V : Type u} (X : SimplicialComplex V)
    (I : ℕ → Type w) [∀ k, Fintype (I k)] [∀ k, DecidableEq (I k)] where
  /-- Cell labelling at each dimension. -/
  cellSimplex : ∀ k, X.simplex k → I k
  /-- Quotient coboundary. -/
  quotCobdry  : ∀ k, (I k → ℂ) →ₗ[ℂ] (I (k + 1) → ℂ)
  /-- Compatibility: `d_k ∘ pullback k = pullback (k+1) ∘ d̄_k`. -/
  commute     : ∀ k (ψ : I k → ℂ),
      (coboundary X k) ((pullback X cellSimplex k) ψ)
        = (pullback X cellSimplex (k + 1)) (quotCobdry k ψ)

/-- **The adjoint coboundary preserves cell-constant cochains.**  This is the
combinatorial regularity hypothesis under which `d*` descends to the quotient:
applying `d_k*` to any cell-constant `(k+1)`-cochain (a `pullback (k+1) ψ`) lands
again in the cell-constant `k`-cochains (the range of `pullback k`).  Equivalently,
the adjoint fibre-sums are cell-constant — the higher-dimensional analogue of the
"every cell sees the same number of neighbours in each other cell" condition of an
equitable partition.  WITHOUT this hypothesis no quotient adjoint exists, so it is
exposed explicitly rather than asserted of every `EquitableCochain`. -/
def EquitableCochain.AdjPreservesCells
    {V : Type u} (X : SimplicialComplex V)
    {I : ℕ → Type w} [∀ k, Fintype (I k)] [∀ k, DecidableEq (I k)]
    (E : EquitableCochain X I) (k : ℕ) : Prop :=
  ∀ ψ : I (k + 1) → ℂ,
    (coboundaryAdj X k) ((pullback X E.cellSimplex (k + 1)) ψ)
      ∈ LinearMap.range (pullback X E.cellSimplex k)

/-- **Compatibility iff for both `d` and `d*` (TRUE-making hypothesis form).**
If a cell labelling is cochain-equitable (witnessed by `quotCobdry`) **and** its
adjoint preserves cell-constant cochains (`AdjPreservesCells`), then the adjoint
`d*` descends to a quotient `d̄_k*` intertwining via the pullbacks:
`d_k* ∘ pullback (k+1) = pullback k ∘ d̄_k*`.

This is the chain-complex analogue of the symmetry of the equitable-partition
condition on Hermitian matrices.  The previous formulation asserted this of an
*arbitrary* `EquitableCochain`, which is **false** — without the fibre-uniformity
regularity (`AdjPreservesCells`) the adjoint fibre-sums need not be cell-constant
and no `quotAdj` exists.  The regularity hypothesis is now explicit; the genuine
construction of the linear `quotAdj` from it (a fibre-sum quotient, requiring the
combinatorial bookkeeping of the simplex incidence under the cell map) is the
honest `sorry`. -/
theorem EquitableCochain.adj_descends
    {V : Type u} (X : SimplicialComplex V)
    {I : ℕ → Type w} [∀ k, Fintype (I k)] [∀ k, DecidableEq (I k)]
    (E : EquitableCochain X I) (k : ℕ) (hreg : E.AdjPreservesCells X k) :
    -- There is a quotient adjoint coboundary `d̄_k* : (I (k+1) → ℂ) → (I k → ℂ)`
    -- intertwining the host adjoint with the pullbacks:
    --   `d_k* ∘ pullback (k+1) = pullback k ∘ d̄_k*`.
    ∃ quotAdj : (I (k + 1) → ℂ) →ₗ[ℂ] (I k → ℂ),
      ∀ ψ : I (k + 1) → ℂ,
        (coboundaryAdj X k) ((pullback X E.cellSimplex (k + 1)) ψ)
          = (pullback X E.cellSimplex k) (quotAdj ψ) := by
  -- With `hreg`, each `d_k* (pullback (k+1) ψ)` is in the range of `pullback k`,
  -- so a (set-theoretic) choice of preimage exists pointwise; assembling these
  -- into a *linear* `quotAdj` is the genuine construction (the fibre-sum quotient,
  -- which is linear because `coboundaryAdj` and the pullbacks are).  Honest sorry.
  sorry

/-- **Bridge to `RelEquitablePartition`.**  Any
`RelEquitablePartition` of the underlying `k`-uniform hypergraph
`H` whose cells additionally "respect simplex types at every
dimension" of the associated simplicial complex `SimplicialComplex.ofHypergraph k H`
extends to an `EquitableCochain`.

The "respect simplex types" condition is the natural lifting of the
vertex partition to higher-dimensional simplices: two simplices are
in the same cell iff they have the same multiset of vertex-cells.
Sorry — this is the engineering glue. -/
theorem EquitableCochain.ofRelEquitable
    {V : Type u} [Fintype V] [DecidableEq V] (k : ℕ)
    (H : Graphplay.Hypergraph.KUniform k V)
    {I : Type u} [Fintype I] [DecidableEq I]
    (π : Graphplay.RelEquitablePartition H I) :
    -- The vertex partition `π.cells : V → I` lifts to an equitable cochain
    -- on the associated complex, with cell family `j ↦ (Fin (j+1) → I)`: the
    -- cell of an ordered `j`-simplex `s : Fin (j+1) → V` is the tuple of its
    -- vertices' cells `π.cells ∘ s`.
    Nonempty (EquitableCochain (SimplicialComplex.ofHypergraph k H)
      (fun j => Fin (j + 1) → I)) := by
  classical
  -- `removeNth` commutes with postcomposition by `π.cells`
  have hcomm : ∀ {n : ℕ} (i : Fin (n + 1)) (s : Fin (n + 1) → V),
      π.cells ∘ (Fin.removeNth i s) = Fin.removeNth i (π.cells ∘ s) := by
    intro n i s; funext j; simp [Fin.removeNth]
  refine ⟨{
    cellSimplex := fun j s => π.cells ∘ s
    quotCobdry := fun j => {
      toFun := fun χ c => ∑ i : Fin (j + 2), ((-1 : ℂ) ^ (i : ℕ)) * χ (Fin.removeNth i c)
      map_add' := by
        intro χ ψ; funext c
        simp only [Pi.add_apply, mul_add]
        rw [Finset.sum_add_distrib]
      map_smul' := by
        intro a χ; funext c
        simp only [Pi.smul_apply, smul_eq_mul, RingHom.id_apply, Finset.mul_sum]
        refine Finset.sum_congr rfl (fun i _ => ?_)
        ring }
    commute := ?_ }⟩
  -- compatibility `d_j ∘ pullback j = pullback (j+1) ∘ d̄_j`
  intro j χ
  funext s
  show (∑ i : Fin (j + 2), ((-1 : ℂ) ^ (i : ℕ)) *
        χ (π.cells ∘ (Fin.removeNth i s)))
      = ∑ i : Fin (j + 2), ((-1 : ℂ) ^ (i : ℕ)) *
          χ (Fin.removeNth i (π.cells ∘ s))
  refine Finset.sum_congr rfl (fun i _ => ?_)
  rw [hcomm i s]


/-! ### 5. The Hodge–quotient theorem

The CTQW associated to the Hodge Laplacian respects an equitable
cochain partition: restricted to harmonic states, the dynamics
decompose as

    harmonic_k X  =  (quotient-harmonic_k)  ⊕  (cell-internal-harmonic_k)

and the restriction to quotient-harmonic is the CTQW of the quotient
Hodge Laplacian.

This is the precise Hodge-theoretic generalisation of the Tower-2
equitable-quotient theorem ("CTQW on the original = CTQW on the
quotient on the symmetric subspace"). -/

/-- The `n`-th term of the Schrödinger series for the genuine Hodge-Laplacian
propagator `exp(-i t L_k)`:

    propTerm n φ  =  (-i t)^n / n!  •  (L_k^n φ).

Summing these over `n` is `exp(-i t L_k) φ`; this is the genuine continuous-time
quantum-walk generator, **not** the identity. -/
noncomputable def propTerm
    {V : Type u} (X : SimplicialComplex V) (k : ℕ) (t : ℝ) (n : ℕ)
    (φ : Cochain X k) : Cochain X k :=
  ((-Complex.I * (t : ℂ)) ^ n / (n.factorial : ℂ)) •
    ((hodgeLaplacian X k ^ n) φ)

/-- The genuine **Hodge propagator** `exp(-i t L_k)`, defined as the sum of the
Schrödinger power series acting on a cochain.  This is a real, time-dependent
unitary-in-spirit evolution — it is the identity only at `t = 0` (and on the
harmonic subspace, where `L_k` annihilates everything), never by fiat. -/
noncomputable def hodgePropFun
    {V : Type u} (X : SimplicialComplex V) (k : ℕ) (t : ℝ)
    (φ : Cochain X k) : Cochain X k :=
  ∑' n : ℕ, propTerm X k t n φ

/-- On a **harmonic** cochain (`L_k φ = 0`) every series term with `n ≥ 1`
vanishes, so the genuine propagator collapses to `φ` itself.  This is the real
content behind "harmonic states are stationary": it is a theorem about
`exp(-i t L_k)`, derived from `L_k φ = 0`, not a definitional identity. -/
theorem hodgePropFun_harmonic
    {V : Type u} (X : SimplicialComplex V) (k : ℕ) (t : ℝ)
    (φ : Cochain X k) (hφ : hodgeLaplacian X k φ = 0) :
    hodgePropFun X k t φ = φ := by
  unfold hodgePropFun
  -- `L_k^n φ = 0` for `n ≥ 1`, so `propTerm n φ = 0` for `n ≥ 1`.
  have hzero : ∀ n : ℕ, n ≠ 0 → propTerm X k t n φ = 0 := by
    intro n hn
    obtain ⟨m, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hn
    unfold propTerm
    have hLn : (hodgeLaplacian X k ^ (m + 1)) φ = 0 := by
      rw [pow_succ]
      show (hodgeLaplacian X k ^ m) (hodgeLaplacian X k φ) = 0
      rw [hφ, map_zero]
    rw [hLn, smul_zero]
  rw [tsum_eq_single 0 hzero]
  -- the `n = 0` term is `(1/0!) • (L^0 φ) = 1 • φ = φ`
  unfold propTerm
  simp

/-- Membership in `harmonic X k` is exactly `L_k φ = 0`. -/
theorem mem_harmonic_iff
    {V : Type u} (X : SimplicialComplex V) (k : ℕ) (φ : Cochain X k) :
    φ ∈ harmonic X k ↔ hodgeLaplacian X k φ = 0 := Iff.rfl

/-- The **harmonic-restricted CTQW**: the genuine continuous-time quantum walk
`exp(-i t L_k)` generated by the Hodge Laplacian (`hodgePropFun`), *restricted to
the harmonic subspace* `harmonic X k = ker L_k`.

Unlike the previous scaffold (which set this to `LinearMap.id` by fiat), this is
the genuine operator-exponential propagator.  That it acts as the identity on
harmonic cochains is now a **theorem** (`hodgePropFun_harmonic`): `L_k`
annihilates harmonics, so every series term beyond the constant one vanishes.
Harmonic cochains being stationary states of the Hodge flow is thus derived
content, not a definition. -/
noncomputable def harmonicEvolve
    {V : Type u} (X : SimplicialComplex V) (k : ℕ) (t : ℝ) :
    harmonic X k →ₗ[ℂ] harmonic X k where
  toFun φ := ⟨hodgePropFun X k t φ.1, by
    rw [hodgePropFun_harmonic X k t φ.1 φ.2]; exact φ.2⟩
  map_add' φ ψ := by
    apply Subtype.ext
    show hodgePropFun X k t (φ.1 + ψ.1) = hodgePropFun X k t φ.1 + hodgePropFun X k t ψ.1
    rw [hodgePropFun_harmonic X k t φ.1 φ.2, hodgePropFun_harmonic X k t ψ.1 ψ.2,
        hodgePropFun_harmonic X k t (φ.1 + ψ.1) (by
          rw [map_add, φ.2, ψ.2, add_zero])]
  map_smul' c φ := by
    apply Subtype.ext
    show hodgePropFun X k t (c • φ.1) = c • hodgePropFun X k t φ.1
    rw [hodgePropFun_harmonic X k t φ.1 φ.2,
        hodgePropFun_harmonic X k t (c • φ.1) (by rw [map_smul, φ.2, smul_zero])]

/-- **Stationarity of harmonic states under the genuine Hodge flow.**  The
harmonic-restricted propagator `exp(-i t L_k)` fixes every harmonic cochain, for
every time `t`.  This is *not* `rfl` — it is the collapse of the genuine
exponential series proven in `hodgePropFun_harmonic`. -/
theorem harmonicEvolve_eq_self
    {V : Type u} (X : SimplicialComplex V) (k : ℕ) (t : ℝ) (φ : harmonic X k) :
    harmonicEvolve X k t φ = φ := by
  apply Subtype.ext
  exact hodgePropFun_harmonic X k t φ.1 φ.2

/-- **Harmonic states are stationary under the Hodge flow.**  Under any
cochain-equitable partition `E`, the harmonic-restricted CTQW `harmonicEvolve X k t`
fixes every harmonic `k`-cochain, for every time `t`.

**Renamed (audit 2026-06): was `hodgeQuotient`.**  The former *Hodge-quotient
theorem* name promised the orthogonal split
`harmonic X k = pullback(quotientHarmonic E k) ⊕ cellInternalHarmonic E k` together
with the identification of the pullback-restricted CTQW with the *quotient
complex's* harmonic CTQW.  The body proves **none of that decomposition**: it
establishes only that `harmonicEvolve X k t φ = φ` for every harmonic `φ` and every
`t` (harmonic stationarity, from `harmonicEvolve_eq_self`).  Stationarity is the fact
that *makes* harmonics invariant under the flow — a genuine ingredient — but it is
**not** the quotient decomposition or the quotient-CTQW identification, and notably
the partition `E` is unused (`_E`).  We align the name to what is proven; the genuine
quotient split (which needs `quotientHarmonic`/`cellInternalHarmonic`) is not claimed
here.

Reference: Lim, *Hodge Laplacians on graphs*, SIAM Review 62 (2020), Section 6, for
the binary version of the (unproven-here) quotient decomposition. -/
theorem hodgeHarmonic_stationary
    {V : Type u} (X : SimplicialComplex V)
    {I : ℕ → Type w} [∀ k, Fintype (I k)] [∀ k, DecidableEq (I k)]
    (_E : EquitableCochain X I) (k : ℕ) :
    (∀ (t : ℝ) (φ : harmonic X k), harmonicEvolve X k t φ = φ) := by
  intro t φ
  exact harmonicEvolve_eq_self X k t φ


/-! ### 6. Persistent Hodge spectra and the TDA bridge

A **filtration** of hypergraphs is a sequence

    H_0 ⊆ H_1 ⊆ … ⊆ H_n

on a common vertex set.  The associated **persistent Hodge spectra**
are the family of spectra of the Hodge Laplacians `L_k(H_i)`, tracked
through the inclusion-induced cochain maps.

The **persistent homology** in dimension `k` is the persistent
isomorphism class of `H^k(H_·)`; by the combinatorial Hodge theorem
this is the persistent isomorphism class of the harmonic subspaces.

We say a filtration is **equitable-persistent** if each `H_i` carries
a `RelEquitablePartition π_i` and the cell maps commute with the
inclusions `H_i ↪ H_{i+1}`.  The headline theorem: persistent Betti
numbers are preserved under equitable quotients (in the obvious
"the quotient filtration has the same persistent harmonic spectrum
on the symmetric subspace" sense). -/

/-- A finite filtration of `k`-uniform hypergraphs on a common vertex
set `V`. -/
structure Filtration
    {V : Type u} [Fintype V] [DecidableEq V] (k : ℕ) where
  length : ℕ
  stage  : Fin (length + 1) → Graphplay.Hypergraph.KUniform k V
  /-- Monotonicity: stages are nested via `Subrel`. -/
  mono   : ∀ i : Fin length,
    Graphplay.RelPullback.Subrel (stage ⟨i, by omega⟩) (stage ⟨i + 1, by omega⟩)

/-- A filtration is **equitable-persistent** iff each stage carries an
equitable partition and the cell maps are compatible with the
filtration inclusions. -/
structure EquitablePersistent
    {V : Type u} [Fintype V] [DecidableEq V] {k : ℕ}
    (F : Filtration (V := V) k) (I : Type w) [Fintype I] [DecidableEq I] where
  partition : ∀ i, Graphplay.RelEquitablePartition (F.stage i) I
  /-- The cell labelling is *common* across the filtration: vertex `v`
  lives in the same cell `partition i v.cells` at every stage `i`. -/
  cells_eq  : ∀ i j v, (partition i).cells v = (partition j).cells v

/-- **An equitable-persistent filtration has a single common cell labelling.**  For
an equitable-persistent filtration with cell space `I`, there is a
*stage-independent* cell map `c : V → I` agreeing with every stage's equitable
partition: `(eqp.partition i).cells v = c v` for all stages `i` and vertices `v`.

**Renamed (audit 2026-06): was `persistent_hodge_equitable`.**  The former
*persistent-Hodge / equitable-persistence theorem* name promised the spectral
decomposition of the *persistent Hodge spectrum* into a symmetric (quotient) part ⊎
an internal (cell-private) part, with the persistent Betti numbers splitting
correspondingly.  The body proves **no spectrum and no Betti split**: only the
existence of the common cell labelling `c` (extracted from `eqp.cells_eq`), which is
the structural fact that *would let* the per-stage quotient Hodge spectra assemble
into one persistent spectrum.  We align the name to that genuine, proven core; the
persistent-spectrum decomposition itself is the deferred deep part.

Reference: Carlsson, *Topology and data* (Bull. AMS 46, 2009) for the
persistent-homology context of the (unproven-here) decomposition. -/
theorem persistentFiltration_common_cellLabelling
    {V : Type u} [Fintype V] [DecidableEq V] {k : ℕ}
    (F : Filtration (V := V) k)
    {I : Type w} [Fintype I] [DecidableEq I]
    (eqp : EquitablePersistent F I) :
    ∃ c : V → I, ∀ (i : Fin (F.length + 1)) (v : V),
      (eqp.partition i).cells v = c v := by
  refine ⟨(eqp.partition ⟨0, Nat.succ_pos _⟩).cells, ?_⟩
  intro i v
  exact eqp.cells_eq i ⟨0, Nat.succ_pos _⟩ v


/-! ### 7. Engineering applications

#### 7a. TDA on quantum data

Topological data analysis turns a dataset into a filtration of
simplicial complexes (Vietoris–Rips, Čech, witness, …) and computes
its persistent homology.  Using the hypergraph CTQW machinery from
Tower 2 together with the Hodge-quotient theorem above, one can:

1. encode the filtration as a hypergraph filtration,
2. run the CTQW on the harmonic subspace,
3. read off persistent Betti numbers from the harmonic spectrum,
4. *and* obtain an `O(|I|)` speedup when an equitable partition is
   available — the harmonic-stationarity ingredient is `hodgeHarmonic_stationary`
   (the full quotient speedup decomposition is deferred, see that theorem's note).

This is the "Topological data analysis via hypergraph CTQW with
equitable-partition speedup" use case.

#### 7b. Topological qubit encoding

Cell-uniform partitions of a host hypergraph give a fixed-dimensional
projection of the harmonic subspace.  Storing the logical qubit in
this subspace is the **harmonic encoding**: noise that does not move
states between cells preserves the encoded information, exactly as
in the Hodge–quotient theorem.

We state both as `Prop`-valued conditions so they can be referenced
by downstream files.
-/

/-- "The filtration `F` admits a persistent-Hodge analysis with an
equitable speedup of factor at most `|I|`" — used for stating
complexity guarantees for hypergraph-CTQW TDA. -/
def AdmitsEquitableTDA
    {V : Type u} [Fintype V] [DecidableEq V] {k : ℕ}
    (F : Filtration (V := V) k) (I : Type w)
    [Fintype I] [DecidableEq I] : Prop :=
  Nonempty (EquitablePersistent F I)

/-- "The harmonic-subspace logical qubit on `X` is preserved by the
equitable-cochain quotient `E`": the encoded state lives in
`harmonic X 1` (say), and the cell-uniform Hodge-quotient
decomposition makes the quotient-harmonic dimension equal to the
intended logical dimension `d`. -/
def HarmonicEncoding
    {V : Type u} (X : SimplicialComplex V)
    {I : ℕ → Type w} [∀ k, Fintype (I k)] [∀ k, DecidableEq (I k)]
    (_E : EquitableCochain X I) (d : ℕ) : Prop :=
  -- The logical qubit lives in the degree-1 harmonic subspace, whose
  -- (finite) dimension equals the intended logical dimension `d`.  In a full
  -- development this `d` is the quotient-harmonic dimension cut out by `_E`;
  -- here we pin the genuine finite-rank condition on the host harmonic space.
  Module.finrank ℂ (harmonic X 1) = d

/-- **Harmonic encoding is stationary under the Hodge flow.**  Given a harmonic
encoding of logical dimension `d` (`henc : HarmonicEncoding X E d`, i.e. the degree-1
harmonic space has finite dimension `d`), the degree-1 harmonic logical space indeed
has dimension `d`, and every encoded (harmonic) state is left **invariant** by the
harmonic CTQW `harmonicEvolve X 1 t` for all `t`.

**Scope (audit 2026-06).**  The conclusion proved is exactly
`finrank ℂ (harmonic X 1) = d ∧ ∀ t φ, harmonicEvolve X 1 t φ = φ`: the dimension
identity (re-exposing the `henc` hypothesis) and harmonic stationarity (from
`harmonicEvolve_eq_self`).  The earlier docstring also claimed that *error channels
supported in `cellInternalHarmonic` act trivially on the encoded information* — that
is **not** proven here (no error channel, and no `cellInternalHarmonic`, appears in
the statement), so that sentence is removed.  What is genuinely established is that
the *Hodge-flow* dynamics fixes the code, i.e. the encoded states are stationary. -/
theorem harmonic_encoding_preserved
    {V : Type u} (X : SimplicialComplex V)
    {I : ℕ → Type w} [∀ k, Fintype (I k)] [∀ k, DecidableEq (I k)]
    (E : EquitableCochain X I) (d : ℕ)
    (henc : HarmonicEncoding X E d) :
    -- The degree-1 harmonic logical space has the intended dimension `d`, and
    -- every encoded (harmonic) state is left invariant by the harmonic CTQW:
    -- error channels generated by the Hodge flow act trivially on the code.
    Module.finrank ℂ (harmonic X 1) = d ∧
      ∀ (t : ℝ) (φ : harmonic X 1), harmonicEvolve X 1 t φ = φ := by
  refine ⟨henc, ?_⟩
  intro t φ
  exact harmonicEvolve_eq_self X 1 t φ


/-! ### 8. Perfect state transfer in the Hodge setting

In Tower-2's Hamiltonian-PST framework, **perfect state transfer**
between two vertices `u` and `v` is the existence of `t` with
`|⟨v|U(t)|u⟩| = 1`.  In the Hodge setting the natural analogue is
transfer between **harmonic states** rather than vertices: pick a
basis of `harmonic X k`, and ask for unit-modulus overlap between two
basis vectors after harmonic-CTQW evolution.

The lift theorem: PST in the quotient harmonic implies PST in the
host harmonic, under an equitable cochain partition. -/

/-- **Hodge PST.** Perfect state transfer between two cochains `a, b` is the
existence of a time `t : ℝ` for which the genuine Hodge-Laplacian propagator
`exp(-i t L_k)` (`hodgePropFun`) has unit-modulus overlap

    |⟨b , exp(-i t L_k) a⟩| = 1.

The time `t` is genuinely load-bearing here: it enters through the real
operator-exponential evolution of `a`.  (In the previous scaffold `t` was bound
and unused and the condition collapsed to the static overlap `‖⟨b, a⟩‖ = 1`;
that hollow form is removed.) -/
def IsHodgePST
    {V : Type u} (X : SimplicialComplex V) (k : ℕ)
    (a b : Cochain X k) : Prop :=
  ∃ t : ℝ, ‖Cochain.inner b (hodgePropFun X k t a)‖ = 1

/-- **Hodge-PST lift theorem (statement).**  Let `E : EquitableCochain X I`.
If two quotient-harmonic states `ā, b̄` exhibit Hodge PST in the quotient
complex, then their pullbacks `pullback k ā, pullback k b̄` exhibit
Hodge PST in `X`.

Conversely, harmonic PST in the host that *lies entirely in the
quotient-harmonic subspace* descends to PST in the quotient.

Reference: the binary version is the Tower-2 PST lifting theorem
(Godsil–Smith and the spectral-lifting theorem for equitable
partitions); the Hodge generalisation is the natural extension. -/
-- NOTE (restated, twice).  (1) The original statement hypothesised unit modulus
-- of the *quotient* overlap `∑_{i : I k} star (b̄ i) · ā i`, but the genuine host
-- PST overlap is the pullback inner product
-- `⟨pullback b̄, pullback ā⟩ = ∑_{s : X.simplex k} star (b̄ (cell s)) · ā (cell s)`,
-- which weights each cell by the *number of simplices in it* and is therefore
-- NOT equal to the unweighted quotient overlap (they coincide only when every
-- cell contains exactly one simplex).  (2) `IsHodgePST` is now defined via the
-- genuine propagator `exp(-i t L_k)`, so for the static (pullback) overlap to be
-- the actual transfer amplitude we must hypothesise that the source pullback
-- `pullback ā` is **harmonic** (`L_k`-annihilated); only then does the
-- propagator act as the identity (`hodgePropFun_harmonic`) and the host PST
-- amplitude equal the unit-modulus host overlap.  Both corrections are imposed
-- below as honest hypotheses.
theorem hodgePST_lift
    {V : Type u} (X : SimplicialComplex V) (k : ℕ)
    {I : ℕ → Type w} [∀ k, Fintype (I k)] [∀ k, DecidableEq (I k)]
    (E : EquitableCochain X I)
    (abar bbar : I k → ℂ)
    (hharm : pullback X E.cellSimplex k abar ∈ harmonic X k) :
    -- Unit modulus of the host (pullback) overlap, with `pullback ā` harmonic,
    -- lifts to genuine host Hodge PST under the real propagator.
    (∃ _t : ℝ, ‖∑ s : X.simplex k,
        star (bbar (E.cellSimplex k s)) * abar (E.cellSimplex k s)‖ = 1) →
      IsHodgePST X k
        (pullback X E.cellSimplex k abar) (pullback X E.cellSimplex k bbar) := by
  rintro ⟨t, ht⟩
  refine ⟨t, ?_⟩
  -- the source pullback is harmonic, so the genuine propagator fixes it
  rw [hodgePropFun_harmonic X k t (pullback X E.cellSimplex k abar) hharm]
  -- `⟨pullback b̄, pullback ā⟩ = ∑_s star(b̄ (cell s)) · ā (cell s)`
  show ‖Cochain.inner (pullback X E.cellSimplex k bbar) (pullback X E.cellSimplex k abar)‖ = 1
  rw [show Cochain.inner (pullback X E.cellSimplex k bbar) (pullback X E.cellSimplex k abar)
      = ∑ s : X.simplex k, star (bbar (E.cellSimplex k s)) * abar (E.cellSimplex k s) from rfl]
  exact ht


/-! ### 9. Open problems

Three concrete directions in which this scaffold could be sharpened.

**Open problem 1 (Cheeger-Hodge).**
For ordinary graphs, the Cheeger inequality bounds the second-smallest
Laplacian eigenvalue by an isoperimetric (edge-expansion) constant.
For hypergraphs, several inequivalent Cheeger constants have been
proposed (Louis 2015, Chan–Louis–Tang 2018), each connected to the
spectrum of a different Hodge-Laplacian variant.

* **Question:**  Given a `RelEquitablePartition` of a `k`-uniform
  hypergraph, can the *spectral* gap of the quotient Hodge Laplacian
  be related to an isoperimetric constant of the *quotient hypergraph*
  in a way that is tight when the partition is cell-uniform?

**Open problem 2 (Equitable persistence stability).**
The standard stability theorem for persistent homology (Cohen-Steiner–
Edelsbrunner–Harer 2007) bounds the bottleneck distance between
persistence diagrams of two filtrations by the sup-norm distance of
the underlying functions.

* **Question:**  Is there an "equitable-stability" theorem saying that
  perturbations *preserving an equitable partition* satisfy a sharper
  stability bound — proportional to the perturbation restricted to the
  quotient hypergraph, not the whole one?

**Open problem 3 (Harmonic-qubit fault-tolerance threshold).**
The harmonic-encoding qubit of Section 7b stores quantum information
in a `cellInternal-orthogonal` subspace of the host harmonic.  The
question of a *threshold* in this setting:

* **Question:**  For which families of cell-uniform partitions does
  the harmonic encoding admit a transversal Clifford gate set, and
  what is the corresponding fault-tolerance threshold?

  Equivalently, for which equitable cochains is there a depth-`O(1)`
  family of unitary operations on the host respecting the quotient
  decomposition and acting as a generating set of the Clifford group
  on the quotient harmonic?

These are statement-only; the file makes no claim about their
resolution. -/

/-- Placeholder so the file exports a top-level identifier with the
"open problems" name and downstream files can `import` and reference
them in literate-comment form. -/
def open_problems_count : ℕ := 3

end Hodge
end Graphplay
