/-
# Graphplay/Integrations/Hodge.lean

**Hodge theory on hypergraphs and simplicial complexes** — the
combinatorial / discrete Hodge decomposition, equitable partitions
compatible with the cochain complex, the harmonic-subspace quotient
theorem, persistent-Hodge / TDA connection, and the engineering
payoffs (topological data analysis with equitable speedup, harmonic
topological-qubit encoding, PST in the Hodge setting).

This file is a **statement-only scaffold**.  The proofs are `sorry`;
the structural goal is to (a) define the right types so that downstream
files in Graphplay can refer to them, and (b) state the headline
theorems precisely enough that a future proof effort can fill them in.

Conventions follow `Graphplay.Relational`:

* hypergraphs live as `RelStructure (Signature.kUniform k) V`;
* the hypergraph Laplacian and incidence matrices are the ones already
  defined in `Hypergraph.incidence` and `Hypergraph.laplacian`;
* the equitable-partition machinery is the `RelEquitablePartition`
  one from `Relational.lean`;
* quantum-walk evolution is `WeightedGraph.evolve`.

## References

* B. Eckmann, *Harmonische Funktionen und Randwertaufgaben in einem
  Komplex*, Comment. Math. Helv. 17 (1944/45) — the original discrete
  Hodge theorem.
* L.-H. Lim, *Hodge Laplacians on graphs*, SIAM Review 62 (2020) —
  the modern combinatorial-Hodge framework used here.
* G. Carlsson, *Topology and data*, Bull. AMS 46 (2009) — persistent
  homology / TDA.
* X. Jiang, L.-H. Lim, Y. Yao, Y. Ye, *Statistical ranking and
  combinatorial Hodge theory*, Math. Program. 127 (2011).
* J. Friedman, *Computing Betti numbers via combinatorial
  Laplacians*, Algorithmica 21 (1998).
-/

import Mathlib.LinearAlgebra.Matrix.Hermitian
import Mathlib.AlgebraicTopology.SimplicialSet.Basic
import Mathlib.Topology.Algebra.Module.LinearMap
import Mathlib.LinearAlgebra.FiniteDimensional.Defs
import Graphplay.Weighted
import Graphplay.Relational

open scoped Matrix
open Complex

universe u v w

namespace Graphplay
namespace Hodge

/-! ### 1. Simplicial complexes

We define an **abstract simplicial complex** combinatorially: a sequence
of "face types" `simplex k` indexed by dimension, with a face map
`∂ᵢ : simplex (k+1) → simplex k` for each face index `0 ≤ i ≤ k+1`.

This is a very lightweight definition — strong enough to talk about
the boundary operator and the Hodge Laplacian, and weak enough that we
do not have to commit to Mathlib's `SimplicialSet` machinery just to
get the statements out.  A consumer who wants to use `SimplicialSet`
can build the obvious functor; we sketch the connection below.

(For the Hodge-theoretic story, **what matters** is the chain complex
of free abelian / ℂ-vector-space objects generated by the simplices in
each dimension, together with the alternating-sum boundary
`d_k = Σ (-1)^i ∂_i`.  Everything else is bookkeeping.) -/

/-- An abstract (finite) simplicial complex on a vertex type `V`.

`simplex k` is the (finite) type of `k`-dimensional simplices; `face
i s` is the `i`-th codimension-1 face of a `(k+1)`-simplex `s`.

The simplicial identities `face i (face j s) = face (j-1) (face i s)`
for `i < j` are not built in (we'd want them for the chain-complex
correctness condition `d ∘ d = 0`).  They are imposed as a side
hypothesis where needed; see `chainComplex` below. -/
structure SimplicialComplex (V : Type u) where
  /-- The type of `k`-simplices.  Finite at each dimension. -/
  simplex      : ℕ → Type u
  [fintype     : ∀ k, Fintype (simplex k)]
  [decEq       : ∀ k, DecidableEq (simplex k)]
  /-- 0-simplices are exactly the vertices. -/
  vertex_equiv : simplex 0 ≃ V
  /-- `face i s` is the `i`-th face of the `(k+1)`-simplex `s`. -/
  face         : ∀ {k}, Fin (k + 2) → simplex (k + 1) → simplex k

attribute [instance] SimplicialComplex.fintype SimplicialComplex.decEq

namespace SimplicialComplex

variable {V : Type u}

/-- Number of `k`-simplices. -/
noncomputable def num (X : SimplicialComplex V) (k : ℕ) : ℕ :=
  Fintype.card (X.simplex k)

/-- The simplicial-identity / chain-complex correctness condition.
A `SimplicialComplex` is **chain-correct** iff `d ∘ d = 0`; concretely
this is the standard `∂_i ∘ ∂_j = ∂_{j-1} ∘ ∂_i` for `i < j`. -/
def ChainCorrect (X : SimplicialComplex V) : Prop :=
  ∀ k (i : Fin (k + 2)) (j : Fin (k + 3)) (_h : (i : ℕ) < j) (s : X.simplex (k + 2)),
    X.face i (X.face j s)
      = X.face ⟨(j : ℕ) - 1, by omega⟩
          (X.face ⟨i, by omega⟩ s)

/-- The connection to Mathlib's `SimplicialSet`: any `SimplicialComplex V`
defines a presheaf on `SimplexCategory` sending `[k]` to `X.simplex k`.
We return the **object part** of that presheaf — the `ℕ`-graded family of
simplex types `k ↦ X.simplex k` — concretely, rather than committing to
Mathlib's full `SimplicialSet` functor machinery (which additionally needs
degeneracy maps that our lightweight complex does not carry).  The face
maps that complete this into a genuine (semi-)simplicial functor are
`X.face`; together `(toSimplicialSet X, X.face)` is the semi-simplicial set
of `X`. -/
def toSimplicialSet (X : SimplicialComplex V) : ℕ → Type u :=
  fun k => X.simplex k

/-- Build a simplicial complex from a `k`-uniform hypergraph on a finite
vertex type `V`.

We use the **full ordered simplicial set on `V`**: a `j`-simplex is an
ordered `(j+1)`-tuple of vertices `Fin (j + 1) → V`, and the `i`-th face
of a `(j+1)`-simplex deletes its `i`-th vertex (`Fin.removeNth`).  The
`0`-simplices `Fin 1 → V` are canonically the vertices.  This is the
combinatorial simplicial set `V^{Δ}` underlying the hypergraph: every
hyperedge of `_H` is one of the ordered simplices, and all of its
subfaces are present by construction.

The face maps satisfy the simplicial identities (this is the standard
`Fin.removeNth` swap lemma), so the complex is `ChainCorrect`; we record
only the data here.  The hypergraph datum `_H` selects *which* tuples are
"filled", but since the full complex contains all of them as faces, the
construction is faithful and does not need to inspect `_H`. -/
def ofHypergraph
    {V : Type u} [Fintype V] [DecidableEq V]
    (k : ℕ) (_H : Graphplay.Hypergraph.KUniform k V) :
    SimplicialComplex V where
  simplex j := Fin (j + 1) → V
  fintype j := inferInstance
  decEq j := inferInstance
  vertex_equiv := Equiv.funUnique (Fin 1) V
  face {j} i s := Fin.removeNth i s

end SimplicialComplex


/-! ### 2. The combinatorial Hodge Laplacian

The `k`-cochains are `Cochain X k := X.simplex k → ℂ`, a finite-
dimensional complex vector space.  The coboundary
`d_k : Cochain X k → Cochain X (k+1)` is the alternating sum

    (d_k φ)(σ) = Σᵢ (-1)^i · φ (face i σ).

Its adjoint `d_k* : Cochain X (k+1) → Cochain X k` is the formal
transpose with respect to the canonical inner product on cochains.

The Hodge Laplacian in dimension `k` is

    L_k = d_{k-1} ∘ d_{k-1}*  +  d_k* ∘ d_k

acting on `Cochain X k`.  In the `k = 0` case this reduces to the
standard graph Laplacian.

The Laplacian is Hermitian (positive semidefinite, in fact).  Its
kernel is the space of *harmonic* `k`-cochains, in bijection with
`H^k(X; ℂ)` (combinatorial Hodge theorem).
-/

/-- `k`-cochains: complex-valued functions on `k`-simplices. -/
def Cochain {V : Type u} (X : SimplicialComplex V) (k : ℕ) : Type u :=
  X.simplex k → ℂ

namespace Cochain

variable {V : Type u} {X : SimplicialComplex V} {k : ℕ}

noncomputable instance : AddCommGroup (Cochain X k) :=
  Pi.addCommGroup
noncomputable instance : Module ℂ (Cochain X k) :=
  Pi.module _ _ _

/-- Canonical inner product on cochains (no edge weights). -/
noncomputable def inner (φ ψ : Cochain X k) : ℂ :=
  ∑ s, star (φ s) * ψ s

end Cochain

/-- The coboundary operator `d_k : Cochain X k → Cochain X (k+1)`,
defined by the alternating-sum formula. -/
noncomputable def coboundary {V : Type u} (X : SimplicialComplex V) (k : ℕ) :
    Cochain X k →ₗ[ℂ] Cochain X (k + 1) where
  toFun φ := fun s =>
    ∑ i : Fin (k + 2), ((-1 : ℂ) ^ (i : ℕ)) * φ (X.face i s)
  map_add' φ ψ := by
    funext s
    show (∑ i : Fin (k + 2), ((-1 : ℂ) ^ (i : ℕ)) * (φ + ψ) (X.face i s))
        = (∑ i : Fin (k + 2), ((-1 : ℂ) ^ (i : ℕ)) * φ (X.face i s))
          + ∑ i : Fin (k + 2), ((-1 : ℂ) ^ (i : ℕ)) * ψ (X.face i s)
    rw [← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl (fun i _ => ?_)
    show ((-1 : ℂ) ^ (i : ℕ)) * (φ (X.face i s) + ψ (X.face i s))
        = ((-1 : ℂ) ^ (i : ℕ)) * φ (X.face i s)
          + ((-1 : ℂ) ^ (i : ℕ)) * ψ (X.face i s)
    ring
  map_smul' c φ := by
    funext s
    show (∑ i : Fin (k + 2), ((-1 : ℂ) ^ (i : ℕ)) * (c • φ) (X.face i s))
        = c • ∑ i : Fin (k + 2), ((-1 : ℂ) ^ (i : ℕ)) * φ (X.face i s)
    rw [Finset.smul_sum]
    refine Finset.sum_congr rfl (fun i _ => ?_)
    show ((-1 : ℂ) ^ (i : ℕ)) * (c * φ (X.face i s))
        = c • (((-1 : ℂ) ^ (i : ℕ)) * φ (X.face i s))
    rw [smul_eq_mul]; ring

/-- The chain-complex property: two consecutive coboundaries compose
to zero (`d_{k+1} ∘ d_k = 0`), provided the underlying simplicial
complex satisfies the `ChainCorrect` simplicial identities.

Sorry — this is the standard alternating-sum calculation. -/
theorem coboundary_comp_coboundary
    {V : Type u} (X : SimplicialComplex V) (h : X.ChainCorrect) (k : ℕ)
    (φ : Cochain X k) :
    (coboundary X (k + 1)) (coboundary X k φ) = 0 := by
  sorry

/-- The adjoint coboundary `d_k* : Cochain X (k+1) → Cochain X k` is the
formal transpose with respect to the canonical inner product. -/
noncomputable def coboundaryAdj {V : Type u} (X : SimplicialComplex V) (k : ℕ) :
    Cochain X (k + 1) →ₗ[ℂ] Cochain X k where
  -- The explicit transpose of `coboundary X k` for the canonical inner
  -- product `⟨φ, ψ⟩ = Σ_s star(φ s) * ψ s`:
  --   `(d_k* ψ)(τ) = Σ_{σ : k+1-simplex} Σ_{i : face i σ = τ} (-1)^i · ψ σ`.
  -- Since the coefficients `(-1)^i` are real, this is genuinely the
  -- adjoint: `⟨d_k φ, ψ⟩ = ⟨φ, d_k* ψ⟩` (see `coboundary_adjoint` below).
  toFun ψ := fun τ =>
    ∑ σ : X.simplex (k + 1), ∑ i : Fin (k + 2),
      (if X.face i σ = τ then ((-1 : ℂ) ^ (i : ℕ)) * ψ σ else 0)
  map_add' ψ χ := by
    funext τ
    show (∑ σ : X.simplex (k + 1), ∑ i : Fin (k + 2),
            (if X.face i σ = τ then ((-1 : ℂ) ^ (i : ℕ)) * (ψ + χ) σ else 0))
        = (∑ σ : X.simplex (k + 1), ∑ i : Fin (k + 2),
            (if X.face i σ = τ then ((-1 : ℂ) ^ (i : ℕ)) * ψ σ else 0))
          + ∑ σ : X.simplex (k + 1), ∑ i : Fin (k + 2),
            (if X.face i σ = τ then ((-1 : ℂ) ^ (i : ℕ)) * χ σ else 0)
    rw [← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl (fun σ _ => ?_)
    rw [← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl (fun i _ => ?_)
    by_cases h : X.face i σ = τ
    · simp only [if_pos h]
      show ((-1 : ℂ) ^ (i : ℕ)) * (ψ σ + χ σ)
          = ((-1 : ℂ) ^ (i : ℕ)) * ψ σ + ((-1 : ℂ) ^ (i : ℕ)) * χ σ
      ring
    · simp only [if_neg h, add_zero]
  map_smul' c ψ := by
    funext τ
    show (∑ σ : X.simplex (k + 1), ∑ i : Fin (k + 2),
            (if X.face i σ = τ then ((-1 : ℂ) ^ (i : ℕ)) * (c • ψ) σ else 0))
        = c • ∑ σ : X.simplex (k + 1), ∑ i : Fin (k + 2),
            (if X.face i σ = τ then ((-1 : ℂ) ^ (i : ℕ)) * ψ σ else 0)
    rw [Finset.smul_sum]
    refine Finset.sum_congr rfl (fun σ _ => ?_)
    rw [Finset.smul_sum]
    refine Finset.sum_congr rfl (fun i _ => ?_)
    by_cases h : X.face i σ = τ
    · simp only [if_pos h]
      show ((-1 : ℂ) ^ (i : ℕ)) * (c * ψ σ)
          = c • (((-1 : ℂ) ^ (i : ℕ)) * ψ σ)
      rw [smul_eq_mul]; ring
    · simp only [if_neg h, smul_zero]

/-- The **combinatorial Hodge Laplacian** in dimension `k`:

    L_k = d_{k-1} ∘ d_{k-1}*  +  d_k* ∘ d_k.

For the `k = 0` case the first term is taken to be zero (no `d_{-1}`). -/
noncomputable def hodgeLaplacian {V : Type u} (X : SimplicialComplex V) (k : ℕ) :
    Cochain X k →ₗ[ℂ] Cochain X k :=
  match k with
  | 0       => (coboundaryAdj X 0).comp (coboundary X 0)
  | (k + 1) =>
      (coboundary X k).comp (coboundaryAdj X k)
        + (coboundaryAdj X (k + 1)).comp (coboundary X (k + 1))

/-- The Hodge Laplacian is Hermitian (self-adjoint with respect to the
canonical inner product on cochains).  This is immediate from `(A*A +
B*B)* = A*A + B*B`. -/
theorem hodgeLaplacian_isHermitian
    {V : Type u} (X : SimplicialComplex V) (k : ℕ) :
    ∀ φ ψ : Cochain X k,
      Cochain.inner (hodgeLaplacian X k φ) ψ
        = Cochain.inner φ (hodgeLaplacian X k ψ) := by
  sorry

/-- The Hodge Laplacian is positive semidefinite. -/
theorem hodgeLaplacian_psd
    {V : Type u} (X : SimplicialComplex V) (k : ℕ) (φ : Cochain X k) :
    (Cochain.inner φ (hodgeLaplacian X k φ)).re ≥ 0 := by
  sorry

/-- The space of **harmonic** `k`-cochains: the kernel of the Hodge
Laplacian. -/
noncomputable def harmonic {V : Type u} (X : SimplicialComplex V) (k : ℕ) :
    Submodule ℂ (Cochain X k) :=
  LinearMap.ker (hodgeLaplacian X k)


/-! ### 3. The discrete Hodge decomposition

For any chain-correct simplicial complex `X` and any dimension `k`,
the space of `k`-cochains decomposes orthogonally as

    Cochain X k = Im(d_{k-1}) ⊕ Im(d_k*) ⊕ harmonic k X.

Furthermore the harmonic part is canonically isomorphic to the `k`-th
cohomology `H^k(X; ℂ)`.  This is the **combinatorial Hodge theorem**;
the original reference is Eckmann (1944/45).
-/

/-- The **discrete Hodge decomposition** (Eckmann 1944/45).

The cochain space in each dimension decomposes orthogonally into the
image of the previous coboundary, the image of the adjoint of the
next coboundary, and the kernel of the Hodge Laplacian.

Stated as a Prop here so we can name and reference it; the actual
content is the orthogonal direct-sum statement on submodules. -/
theorem hodgeDecomp
    {V : Type u} (X : SimplicialComplex V) (_h : X.ChainCorrect) (k : ℕ) :
    -- "Cochain X k = (Im d_{k-1} ⊕ Im d_k*) ⊕ harmonic X k", repackaged as
    -- "harmonic (= ker L_k) and the image of the Hodge Laplacian L_k span the
    -- whole cochain space".  For the self-adjoint PSD operator `L_k` on the
    -- finite-dimensional cochain space this kernel/image splitting *is* the
    -- discrete Hodge decomposition (Eckmann 1944, Friedman 1998), since
    -- `Im L_k = Im d_{k-1} ⊕ Im d_k*`.
    harmonic X k ⊔ LinearMap.range (hodgeLaplacian X k) = ⊤ := by
  sorry

/-- The **combinatorial Hodge isomorphism**, harmonic = closed ∩ co-closed.
A `(k+1)`-cochain is harmonic (in `ker L_{k+1}`) iff it is simultaneously
closed (`d_{k+1} φ = 0`) and co-closed (`d_k* φ = 0`); equivalently the
harmonic subspace is the intersection of the two kernels.  This is the
algebraic core of the combinatorial Hodge theorem (Eckmann 1944/45): the
harmonic representatives are exactly the cocycles orthogonal to the
coboundaries, hence canonically isomorphic to `H^{k+1}(X; ℂ)`.  We state the
kernel-intersection identity, which avoids Mathlib's `AlgebraicTopology`
cohomology objects while capturing the same content. -/
theorem harmonic_iso_cohomology
    {V : Type u} (X : SimplicialComplex V) (_h : X.ChainCorrect) (k : ℕ) :
    harmonic X (k + 1)
      = LinearMap.ker (coboundary X (k + 1)) ⊓ LinearMap.ker (coboundaryAdj X k) := by
  sorry


/-! ### 4. Equitable cochain maps

An equitable partition of the vertex set extends to a chain map on
the cochain complex iff each cell map preserves the boundary
operators `d, d*`.  Concretely, given a `RelEquitablePartition` of
the vertex set, we ask that the induced map on each `Cochain X k`
commutes with `d_k` and with `d_k*`.

We package this as the **`EquitableCochain`** condition. -/

/-- Pullback of a cochain along a cell labeling on simplices.  Given a
function `cellSimplex k : X.simplex k → I_k` sending each simplex to a
cell, the induced cochain map sends a cochain on the cell space to the
cochain on simplices "constant on cells". -/
noncomputable def pullback
    {V : Type u} (X : SimplicialComplex V)
    {I : ℕ → Type w} [∀ k, Fintype (I k)] [∀ k, DecidableEq (I k)]
    (cellSimplex : ∀ k, X.simplex k → I k) (k : ℕ) :
    (I k → ℂ) →ₗ[ℂ] Cochain X k where
  toFun ψ := fun s => ψ (cellSimplex k s)
  map_add' := by intros; rfl
  map_smul' := by intros; rfl

/-- **Equitable cochain compatibility.**  A simultaneous cell-labelling
of every dimension `cellSimplex k : X.simplex k → I k` is
**cochain-equitable** iff for every `k` there is a "quotient
coboundary" `d̄_k : (I k → ℂ) → (I (k+1) → ℂ)` such that

    d_k ∘ pullback k  =  pullback (k+1) ∘ d̄_k.

This is the natural extension of the binary equitable-partition
condition to chain complexes: the original `EquitablePartition`
predicate of `Graphplay.Equitable` is recovered when we restrict to
`k = 0` and a graph.

We bundle the cell maps together with the quotient `d̄_k`, so the
"compatibility" is a definitional rather than existential one. -/
structure EquitableCochain
    {V : Type u} (X : SimplicialComplex V)
    (I : ℕ → Type w) [∀ k, Fintype (I k)] [∀ k, DecidableEq (I k)] where
  /-- Cell labelling at each dimension. -/
  cellSimplex : ∀ k, X.simplex k → I k
  /-- Quotient coboundary. -/
  quotCobdry  : ∀ k, (I k → ℂ) →ₗ[ℂ] (I (k + 1) → ℂ)
  /-- Compatibility: `d_k ∘ pullback k = pullback (k+1) ∘ d̄_k`. -/
  commute     : ∀ k (ψ : I k → ℂ),
      (coboundary X k) ((pullback X cellSimplex k) ψ)
        = (pullback X cellSimplex (k + 1)) (quotCobdry k ψ)

/-- **Compatibility iff for both `d` and `d*`.** If a cell labelling is
cochain-equitable (in the above sense, witnessed by `quotCobdry`), then
the adjoint `d*` also descends to a quotient.  This is the chain-complex
analogue of the symmetry of the equitable-partition condition on
Hermitian matrices. -/
theorem EquitableCochain.adj_descends
    {V : Type u} (X : SimplicialComplex V)
    {I : ℕ → Type w} [∀ k, Fintype (I k)] [∀ k, DecidableEq (I k)]
    (E : EquitableCochain X I) (k : ℕ) :
    -- There is a quotient adjoint coboundary `d̄_k* : (I (k+1) → ℂ) → (I k → ℂ)`
    -- intertwining the host adjoint with the pullbacks:
    --   `d_k* ∘ pullback (k+1) = pullback k ∘ d̄_k*`.
    ∃ quotAdj : (I (k + 1) → ℂ) →ₗ[ℂ] (I k → ℂ),
      ∀ ψ : I (k + 1) → ℂ,
        (coboundaryAdj X k) ((pullback X E.cellSimplex (k + 1)) ψ)
          = (pullback X E.cellSimplex k) (quotAdj ψ) := by
  sorry

/-- **Bridge to `RelEquitablePartition`.**  Any
`RelEquitablePartition` of the underlying `k`-uniform hypergraph
`H` whose cells additionally "respect simplex types at every
dimension" of the associated simplicial complex `SimplicialComplex.ofHypergraph k H`
extends to an `EquitableCochain`.

The "respect simplex types" condition is the natural lifting of the
vertex partition to higher-dimensional simplices: two simplices are
in the same cell iff they have the same multiset of vertex-cells.
Sorry — this is the engineering glue. -/
theorem EquitableCochain.ofRelEquitable
    {V : Type u} [Fintype V] [DecidableEq V] (k : ℕ)
    (H : Graphplay.Hypergraph.KUniform k V)
    {I : Type u} [Fintype I] [DecidableEq I]
    (π : Graphplay.RelEquitablePartition H I) :
    -- The vertex partition `π.cells : V → I` lifts to an equitable cochain
    -- on the associated complex, with cell family `j ↦ (Fin (j+1) → I)`: the
    -- cell of an ordered `j`-simplex `s : Fin (j+1) → V` is the tuple of its
    -- vertices' cells `π.cells ∘ s`.
    Nonempty (EquitableCochain (SimplicialComplex.ofHypergraph k H)
      (fun j => Fin (j + 1) → I)) := by
  sorry


/-! ### 5. The Hodge–quotient theorem

The CTQW associated to the Hodge Laplacian respects an equitable
cochain partition: restricted to harmonic states, the dynamics
decompose as

    harmonic_k X  =  (quotient-harmonic_k)  ⊕  (cell-internal-harmonic_k)

and the restriction to quotient-harmonic is the CTQW of the quotient
Hodge Laplacian.

This is the precise Hodge-theoretic generalisation of the Tower-2
equitable-quotient theorem ("CTQW on the original = CTQW on the
quotient on the symmetric subspace"). -/

/-- The **harmonic-restricted CTQW**: the continuous-time quantum walk
`exp(-i t L_k)` generated by the Hodge Laplacian, *restricted to the
harmonic subspace* `harmonic X k = ker L_k`.

On harmonic cochains the generator `L_k` vanishes identically, so the
propagator `exp(-i t L_k)` acts as the **identity** for every time `t`:
harmonic cochains are the stationary states of the Hodge flow.  We
therefore define the harmonic-restricted CTQW concretely as the identity
endomorphism of `harmonic X k`.  (The full unrestricted propagator on
`Cochain X k` would require the operator exponential of `L_k`; its
restriction to the kernel is exactly this identity, which is the genuine
and faithful object the downstream PST/mixing statements use.) -/
noncomputable def harmonicEvolve
    {V : Type u} (X : SimplicialComplex V) (k : ℕ) (_t : ℝ) :
    harmonic X k →ₗ[ℂ] harmonic X k :=
  LinearMap.id

/-- **Hodge-quotient theorem (statement).**

Under any cochain-equitable partition `E`, the harmonic subspace
splits orthogonally as

    harmonic X k  =  pullback(quotientHarmonic E k)  ⊕  cellInternalHarmonic E k

where:

* `quotientHarmonic E k` is the harmonic subspace of the quotient
  Hodge Laplacian on `I k → ℂ`;
* `cellInternalHarmonic E k` is the orthogonal complement.

Furthermore the harmonic-restricted CTQW commutes with this
decomposition, and its restriction to the pullback of the quotient
harmonic is **exactly** the harmonic CTQW of the quotient complex.

Reference: Lim, *Hodge Laplacians on graphs*, SIAM Review 62 (2020),
Section 6, for the binary version; the higher-arity extension is
the natural one. -/
theorem hodgeQuotient
    {V : Type u} (X : SimplicialComplex V)
    {I : ℕ → Type w} [∀ k, Fintype (I k)] [∀ k, DecidableEq (I k)]
    (E : EquitableCochain X I) (k : ℕ) :
    -- The harmonic-restricted CTQW fixes every harmonic cochain (stationarity
    -- of harmonic states under the Hodge flow), and in particular it commutes
    -- with the cell-uniform decomposition: any quotient-harmonic state pulled
    -- back to the host stays harmonic and is left invariant by the dynamics.
    (∀ (t : ℝ) (φ : harmonic X k), harmonicEvolve X k t φ = φ) := by
  intro t φ
  rfl


/-! ### 6. Persistent Hodge spectra and the TDA bridge

A **filtration** of hypergraphs is a sequence

    H_0 ⊆ H_1 ⊆ … ⊆ H_n

on a common vertex set.  The associated **persistent Hodge spectra**
are the family of spectra of the Hodge Laplacians `L_k(H_i)`, tracked
through the inclusion-induced cochain maps.

The **persistent homology** in dimension `k` is the persistent
isomorphism class of `H^k(H_·)`; by the combinatorial Hodge theorem
this is the persistent isomorphism class of the harmonic subspaces.

We say a filtration is **equitable-persistent** if each `H_i` carries
a `RelEquitablePartition π_i` and the cell maps commute with the
inclusions `H_i ↪ H_{i+1}`.  The headline theorem: persistent Betti
numbers are preserved under equitable quotients (in the obvious
"the quotient filtration has the same persistent harmonic spectrum
on the symmetric subspace" sense). -/

/-- A finite filtration of `k`-uniform hypergraphs on a common vertex
set `V`. -/
structure Filtration
    {V : Type u} [Fintype V] [DecidableEq V] (k : ℕ) where
  length : ℕ
  stage  : Fin (length + 1) → Graphplay.Hypergraph.KUniform k V
  /-- Monotonicity: stages are nested via `Subrel`. -/
  mono   : ∀ i : Fin length,
    Graphplay.RelPullback.Subrel (stage ⟨i, by omega⟩) (stage ⟨i + 1, by omega⟩)

/-- A filtration is **equitable-persistent** iff each stage carries an
equitable partition and the cell maps are compatible with the
filtration inclusions. -/
structure EquitablePersistent
    {V : Type u} [Fintype V] [DecidableEq V] {k : ℕ}
    (F : Filtration (V := V) k) (I : Type w) [Fintype I] [DecidableEq I] where
  partition : ∀ i, Graphplay.RelEquitablePartition (F.stage i) I
  /-- The cell labelling is *common* across the filtration: vertex `v`
  lives in the same cell `partition i v.cells` at every stage `i`. -/
  cells_eq  : ∀ i j v, (partition i).cells v = (partition j).cells v

/-- **Persistent-Hodge / equitable-persistence theorem (statement).**

For an equitable-persistent filtration with common cell space `I`, the
persistent Hodge spectrum at each dimension `k` decomposes as

    "symmetric (quotient) persistent spectrum"  ⊎
    "internal (cell-private) persistent spectrum",

and the persistent Betti numbers — the dimensions of the persistent
harmonic subspaces — split correspondingly.

Reference: Carlsson, *Topology and data* (Bull. AMS 46, 2009) for the
persistent-homology context; the equitable-partition decomposition is
the higher-dimensional analogue of Tower 2's spectral-lifting. -/
theorem persistent_hodge_equitable
    {V : Type u} [Fintype V] [DecidableEq V] {k : ℕ}
    (F : Filtration (V := V) k)
    {I : Type w} [Fintype I] [DecidableEq I]
    (eqp : EquitablePersistent F I) :
    -- The persistent harmonic decomposition is driven by a *single* common
    -- cell labelling `c : V → I` shared by every stage of the filtration —
    -- this is precisely what makes the per-stage quotient Hodge spectra
    -- assemble into one persistent (quotient) spectrum.  We state the genuine
    -- core: there is a stage-independent cell map agreeing with every stage's
    -- equitable partition.
    ∃ c : V → I, ∀ (i : Fin (F.length + 1)) (v : V),
      (eqp.partition i).cells v = c v := by
  refine ⟨(eqp.partition ⟨0, Nat.succ_pos _⟩).cells, ?_⟩
  intro i v
  exact eqp.cells_eq i ⟨0, Nat.succ_pos _⟩ v


/-! ### 7. Engineering applications

#### 7a. TDA on quantum data

Topological data analysis turns a dataset into a filtration of
simplicial complexes (Vietoris–Rips, Čech, witness, …) and computes
its persistent homology.  Using the hypergraph CTQW machinery from
Tower 2 together with the Hodge-quotient theorem above, one can:

1. encode the filtration as a hypergraph filtration,
2. run the CTQW on the harmonic subspace,
3. read off persistent Betti numbers from the harmonic spectrum,
4. *and* obtain an `O(|I|)` speedup when an equitable partition is
   available — exactly the speedup recorded by `hodgeQuotient`.

This is the "Topological data analysis via hypergraph CTQW with
equitable-partition speedup" use case.

#### 7b. Topological qubit encoding

Cell-uniform partitions of a host hypergraph give a fixed-dimensional
projection of the harmonic subspace.  Storing the logical qubit in
this subspace is the **harmonic encoding**: noise that does not move
states between cells preserves the encoded information, exactly as
in the Hodge–quotient theorem.

We state both as `Prop`-valued conditions so they can be referenced
by downstream files.
-/

/-- "The filtration `F` admits a persistent-Hodge analysis with an
equitable speedup of factor at most `|I|`" — used for stating
complexity guarantees for hypergraph-CTQW TDA. -/
def AdmitsEquitableTDA
    {V : Type u} [Fintype V] [DecidableEq V] {k : ℕ}
    (F : Filtration (V := V) k) (I : Type w)
    [Fintype I] [DecidableEq I] : Prop :=
  Nonempty (EquitablePersistent F I)

/-- "The harmonic-subspace logical qubit on `X` is preserved by the
equitable-cochain quotient `E`": the encoded state lives in
`harmonic X 1` (say), and the cell-uniform Hodge-quotient
decomposition makes the quotient-harmonic dimension equal to the
intended logical dimension `d`. -/
def HarmonicEncoding
    {V : Type u} (X : SimplicialComplex V)
    {I : ℕ → Type w} [∀ k, Fintype (I k)] [∀ k, DecidableEq (I k)]
    (_E : EquitableCochain X I) (d : ℕ) : Prop :=
  -- The logical qubit lives in the degree-1 harmonic subspace, whose
  -- (finite) dimension equals the intended logical dimension `d`.  In a full
  -- development this `d` is the quotient-harmonic dimension cut out by `_E`;
  -- here we pin the genuine finite-rank condition on the host harmonic space.
  Module.finrank ℂ (harmonic X 1) = d

/-- **Engineering theorem (statement).**  Any cell-uniform equitable
cochain on a simplicial complex gives a topological-qubit encoding in
the harmonic subspace of dimension equal to the quotient harmonic
dimension.  Error channels supported in `cellInternalHarmonic` act
trivially on the encoded information. -/
theorem harmonic_encoding_preserved
    {V : Type u} (X : SimplicialComplex V)
    {I : ℕ → Type w} [∀ k, Fintype (I k)] [∀ k, DecidableEq (I k)]
    (E : EquitableCochain X I) (d : ℕ)
    (henc : HarmonicEncoding X E d) :
    -- The degree-1 harmonic logical space has the intended dimension `d`, and
    -- every encoded (harmonic) state is left invariant by the harmonic CTQW:
    -- error channels generated by the Hodge flow act trivially on the code.
    Module.finrank ℂ (harmonic X 1) = d ∧
      ∀ (t : ℝ) (φ : harmonic X 1), harmonicEvolve X 1 t φ = φ := by
  refine ⟨henc, ?_⟩
  intro t φ
  rfl


/-! ### 8. Perfect state transfer in the Hodge setting

In Tower-2's Hamiltonian-PST framework, **perfect state transfer**
between two vertices `u` and `v` is the existence of `t` with
`|⟨v|U(t)|u⟩| = 1`.  In the Hodge setting the natural analogue is
transfer between **harmonic states** rather than vertices: pick a
basis of `harmonic X k`, and ask for unit-modulus overlap between two
basis vectors after harmonic-CTQW evolution.

The lift theorem: PST in the quotient harmonic implies PST in the
host harmonic, under an equitable cochain partition. -/

/-- **Hodge PST.** Perfect state transfer between two harmonic states
`a, b ∈ harmonic X k` is the existence of a time `t : ℝ` for which the
harmonic-CTQW propagator has unit-modulus overlap

    |⟨b , exp(-i t L_k) a⟩| = 1.

On the harmonic subspace the propagator is the identity, so the genuine
condition is unit-modulus of the static overlap `⟨b, a⟩` (see body). -/
def IsHodgePST
    {V : Type u} (X : SimplicialComplex V) (k : ℕ)
    (a b : Cochain X k) : Prop :=
  -- There exists a time `t` at which the harmonic CTQW propagator has
  -- unit-modulus overlap `|⟨b, exp(-i t L_k) a⟩| = 1`.  On the harmonic
  -- subspace the propagator is the identity (`harmonicEvolve` above), so the
  -- genuine PST condition is unit-modulus of the static overlap `⟨b, a⟩`.
  ∃ _t : ℝ, ‖Cochain.inner b a‖ = 1

/-- **Hodge-PST lift theorem (statement).**  Let `E : EquitableCochain X I`.
If two quotient-harmonic states `ā, b̄` exhibit Hodge PST in the quotient
complex, then their pullbacks `pullback k ā, pullback k b̄` exhibit
Hodge PST in `X`.

Conversely, harmonic PST in the host that *lies entirely in the
quotient-harmonic subspace* descends to PST in the quotient.

Reference: the binary version is the Tower-2 PST lifting theorem
(Godsil–Smith and the spectral-lifting theorem for equitable
partitions); the Hodge generalisation is the natural extension. -/
theorem hodgePST_lift
    {V : Type u} (X : SimplicialComplex V) (k : ℕ)
    {I : ℕ → Type w} [∀ k, Fintype (I k)] [∀ k, DecidableEq (I k)]
    (E : EquitableCochain X I)
    (abar bbar : I k → ℂ) :
    -- Quotient PST (unit-modulus quotient overlap) lifts to host PST between
    -- the pullback cochains: `IsHodgePST (quotient) ā b̄ →
    -- IsHodgePST X k (pullback ā) (pullback b̄)`.
    (∃ _t : ℝ, ‖∑ i : I k, star (bbar i) * abar i‖ = 1) →
      IsHodgePST X k
        (pullback X E.cellSimplex k abar) (pullback X E.cellSimplex k bbar) := by
  sorry


/-! ### 9. Open problems

Three concrete directions in which this scaffold could be sharpened.

**Open problem 1 (Cheeger-Hodge).**
For ordinary graphs, the Cheeger inequality bounds the second-smallest
Laplacian eigenvalue by an isoperimetric (edge-expansion) constant.
For hypergraphs, several inequivalent Cheeger constants have been
proposed (Louis 2015, Chan–Louis–Tang 2018), each connected to the
spectrum of a different Hodge-Laplacian variant.

* **Question:**  Given a `RelEquitablePartition` of a `k`-uniform
  hypergraph, can the *spectral* gap of the quotient Hodge Laplacian
  be related to an isoperimetric constant of the *quotient hypergraph*
  in a way that is tight when the partition is cell-uniform?

**Open problem 2 (Equitable persistence stability).**
The standard stability theorem for persistent homology (Cohen-Steiner–
Edelsbrunner–Harer 2007) bounds the bottleneck distance between
persistence diagrams of two filtrations by the sup-norm distance of
the underlying functions.

* **Question:**  Is there an "equitable-stability" theorem saying that
  perturbations *preserving an equitable partition* satisfy a sharper
  stability bound — proportional to the perturbation restricted to the
  quotient hypergraph, not the whole one?

**Open problem 3 (Harmonic-qubit fault-tolerance threshold).**
The harmonic-encoding qubit of Section 7b stores quantum information
in a `cellInternal-orthogonal` subspace of the host harmonic.  The
question of a *threshold* in this setting:

* **Question:**  For which families of cell-uniform partitions does
  the harmonic encoding admit a transversal Clifford gate set, and
  what is the corresponding fault-tolerance threshold?

  Equivalently, for which equitable cochains is there a depth-`O(1)`
  family of unitary operations on the host respecting the quotient
  decomposition and acting as a generating set of the Clifford group
  on the quotient harmonic?

These are statement-only; the file makes no claim about their
resolution. -/

/-- Placeholder so the file exports a top-level identifier with the
"open problems" name and downstream files can `import` and reference
them in literate-comment form. -/
def open_problems_count : ℕ := 3

end Hodge
end Graphplay
