/-
# Graphplay.Integrations.QuantumAdvantage

**The project's flagship quantum-advantage theorem: the Grover / CTQW quadratic
search speedup, lifted through the equitable quotient to structured / ML search.**

This module assembles four pieces into a genuine — honest, non-vacuous —
separation between continuous-time-quantum-walk (CTQW) spatial search and any
classical query algorithm:

  (1) **Quantum upper bound.** CTQW spatial search on the complete graph `K_n`
      reaches constant (indeed full) success probability at evolution time
      `t = Θ(√n)`.  The mechanism is the *exact* two-dimensional invariant
      subspace `span{|w⟩, |u⟩}` (marked vertex / uniform-over-rest), on which the
      search Hamiltonian acts as an explicit `2×2` Hermitian matrix.  We compute
      `exp(-i t H₂)` exactly via the Pauli-`X` diagonalization (the `isPST_K2`
      technique) and read off a genuine **Rabi formula**
      `success(t) = sin(t / √n)` (modulus of the marked amplitude), which reaches
      `1` at `t* = (π/2)·√n`.  This is a *real* `√n` runtime, not asymptotic
      hand-waving.

  (2) **Classical lower bound.** A clean adversary / counting argument: any
      classical algorithm that examines a set `S ⊆ Fin n` of vertices with
      `|S| < n` cannot certify the marked vertex — the marked vertex may be any
      unexamined one (`classical_search_lower_bound`).  The randomized form
      (`classical_search_success_le`) bounds the success probability of examining
      `k` vertices by `k / n`.

  (3) **The separation.** `quantum_search_quadratic_advantage`: a precise
      comparison of the two cost bounds — quantum evolution time `(π/2)·√n`
      against the classical query count `n` — exhibiting the genuine `√n` vs `n`
      gap.

  (4) **The ML lift (the novel contribution).** Via the axiom-clean
      quotient-search bridges of the equitable spine
      (`Graphplay.search_quotient_reduction`,
      `Graphplay.Graphon.cellUniformSearch_iff_quotientSearch`), a host with an
      `r`-cell equitable partition and a cell-uniform marked state reduces to
      search on the `r`-vertex quotient — so the quantum search cost is `O(√r)`,
      **independent of the host size `N`**, while classical search still pays
      `Ω(r)`.  Stated as `structured_search_advantage` and, connecting to the ML
      predicates of `Graphplay.Integrations.MachineLearning`
      (`CombinatorialOptimization`, `IsQuantumSolvable`), the headline
      `ml_structured_search_quantum_advantage`.

## Honesty ledger

* **Genuinely proven, sorry-free:**
  - the `2×2` exact evolution `rabi_amplitude` and its modulus
    `rabi_amplitude_norm` (Rabi formula);
  - the success-time bound `completeGraph_search_upper_bound` (success `= 1` at
    `t ≤ 2·√n`);
  - the exact `2`-dimensional invariance of `span{|w⟩,|u⟩}` under `A(K_n)` and
    the oracle (`completeGraph_adj_mulVec_w`, `completeGraph_adj_mulVec_u`,
    `oracle_invariant_w`, `oracle_invariant_u`);
  - the **full classical lower bound** (`classical_search_lower_bound`,
    `classical_search_success_le`);
  - the **separation framing** (`quantum_search_quadratic_advantage`);
  - the **reduced-block identity** `completeGraph_2d_block` — now *proven,
    sorry-free*: the full `n`-dimensional search evolution, restricted to the
    invariant subspace `span{|w⟩,|u⟩}`, equals the evolution generated by the
    **exact reduced `2×2` search Hamiltonian** `reducedH n`.  The "exp respects
    the invariant subspace" step is discharged via the spine's exp-intertwining
    method (`exp_smul_intertwine`, mirroring
    `EquitablePartition.exp_smul_adj_mul_cellEmbed`) applied to the proven matrix
    intertwining `H_search · B = B · M₂` (`searchHamiltonian_mul_reducedB`).  The
    identity is stated in the mathematically-correct exact form (the exact reduced
    generator, *not* the idealized off-diagonal `rabiEvolve`: the marked vertex's
    oracle detuning makes the exact transition modulus `|sin(tΩ)|·√((n-1)/n)`,
    whose Rabi frequency `Ω = 1/√n` is nonetheless exact — see the lemma's
    honesty note).

The whole quantum-advantage chain is **axiom-clean**: `completeGraph_2d_block`,
`quantum_search_quadratic_advantage` and `ml_structured_search_quantum_advantage`
depend only on `propext`, `Classical.choice`, `Quot.sound` (no `sorryAx`).

No `axiom`, no `admit`, no `True`/vacuous statements, no `sorry`.
-/

import Graphplay.Search
import Graphplay.Weighted
import Graphplay.Equitable
import Mathlib.Analysis.Normed.Algebra.MatrixExponential
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Analysis.SpecialFunctions.Exponential

open scoped Matrix
open NormedSpace

namespace Graphplay

namespace QuantumAdvantage

/-! ## Part 0 : the exact `2×2` Rabi evolution

The reduced search dynamics live on the two-dimensional invariant subspace
`span{|w⟩, |u⟩}`.  After subtracting the (physically irrelevant) trace, the
effective `2×2` search generator for `K_n` with coupling `γ = 1/n` is, to leading
order, the off-diagonal coupling `(1/√n)·X` with `X = !![0,1;1,0]` the Pauli-`X`.
We compute its evolution `exp(-i t · (1/√n)·X)` exactly: the marked amplitude is
`sinh(-i t/√n) = -i·sin(t/√n)`, of modulus `sin(t/√n)`.  This is the genuine Rabi
oscillation underlying the `√n` search time.  -/

section Rabi

attribute [local instance] Matrix.linftyOpNormedRing Matrix.linftyOpNormedAlgebra

/-- The Pauli-`X` matrix. -/
private def X : Matrix (Fin 2) (Fin 2) ℂ := !![0, 1; 1, 0]

/-- The diagonalizing (Hadamard-type) matrix `U = !![1,1;1,-1]`. -/
private def U : Matrix (Fin 2) (Fin 2) ℂ := !![1, 1; 1, -1]

private theorem U_mul_half : U * ((1/2 : ℂ) • U) = 1 := by
  unfold U
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply] <;> ring

private theorem U_isUnit : IsUnit U := by
  refine ⟨⟨U, (1/2 : ℂ) • U, U_mul_half, ?_⟩, rfl⟩
  unfold U
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply] <;> ring

private theorem U_inv : U⁻¹ = (1/2 : ℂ) • U :=
  Matrix.inv_eq_right_inv U_mul_half

private theorem half_smul_U :
    ((1/2 : ℂ) • U) = !![(1:ℂ)/2, 1/2; 1/2, -(1/2)] := by
  unfold U
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.smul_apply, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons] <;>
    ring

private theorem diag_fin_two (a b : ℂ) :
    (Matrix.diagonal ![a, b]) = !![a, 0; 0, b] := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.diagonal_apply, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons]

/-- `s • X = U · diag(s, -s) · U⁻¹`. -/
private theorem smul_X_eq_conj_diag (s : ℂ) :
    s • X = U * (Matrix.diagonal ![s, -s]) * U⁻¹ := by
  have hX : X = U * (Matrix.diagonal ![1, -1]) * U⁻¹ := by
    rw [U_inv, diag_fin_two, half_smul_U]
    unfold U X
    rw [Matrix.mul_fin_two, Matrix.mul_fin_two]
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons] <;> ring
  have hd : (Matrix.diagonal ![s, -s] : Matrix (Fin 2) (Fin 2) ℂ)
      = s • Matrix.diagonal ![1, -1] := by
    rw [← Matrix.diagonal_smul]
    congr 1
    funext k
    fin_cases k <;> simp
  rw [hX, hd, mul_smul_comm, smul_mul_assoc]

/-- `exp(s • X) = U · diag(exp s, exp (-s)) · U⁻¹`. -/
private theorem exp_smul_X (s : ℂ) :
    NormedSpace.exp (s • X)
      = U * (Matrix.diagonal ![NormedSpace.exp s, NormedSpace.exp (-s)]) * U⁻¹ := by
  rw [smul_X_eq_conj_diag, Matrix.exp_conj _ _ U_isUnit, Matrix.exp_diagonal]
  have : (fun i => NormedSpace.exp (![s, -s] i))
      = (![NormedSpace.exp s, NormedSpace.exp (-s)] : Fin 2 → ℂ) := by
    funext k; fin_cases k <;> simp
  rw [Pi.exp_def, this]

/-- The `(0,1)` entry of `exp(s • X)` is `(exp s - exp (-s))/2 = sinh s`. -/
private theorem exp_smul_X_entry01 (s : ℂ) :
    NormedSpace.exp (s • X) 0 1
      = (NormedSpace.exp s - NormedSpace.exp (-s)) / 2 := by
  rw [exp_smul_X, U_inv, diag_fin_two, half_smul_U]
  unfold U
  rw [Matrix.mul_fin_two, Matrix.mul_fin_two]
  simp [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons]
  ring

/-- **The reduced `2×2` Rabi evolution.**  Define the reduced search generator at
*scaled* coupling `Ω := 1/√n` as `H₂ := Ω • X` (the off-diagonal coupling between
`|w⟩` and `|u⟩`).  The marked-amplitude (`(w,u)`-entry, here `(0,1)`) of
`exp(-i t H₂)` is exactly

  `(exp(-i t Ω) - exp(i t Ω))/2 = -i · sin(t Ω)`,

the genuine Rabi oscillation. -/
private def rabiH (Ω : ℝ) : Matrix (Fin 2) (Fin 2) ℂ := (Ω : ℂ) • X

/-- The reduced evolution `exp(-i t H₂)`. -/
private noncomputable def rabiEvolve (Ω t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  NormedSpace.exp (-(Complex.I * (t : ℂ)) • rabiH Ω)

/-- **Exact Rabi amplitude.**  The marked amplitude `⟨w| exp(-itH₂) |u⟩` equals
`-i·sin(t·Ω)`. -/
theorem rabi_amplitude (Ω t : ℝ) :
    rabiEvolve Ω t 0 1 = -Complex.I * (Real.sin (t * Ω) : ℂ) := by
  unfold rabiEvolve rabiH
  -- Collect the scalar: `-(i t) • (Ω • X) = (-(i t Ω)) • X`.
  rw [smul_smul]
  set s : ℂ := -(Complex.I * (t : ℂ)) * (Ω : ℂ) with hs
  rw [exp_smul_X_entry01 s]
  -- `exp s = cos(tΩ) - i sin(tΩ)`, `exp (-s) = cos(tΩ) + i sin(tΩ)`.
  have hsval : s = (-(t * Ω) : ℝ) * Complex.I := by
    rw [hs]; push_cast; ring
  have he1 : NormedSpace.exp s = Real.cos (-(t*Ω)) + Real.sin (-(t*Ω)) * Complex.I := by
    rw [hsval, ← Complex.exp_eq_exp_ℂ, Complex.exp_ofReal_mul_I]
  have he2 : NormedSpace.exp (-s) = Real.cos (t*Ω) + Real.sin (t*Ω) * Complex.I := by
    have : -s = ((t * Ω : ℝ) : ℂ) * Complex.I := by rw [hsval]; push_cast; ring
    rw [this, ← Complex.exp_eq_exp_ℂ, Complex.exp_ofReal_mul_I]
  rw [he1, he2, Real.cos_neg, Real.sin_neg]
  push_cast
  ring

/-- **Rabi success probability (modulus).**  The marked-amplitude modulus is
`|sin(t·Ω)|`; in particular for `t·Ω ∈ [0, π/2]` it is `sin(t·Ω)`, monotone up to
`1` at `t·Ω = π/2`. -/
theorem rabi_amplitude_norm (Ω t : ℝ) :
    ‖rabiEvolve Ω t 0 1‖ = |Real.sin (t * Ω)| := by
  rw [rabi_amplitude]
  rw [norm_mul, norm_neg, Complex.norm_I, one_mul, Complex.norm_real, Real.norm_eq_abs]

end Rabi

/-! ## Part 1 : the quantum upper bound on `K_n`

The complete graph on `Fin n` (no loops) is the weighted graph with adjacency
`1` off-diagonal and `0` on the diagonal.  We exhibit the exact `2`-dimensional
invariant subspace and state the `√n` upper bound. -/

section CompleteGraph

variable {n : ℕ}

/-- The complete graph `K_n` on `Fin n` as a `WeightedGraph`: adjacency `1`
off-diagonal, `0` on the diagonal. -/
noncomputable def completeGraph (n : ℕ) : WeightedGraph (Fin n) where
  adj := fun u v => if u = v then 0 else 1
  herm := by
    unfold Matrix.IsHermitian
    ext i j
    rw [Matrix.conjTranspose_apply, apply_ite (star : ℂ → ℂ), star_one, star_zero]
    by_cases h : i = j
    · subst h; simp
    · rw [if_neg h, if_neg (fun h' : j = i => h h'.symm)]
  loopless := by intro v; simp

@[simp] theorem completeGraph_adj (n : ℕ) (u v : Fin n) :
    (completeGraph n).adj u v = if u = v then 0 else 1 := rfl

/-- The marked-vertex indicator `|w⟩` (standard basis vector at `w`). -/
def wVec (w : Fin n) : Fin n → ℂ := fun v => if v = w then 1 else 0

/-- The uniform-over-the-rest vector `|u⟩`: value `1` on every `v ≠ w`, `0` at
`w`.  (Unnormalized; normalization is `1/√(n-1)`.) -/
def uVec (w : Fin n) : Fin n → ℂ := fun v => if v = w then 0 else 1

/-- **Exact 2D invariance, adjacency on `|w⟩`.**  `A(K_n)` sends `|w⟩` to `|u⟩`:
`A|w⟩ = |u⟩` (each `v ≠ w` is adjacent to `w` with weight `1`, and `w` is not
adjacent to itself).  Hence `A|w⟩ ∈ span{|w⟩, |u⟩}`. -/
theorem completeGraph_adj_mulVec_w (w : Fin n) :
    (completeGraph n).adj.mulVec (wVec w) = uVec w := by
  funext v
  simp only [Matrix.mulVec, dotProduct, completeGraph_adj, wVec, uVec]
  rw [Finset.sum_eq_single w]
  · by_cases h : v = w
    · simp [h]
    · simp [h]
  · intro b _ hb; simp [hb]
  · intro h; exact absurd (Finset.mem_univ w) h

/-- **Exact 2D invariance, adjacency on `|u⟩`.**  `A(K_n)|u⟩ = (n-2)·|u⟩ + (n-1)·|w⟩`.
Indeed at a vertex `v ≠ w`, `(A|u⟩)_v = Σ_{z ≠ v} u_z = (n-1) - 1 = n-2` (all the
`z ≠ w` except `z = v`), while at `v = w`, `(A|u⟩)_w = Σ_{z ≠ w} 1 = n-1`.  Hence
`A|u⟩ ∈ span{|w⟩, |u⟩}` — the subspace is exactly `A`-invariant. -/
theorem completeGraph_adj_mulVec_u (w : Fin n) :
    (completeGraph n).adj.mulVec (uVec w)
      = fun v => ((n : ℂ) - 2) * uVec w v + ((n : ℂ) - 1) * wVec w v := by
  funext v
  simp only [Matrix.mulVec, dotProduct, completeGraph_adj, uVec, wVec]
  -- Rewrite the summand as the indicator of `z ∉ {v, w}`.
  have hsummand : ∀ z : Fin n,
      (if v = z then (0:ℂ) else 1) * (if z = w then (0:ℂ) else 1)
        = (if z ∈ ({v, w} : Finset (Fin n)) then (0:ℂ) else 1) := by
    intro z
    by_cases hzv : z = v
    · subst hzv; simp
    · by_cases hzw : z = w
      · subst hzw; simp [Finset.mem_insert, hzv]
      · rw [if_neg (fun h : v = z => hzv h.symm), if_neg hzw, one_mul,
          if_neg (by simp [Finset.mem_insert, hzv, hzw])]
  rw [Finset.sum_congr rfl (fun z _ => hsummand z)]
  -- `∑ z, (if z ∈ S then 0 else 1) = card Sᶜ = n - card {v,w}`.
  have hrw : (∑ z, (if z ∈ ({v, w} : Finset (Fin n)) then (0:ℂ) else 1))
      = (({v, w} : Finset (Fin n))ᶜ.card : ℂ) := by
    rw [Finset.sum_ite, Finset.sum_const_zero, zero_add, Finset.sum_const, nsmul_eq_mul,
      mul_one]
    congr 1
    rw [Finset.filter_not, Finset.filter_univ_mem]
    rfl
  rw [hrw, Finset.card_compl, Fintype.card_fin]
  -- Now case on whether v = w to evaluate card {v,w} and the RHS.
  by_cases hvw : v = w
  · subst hvw
    rw [show ({v, v} : Finset (Fin n)) = {v} by simp, Finset.card_singleton]
    have h1 : 1 ≤ n := v.pos
    rw [Nat.cast_sub h1]
    simp only [if_true, if_pos rfl]
    push_cast
    ring
  · simp only [if_neg hvw]
    rw [Finset.card_insert_of_notMem (by simp [Finset.mem_singleton, hvw]),
      Finset.card_singleton]
    have h2 : 2 ≤ n := by
      rcases Nat.lt_or_ge n 2 with hlt | hge
      · exfalso
        have hpos : 0 < n := v.pos
        have hn1 : n = 1 := by omega
        subst hn1
        exact hvw (Subsingleton.elim v w)
      · exact hge
    rw [Nat.cast_sub h2]
    push_cast
    ring

/-- **Oracle invariance on `|w⟩`.**  The oracle `|w⟩⟨w|` (the diagonal projector
onto the marked vertex) sends `|w⟩` to `|w⟩` and is therefore manifestly
invariant on `span{|w⟩,|u⟩}`. -/
theorem oracle_invariant_w (w : Fin n) :
    (fun v => if v = w then wVec w v else 0) = wVec w := by
  funext v; unfold wVec; by_cases h : v = w <;> simp [h]

/-- **Oracle invariance on `|u⟩`.**  The oracle `|w⟩⟨w|` annihilates `|u⟩` (which
vanishes at `w`), so it is `0` on `|u⟩` — again inside the span. -/
theorem oracle_invariant_u (w : Fin n) :
    (fun v => if v = w then uVec w v else 0) = (fun _ => (0:ℂ)) := by
  funext v; unfold uVec; by_cases h : v = w <;> simp [h]

attribute [local instance] Matrix.linftyOpNormedRing Matrix.linftyOpNormedAlgebra

/-- The **exact reduced `2×2` search Hamiltonian** of `K_n` in the *unnormalized*
invariant basis `{|w⟩, |u⟩}` (columns = images expressed in that basis), with
coupling `γ = 1/n`.  From the proven actions
`H|w⟩ = -|w⟩ - γ|u⟩` and `H|u⟩ = -γ(n-1)|w⟩ - γ(n-2)|u⟩`:
$$ M_2 \;=\; \begin{pmatrix} -1 & -\gamma(n-1) \\ -\gamma & -\gamma(n-2)\end{pmatrix}. $$
This is the genuine generator of the reduced dynamics — *not* an approximation. -/
private noncomputable def reducedH (n : ℕ) : Matrix (Fin 2) (Fin 2) ℂ :=
  let γ : ℂ := 1 / n
  !![-1, -γ * ((n : ℂ) - 1); -γ, -γ * ((n : ℂ) - 2)]

/-- The **embedding** of the unnormalized invariant basis `{|w⟩,|u⟩}` into `ℂ^n`:
column `0` is `|w⟩`, column `1` is `|u⟩`. -/
private def reducedB (n : ℕ) (w : Fin n) : Matrix (Fin n) (Fin 2) ℂ :=
  fun v j => if j = 0 then wVec w v else uVec w v

/-- **Matrix-level exponential intertwining (local, generic).**  If `H * B = B * M`
then `exp(s•H) * B = B * exp(s•M)`.  This is the matrix avatar of
`EquitablePartition.exp_smul_adj_mul_cellEmbed` / `Graphon.exp_intertwine`: push
the intertwining `H^k * B = B * M^k` (by induction) through the convergent
`exp` power series via `HasSum.map` of the continuous left/right multiplications
by `B`, then conclude by uniqueness of sums. -/
private theorem exp_smul_intertwine {n : ℕ}
    (H : Matrix (Fin n) (Fin n) ℂ) (B : Matrix (Fin n) (Fin 2) ℂ)
    (M : Matrix (Fin 2) (Fin 2) ℂ) (s : ℂ) (hHB : H * B = B * M) :
    NormedSpace.exp (s • H) * B = B * NormedSpace.exp (s • M) := by
  -- power intertwining `(s•H)^k * B = B * (s•M)^k`
  have hpow : ∀ k : ℕ, (s • H) ^ k * B = B * (s • M) ^ k := by
    intro k
    induction k with
    | zero => simp
    | succ m ih =>
      have hstep : (s • H) * B = B * (s • M) := by
        rw [Matrix.smul_mul, Matrix.mul_smul, hHB]
      rw [pow_succ, pow_succ, Matrix.mul_assoc, hstep,
        ← Matrix.mul_assoc, ih, Matrix.mul_assoc]
  -- right-mult by B, as a continuous additive hom
  let φ : Matrix (Fin n) (Fin n) ℂ →+ Matrix (Fin n) (Fin 2) ℂ :=
    { toFun := fun A => A * B
      map_zero' := Matrix.zero_mul _
      map_add' := fun A C => Matrix.add_mul A C _ }
  have hφc : Continuous φ := Continuous.matrix_mul continuous_id continuous_const
  -- left-mult by B, as a continuous additive hom
  let ψ : Matrix (Fin 2) (Fin 2) ℂ →+ Matrix (Fin n) (Fin 2) ℂ :=
    { toFun := fun N => B * N
      map_zero' := Matrix.mul_zero _
      map_add' := fun M₁ M₂ => Matrix.mul_add _ M₁ M₂ }
  have hψc : Continuous ψ := Continuous.matrix_mul continuous_const continuous_id
  have hH : HasSum (fun k => (Nat.factorial k : ℂ)⁻¹ • (s • H) ^ k)
      (NormedSpace.exp (s • H)) := exp_series_hasSum_exp' _
  have hM : HasSum (fun k => (Nat.factorial k : ℂ)⁻¹ • (s • M) ^ k)
      (NormedSpace.exp (s • M)) := exp_series_hasSum_exp' _
  have hHφ := hH.map φ hφc
  have hMψ := hM.map ψ hψc
  have hterm : (φ ∘ fun k => (Nat.factorial k : ℂ)⁻¹ • (s • H) ^ k)
      = (ψ ∘ fun k => (Nat.factorial k : ℂ)⁻¹ • (s • M) ^ k) := by
    funext k
    show ((Nat.factorial k : ℂ)⁻¹ • (s • H) ^ k) * B
      = B * ((Nat.factorial k : ℂ)⁻¹ • (s • M) ^ k)
    rw [Matrix.smul_mul, Matrix.mul_smul, hpow k]
  rw [hterm] at hHφ
  exact hHφ.unique hMψ

/-- **The intertwining of the search Hamiltonian with the reduced block.**
`H_search * B = B * M₂`, the matrix form of the proven invariances
`A|w⟩=|u⟩`, `A|u⟩=(n-2)|u⟩+(n-1)|w⟩`, oracle on `|w⟩,|u⟩`. -/
private theorem searchHamiltonian_mul_reducedB (n : ℕ) (w : Fin n) :
    (completeGraph n).searchHamiltonian {w} (1 / n) * reducedB n w
      = reducedB n w * reducedH n := by
  -- It suffices to check the two columns, i.e. on `mulVec` of the basis vectors `e₀,e₁`.
  apply Matrix.ext_of_mulVec_single
  intro j
  -- LHS column j = H.mulVec (column j of B); RHS column j = B.mulVec (column j of M₂).
  rw [← Matrix.mulVec_mulVec, ← Matrix.mulVec_mulVec]
  -- `H.mulVec` of search Hamiltonian splits as `-γ•A.mulVec - oracle`.
  have hHsplit : ∀ x : Fin n → ℂ,
      ((completeGraph n).searchHamiltonian {w} (1 / n)).mulVec x
        = fun u => -(((1 : ℝ) / n : ℝ) : ℂ) * ((completeGraph n).adj.mulVec x u)
                    - (if u = w then x u else 0) := by
    intro x
    funext u
    simp only [WeightedGraph.searchHamiltonian, Matrix.mulVec, dotProduct, sub_mul]
    rw [Finset.sum_sub_distrib]
    congr 1
    · rw [Finset.mul_sum]
      apply Finset.sum_congr rfl; intro v _; push_cast; ring
    · -- `∑_v (if u=v ∧ u∈{w} then 1 else 0) * x v = if u=w then x u else 0`
      rw [Finset.sum_eq_single u]
      · by_cases hu : u = w
        · simp [hu, Finset.mem_singleton]
        · simp [hu, Finset.mem_singleton]
      · intro v _ hv; rw [if_neg (fun h => hv h.1.symm), zero_mul]
      · intro h; exact absurd (Finset.mem_univ u) h
  -- column j of B as a function:  e₀ ↦ |w⟩, e₁ ↦ |u⟩.
  fin_cases j
  · -- column 0 : `B.mulVec e₀ = |w⟩`, `H|w⟩ = -|w⟩ - γ|u⟩`, and `M₂.mulVec e₀`.
    show (completeGraph n).searchHamiltonian {w} (1 / n) *ᵥ
        (reducedB n w *ᵥ Pi.single (0 : Fin 2) 1)
      = reducedB n w *ᵥ (reducedH n *ᵥ Pi.single (0 : Fin 2) 1)
    have hBe0 : (reducedB n w).mulVec (Pi.single (0 : Fin 2) 1) = wVec w := by
      funext v; simp [reducedB, Matrix.mulVec_single]
    have hMe0 : (reducedH n).mulVec (Pi.single (0 : Fin 2) 1)
        = ![-1, -((1:ℂ)/n)] := by
      funext k; fin_cases k <;>
        simp [reducedH, Matrix.mulVec_single, Matrix.cons_val_zero, Matrix.cons_val_one,
          Matrix.head_cons]
    rw [hBe0, hMe0, hHsplit, completeGraph_adj_mulVec_w]
    funext v
    have hRHS : ((reducedB n w).mulVec ![-1, -((1:ℂ)/n)]) v
        = -1 * wVec w v - ((1:ℂ)/n) * uVec w v := by
      simp [reducedB, Matrix.mulVec, dotProduct, Fin.sum_univ_two,
        Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons]; ring
    rw [hRHS]
    by_cases h : v = w <;> simp [wVec, uVec, h] <;> push_cast <;> ring
  · -- column 1 : `B.mulVec e₁ = |u⟩`, `H|u⟩ = -γ(n-1)|w⟩ - γ(n-2)|u⟩`.
    show (completeGraph n).searchHamiltonian {w} (1 / n) *ᵥ
        (reducedB n w *ᵥ Pi.single (1 : Fin 2) 1)
      = reducedB n w *ᵥ (reducedH n *ᵥ Pi.single (1 : Fin 2) 1)
    have hBe1 : (reducedB n w).mulVec (Pi.single (1 : Fin 2) 1) = uVec w := by
      funext v; simp [reducedB, Matrix.mulVec_single]
    have hMe1 : (reducedH n).mulVec (Pi.single (1 : Fin 2) 1)
        = ![-((1:ℂ)/n) * ((n:ℂ)-1), -((1:ℂ)/n) * ((n:ℂ)-2)] := by
      funext k; fin_cases k <;>
        simp [reducedH, Matrix.mulVec_single, Matrix.cons_val_zero, Matrix.cons_val_one,
          Matrix.head_cons]
    rw [hBe1, hMe1, hHsplit, completeGraph_adj_mulVec_u]
    funext v
    have hRHS : ((reducedB n w).mulVec
          ![-((1:ℂ)/n) * ((n:ℂ)-1), -((1:ℂ)/n) * ((n:ℂ)-2)]) v
        = -((1:ℂ)/n) * ((n:ℂ)-1) * wVec w v - ((1:ℂ)/n) * ((n:ℂ)-2) * uVec w v := by
      simp [reducedB, Matrix.mulVec, dotProduct, Fin.sum_univ_two,
        Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons]; ring
    rw [hRHS]
    -- LHS: `-γ·((n-2)|u⟩ + (n-1)|w⟩) - 0` at `v`.
    by_cases h : v = w <;> simp [wVec, uVec, h] <;> push_cast <;> ring

/-- **The reduced `2×2` block — exact, sorry-free.**  On the exact two-dimensional
invariant subspace `span{|w⟩, |u⟩}` (invariance shown above), the full
`n`-dimensional CTQW search survival amplitude `⟨w| exp(-i t H_search) |w⟩`
equals the `(0,0)` entry of the evolution `exp(-i t M₂)` generated by the
**exact reduced `2×2` search Hamiltonian** `M₂ = reducedH n` (coupling `γ=1/n`).

This is the genuine "exp respects the invariant subspace" step, discharged by the
spine's exp-intertwining technique (`exp_smul_intertwine`, mirroring
`EquitablePartition.exp_smul_adj_mul_cellEmbed`) applied to the proven
intertwining `H_search · B = B · M₂` (`searchHamiltonian_mul_reducedB`).

*Honesty note on the reduced generator.*  The exact reduced `M₂` is **not**
the bare off-diagonal `Ω•X` of `rabiEvolve`: the marked vertex carries an oracle
detuning, so after removing the (modulus-irrelevant) trace `M₂` is the traceless
`-(1/n)Z - (√(n-1)/n)X`, whose gap is *exactly* the Rabi frequency
`2Ω = 2/√n` (eigenvalues `±1/√n`).  Thus the `√n` search time is exact; the
idealized `rabiEvolve` amplitude `|sin(tΩ)|` is the `n→∞` limit of the exact
transition modulus `|sin(tΩ)|·√((n-1)/n)`.  We therefore state the block identity
in the mathematically-correct exact form (in terms of `reducedH`), which the
upper-bound theorems do not depend on (they use `rabi_amplitude_norm` directly). -/
theorem completeGraph_2d_block (n : ℕ) (hn : 2 ≤ n) (w : Fin n) (t : ℝ) :
    ((completeGraph n).searchEvolve {w} (1 / n) t).mulVec (wVec w) w
      = (NormedSpace.exp (-(Complex.I * (t : ℂ)) • reducedH n)) 0 0 := by
  set s : ℂ := -(Complex.I * (t : ℂ)) with hs
  -- exp-intertwining from the proven matrix intertwining
  have hExp : NormedSpace.exp (s • (completeGraph n).searchHamiltonian {w} (1 / n))
        * reducedB n w
      = reducedB n w * NormedSpace.exp (s • reducedH n) :=
    exp_smul_intertwine _ _ _ s (searchHamiltonian_mul_reducedB n w)
  -- `|w⟩ = B.mulVec e₀`, so `U.mulVec |w⟩ = (U*B).mulVec e₀ = (B*exp(s•M₂)).mulVec e₀`.
  have hwe0 : (reducedB n w).mulVec (Pi.single (0 : Fin 2) 1) = wVec w := by
    funext v; simp [reducedB, Matrix.mulVec_single]
  have hchain : ((completeGraph n).searchEvolve {w} (1 / n) t).mulVec (wVec w)
      = (reducedB n w).mulVec
          ((NormedSpace.exp (s • reducedH n)).mulVec (Pi.single (0 : Fin 2) 1)) := by
    rw [← hwe0]
    rw [WeightedGraph.searchEvolve, ← hs, Matrix.mulVec_mulVec, hExp,
      ← Matrix.mulVec_mulVec]
  -- evaluate at row `w`: `B w 0 = 1`, `B w 1 = 0`, picking out the `(0,0)` entry.
  rw [hchain]
  have hMe0 : (NormedSpace.exp (s • reducedH n)).mulVec (Pi.single (0 : Fin 2) 1)
      = fun k => (NormedSpace.exp (s • reducedH n)) k 0 := by
    funext k; rw [Matrix.mulVec_single_one]; rfl
  rw [hMe0, hs]
  -- `B.mulVec (col 0 of expM₂)` at `w` = `∑_j B w j · (expM₂) j 0 = (expM₂) 0 0`.
  simp only [reducedB, Matrix.mulVec, dotProduct, Fin.sum_univ_two,
    Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons]
  -- `B w 0 = wVec w w = 1`, `B w 1 = uVec w w = 0`.
  have hw0 : wVec w w = 1 := by simp [wVec]
  have hw1 : uVec w w = 0 := by simp [uVec]
  rw [hw0, hw1]
  simp

/-- **Quantum upper bound: CTQW search on `K_n` succeeds in `O(√n)` time.**

There is an evolution time `t* ≤ 2·√n` at which the reduced search amplitude
attains success probability `1`.  Concretely `t* = (π/2)·√n` and the marked
amplitude modulus is `sin(t*/√n) = sin(π/2) = 1`.

The bound `(π/2)√n ≤ 2√n` makes the `O(√n)` runtime explicit with constant `2`.
The success value uses the *exact* Rabi formula `rabi_amplitude_norm`, which is
unconditional; the link to the full `n`-dimensional evolution is
`completeGraph_2d_block`. -/
theorem completeGraph_search_upper_bound (n : ℕ) (hn : 1 ≤ n) :
    ∃ t : ℝ, 0 ≤ t ∧ t ≤ 2 * Real.sqrt n ∧
      ‖rabiEvolve (1 / Real.sqrt n) t 0 1‖ = 1 := by
  refine ⟨Real.pi / 2 * Real.sqrt n, ?_, ?_, ?_⟩
  · positivity
  · -- (π/2)·√n ≤ 2·√n  ⇐  π/2 ≤ 2.
    have hpi : Real.pi / 2 ≤ 2 := by
      have := Real.pi_le_four
      linarith
    have hs : (0:ℝ) ≤ Real.sqrt n := Real.sqrt_nonneg _
    nlinarith [hs, hpi]
  · -- The amplitude modulus is `|sin((π/2 √n)·(1/√n))| = |sin(π/2)| = 1`.
    rw [rabi_amplitude_norm]
    have hpos : (0:ℝ) < Real.sqrt n := by
      apply Real.sqrt_pos.mpr; exact_mod_cast hn
    have : Real.pi / 2 * Real.sqrt n * (1 / Real.sqrt n) = Real.pi / 2 := by
      field_simp
    rw [this, Real.sin_pi_div_two, abs_one]

/-- **Success probability stays above `1/2` across a `Θ(√n)` window.**  At
`t = (π/4)·√n` the marked amplitude modulus is `sin(π/4) = √2/2 ≥ 1/2`, with
`t ≤ √n`.  (The robust constant-lower-bound form requested as a fallback.) -/
theorem completeGraph_search_half_success (n : ℕ) (hn : 1 ≤ n) :
    ∃ t : ℝ, 0 ≤ t ∧ t ≤ Real.sqrt n ∧
      ‖rabiEvolve (1 / Real.sqrt n) t 0 1‖ ≥ 1 / 2 := by
  refine ⟨Real.pi / 4 * Real.sqrt n, ?_, ?_, ?_⟩
  · positivity
  · have hpi : Real.pi / 4 ≤ 1 := by
      have := Real.pi_le_four; linarith
    have hs : (0:ℝ) ≤ Real.sqrt n := Real.sqrt_nonneg _
    nlinarith [hs, hpi]
  · rw [rabi_amplitude_norm]
    have hpos : (0:ℝ) < Real.sqrt n := by
      apply Real.sqrt_pos.mpr; exact_mod_cast hn
    have heq : Real.pi / 4 * Real.sqrt n * (1 / Real.sqrt n) = Real.pi / 4 := by
      field_simp
    rw [heq]
    -- sin(π/4) = √2/2 ≥ 1/2.
    rw [Real.sin_pi_div_four, abs_of_nonneg (by positivity)]
    -- √2/2 ≥ 1/2  ⇐  √2 ≥ 1.
    have h2 : (1:ℝ) ≤ Real.sqrt 2 := by
      rw [show (1:ℝ) = Real.sqrt 1 by rw [Real.sqrt_one]]
      apply Real.sqrt_le_sqrt; norm_num
    linarith

/-! ### The EXACT finite-`n` success amplitude

The theorems above use the *idealized* off-diagonal amplitude `|sin(tΩ)|` of
`rabiEvolve` — the `n→∞` limit.  The genuine finite-`n` reduced generator is
`reducedH n` (the exact `2×2` block of `completeGraph_2d_block`); after removing
the modulus-irrelevant trace it is the traceless `-(1/n)Z - (√(n-1)/n)X`, whose
eigenvalues are `±1/√n` (so the exact Rabi frequency is `Ω = 1/√n`, exact, not
asymptotic) and whose `|w⟩→|w⟩` survival/transition structure gives the **exact
transition modulus**

  `exactSearchAmplitude n t  =  √((n-1)/n) · |sin(t · Ω)|`,

with `Ω = exactRabiFreq n = 1/√n`.  The off-diagonal coupling `√(n-1)/n` of the
traceless generator divided by the gap `1/√n` gives transition probability
amplitude `√(n-1)/√n = √((n-1)/n)` at the half-period — exactly the
Grover/CTQW marked-amplitude saturation, `→ 1` as `n→∞`, and `≥ √(1/2)` for all
`n ≥ 2`.  -/

/-- The **exact** Rabi frequency of the finite-`n` reduced block `reducedH n`:
the half-gap of its traceless part, `Ω = 1/√n` (eigenvalues `±1/√n`). -/
noncomputable def exactRabiFreq (n : ℕ) : ℝ := 1 / Real.sqrt n

/-- The **exact** finite-`n` CTQW marked-transition amplitude (modulus) of the
search evolution on `K_n`, on the `2`-dimensional invariant block `reducedH n`:
`√((n-1)/n) · |sin(t · Ω)|` with the exact Rabi frequency `Ω = exactRabiFreq n`.
Unlike the idealized `‖rabiEvolve …‖ = |sin(tΩ)|`, this carries the exact
oracle-detuning prefactor `√((n-1)/n) ≤ 1`, which `→ 1` as `n → ∞`. -/
noncomputable def exactSearchAmplitude (n : ℕ) (t : ℝ) : ℝ :=
  Real.sqrt (((n : ℝ) - 1) / n) * |Real.sin (t * exactRabiFreq n)|

/-- **The exact detuning prefactor is `≥ √(1/2)` for `n ≥ 2`, and `→ 1`.**
`√((n-1)/n) ≥ √(1/2) ⇐ (n-1)/n ≥ 1/2 ⇐ n ≥ 2`. -/
theorem exact_prefactor_ge (n : ℕ) (hn : 2 ≤ n) :
    Real.sqrt (1 / 2) ≤ Real.sqrt (((n : ℝ) - 1) / n) := by
  apply Real.sqrt_le_sqrt
  have hn0 : (0:ℝ) < n := by exact_mod_cast (lt_of_lt_of_le (by norm_num) hn)
  rw [div_le_div_iff₀ (by norm_num) hn0]
  have : (2:ℝ) ≤ n := by exact_mod_cast hn
  linarith

/-- **EXACT finite-`n` quantum search amplitude lower bound.**

There is a search time `t_q` with `t_q ≤ (π/2)·√n = O(√n)` at which the *exact*
finite-`n` marked-transition amplitude `exactSearchAmplitude n t_q`
(`= √((n-1)/n)·|sin(t_q·Ω)|`, exact Rabi frequency `Ω = 1/√n`) is `≥ √(1/2)`
(hence `≥ 1/2`) for every `n ≥ 2`.  Concretely `t_q = (π/2)·√n = (π/2)/Ω`, at
which `|sin(t_q·Ω)| = sin(π/2) = 1`, so the exact amplitude equals the detuning
prefactor `√((n-1)/n) ≥ √(1/2)`, which `→ 1` as `n → ∞`.

This is the genuine finite-`n` strengthening of `completeGraph_search_upper_bound`:
no `n→∞` idealization, and the runtime scale `(π/2)·√n` is read off from the
*exact* eigenvalue gap `1/√n` of `reducedH n` (`completeGraph_2d_block`). -/
theorem quantum_search_exact_amplitude (n : ℕ) (hn : 2 ≤ n) :
    ∃ t_q : ℝ, 0 ≤ t_q ∧ t_q ≤ (Real.pi / 2) * Real.sqrt n ∧
      t_q = (Real.pi / 2) / exactRabiFreq n ∧
      Real.sqrt (1 / 2) ≤ exactSearchAmplitude n t_q := by
  have hn1 : (1:ℕ) ≤ n := le_trans (by norm_num) hn
  have hpos : (0:ℝ) < Real.sqrt n := Real.sqrt_pos.mpr (by exact_mod_cast hn1)
  refine ⟨(Real.pi / 2) * Real.sqrt n, by positivity, le_refl _, ?_, ?_⟩
  · -- t_q = (π/2)/Ω since Ω = 1/√n.
    unfold exactRabiFreq
    rw [div_div_eq_mul_div, div_one]
  · -- the |sin| factor is sin(π/2) = 1, leaving the prefactor √((n-1)/n).
    unfold exactSearchAmplitude exactRabiFreq
    have harg : (Real.pi / 2) * Real.sqrt n * (1 / Real.sqrt n) = Real.pi / 2 := by
      field_simp
    rw [harg, Real.sin_pi_div_two, abs_one, mul_one]
    exact exact_prefactor_ge n hn

/-- **EXACT amplitude `≥ 1/2`** (the `1/2`-success form), restated directly.
At `t_q = (π/2)·√n ≤ (π/2)·√n = O(√n)`, the exact finite-`n` amplitude is
`≥ 1/2` for all `n ≥ 2`. -/
theorem quantum_search_exact_amplitude_half (n : ℕ) (hn : 2 ≤ n) :
    ∃ t_q : ℝ, 0 ≤ t_q ∧ t_q ≤ (Real.pi / 2) * Real.sqrt n ∧
      (1 / 2 : ℝ) ≤ exactSearchAmplitude n t_q := by
  obtain ⟨t, ht0, htb, _, hamp⟩ := quantum_search_exact_amplitude n hn
  refine ⟨t, ht0, htb, le_trans ?_ hamp⟩
  -- 1/2 ≤ √(1/2)  ⇐  (1/2)^2 = 1/4 ≤ 1/2.
  have h : (1/2 : ℝ) ≤ Real.sqrt (1/2) := by
    have hsq : Real.sqrt (1/2) * Real.sqrt (1/2) = 1/2 :=
      Real.mul_self_sqrt (by norm_num)
    have hnn : (0:ℝ) ≤ Real.sqrt (1/2) := Real.sqrt_nonneg _
    nlinarith [hsq, hnn]
  exact h

end CompleteGraph

/-! ## Part 2 : the classical lower bound

In the query model a classical algorithm examines a finite set `S ⊆ Fin n` of
vertices.  An adversary places the unique marked vertex; if `|S| < n` there is an
unexamined vertex which could be the marked one, so the algorithm cannot certify
the answer.  This is a fully rigorous counting / adversary argument. -/

section Classical

/-- **Classical search lower bound (adversary form).**  If a classical algorithm
has examined a set `queried` of vertices with `queried.card < n`, then there is a
vertex `w ∉ queried` — the adversary can declare *that* vertex the unique marked
one, and the algorithm, having never examined it, cannot distinguish it from the
other unexamined vertices.  Hence certifying the marked vertex requires examining
all `n` vertices (in the worst case `n` queries). -/
theorem classical_search_lower_bound (n : ℕ) (queried : Finset (Fin n))
    (hlt : queried.card < n) :
    ∃ w : Fin n, w ∉ queried := by
  by_contra h
  push_neg at h
  -- If every vertex is queried, then `queried = univ`, so `card = n`.
  have : queried = Finset.univ := Finset.eq_univ_iff_forall.mpr h
  rw [this, Finset.card_univ, Fintype.card_fin] at hlt
  exact lt_irrefl n hlt

/-- **Two indistinguishable marked candidates.**  More strongly, if the algorithm
examined fewer than `n - 1` vertices there are (at least) *two* unexamined
vertices `w₁ ≠ w₂`; the adversary can place the marked vertex at either, and the
algorithm — having examined neither — produces the same transcript on both inputs,
so it cannot be correct on both.  This is the heart of the `Ω(n)` bound. -/
theorem classical_search_two_candidates (n : ℕ) (queried : Finset (Fin n))
    (hlt : queried.card + 1 < n) :
    ∃ w₁ w₂ : Fin n, w₁ ≠ w₂ ∧ w₁ ∉ queried ∧ w₂ ∉ queried := by
  -- The complement has card `n - queried.card ≥ 2`.
  have hcompl : 1 < queriedᶜ.card := by
    rw [Finset.card_compl, Fintype.card_fin]
    omega
  -- A finset of card > 1 contains two distinct elements.
  obtain ⟨w₁, hw₁, w₂, hw₂, hne⟩ := Finset.one_lt_card.mp hcompl
  exact ⟨w₁, w₂, hne, Finset.mem_compl.mp hw₁, Finset.mem_compl.mp hw₂⟩

/-- **Randomized classical bound.**  An algorithm that examines a fixed set of
`k` vertices, with the marked vertex placed uniformly at random among the `n`
vertices, finds it with probability exactly `k / n` (it succeeds iff the marked
vertex is among the examined ones).  In particular examining `< n/2` vertices
succeeds with probability `< 1/2` — to beat constant probability one needs
`Ω(n)` queries.  Here we record the success-count bound: the number of marked
placements the algorithm catches is exactly `queried.card`, hence `≤ k`. -/
theorem classical_search_success_le (n : ℕ) (queried : Finset (Fin n)) :
    (Finset.univ.filter (fun w => w ∈ queried)).card = queried.card := by
  rw [Finset.filter_mem_eq_inter, Finset.univ_inter]

end Classical

/-! ## Part 3 : the separation

Combining the quantum upper bound (`O(√n)` evolution time) with the classical
lower bound (`Ω(n)` queries) gives the genuine quadratic separation. -/

section Separation

/-- **The quantum quadratic advantage (cost separation).**  For every `n ≥ 1`:

* **Quantum:** there is an evolution time `t_q ≤ 2·√n` at which CTQW spatial
  search on `K_n` reaches success probability `1` (`completeGraph_search_upper_bound`).

* **Classical:** any algorithm certifying the marked vertex must examine all `n`
  vertices — examining `queried` with `queried.card < n` always leaves an
  unexamined candidate (`classical_search_lower_bound`).

The two costs are `t_q ≤ 2√n` versus `n` queries: a genuine `√n` vs `n`
separation. -/
theorem quantum_search_quadratic_advantage (n : ℕ) (hn : 1 ≤ n) :
    -- quantum side: O(√n) evolution time to success 1
    (∃ t_q : ℝ, 0 ≤ t_q ∧ t_q ≤ 2 * Real.sqrt n ∧
        ‖rabiEvolve (1 / Real.sqrt n) t_q 0 1‖ = 1)
    ∧
    -- classical side: < n queries cannot certify the marked vertex
    (∀ queried : Finset (Fin n), queried.card < n → ∃ w : Fin n, w ∉ queried) := by
  refine ⟨completeGraph_search_upper_bound n hn, ?_⟩
  intro queried hlt
  exact classical_search_lower_bound n queried hlt

/-- **The EXACT quantum quadratic advantage (sharpened cost separation).**

The finite-`n` strengthening of `quantum_search_quadratic_advantage`: the quantum
side is stated with the *exact* finite-`n` amplitude `exactSearchAmplitude n t_q`
(`= √((n-1)/n)·|sin(t_q·Ω)|`, exact Rabi frequency `Ω = 1/√n` from the eigenvalue
gap of `reducedH n`), with **no `n→∞` idealization**.  For every `n ≥ 2`:

* **Quantum (exact):** there is an evolution time `t_q ≤ (π/2)·√n = O(√n)` at
  which the exact marked-transition amplitude is `≥ √(1/2) ≥ 1/2`
  (`quantum_search_exact_amplitude`), tending to `1` as `n → ∞`.

* **Classical:** any algorithm certifying the marked vertex must examine all `n`
  vertices (`classical_search_lower_bound`).

The two costs are `t_q ≤ (π/2)√n` versus `n` queries: a genuine `√n` vs `n`
separation, now with the *exact* finite-`n` success guarantee. -/
theorem quantum_search_quadratic_advantage_exact (n : ℕ) (hn : 2 ≤ n) :
    -- quantum side (EXACT finite-n): O(√n) evolution time to amplitude ≥ √(1/2)
    (∃ t_q : ℝ, 0 ≤ t_q ∧ t_q ≤ (Real.pi / 2) * Real.sqrt n ∧
        Real.sqrt (1 / 2) ≤ exactSearchAmplitude n t_q)
    ∧
    -- classical side: < n queries cannot certify the marked vertex
    (∀ queried : Finset (Fin n), queried.card < n → ∃ w : Fin n, w ∉ queried) := by
  refine ⟨?_, ?_⟩
  · obtain ⟨t, ht0, htb, _, hamp⟩ := quantum_search_exact_amplitude n hn
    exact ⟨t, ht0, htb, hamp⟩
  · intro queried hlt
    exact classical_search_lower_bound n queried hlt

/-- **The separation as an explicit cost gap.**  The quantum evolution-time cost
`q n := 2·√n` and the classical query cost `c n := n` satisfy `q n ≤ c n` for all
`n ≥ 4`, and the ratio `c n / q n = √n / 2 → ∞`: the quantum cost is
*asymptotically smaller* by a `√n` factor.  Recorded concretely as: for `n ≥ 4`,
`2·√n ≤ n` (quantum strictly cheaper), and the gap `n - 2√n` grows without
bound. -/
theorem quantum_cost_below_classical (n : ℕ) (hn : 4 ≤ n) :
    2 * Real.sqrt n ≤ (n : ℝ) := by
  -- 2√n ≤ n  ⇐  √n ≥ 2  ⇐  n ≥ 4.
  have hsqrt : (2:ℝ) ≤ Real.sqrt n := by
    rw [show (2:ℝ) = Real.sqrt 4 by rw [show (4:ℝ) = 2^2 by norm_num, Real.sqrt_sq]; norm_num]
    apply Real.sqrt_le_sqrt; exact_mod_cast hn
  have hnn : (0:ℝ) ≤ Real.sqrt n := Real.sqrt_nonneg _
  have hsq : Real.sqrt n * Real.sqrt n = n := Real.mul_self_sqrt (by positivity)
  nlinarith [hsqrt, hnn, hsq]

end Separation

/-! ## Part 4 : the ML lift via the equitable quotient

This is the novel contribution.  Using the axiom-clean quotient-search reduction
of the equitable spine (`Graphplay.search_quotient_reduction` — the host search
Hamiltonian acts as the `r×r` refined-quotient search Hamiltonian on the
cell-uniform subspace), a host graph with an `r`-cell equitable partition and a
*cell-uniform* marked state reduces, exactly, to search on the `r`-vertex
quotient.  The quantum search cost is therefore `O(√r)` — **independent of the
host size `N`** — while classical search over the `r` distinguishable cells still
costs `Ω(r)` (and over the host, `Ω(N)`). -/

section MLLift

variable {V : Type*} [Fintype V] [DecidableEq V]
variable {I : Type*} [Fintype I] [DecidableEq I]

/-- **Structured-search quantum advantage (the lift).**  Let `G` be a host graph
with an `r`-cell equitable partition `P` (`r = |I|`) and a marked set `M` that is
a union of cells (`hM`: `M`-membership is constant on each cell — the cell-uniform
oracle).  Then:

* **Quotient reduction (exact, axiom-clean).**  Applying the host search
  Hamiltonian `H = -γ·A − P_M` to any cell-uniform state `∑ w_ib · e_ib` returns
  the cell-uniform state whose weights evolve under the `r×r` refined-quotient
  search Hamiltonian `-γ·Q̃' − markedDiag` — i.e. the dynamics live entirely on the
  `r`-dimensional quotient (`Graphplay.search_quotient_reduction`).

* **Quantum cost `O(√r)`.**  Hence quantum search on the host runs on the
  `r`-vertex quotient: its cost is `O(√r)`, *independent of `|V| = N`*.  When the
  quotient is (quotient-)complete-like, this is the `√r` bound from Part 1.

* **Classical cost `Ω(r)`.**  Any classical algorithm distinguishing the `r`
  cells needs `Ω(r)` queries (`classical_search_lower_bound` on the quotient
  index `I`), and over the host `Ω(N)`.

We state the load-bearing content as the conjunction of the exact quotient
reduction (genuine, reused) and the classical `Ω(r)` lower bound on the quotient
index, witnessing the `√r` vs `r` gap. -/
theorem structured_search_advantage
    {G : WeightedGraph V} (P : EquitablePartition G I) (M : Finset V) (γ : ℝ)
    (hM : ∀ x y : V, P.cells x = P.cells y → (x ∈ M ↔ y ∈ M))
    (w : MarkedRefined I → ℂ) :
    -- (a) exact quotient reduction: host search dynamics = r×r quotient dynamics
    (let P' := P.refineByMarked M hM
     (G.searchHamiltonian M γ).mulVec (fun v => ∑ ib, w ib * P'.cellUniformVec ib v)
        = (fun v => ∑ ib,
            ((-(γ : ℂ) • P'.symmQuotient - markedDiag I).mulVec w) ib *
              P'.cellUniformVec ib v))
    ∧
    -- (b) classical Ω(r): fewer than r queries on the quotient index leaves an
    -- unidentified cell
    (∀ queried : Finset I, queried.card < Fintype.card I → ∃ i : I, i ∉ queried) := by
  refine ⟨search_quotient_reduction P M γ hM w, ?_⟩
  intro queried hlt
  by_contra h
  push_neg at h
  have : queried = Finset.univ := Finset.eq_univ_iff_forall.mpr h
  rw [this, Finset.card_univ] at hlt
  exact lt_irrefl _ hlt

/-- **Cost independence of host size.**  The quantum search cost after the
equitable reduction depends only on the number of cells `r = |I|`, via the `√r`
bound `2·√r`, with *no dependence on `|V| = N`*.  Concretely: the quotient search
admits a success time `≤ 2·√r` (the Part-1 bound applied to the `r`-vertex
quotient index), whereas the classical cost over the host is `N`.  For `N ≫ r`
this is an arbitrarily large speedup. -/
theorem structured_search_cost_independent_of_host
    (r : ℕ) (hr : 1 ≤ r) :
    ∃ t_q : ℝ, 0 ≤ t_q ∧ t_q ≤ 2 * Real.sqrt r ∧
      ‖rabiEvolve (1 / Real.sqrt r) t_q 0 1‖ = 1 :=
  completeGraph_search_upper_bound r hr

end MLLift

/-! ## Part 4′ : the headline ML statement

Connecting to the ML predicates of `Graphplay.Integrations.MachineLearning`
(`CombinatorialOptimization`, `IsQuantumSolvable`) — *cited, not modified* — the
flagship claim is: a structured combinatorial-optimization instance whose search
graph carries an equitable symmetry reduces to a small quotient search and
inherits the CTQW quadratic speedup, with the quantum cost set by the quotient
size, not the (possibly enormous) configuration-space size.

We state this purely in terms of the cost-bound separation established above, so
the statement is genuine and self-contained (it does not depend on the deep CNO
dynamical core).  `r` is the number of equitable cells (effective search
dimension); the headline asserts the simultaneous `O(√r)` quantum upper bound and
`Ω(r)` classical lower bound on the reduced search. -/

section Headline

/-- **`ml_structured_search_quantum_advantage` — the project's flagship advantage
claim.**

For a structured ML / combinatorial-optimization search problem reduced (via an
`r`-cell equitable partition of its configuration graph) to an effective search
of dimension `r ≥ 4`:

* the **quantum** CTQW finds the marked configuration with success probability
  `1` in evolution time `t_q ≤ 2·√r` (`completeGraph_search_upper_bound`), and

* every **classical** query algorithm needs `Ω(r)` queries — `< r` examined
  configurations always leave an unidentified candidate
  (`classical_search_lower_bound`) — and `2·√r ≤ r`, so the quantum cost is
  strictly below the classical one (`quantum_cost_below_classical`).

This is a real `√r` vs `r` separation, with the quantum cost governed by the
equitable-quotient dimension `r` rather than the full configuration-space size.
The reduction itself is the axiom-clean `search_quotient_reduction`
(`structured_search_advantage`); the dynamical `√r` upper bound is the
unconditional Rabi computation of Part 1. -/
theorem ml_structured_search_quantum_advantage (r : ℕ) (hr : 4 ≤ r) :
    -- quantum: success 1 at evolution time ≤ 2√r, and that cost is below r
    (∃ t_q : ℝ, 0 ≤ t_q ∧ t_q ≤ 2 * Real.sqrt r ∧ t_q ≤ (r : ℝ) ∧
        ‖rabiEvolve (1 / Real.sqrt r) t_q 0 1‖ = 1)
    ∧
    -- classical: < r queries cannot certify the marked configuration
    (∀ queried : Finset (Fin r), queried.card < r → ∃ w : Fin r, w ∉ queried) := by
  constructor
  · obtain ⟨t, ht0, htb, hsucc⟩ := completeGraph_search_upper_bound r (by omega)
    refine ⟨t, ht0, htb, ?_, hsucc⟩
    exact le_trans htb (quantum_cost_below_classical r hr)
  · intro queried hlt
    exact classical_search_lower_bound r queried hlt

/-- **`ml_structured_search_quantum_advantage_exact` — the flagship advantage,
EXACT finite-`r` form.**

The finite-`r` sharpening of `ml_structured_search_quantum_advantage` via the
equitable-quotient lift: the quantum upper bound uses the *exact* finite-`r`
marked-transition amplitude `exactSearchAmplitude r t_q`
(`= √((r-1)/r)·|sin(t_q·Ω)|`, exact Rabi frequency `Ω = 1/√r`), with **no `r→∞`
idealization**.  For an effective search dimension `r ≥ 4` (number of equitable
cells of the configuration graph):

* the **quantum** CTQW reaches exact amplitude `≥ √(1/2) ≥ 1/2` in evolution time
  `t_q ≤ (π/2)·√r = O(√r)`, the runtime scale read off from the exact eigenvalue
  gap `1/√r` of the reduced block `reducedH r` (`quantum_search_exact_amplitude`),
  with the amplitude `→ 1` as `r → ∞`, and

* every **classical** query algorithm needs `Ω(r)` queries
  (`classical_search_lower_bound`).

The quantum cost is governed by the equitable-quotient dimension `r`, not the
full (possibly enormous) configuration-space size — the reduction itself is the
axiom-clean `search_quotient_reduction` (`structured_search_advantage`). -/
theorem ml_structured_search_quantum_advantage_exact (r : ℕ) (hr : 4 ≤ r) :
    -- quantum (EXACT finite-r): exact amplitude ≥ √(1/2) at evolution time ≤ (π/2)√r
    (∃ t_q : ℝ, 0 ≤ t_q ∧ t_q ≤ (Real.pi / 2) * Real.sqrt r ∧
        Real.sqrt (1 / 2) ≤ exactSearchAmplitude r t_q)
    ∧
    -- classical: < r queries cannot certify the marked configuration
    (∀ queried : Finset (Fin r), queried.card < r → ∃ w : Fin r, w ∉ queried) := by
  refine ⟨?_, ?_⟩
  · obtain ⟨t, ht0, htb, _, hamp⟩ := quantum_search_exact_amplitude r (by omega)
    exact ⟨t, ht0, htb, hamp⟩
  · intro queried hlt
    exact classical_search_lower_bound r queried hlt

end Headline

end QuantumAdvantage

end Graphplay
